src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Dependent on type</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HOB Club-Club Nights</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Music Hall</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Foundation Room</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Restaurant</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Special Event</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Special Event Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify TBD Venues.  Used in Apex to perform calculations based on business processes.</description>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EventSubtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDConfirmedCount__c</fullName>
        <label>TBD Confirmed Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TBDMonthValue__c</fullName>
        <formula>TEXT(MONTH(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDMonthValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDMonth__c</fullName>
        <label>TBD Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <formula>IF(RecordType.DeveloperName ==&apos;TBDEvents&apos;, False, Venue__r.TBDVenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBDYearValue__c</fullName>
        <formula>TEXT(YEAR(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDYearValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDYear__c</fullName>
        <description>Used in TBD Apex logic</description>
        <label>TBD Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>TBDEvents</fullName>
        <active>true</active>
        <description>Used for TBD Events</description>
        <label>TBD Events</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/EventSubtype.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Club Night</fullName>
    </customValue>
    <customValue>
        <fullName>Filler Show</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Promoted</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Show</fullName>
    </customValue>
    <customValue>
        <fullName>Rental/Special Events/Venue Holds</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant Show</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event</fullName>
    </customValue>
    <customValue>
        <fullName>Tentpole</fullName>
    </customValue>
    <customValue>
        <fullName>Not Used</fullName>
    </customValue>
    <description>Centralized values for the Event Subtype field</description>
    <masterLabel>Event Subtype</masterLabel>
</GlobalValueSet>

src/classes/LNE_TBDCountUpdateClass.cls
/**
 * This class queries all events that has the TBDVenue__c
 * (All Account.TBDvenues__c=Y and not TBDEvents Record Type) flag, 
 * status is cofirmed or pending likely and not a filler show
 * Get the total count by venue, month and year and update 
 * the corresponding Event__c.TBDConfirmedCount__c 
 * 
 * @author Henry Akpala <hakpala@salesforce.com>
 **/
public class LNE_TBDCountUpdateClass {

            
           // public void TBDCountUpdateClass(){ 
             public void TBDCountUpdateClass(List<Event__c> listEvent){ 
                
                        Integer janCount=0,febCount=0,marCount=0,aprCount=0,mayCount=0,junCount=0,julCount=0,augCount=0,sepCount=0,octCount=0,novCount=0,decCount=0;
                       
                        //get current year
                        Date myDate = Date.today();
                        Integer intYear = myDate.Year();
                        List<Event__c> lstEvent = new List<Event__c>();
                        if(listEvent != null && listEvent.size()>0){
                            lstEvent.addAll( listEvent);
                        }else
                        {
                            //list of all events that are in tbd venues so they are flagged as tbdVenue__c = true
                                 lstEvent = new List<Event__c>([SELECT Id, Venue__c, TBDConfirmedCount__c,TBDMonth__c, TBDYear__c, TBDVenue__c, TBDMonthValue__c, TBDYearValue__c, EventLastDate__c from Event__c WHERE  RecordTypeName__c!='TBDEvents' AND (Status__c ='Pending Likely' OR Status__c ='Confirmed')
                             AND (SubType__c!='Filler Show') AND (TBDVenue__c=True) AND (TBDMonthValue__c != null) AND (TBDYearValue__c =:String.valueof(intYear) ) ]); 
                        }
                        //List of all TBD events records created for the TBD Events Record Type
                        List<Event__c> lstTBDEvents = new List<Event__c>([SELECT  Id, Status__c, Venue__c, TBDConfirmedCount__c, TBDVenue__c, TBDMonthValue__c, TBDMonth__c, TBDYear__c, TBDYearValue__c FROM Event__c WHERE RecordTypeName__c='TBDEvents' AND (TBDVenue__c=False) AND TBDYear__c=:String.valueof(intYear)  ]); 
                        
                        Set<Id> setTBDVenue = new Set<Id>();
                        //Get all the unique venues that are associated to Events in TBD Venues
                        for (Event__c e2 : lstTBDEvents){
                            setTBDVenue.add(e2.Venue__c);
                        }           
                        List<Event__c> lstToUpdate = new List<Event__c>();
                        // list of events for each tbdvenue
                        List<Event__c> lstSameVenue = new List<Event__c>();
                    
                        for (Id e3 : setTBDVenue){
                             
                              for (Event__c d : lstEvent){
                                    if( e3 == d.Venue__c){
                                          lstSameVenue.add(d);
                                          //get the count of each confirmed & pending likely event by month for all flagged tbd venues
                                          if (d.TBDMonthValue__c == '1')  {janCount++; }
                                          if (d.TBDMonthValue__c == '2')  {febCount++; }
                                          if (d.TBDMonthValue__c == '3')  {marCount++; }
                                          if (d.TBDMonthValue__c == '4')  {aprCount++; }
                                          if (d.TBDMonthValue__c == '5')  {mayCount++; }
                                          if (d.TBDMonthValue__c == '6')  {junCount++; }
                                          if (d.TBDMonthValue__c == '7')  {julCount++; }
                                          if (d.TBDMonthValue__c == '8')  {augCount++; }
                                          if (d.TBDMonthValue__c == '9')  {sepCount++; }
                                          if (d.TBDMonthValue__c == '10') {octCount++; }
                                          if (d.TBDMonthValue__c == '11') {novCount++; }
                                          if (d.TBDMonthValue__c == '12') {decCount++; }
                                    }
                              }//end for loop for event
                              //set the TBDConfirmedCount__c value for each month for all TBD Events.   
                              for (Event__c e : lstTBDEvents){
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '1') )  {e.TBDConfirmedCount__c    = janCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '2') )  {e.TBDConfirmedCount__c   = febCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '3') )  {e.TBDConfirmedCount__c   = marCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '4') )  {e.TBDConfirmedCount__c   = aprCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '5') )  {e.TBDConfirmedCount__c   = mayCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '6') )  {e.TBDConfirmedCount__c   = junCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '7') )  {e.TBDConfirmedCount__c   = julCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '8') )  {e.TBDConfirmedCount__c   = augCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '9') )  {e.TBDConfirmedCount__c   = sepCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '10'))  {e.TBDConfirmedCount__c   = octCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '11'))  {e.TBDConfirmedCount__c   = novCount; }
                                    if ( ( e3 == e.Venue__c) && (e.TBDMonth__c == '12'))  {e.TBDConfirmedCount__c   = decCount; }
                              }
                              janCount=0;febCount=0;marCount=0;aprCount=0;mayCount=0;junCount=0;julCount=0;augCount=0;sepCount=0;octCount=0;novCount=0;decCount=0;
                        }
                        //Update the TBD Events confirmed count value.
                        Database.update(lstTBDEvents);
                }
}