src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Misc</fullName>
        <active>true</active>
        <description>Represents misc expenses</description>
        <label>Misc</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_GenerateTourShortlinks_C_Test.cls
@IsTest
private class LNE_GenerateTourShortlinks_C_Test {

	final static Id RECTYPE_ID_TOURCAMPAIGN_MISC;

	static {

		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{'TourCampaign__c.Misc'}
		);

		RECTYPE_ID_TOURCAMPAIGN_MISC = recordTypeMap.get('TourCampaign__c.Misc');
	}
	
	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
		//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: before standard data set' );
		LNE_TestObjectFactory.createStandardDataSet();
		//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: after standardDataSet. Should not count towards limits, no? :' + LNE_FinancialCalculator.currentlyRunning );
	}

	class TestSettings {

		public Tour__c testTour;
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_GenerateTourShortlinks_C_Test' );
		}
		
		public TestSettings typicalSetup(){
			//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: starting typical setup:' + LNE_FinancialCalculator.currentlyRunning );
			
			Account artist = LNE_TestObjectFactory.createAccount('Account.Name');
			insert artist;
			
			//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: after artist:' + LNE_FinancialCalculator.currentlyRunning );
			
			this.testTour = LNE_TestObjectFactory.createTour('name', artist.Id);
			insert this.testTour;

			//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: after tour:' + LNE_FinancialCalculator.currentlyRunning );
			
			Event__c event = [select Id, Tour__c from Event__c limit 1];
			event.Tour__c = this.testTour.Id;
			update event;

			// odd place for this statement, but it is being used to reset SOQL limits
			Test.startTest();
			
			//System.debug( '21567c5c-436d-48bc-ad4d-e7221a312181: after event, Prior to inserting Ad Plans:' + LNE_FinancialCalculator.currentlyRunning );
			AdPlan__c adplan = LNE_TestObjectFactory.createAdPlan('name', 100, event.Id, this.testTour.Id);
			insert adplan;

			TourCampaign__c tc = LNE_TestObjectFactory.createTourCampaign(this.testTour.Id, RECTYPE_ID_TOURCAMPAIGN_MISC);
			insert tc;

			//TourCampaignAdPlan__c tcap = LNE_TestObjectFactory.createTourCampaignAdPlan(tc.Id, adplan.Id, 100);
			//insert tcap;
			

			Test.stopTest();

			return this;
		}
		
		public TestSettings finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();

			return this;
		}
	}
	
	
	//-- test test methods here
	
	static testMethod void runSetupAWithoutException() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		System.assert( true, 'No Exceptions have occurred in getting here' );
	}
	
   	//-- test functionality here
	
	static testMethod void testScenario1() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		
		List<TourCampaignAdPlan__c> tcaps = LNE_GenerateTourShortlinks_C.getTourCampaignAdPlans(ts.testTour.Id, new List<String>(), new List<String>());
		System.assert(!tcaps.isEmpty());

		List<Id> recordIds = new List<Id> { tcaps[0].Id };
		Map<Id,String> result = LNE_GenerateTourShortlinks_C.updateShortUrls(recordIds, 'foo');

	}

	static testMethod void testScenario_Types() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		List<String> types = LNE_GenerateTourShortlinks_C.getTypes(ts.testTour.Id);
	}

	static testMethod void testScenario_Vendors() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		List<String> vendors = LNE_GenerateTourShortlinks_C.getVendors(ts.testTour.Id);
	}

	static testMethod void testScenario_Tour() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		LNE_GenerateTourShortlinks_C.updateTour(ts.testTour.Id, 'foo');
	}

}