src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>BuyingGroup__c</fullName>
        <label>Buying Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BuyingGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourName__c</fullName>
        <formula>Tour__r.TourName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tour Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>BuyingGroup__c</fullName>
        <label>Buying Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BuyingGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TourHeadliner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Headliner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Artist</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tours (Tour Headliner)</relationshipLabel>
        <relationshipName>Tours1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TourName__c</fullName>
        <label>Tour Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FBEvent - buyticketslink</fullName>
                </value>
                <value>
                    <fullName>FBEvent - description</fullName>
                </value>
                <value>
                    <fullName>FBX</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page image</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page link</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page video</fullName>
                </value>
                <value>
                    <fullName>Paid - dark post</fullName>
                </value>
                <value>
                    <fullName>Paid - link post</fullName>
                </value>
                <value>
                    <fullName>Paid - Lncom</fullName>
                </value>
                <value>
                    <fullName>Paid - photo</fullName>
                </value>
                <value>
                    <fullName>Paid - promotion</fullName>
                </value>
                <value>
                    <fullName>Paid - Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Paid - text only</fullName>
                </value>
                <value>
                    <fullName>Paid - video</fullName>
                </value>
                <value>
                    <fullName>Advertising Materials Production</fullName>
                </value>
                <value>
                    <fullName>Agency Commission</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Distribution</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Production</fullName>
                </value>
                <value>
                    <fullName>Graphic/Digital Design</fullName>
                </value>
                <value>
                    <fullName>National Allocation - Misc</fullName>
                </value>
                <value>
                    <fullName>Press Conference</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Tour Launch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Rich Media</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Digital</fullName>
        <active>true</active>
        <description>Represents digital ads</description>
        <label>Digital</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/BuyingGroup.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Canada Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Comedy Touring</fullName>
    </customValue>
    <customValue>
        <fullName>EDM Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Global Touring</fullName>
    </customValue>
    <customValue>
        <fullName>NAC Touring</fullName>
    </customValue>
    <customValue>
        <fullName>T&amp;C Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Local Offer</fullName>
    </customValue>
    <masterLabel>Buying Group</masterLabel>
</GlobalValueSet>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/classes/LNE_TSOTab_CX_Test.cls
@isTest
public class LNE_TSOTab_CX_Test {
	class TestSettings {
    	public Tour__c testTour;
    	public Event__c testEvent;

    	public TestSettings() {
	        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue', 'Account.Office', 'Account.Artist', 'Event__c.PromotedShow', 'Event__c.Rental', 'Event__c.Hold', 'TourCampaign__c.Digital'});         
	        Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
	        Id RT_ACCOUNT_OFFICE_ID = recordTypeMap.get( 'Account.Office' );
	        Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );
	        Id RT_EVENT_PROMOTEDSHOW_ID = recordTypeMap.get( 'Event__c.PromotedShow' );	
			Id RT_Rental_ID = recordTypeMap.get( 'Event__c.Rental' );
			Id RT_Hold_ID = recordTypeMap.get( 'Event__c.Hold' );
			Id RT_TOUR_CAMPAIGN_DIGITAL = recordTypeMap.get( 'TourCampaign__c.Digital' );

			Account artist = LNE_TestObjectFactory.createAccount( 'Artist1' );
			insert artist;

			GLAccount__c testGlaAcct1 = new GLAccount__c (
	            Type__c = 'Ancillary',
	            Name = 'Parking Revenue',
	            Category__c = 'Other Event Revenue',
	            GLCode__c = '12346'
	        );
			
			insert testGlaAcct1;            

	        // create office
	        Account office = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Office', RT_ACCOUNT_OFFICE_ID)).buildAccount();
	        office.Type = 'Geography';
	        office.BillingStreet = '123 main st.';
	        office.BillingCity = 'chicago';
	        office.BillingStateCode = 'IL';
	        office.BillingPostalCode = '60654';
	        office.BillingCountryCode = 'US';
	        office.ShippingStreet = '123 main st.';
	        office.ShippingCity = 'chicago';
	        office.ShippingStateCode = 'IL';
	        office.ShippingPostalCode = '60654';
	        office.ShippingCountryCode = 'US';
	        insert office;
	    
	        // create venue
	        Account venue = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Venue', RT_ACCOUNT_VENUE_ID)).buildAccount();
	        venue.BillingStreet = '123 main st.';
	        venue.BillingCity = 'chicago';
	        venue.BillingStateCode = 'IL';
	        venue.BillingPostalCode = '60654';
	        venue.BillingCountryCode = 'US';
	        venue.ShippingStreet = '123 main st.';
	        venue.ShippingCity = 'chicago';
	        venue.ShippingStateCode = 'IL';
	        venue.ShippingPostalCode = '60654';
	        venue.ShippingCountryCode = 'US';
	        venue.Market__c = 'Chicago';
	        venue.Capacity__c = 100;
	        venue.PrimaryOffice__c = office.id;
	        insert venue;

			Tour__c tour = new Tour__c();
			tour.TourName__c = 'Test';
			tour.TourHeadliner__c = artist.Id;
			tour.BuyingGroup__c = 'Local Offer';
			insert tour;

			testTour = tour;

			TourCampaign__c tc = new TourCampaign__c();
			tc.RecordTypeId = RT_TOUR_CAMPAIGN_DIGITAL;
			tc.Tour__c = tour.Id;
			insert tc;
	    }
	}

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    @isTest
    static void testTSOTab(){
    	TestSettings ts = new TestSettings();
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.testTour);
        LNE_TSOTab_CX cx = new LNE_TSOTab_CX(sc);
        PageReference pr = cx.getTourTotals();

        //TODO: Add Assertions

    }
}