src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>2</defaultValue>
        <description>Ordinal number that represents the artist&apos;s rank in the event lineup</description>
        <label>Rank</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalSupportActExpenses__c</fullName>
        <description>Total Support Act Expenses</description>
        <label>Total Support Act Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/classes/LNE_EventAssociatedArtists_T_Test.cls
@isTest
public class LNE_EventAssociatedArtists_T_Test {
    static final String RT_Rental = '';
    static final String RT_Hold = '';
    
    class TestSettings {
        Deal__c[] newDeals;
        Deal__c[] oldDeals;        
        Map<Id, Deal__c> oldDealsMap;
        Account[] artists;
        Event__c Evt1;
        Deal__c testDeal1;
        Deal__c testDeal2;
        Deal__c testDeal3;

        public TestSettings() {
        	
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
        
            //-- global setup here
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue', 'Account.Office', 'Account.Artist', 'Event__c.PromotedShow', 'Event__c.Rental', 'Event__c.Hold', 'Deal__c.Artist'});         
            Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
            Id RT_ACCOUNT_OFFICE_ID = recordTypeMap.get( 'Account.Office' );
            Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );
            Id RT_EVENT_PROMOTEDSHOW_ID = recordTypeMap.get( 'Event__c.PromotedShow' );	
			Id RT_Rental_ID = recordTypeMap.get( 'Event__c.Rental' );
			Id RT_Hold_ID = recordTypeMap.get( 'Event__c.Hold' );
			Id RT_DEAL_ARTIST_ID = recordTypeMap.get( 'Deal__c.Artist' );
            
            newDeals = new List<Deal__c>(); 
            oldDeals = new List<Deal__c>();
            Map<Id, Deal__c> oldDealsMap = new Map<Id, Deal__c>();

            GLAccount__c testGlaAcct1 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12346'
            );
			
			insert testGlaAcct1;
			
			/**
			// create office
            Account office = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Office', RT_ACCOUNT_OFFICE_ID)).buildAccount();
            office.Type = 'Geography';
            office.BillingStreet = '123 main st.';
            office.BillingCity = 'chicago';
            office.BillingStateCode = 'IL';
            office.BillingPostalCode = '60654';
            office.BillingCountryCode = 'US';
            office.ShippingStreet = '123 main st.';
            office.ShippingCity = 'chicago';
            office.ShippingStateCode = 'IL';
            office.ShippingPostalCode = '60654';
            office.ShippingCountryCode = 'US';
            insert office;
            */
        
            // create venue
            Account venue = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Venue', RT_ACCOUNT_VENUE_ID)).buildAccount();
            venue.BillingStreet = '123 main st.';
            venue.BillingCity = 'chicago';
            venue.BillingStateCode = 'IL';
            venue.BillingPostalCode = '60654';
            venue.BillingCountryCode = 'US';
            venue.ShippingStreet = '123 main st.';
            venue.ShippingCity = 'chicago';
            venue.ShippingStateCode = 'IL';
            venue.ShippingPostalCode = '60654';
            venue.ShippingCountryCode = 'US';
            venue.Market__c = 'Chicago';
            venue.Capacity__c = 100;
            //venue.PrimaryOffice__c = office.id;
            //insert venue;
            
			LNE_TestObjectFactory.VenueHierarchy acctHierarchy = LNE_TestObjectFactory.createVenueHierarchy(
            	LNE_TestObjectFactory.ACCT_TYPE_DIVISION, null, venue
            );
            
            Evt1 = new Event__c(
                ProjectedPaidTickets__c = 50000,
                ProjectedDropCount__c = 50000,
                Status__c = 'Draft',
               	RecordTypeId = RT_Rental_ID,
               	Venue__c = venue.Id,
			    TotalSupportActExpenses__c = 0.0,
			    Office__c = acctHierarchy.division.Id
            );
            insert Evt1;
        
            Account[] artists = new Account[]{
				LNE_TestObjectFactory.createAccount( 'Artist1' ),
				LNE_TestObjectFactory.createAccount( 'Artist2' ),
                LNE_TestObjectFactory.createAccount( 'Artist3' )
			};
                
           	insert artists;
            
            Deal__c testDeal1 = new Deal__c(Type__c='Primary Headliner',
                                            Rank__c = 1,
                                            Artist__c = artists[0].Id,
                                            GuaranteeAmount__c = 200,
                                            DealType__c = 'Flat',
                                            DealCalculation__c = 'Guarantee Only',
                                            Event__c = Evt1.Id,
                                            StageType__c = 'Plan',
                                            RecordTypeId=RT_DEAL_ARTIST_ID);
            insert testDeal1;
            newDeals.add(testDeal1);
            
            Deal__c testDeal2 = new Deal__c(Type__c='Support',
                                            Rank__c = 2,
                                            Artist__c = artists[1].Id,
                                            GuaranteeAmount__c = 200,
                                            DealCalculation__c = 'Guarantee Only',
                                            Event__c = Evt1.Id,
                                            StageType__c = 'Plan',
                                            RecordTypeId=RT_DEAL_ARTIST_ID);
            insert testDeal2;
            newDeals.add(testDeal2);

            Deal__c testDeal3 = new Deal__c(Type__c='Primary Headliner',
                                            Rank__c = 3,
                                            Artist__c = artists[2].Id,
                                            GuaranteeAmount__c = 200,
                                            DealCalculation__c = 'Guarantee Only',
                                            Event__c = Evt1.Id,
                                            StageType__c = 'Settlement',
                                            RecordTypeId=RT_DEAL_ARTIST_ID);
            insert testDeal3;
            newDeals.add(testDeal3);

            Deal__c testDeal4 = new Deal__c(Type__c='Primary Headliner',
                                            Rank__c = 3,
                                            Artist__c = artists[2].Id,
                                            GuaranteeAmount__c = 200,
                                            DealCalculation__c = 'Guarantee Only',
                                            Event__c = Evt1.Id,
                                            StageType__c = 'Plan',
                                            RecordTypeId=RT_DEAL_ARTIST_ID);
            
            try{
                 insert testDeal4;
            }catch(Exception e){
                Boolean expectedExceptionThrown = e.getMessage().contains('You can only select one Primary Headliner per Event.') ? true : false;
                System.assertEquals(expectedExceptionThrown, true);
            }
            
        }
        
        public void typicalSetup(){
                
        }
        
        public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
        }
    }
     
    //-- test functionality here

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    /**
     *  Test: The Artists__c string should be a line break delimited list of all artists involved (via associated deals) in order of deal rank
     */ 
    static testMethod void testInsertPrimaryHeadliner() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        
        Test.startTest();
        List<Deal__c> results = [SELECT Id, Type__c FROM Deal__c WHERE Event__c = :ts.Evt1.Id AND Type__c IN ('Primary Headliner','Support')];
        System.assertEquals(3, results.size());

        Event__c newEvent = [SELECT Artists__c FROM Event__c WHERE Id = :ts.Evt1.Id];
        String expString = 'Artist1\nArtist2';
        System.assertEquals(expString, newEvent.Artists__c);
        Test.stopTest();
    }

}