src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify TBD Venues.  Used in Apex to perform calculations based on business processes.</description>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>BatchFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to track records that were processed by the batch apex class.</description>
        <label>BatchFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <formula>IF(RecordType.DeveloperName ==&apos;TBDEvents&apos;, False, Venue__r.TBDVenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_RunCalculation_Batch_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class LNE_RunCalculation_Batch_Test{
    

    static testMethod void testMethod1() 
    {
        
         LNE_GeneralSettingsUtil.setLocalBypassSettings(true, true, true);
          
            List<RecordType> rT = new List<RecordType>([SELECT Id, sObjectType, DeveloperName From RecordType Where  (DeveloperName='Rental' OR DeveloperName='Venue' OR DeveloperName='Office') ] ) ;
            String sRental, sVenue;
            String sOffice;
            
            for (RecordType r : rT){
                 if(r.DeveloperName =='Rental' ) {sRental=r.Id;}
                 if(r.DeveloperName =='Venue' ) {sVenue=r.Id;}
                 if(r.DeveloperName =='Office' ) {sOffice=r.Id;}
            
            }
            System.debug(sOffice + ' , ' + sRental + ' , ' +  sVenue );
            
            List<Account> acL = new List<Account>(); 
            Integer i=0;
            Account c ;
            for(i=0;  i< 2 ; i++){
                               
              c = new  Account(TBDVenue__c =True, Name='TBDVENUE' +i , RecordTypeId=sVenue,BillingState='California', BillingPostalCode='92929', BillingCity='Same',BillingStreet='112 SAME' );
             acL.add(c);
            }
            insert acL; 
            
            Account tbdVenue1 = acL[1];
            System.debug(' tbdVenue1  = ' + tbdVenue1.Name);
            System.Assert(acL.size() == 2);
            
             c = new  Account( Name='OFFICE', RecordTypeId=sOffice,BillingState='California', BillingPostalCode='92929', BillingCity='Same',BillingStreet='112 SAME',Type=
             'Office');
            insert c; 
            System.Assert(c.Id != null);
            
            date k1  = Date.today();
          
            List<Event__c> evtE  = new List<Event__c>();
            Event__c e;
            
            for (Account a : acL){
                e = new Event__c(BatchFlag__c=false, Office__c=c.Id,EventLastDate__c=k1, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                evtE.add(e);                  
            }  
            insert evtE;
             
        
        Test.startTest();
            String q = 'Select  Id from Event__c where BatchFlag__c=false';
            
            LNE_RunCalculations_Batch obj = new LNE_RunCalculations_Batch(q);
            Database.executeBatch(obj); 
            
        Test.stopTest();
    }
 }