src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <description>Record type for co-promoters related to events and shows</description>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>AncillaryRevenue__c</fullName>
        <label>Ancillary Revenue</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CoPromoter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Promoter</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Co-Promoter Deals</relationshipLabel>
        <relationshipName>CoPromoterDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventLoss__c</fullName>
        <label>Event Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EventProfit__c</fullName>
        <label>Event Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentLoss__c</fullName>
        <label>Expense Adjustment Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentProfit__c</fullName>
        <label>Expense Adjustment Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DealSettlementLedger__c.object
<CustomObject>
    <description>Junction object linking the Deal with Ledger Entries so settlement values can be planned and settled upon per Deal</description>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <formula>text( Deal__r.PrimarySecondaryCoPromoter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Share</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>LedgerEntry__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Settlement-Ledger</label>
    <nameField>
        <displayFormat>DSL-{000000}</displayFormat>
        <label>Deal Settlement-Ledger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Settlement-Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EnvironmentIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Key IDs that may differ between environments but require reference in configured automation</description>
    <fields>
        <fullName>LiveNationAccountID__c</fullName>
        <label>Live Nation Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Environment IDs</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>GlobalDataAdministrator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked for a profile or user, enables user to bypass many workflows and validation rules that might otherwise prevent successful editing or loading of data. Generally used for the integration and system admin profiles as well as granting a higher level of access to trusted users.</description>
        <inlineHelpText>When checked for a profile or user, enables user to bypass many workflows and validation rules that might otherwise prevent successful editing or loading of data. May grant a higher level of access to trusted users on an exception basis.</inlineHelpText>
        <label>Global Data Administrator</label>
        <type>Checkbox</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SettleAtActual__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Settle At Actual</label>
        <type>Checkbox</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_DealCoPromoter_T.cls
/** 
 *  Trigger logic to add validation to the CoPromoter(Deal__c) records.
 *  @author John Casimiro
 **/
 public class LNE_DealCoPromoter_T {
    
    /**
    *  Creates Deal Settlement Ledgers when a copromoter record is created.
    *  @param newList Deal__c[]
    *  @param oldMap Map<Id,Deal__c>
    *  @return Deal__c[] - list of ledger entries updated.
    **/
    public static Deal__c[] createDealSettlementLedgers( Deal__c[] newList, Map<Id,Deal__c> oldMap ){
        String RT_COPROMOTER = 'Deal__c.CoPromoter';
        String RT_EXPENSES = 'LedgerEntry__c.Expenses';
        String RT_ANCILLARY = 'LedgerEntry__c.Ancillary';
        String RT_COGS = 'LedgerEntry__c.COGS';
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
            new String[]{ RT_COPROMOTER, RT_EXPENSES, RT_ANCILLARY, RT_COGS}
        );
        Id RT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
        Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
        Id RT_ANCILLARY_ID = recordTypeMap.get( RT_ANCILLARY );
        Id RT_COGS_ID = recordTypeMap.get( RT_COGS );
        
        EnvironmentIds__c eids = EnvironmentIds__c.getInstance();
        String LIVENATIONACCOUNTID = eids.LiveNationAccountID__c;
        
        
        // filter only co-promoter deals
        set<Id> eventIds = new set<Id>();
        //map<Id,Id> eventIdDealIdMap = new map<Id,Id>();
        List<Deal__c> filteredDeals = new List<Deal__c>();
        for(Deal__c d : newList){
            if (d.RecordTypeId == RT_COPROMOTER_ID && d.CoPromoter__c != LIVENATIONACCOUNTID){
                eventIds.add(d.Event__c);
                //eventIdDealIdMap.put(d.Event__c, d.Id);
                filteredDeals.add(d);
            }
        }
        //system.debug('event to deal map = ' + eventIdDealIdMap);
        
        // query for ledger entries where (RT = Expense && settle at actual = false) || RT = Ancillary || RT = COGS && LE.Event = Deal.Event
        if (eventIds.size() >0){
            List<LedgerEntry__c> entries = new List<LedgerEntry__c>([Select Id, Event__c from LedgerEntry__c 
                where Event__c in :eventIds 
                and ((RecordTypeId = :RT_EXPENSES_ID and SettleAtActual__c = false) or RecordTypeId = :RT_ANCILLARY_ID or RecordTypeId = :RT_COGS_ID)]);
            system.debug('entries = ' + entries);  
            
            // if ledger entris exist, create a deal settlement-ledger
            if (entries.size() > 0){
                List<DealSettlementLedger__c> dsls = new List<DealSettlementLedger__c>();
                for(LedgerEntry__c entry : entries){
                    for (Deal__c d : filteredDeals){
                        DealSettlementLedger__c dsl = new DealSettlementLedger__c();
                        dsl.LedgerEntry__c = entry.Id;
                        dsl.Deal__c = d.Id;
                        dsl.share__c = true;
                        system.debug(dsl);
                        dsls.add(dsl);
                    }
                }
                if (dsls.size() > 0)
                    insert dsls;
            }
        }
        
        return ( null );
    }
    
    /**
    *  Prevent delete of Live Nation Co-Promoter Deals for users except system admins
    *  @param newList Deal__c[]
    *  @return Deal__c[] - list of ledger entries updated.
    **/
    public static Deal__c[] checkDeletePermission( Deal__c[] newList){
        GeneralSettings__c gs = GeneralSettings__c.getInstance(UserInfo.getProfileId());
        EnvironmentIds__c eids = EnvironmentIds__c.getInstance();
        String RT_COPROMOTER = 'Deal__c.CoPromoter';
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
            new String[]{ RT_COPROMOTER }
        );
        Id RT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
        
        for (Deal__c d : newList){
            if (d.CoPromoter__c != null && d.CoPromoter__c == eids.LiveNationAccountID__c && gs.GlobalDataAdministrator__c != true && d.RecordTypeId == RT_COPROMOTER_ID) {
            	if (LNE_EventDeletionUtil.CURRENTLY_DELETING == false) {
                	d.addError('Only Global Data Administrators are permitted to delete Live Nation Co-Promoter records.');
            	}
            }
        }
        
        return ( newList );
    }
    
    /**
    *  Updates remainder record on delete of a Co-Promoter Deal.
    *  @param newList Deal__c[]
    *  @return Deal__c[] - list of ledger entries updated.
    **/
    public static Deal__c[] updateRemainderOnDelete( Deal__c[] newList){
        system.debug('trigger size = '+ newList.size());
        EnvironmentIds__c eids = EnvironmentIds__c.getInstance();
        String LIVENATIONACCOUNTID = eids.LiveNationAccountID__c;
        String RT_COPROMOTER = 'Deal__c.CoPromoter';
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
            new String[]{ RT_COPROMOTER }
        );
        Id RT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
        
        Set<id> eventIds = new set<id>();
        Set<id> processedEventIds = new set<id>();
        Map<id, Deal__c> dealsMap = new map<id, Deal__c>();
        
        for(Deal__c d : newList){
            eventIds.add(d.Event__c);
            dealsMap.put(d.Id, d);
        }
        
        //get Co-Promoter Deals (primary and secondary)
        Map<Id, Event__c> events = new Map<Id, Event__c>([SELECT Id, (SELECT Id, CoPromoter__r.Name, Type__c, Event__c, EventLoss__c, EventProfit__c, ExpenseAdjustmentLoss__c, ExpenseAdjustmentProfit__c, AncillaryRevenue__c, PrimarySecondaryCoPromoter__c FROM Deals__r where recordTypeid = :RT_COPROMOTER_ID) FROM Event__c WHERE Id IN :eventIds]);
        List<Deal__c> updatedList = new List<Deal__c>();
        
        system.debug('events = ' + events);
        
        for(Deal__c d : newList) {
            system.debug('deleted deal = ' + d);
            if (d.recordTypeId != RT_COPROMOTER_ID || processedEventIds.contains(d.Event__r.Id)) {
                continue; // if there are multiple deals deleted on the same Event we only want to run once.
            } else {
                processedEventIds.add(d.Event__r.Id);
            }
            
            Decimal TotalPrimaryEventLoss = 0;
            Decimal TotalPrimaryEventProfit = 0;
            Decimal TotalPrimaryExpenseAdjustmentLoss = 0;
            Decimal TotalPrimaryExpenseAdjustmentProfit = 0;
            Decimal TotalPrimaryAncillaryRevenue = 0;
            Decimal TotalSecondaryEventLoss = 0;
            Decimal TotalSecondaryEventProfit = 0;
            Decimal TotalSecondaryExpenseAdjustmentLoss = 0;
            Decimal TotalSecondaryExpenseAdjustmentProfit = 0;
            Decimal TotalSecondaryAncillaryRevenue = 0;
            
            // calculate totals across all the sibling co-promoter deals
            if (events.size() > 0 ){
                for(Deal__c deal : events.get(d.Event__c).Deals__r){
                    if (deal.PrimarySecondaryCoPromoter__c == 'Primary' && deal.PrimarySecondaryCoPromoter__c != null && deal.CoPromoter__c != LIVENATIONACCOUNTID){
                        system.debug('primary sibling deal = ' + deal);
                        if (deal.EventLoss__c != null) {
                            TotalPrimaryEventLoss += deal.EventLoss__c;
                        }
                        if (deal.EventProfit__c != null) {
                            TotalPrimaryEventProfit += deal.EventProfit__c;
                        }
                        if (deal.ExpenseAdjustmentLoss__c != null) {
                            TotalPrimaryExpenseAdjustmentLoss += deal.ExpenseAdjustmentLoss__c;
                        }
                        if (deal.ExpenseAdjustmentProfit__c != null) {
                            TotalPrimaryExpenseAdjustmentProfit += deal.ExpenseAdjustmentProfit__c;
                        }
                        if (deal.AncillaryRevenue__c != null) {
                            TotalPrimaryAncillaryRevenue += deal.AncillaryRevenue__c;
                        }
                    } else if (deal.PrimarySecondaryCoPromoter__c == 'Secondary' && deal.PrimarySecondaryCoPromoter__c != null && deal.CoPromoter__c != LIVENATIONACCOUNTID) {
                        system.debug('secondary sibling deal = ' + deal);
                        if (deal.EventLoss__c != null) {
                            TotalSecondaryEventLoss += deal.EventLoss__c;
                        }
                        if (deal.EventProfit__c != null) {
                            TotalSecondaryEventProfit += deal.EventProfit__c;
                        }
                        if (deal.ExpenseAdjustmentLoss__c != null) {
                            TotalSecondaryExpenseAdjustmentLoss += deal.ExpenseAdjustmentLoss__c;
                        }
                        if (deal.ExpenseAdjustmentProfit__c != null) {
                            TotalSecondaryExpenseAdjustmentProfit += deal.ExpenseAdjustmentProfit__c;
                        }
                        if (deal.AncillaryRevenue__c != null) {
                            TotalSecondaryAncillaryRevenue += deal.AncillaryRevenue__c;
                        } 
                    }
                } // end loop of deals related to events
                
                // Update Live Nation Co-Promoter Deals
                for(Deal__c deal : events.get(d.Event__c).Deals__r){
                    if (deal.CoPromoter__c != null && deal.CoPromoter__c == LIVENATIONACCOUNTID && deal.PrimarySecondaryCoPromoter__c == 'Primary' && deal.PrimarySecondaryCoPromoter__c != null){
                        deal.EventLoss__c = 100 - TotalPrimaryEventLoss;
                        deal.EventProfit__c = 100 - TotalPrimaryEventProfit;
                        deal.ExpenseAdjustmentLoss__c = 100 - TotalPrimaryExpenseAdjustmentLoss;
                        deal.ExpenseAdjustmentProfit__c = 100 - TotalPrimaryExpenseAdjustmentProfit;
                        deal.AncillaryRevenue__c = 100 - TotalPrimaryAncillaryRevenue;
                        updatedList.add(deal);
                        system.debug('updated primary deal = ' + deal);
                    } else if (deal.CoPromoter__c != null && deal.CoPromoter__c == LIVENATIONACCOUNTID && deal.PrimarySecondaryCoPromoter__c == 'Secondary' && deal.PrimarySecondaryCoPromoter__c != null){
                        deal.EventLoss__c = 100 - TotalSecondaryEventLoss;
                        deal.EventProfit__c = 100 - TotalSecondaryEventProfit;
                        deal.ExpenseAdjustmentLoss__c = 100 - TotalSecondaryExpenseAdjustmentLoss;
                        deal.ExpenseAdjustmentProfit__c = 100 - TotalSecondaryExpenseAdjustmentProfit;
                        deal.AncillaryRevenue__c = 100 - TotalSecondaryAncillaryRevenue;
                        updatedList.add(deal);
                        system.debug('updated secondary deal = ' + deal); 
                    }
                }
            }
            
        } // end loop of trigger.new Deals
  
        if (updatedList.size() > 0 )
            update updatedList;
            
        return ( updatedList );
    }
    
}