src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <description>Record type for co-promoters related to events and shows</description>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>AncillaryRevenue__c</fullName>
        <label>Ancillary Revenue</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CoPromoter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Promoter</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Co-Promoter Deals</relationshipLabel>
        <relationshipName>CoPromoterDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DownsideRisk__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Downside Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventLoss__c</fullName>
        <label>Event Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EventProfit__c</fullName>
        <label>Event Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentLoss__c</fullName>
        <label>Expense Adjustment Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentProfit__c</fullName>
        <label>Expense Adjustment Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShareInTalentOverhead__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Share In Talent Overhead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DealSettlementLedger__c.object
<CustomObject>
    <description>Junction object linking the Deal with Ledger Entries so settlement values can be planned and settled upon per Deal</description>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentAtSellout__c</fullName>
        <formula>IF(!Share__c, 0,
   IF(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,
      IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c - LedgerEntry__r.PrimaryCoProShareAtSellout__c
      ),
      0
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <formula>text( Deal__r.PrimarySecondaryCoPromoter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Share</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>LedgerEntry__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Settlement-Ledger</label>
    <nameField>
        <displayFormat>DSL-{000000}</displayFormat>
        <label>Deal Settlement-Ledger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Settlement-Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalSupportActExpenses__c</fullName>
        <description>Total Support Act Expenses</description>
        <label>Total Support Act Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustment__c</fullName>
        <label>Expense Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentatSellout__c</fullName>
        <label>Expense Adjustment at Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InHouseatSellout__c</fullName>
        <label>In House at Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferAtSellout__c</fullName>
        <label>Offer At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettleAtActual__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Settle At Actual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_DealSettlementSSID_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_DealSettlementSSID_Test {
	
	public static final String GL_CODE_LEDGER_ENTRY = '40205';//'50103';
	
	public static final String CO_PRO_1 = 'Co Pro 1';
	public static final String CO_PRO_2 = 'Co Pro 2';
	
	static String RT_EXPENSES = 'LedgerEntry__c.Expenses';
	static String RT_ANCILLARY = 'LedgerEntry__c.Ancillary';
	static String RT_COPROMOTER = 'Account.CoPromoter';
	static String RT_DEAL_COPROMOTER = 'Deal__c.CoPromoter';
    
	static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
	    new String[]{ RT_EXPENSES, RT_ANCILLARY, RT_COPROMOTER, RT_DEAL_COPROMOTER }
    );
	
	static Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
    static Id RT_ANCILLARY_ID = recordTypeMap.get( RT_ANCILLARY );
    static Id RT_ACCOUNT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
    static Id RT_DEAL_COPROMOTER_ID = recordTypeMap.get( RT_DEAL_COPROMOTER );
    
    public static Event__c currentEvent;
	
	public static final String CURRENT_EVENT_NAME = 'MyTestEvent';
	
	@testSetup
	static void setup(){
		
		Event__c event = new LNE_TestObjectFactory(
	        LNE_TestObjectFactory.createEvent()
		).addProperties( new Map<String,Object>{
			'EventName__c' => CURRENT_EVENT_NAME,
		    'Status__c' => 'Draft',
		    'TotalSupportActExpenses__c' => 0.0
		}).buildEvent();
		
		LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet( event );
	}

    class TestSettings {
    	
    	Map<String,GLAccount__c> glAccountsMap = LNE_Util.getGLAccounts(new String[] { GL_CODE_LEDGER_ENTRY });
    	
    	Account copro1, copro2;
    	Event__c event;
    	Deal__c currentDeal;
    	Deal__c newDeal;
    	LedgerEntry__c currentLedger;
    	DealSettlementLedger__c currentDSL;

        public TestSettings() {
        	
        	//-- disable the financial calculator for this test.
        	//-- it isn't needed, and only makes the test take longer.
        	LNE_FinancialCalculator.currentlyRunning = true;
			
            this.event = [ SELECT Id, EventName__c
            	FROM event__c
            	limit 1
            ];
            
            //-- generated from createStandardDataSet 
            Set<String> coProNames = new Set<String>{ CO_PRO_1, CO_PRO_2 };
            for( Account coPro: [SELECT Id, Name FROM Account WHERE name in :coProNames ]){
            	if( CO_PRO_1.equals( coPro.Name ) ){
            		this.copro1 = coPro;
            	} else if( CO_PRO_2.equals( coPro.name )){
            		this.copro2 = coPro;
            	}
            }

            glAccountsMap = LNE_Util.getGLAccounts(new String[] { GL_CODE_LEDGER_ENTRY });
            
            System.debug( 'glAccountsMap' );
            System.debug( glAccountsMap );
            
            //-- based on LNE_LedgerEntryDSLCreateDelete_T
            //-- appears to require that the recordTYpe is CoPromoter and the CoPromoter is not liveNation.
            this.currentLedger = new LedgerEntry__c(
	            GLAccount__c = glAccountsMap.get( GL_CODE_LEDGER_ENTRY ).Id,
	            Event__c = event.Id,
	            RecordTypeId = RT_ANCILLARY_ID,
	            SettleAtActual__c = false,
	            ExpenseAdjustment__c = 333,
	            OfferAtSellout__c = 200, // OfferAtSellout__c - InHouseatSellout__c = le.ExpenseAdjustmentatSellout__c //calculated in FC
	            InHouseatSellout__c = 100,
	            SourceSystemId__c = '309576-50138'
	        );
	        insert this.currentLedger;
	        
	        //-- based on LNE_LedgerEntryDSLCreateDelete_T
            //-- appears to require RecordType of Ancillary and appropriate GL CODE
            this.currentDeal = new Deal__c (
				Event__c = event.Id,
				Type__c = '3rd Party',
				CoPromoter__c = copro1.id,
				EventProfit__c = 50,
				EventLoss__c = 50,
				ExpenseAdjustmentProfit__c = 50,
				ExpenseAdjustmentLoss__c = 50,
				AncillaryRevenue__c = 50,
				PrimarySecondaryCoPromoter__c = 'Primary',
				ShareInTalentOverhead__c = True,
				DownsideRisk__c = True,
				RecordTypeId = RT_DEAL_COPROMOTER_ID,
				SourceSystemId__c = 'Deal-123423'
            );
            insert this.currentDeal;
            System.debug( 'currentDeal' );
            System.debug( currentDeal );
            
            //-- @TODO: support testing updates updates the SourceSystemId more thoroughly.
            //-- initial attempt seems to cause an exception where the account BillingCountryCode is null,
            //-- but it isn't null when trying it before..?
            /*
            this.newDeal = new Deal__c (
				Event__c = event.Id,
				Type__c = '3rd Party',
				CoPromoter__c = this.copro2.id,
				EventProfit__c = 50,
				EventLoss__c = 50,
				ExpenseAdjustmentProfit__c = 50,
				ExpenseAdjustmentLoss__c = 50,
				AncillaryRevenue__c = 50,
				PrimarySecondaryCoPromoter__c = 'Primary',
				ShareInTalentOverhead__c = True,
				DownsideRisk__c = True,
				RecordTypeId = RT_DEAL_COPROMOTER_ID,
				SourceSystemId__c = 'Deal-789789'
            );
            //insert this.newDeal;
            */
        }
        
        public void setupWithExistingDSL(){
        	System.debug( 'ledgerEntries' );
	        System.debug( [ SELECT Id, SourceSystemId__c from LedgerEntry__c ] );
	        
        	//-- dsl created for us.
        	//currentDSL = new DealSettlementLedger__c(
        	//	LedgerEntry__c = this.currentLedger.Id,
        	//	Deal__c = this.currentDeal.Id,
        	//	Share__c = false
        	//);
        	
        	this.currentDSL = [ SELECT Id, LedgerEntry__c, Deal__c, SourceSystemId__c
	        	FROM DealSettlementLedger__c
	        	WHERE LedgerEntry__c = :this.currentLedger.Id and Deal__c = :this.currentDeal.Id
	        	LIMIT 1
	        ];
        }
		
		public void finalize(){
			/*
			System.debug( 'ledgerEntries' );
	        System.debug( [ SELECT Id, SourceSystemId__c from LedgerEntry__c ] );
	        
	        System.debug( 'My Ledger Entry' );
	        System.debug( this.currentLedger );
	        
	        System.debug( 'MY Deal' );
	        System.debug( this.currentDeal );
	        
	        System.debug( 'currentDSL' );
	        System.debug( this.currentDSL );
	        
	        System.debug( 'ALLDSLs' );
	        System.debug( [ SELECT id, LedgerEntry__c, Deal__c, SourceSystemId__c from DealSettlementLedger__c ] );
	        
	        System.debug( 'what we want:' );
	        System.debug( [ SELECT Id, LedgerEntry__c, Deal__c, SourceSystemId__c
	        	FROM DealSettlementLedger__c
	        ]);
	        */
		}
    }
    
	
    //-- test test methods here
	
	static testMethod void setupDSL_WithExistingRecord() {
        TestSettings ts = new TestSettings();
    	ts.setupWithExistingDSL();
    	ts.finalize();
    	
    	System.debug( 'setupWithoutExceptions:' ); System.debug( ts.currentDSL );
    	
    	System.assert( ts.currentDSL != null, 'There must be a currentDSL made to get to this point' );
    	
        System.assert( true, 'No Exceptions have occurred in getting here' );
	}
	
	static testMethod void testExistingDSL_SourceSystemId(){
		TestSettings ts = new TestSettings();
        ts.setupWithExistingDSL();
        ts.finalize();
        
        //-- because we are querying, we assume that one is automatically created because of existing triggers.
        //-- so we use it.
        System.assert( ts.currentDSL != null, 'A DSL must have been generated at this point' );
        
        String expectedSourceSystemId = 'Deal-123423-309576-50138';
        System.assert( expectedSourceSystemId.equals( ts.currentDSL.SourceSystemId__c ), 'SourceSystemId__c must be the DealSSID-EventSSID');
	}
	
	//-- @TODO: support testing updated SourceSystemId more thoroughly.
}