src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BackendPercent__c</fullName>
        <label>Backend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SplitBackendPercent__c</fullName>
        <label>Split Backend %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SplitPercentage__c</fullName>
        <label>Split %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SplitHeadlinerPayouts_C_Test.cls
/**
 * Test class for LNE_SplitHeadlinerPayouts_C
 * @author Vinay
 * US648
 * @version - us648 
 **/
@isTest
private class LNE_SplitHeadlinerPayouts_C_Test
{
	
	@testSetup
    static void globalSetup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
    }

	class TestSettings {
        public TestSettings() {
            //-- global setup here//-- we don't need the financial calculator to run until we're done with all this
            
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );

		}

        //-- whatever your setups, and you can make it as varied as you'd like.
        public void typicalSetup(){
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Artist'});         
            Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );

            Event__c event = [Select Id, Status__c from Event__c limit 1];
            Account artist = [Select Id, Name from Account where RecordTypeId =: RT_ACCOUNT_ARTIST_ID limit 1];
            // Deal - Co Headliner
            Deal__c deal = new Deal__c();
            deal.Event__c = event.Id;
            deal.Type__c = 'Co-Headliner';
            deal.Artist__c = artist.Id;
            deal.GuaranteeAmount__c = 1000;
            deal.dealType__c = 'Flat';
            deal.DealCalculation__c = 'Guarantee Only';
            deal.StageType__c = 'Plan';
            
            LNE_FinancialCalculator.runUpdates = true;
            insert deal;
        }

        public void finalize(){
            //-- always should be called.
            
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		} 
	}

    //-- test setups here to find out if errors have nothing to do with the test.
    static testMethod void runSetupAWithoutException() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
        System.assert( true, 'No Exceptions have occurred in getting here' );
    }

    //-- test method with only one primary headliner with no co Headliner, assert page error messages.
    static testMethod void testWithOnlyPrimaryHeadliner() {
        TestSettings ts = new TestSettings();
        //ts.typicalSetup();
        ts.finalize();
        
        Event__c event = [Select Id, Status__c from Event__c limit 1];
        test.startTest();
            Test.setCurrentPage(Page.LNE_SplitHeadlinerPayouts);
            ApexPages.currentPage().getParameters().put('eventId', event.Id);
            ApexPages.currentPage().getParameters().put('stageType', 'Plan');
        	LNE_SplitHeadlinerPayouts_C lneSplitHeadlinerPayoutsController = new LNE_SplitHeadlinerPayouts_C();
        	lneSplitHeadlinerPayoutsController.init();
        test.stopTest();

        System.assert(ApexPages.hasMessages()); 
        List<Apexpages.Message> msgs = ApexPages.getMessages();
		boolean b = false;
		for(Apexpages.Message msg:msgs){
		    if (msg.getDetail().contains('Atleast one Primary and one Co-Headliner should exist.')) b = true;
		}
		system.assert(b);
    }

    //-- test method to check for positive use case of positive split percentage adding to 100%
    static testMethod void testWithPrimaryandCoHeadlinerPositive() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
        
        Event__c event = [Select Id, Status__c from Event__c limit 1];
        List<Id> dealIds = new List<Id>();
        test.startTest();
            Test.setCurrentPage(Page.LNE_SplitHeadlinerPayouts);
            ApexPages.currentPage().getParameters().put('eventId', event.Id);
            ApexPages.currentPage().getParameters().put('stageType', 'Plan');
            LNE_SplitHeadlinerPayouts_C lneSplitHeadlinerPayoutsController = new LNE_SplitHeadlinerPayouts_C();
            lneSplitHeadlinerPayoutsController.init();

            for(Deal__c deal : lneSplitHeadlinerPayoutsController.headlinerList){
                deal.SplitPercentage__c  = 50;
                dealIds.add(deal.Id);
            }  

            lneSplitHeadlinerPayoutsController.save();

        test.stopTest();

        //assert no errors and split are set.
        List<Deal__c> dealList = [SELECT Id, BackendPercent__c, Artist__c, Artist__r.Name, SplitPercentage__c
                                                          , SplitBackendPercent__c, Type__c FROM Deal__c where Id IN :dealIds];
        system.assertNOTEquals(NULL, dealList);
        for(Deal__c deal : dealList){
            system.assertEquals(50, deal.SplitPercentage__c);
        }
    }

    //-- test method to check for negative use case of split percentage not adding to 100%
    static testMethod void testWithPrimaryandCoHeadlinerNot100() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
        
        Event__c event = [Select Id, Status__c from Event__c limit 1];
        List<Id> dealIds = new List<Id>();
        test.startTest();
            Test.setCurrentPage(Page.LNE_SplitHeadlinerPayouts);
            ApexPages.currentPage().getParameters().put('eventId', event.Id);
            ApexPages.currentPage().getParameters().put('stageType', 'Plan');
            LNE_SplitHeadlinerPayouts_C lneSplitHeadlinerPayoutsController = new LNE_SplitHeadlinerPayouts_C();
            lneSplitHeadlinerPayoutsController.init();

            for(Deal__c deal : lneSplitHeadlinerPayoutsController.headlinerList){
                deal.SplitPercentage__c  = 10;
                dealIds.add(deal.Id);
            }  

            lneSplitHeadlinerPayoutsController.save();

        test.stopTest();
        System.assert(ApexPages.hasMessages()); 
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        boolean b = false;
        for(Apexpages.Message msg:msgs){
            if (msg.getDetail().contains('The Split % must total to 100%')) b = true;
        }
        system.assert(b);
    }

    //-- test method to check for negative use case of negative split percentage.
    static testMethod void testWithPrimaryandCoHeadlinerNegative() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
        
        Event__c event = [Select Id, Status__c from Event__c limit 1];
        List<Id> dealIds = new List<Id>();
        test.startTest();
            Test.setCurrentPage(Page.LNE_SplitHeadlinerPayouts);
            ApexPages.currentPage().getParameters().put('eventId', event.Id);
            ApexPages.currentPage().getParameters().put('stageType', 'Plan');
            LNE_SplitHeadlinerPayouts_C lneSplitHeadlinerPayoutsController = new LNE_SplitHeadlinerPayouts_C();
            lneSplitHeadlinerPayoutsController.init();

            for(Deal__c deal : lneSplitHeadlinerPayoutsController.headlinerList){
                deal.SplitPercentage__c  = -10;
                dealIds.add(deal.Id);
            }  

            lneSplitHeadlinerPayoutsController.save();
            lneSplitHeadlinerPayoutsController.cancel();

        test.stopTest();
        System.assert(ApexPages.hasMessages()); 
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        boolean b = false;
        for(Apexpages.Message msg:msgs){
            if (msg.getDetail().contains('The Split % must be positive')) b = true;
        }
        system.assert(b);
    }

}