src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryHeadlinerArtist__c</fullName>
        <description>Automatically populated via trigger on Deal and Event PB Flow</description>
        <label>Primary Headliner Artist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SettlementTotalSupportActExpenses__c</fullName>
        <label>Settlement Total Support Act Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalSupportActExpenses__c</fullName>
        <description>Total Support Act Expenses</description>
        <label>Total Support Act Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryHeadlinerArtist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Headliner Artist</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Artist does not exist or does not match search entry.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Artist</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times (Primary Headliner Artist)</relationshipLabel>
        <relationshipName>PrimaryHeadlinerEventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>San Francisco</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_SupportDealsSummary_T_Test.cls
@isTest
private class LNE_SupportDealsSummary_T_Test {
    static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';
    static final String RT_VENDOR = 'Account.Vendor';
    
    class TestSettings {
        Event__c Evt1;
        Account venue;
        List<Account> artists;
        
        List<Event__c> primaryHeadlinerEvents;
        List<EventDateTime__c> primaryHeadlinerEventDateTimes;

        List<Event__c> rentalEvents;
        List<EventDateTime__c> rentalEventDateTimes;
        
        public TestSettings() {
        
            //-- global setup here

            //create account__c(venue)
            venue = LNE_TestObjectFactory.createAccount('Test Venue');
            Id venueRecordTypeId = [select Id from RecordType where Name = 'Venue' and SobjectType = 'Account'].Id;
            venue.RecordTypeId = venueRecordTypeId;
            venue.Format__c = 'Country';
            venue.Market__c = 'San Francisco';
            venue.BillingStreet = 'One Market';
            venue.BillingCity = 'San Francisco';
            venue.BillingState = 'California';
            venue.BillingPostalCode = '94105';
            insert venue;

            //create artists
            artists = new Account[]{
				LNE_TestObjectFactory.createAccount( 'Artist1' ),
				LNE_TestObjectFactory.createAccount( 'Artist2' ),
                LNE_TestObjectFactory.createAccount( 'Artist3' )
			};  
            insert artists;

            //----------------------------------------------------------------------------------------
            //create primary headliner events
            primaryHeadlinerEvents = new List<Event__c>();
            Id promotedShowRecordId = [select Id from RecordType where Name = 'Promoted Show' and SobjectType = 'Event__c'].Id;
            for(Account a : artists){
                Event__c event = new Event__c(
                    ProjectedPaidTickets__c = 20000,
                    ProjectedDropCount__c = 30000,
                    status__c = 'Draft',
                    Venue__c = venue.Id,
                    RecordTypeId = promotedShowRecordId
                );
                primaryHeadlinerEvents.add(event);
            }
            insert primaryHeadlinerEvents;

            //create primary headliner event date times
            primaryHeadlinerEventDateTimes = new List<EventDateTime__c>();
            Integer index = 0;
            for(Event__c e : primaryHeadlinerEvents){
                EventDateTime__c edt = new EventDateTime__c(
                    EventName__c = 'Test Event',
                    EventDate__c = Date.today() + 14,
                    Event__c = e.Id,
                    PrimaryHeadlinerArtist__c = artists[index].Id,
                    Venue__c = venue.Id
                );
                primaryHeadlinerEventDateTimes.add(edt);
            }

            //----------------------------------------------------------------------------------------
            //create rental events
            rentalEvents = new List<Event__c>();
            Id rentalRecordId = [select Id from RecordType where Name = 'Rental' and SobjectType = 'Event__c'].Id;
            for(Account a : artists){
                Event__c event = new Event__c(
                    ProjectedPaidTickets__c = 20000,
                    ProjectedDropCount__c = 30000,
                    status__c = 'Draft',
                    Venue__c = venue.Id,
                    RecordTypeId = rentalRecordId
                );
                rentalEvents.add(event);
            }
            insert rentalEvents;

            //create rental event date times
            rentalEventDateTimes = new List<EventDateTime__c>();
            index = 0;
            for(Event__c e : rentalEvents){
                EventDateTime__c edt = new EventDateTime__c(
                    EventName__c = 'Test Event',
                    EventDate__c = Date.today() + 14,
                    Event__c = e.Id,
                    PrimaryHeadlinerArtist__c = artists[index].Id,
                    Venue__c = venue.Id
                );
                rentalEventDateTimes.add(edt);
                index += 1;
            }
            insert rentalEventDateTimes;

            //TODO: This needs to be moved down the the testMethod, apply adequate and appropriate assertions
            Deal__c testDeal1 = new Deal__c(Type__c='Primary Headliner',  Artist__c = primaryHeadlinerEventDateTimes[0].PrimaryHeadlinerArtist__c, GuaranteeAmount__c = 200, DealType__c = 'Flat', DealCalculation__c = 'Guarantee Only', Event__c = primaryHeadlinerEventDateTimes[0].Event__c, StageType__c = 'Plan');
           	
            insert testDeal1;
            
            Deal__c testDeal2 = new Deal__c(Type__c='Support', Artist__c = rentalEventDateTimes[0].PrimaryHeadlinerArtist__c, GuaranteeAmount__c = 200, DealType__c = 'Flat', DealCalculation__c = 'Guarantee Only', Event__c = rentalEventDateTimes[0].Event__c);
            
            insert testDeal2;
           
        }
        
        public List<EventDateTime__c> typicalSetup(){
            return rentalEventDateTimes;
                
        }
        
        public void finalize(){
        }
    }
    
    //-- test functionality here
    
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    static testMethod void testPrimaryHeadliner() {
        TestSettings ts = new TestSettings();
        List<EventDateTime__c> rentalEventDateTimes = ts.typicalSetup();
        
        Test.startTest();
        Deal__c testDeal3 = new Deal__c(Type__c='Support', StageType__c='Plan', Artist__c = rentalEventDateTimes[1].PrimaryHeadlinerArtist__c, GuaranteeAmount__c = 200, DealType__c = 'Flat', DealCalculation__c = 'Guarantee Only', Event__c = rentalEventDateTimes[1].Event__c);
        Deal__c testDeal4 = new Deal__c(Type__c='Support', StageType__c='Settlement', Artist__c = rentalEventDateTimes[1].PrimaryHeadlinerArtist__c, GuaranteeAmount__c = 444, DealType__c = 'Flat', DealCalculation__c = 'Guarantee Only', Event__c = rentalEventDateTimes[1].Event__c);
		insert new List<Deal__c>{testDeal3,testDeal4};
       
        Test.stopTest();
        
        Event__c newEvt1 = [SELECT TotalSupportActExpenses__c, SettlementTotalSupportActExpenses__c FROM Event__c WHERE Id =: rentalEventDateTimes[1].Event__c ];
        System.assertEquals(newEvt1.TotalSupportActExpenses__c, 200);
        System.assertEquals(newEvt1.SettlementTotalSupportActExpenses__c, 444);
    }
}