src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventFirstDate__c</fullName>
        <label>Event First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventTitle__c</fullName>
        <formula>Name &amp; &quot; - &quot; &amp; EventName__c</formula>
        <label>Event Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryHeadlinerArtist__c</fullName>
        <description>Automatically populated via trigger on Deal and Event PB Flow</description>
        <label>Primary Headliner Artist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>FilterArtist__c</fullName>
        <description>The Tour daily auto association process will include this Artist&apos;s name in its search of Events to associate.</description>
        <label>Filter Artist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterExpirationDate__c</fullName>
        <description>Until the date in this field, the Tour daily auto association process will include this record&apos;s filter criteria in its search of Events to associate.</description>
        <label>Filter Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FilterStartDate__c</fullName>
        <description>The Tour daily auto association process will include this date as the earliest show date in its search of Events to associate.</description>
        <label>Filter Start Date</label>
        <type>Date</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_EventAutoMatchTour_Batch_Test.cls
@IsTest
private class LNE_EventAutoMatchTour_Batch_Test {
	
	final static Id ACCOUNT_VENUE_RECTYPE_ID;

	static {

		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 
			'Account.Venue'
		});

		ACCOUNT_VENUE_RECTYPE_ID = recordTypeMap.get('Account.Venue');

	}
	
	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
	}

	class TestSettings {

		public Tour__c tour {get;set;}
		public Event__c event {get;set;}
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'Test_Class' );
		}
		
		public TestSettings typicalSetup(){

			// create Account Artist
			Account artist = [select Name from Account where Name = 'Pennyback'];
			this.event = [select EventTitle__c, Name, PrimaryHeadlinerArtist__c from Event__c limit 1];
			this.event.PrimaryHeadlinerArtist__c = artist.Name;
			this.event.EventFirstDate__c = System.today();
			update this.event;

			// create a Tour__c
			this.tour = LNE_TestObjectFactory.createTour('Name', artist.Id);
			this.tour.FilterExpirationDate__c = System.today().addDays(1);
			this.tour.FilterArtist__c = artist.Name;
			this.tour.FilterStartDate__c = System.today().addDays(-1);
			insert this.tour;

			return this;
			
		}
		
		public TestSettings finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
			return this;
		}
	}

	private static testMethod void test_EventAutoMatchTour_Batch() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();

		Test.startTest();

		new LNE_EventAutoMatchTour_Batch().execute(null);

		Test.stopTest();

	}

}