src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <description>Record type for co-promoters related to events and shows</description>
        <label>Co-Promoter</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>BuySell</fullName>
        <active>true</active>
        <description>Event where Live Nation is not managing production but contractually supporting</description>
        <label>Buy Sell</label>
    </recordTypes>
    <recordTypes>
        <fullName>Festival</fullName>
        <active>true</active>
        <description>All-day or multi-day event featuring multiple artists usually with multiple stages</description>
        <label>Festival</label>
    </recordTypes>
    <recordTypes>
        <fullName>GospelBrunch</fullName>
        <active>true</active>
        <description>House of Blues promoted event for Sunday gospel performance</description>
        <label>Gospel Brunch</label>
    </recordTypes>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CoPromoteExpense</fullName>
        <active>true</active>
        <description>Expenses associated with co-promoter deals</description>
        <label>Co Promote Expense</label>
    </recordTypes>
    <recordTypes>
        <fullName>CoPromoteRevenue</fullName>
        <active>true</active>
        <description>Revenues associated with co-promoter deals</description>
        <label>Co Promote Revenue</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>TalentFees</fullName>
        <active>true</active>
        <description>Expenses associated with artist deals</description>
        <label>Talent Fees</label>
    </recordTypes>
    <recordTypes>
        <fullName>TicketRevenue</fullName>
        <active>true</active>
        <description>Revenue from ticket sales</description>
        <label>Ticket Revenue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_RT.cls
public class LNE_RT {
	
	public static String RT_COPROMOTER = 'Account.CoPromoter';
	public static String RT_ARTIST = 'Account.Artist';
	public static String RT_OFFICE = 'Account.Office';
	public static String RT_VENUE = 'Account.Venue';
	
    public static String RT_BUYSELL = 'Event__c.BuySell';
    public static String RT_RENTAL = 'Event__c.Rental';
    public static String RT_PROMOTEDSHOW = 'Event__c.PromotedShow';
    public static String RT_GOSPELBRUNCH = 'Event__c.GospelBrunch';
    public static String RT_FESTIVAL = 'Event__c.Festival';
    
    public static String RT_ANCILLARY = 'LedgerEntry__c.Ancillary';
    public static String RT_COGS = 'LedgerEntry__c.COGS';
    public static String RT_TICKETREVENUE = 'LedgerEntry__c.TicketRevenue';
    public static String RT_EXPENSES = 'LedgerEntry__c.Expenses';
    public static String RT_CONTRA = 'LedgerEntry__c.Contra';
    public static String RT_COPROMOTE_EXPENSE = 'LedgerEntry__c.CoPromoteExpense';
    public static String RT_COPROMOTE_REVENUE = 'LedgerEntry__c.CoPromoteRevenue';
    public static String RT_OTHER = 'LedgerEntry__c.Other';
    public static String RT_TALENT_FEES = 'LedgerEntry__c.TalentFees';
    
    private static Map<String,Id> pRecordTypeMap = null;
	public static Map<String,Id> recordTypeMap {
		get {
			if (pRecordTypeMap == null) {
				pRecordTypeMap = LNE_Util.getRecordTypes(
	            	new String[]{ 
	            	    RT_COPROMOTER, RT_ARTIST, RT_OFFICE, RT_VENUE, 
	            	    RT_BUYSELL, RT_RENTAL,  RT_PROMOTEDSHOW, RT_GOSPELBRUNCH, 
	            		RT_ANCILLARY, RT_COGS,RT_TICKETREVENUE, RT_EXPENSES, RT_CONTRA, RT_FESTIVAL, RT_COPROMOTE_EXPENSE,
                        RT_COPROMOTE_REVENUE, RT_OTHER, RT_TALENT_FEES});
			}
			return pRecordTypeMap;
		}
	}
	
	public static Id RT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
	public static Id RT_ARTIST_ID = recordTypeMap.get( RT_ARTIST );
	public static Id RT_OFFICE_ID = recordTypeMap.get( RT_OFFICE );
	public static Id RT_VENUE_ID = recordTypeMap.get( RT_VENUE );
	
	public static Id RT_BUYSELL_ID = recordTypeMap.get( RT_BUYSELL );
    public static Id RT_RENTAL_ID = recordTypeMap.get( RT_RENTAL );
    public static Id RT_PROMOTEDSHOW_ID = recordTypeMap.get( RT_PROMOTEDSHOW );
    public static Id RT_GOSPELBRUNCH_ID = recordTypeMap.get( RT_GOSPELBRUNCH );
    public static Id RT_FESTIVAL_ID = recordTypeMap.get(RT_FESTIVAL);
        
    public static Id RT_ANCILLARY_ID = recordTypeMap.get( RT_ANCILLARY );
    public static Id RT_COGS_ID = recordTypeMap.get( RT_COGS );
    public static Id RT_TICKETREVENUE_ID = recordTypeMap.get( RT_TICKETREVENUE );
    public static Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
    public static Id RT_CONTRA_ID = recordTypeMap.get( RT_CONTRA );	
    public static Id RT_COPROMOTE_EXPENSE_ID = recordTypeMap.get( RT_COPROMOTE_EXPENSE );
    public static Id RT_COPROMOTE_REVENUE_ID = recordTypeMap.get( RT_COPROMOTE_EXPENSE );
    public static Id RT_OTHER_ID = recordTypeMap.get( RT_OTHER );
    public static Id RT_TALENT_FEES_ID = recordTypeMap.get( RT_TALENT_FEES );
}