src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BackendPercent__c</fullName>
        <label>Backend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DealApplicationType__c</fullName>
        <label>Deal Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DealType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>To Be Shared Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>2</defaultValue>
        <description>Ordinal number that represents the artist&apos;s rank in the event lineup</description>
        <label>Rank</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_CopyPrimaryHeadlinerToCoH_T_Test.cls
@isTest
private class LNE_CopyPrimaryHeadlinerToCoH_T_Test {
	
	@testSetup
    static void setup(){
        LNE_FinancialCalculator.currentlyRunning = true;
        LNE_TestObjectFactory.prepStandardCustomSettings();
        
        LNE_TestObjectFactory.VenueHierarchy acctHierarchy = LNE_TestObjectFactory.createVenueHierarchy(
            	LNE_TestObjectFactory.ACCT_TYPE_DIVISION, null, null
            );
        
        LNE_TestObjectFactory.createStandardDataSet( null, acctHierarchy );

        Deal__c testDeal1 = [SELECT Id FROM Deal__c WHERE Type__c = 'Primary Headliner' LIMIT 1];
        testDeal1 = new Deal__c(Id = testDeal1.Id,
                                Rank__c = 1,
                                GuaranteeAmount__c = 200,
                                DealType__c = 'Retro Gross Deal',
                                DealCalculation__c = 'Guarantee Only',
                                BackendPercent__c = 1,
                                DealApplicationType__c = 'Paid Tickets',
                                StageType__c = 'Plan');

        update testDeal1;
    }
    
    class TestSettings {
        Event__c testEvent;
        Account testArtist;

        public TestSettings() {

            LNE_FinancialCalculator.currentlyRunning = true;

            testEvent = [SELECT Id FROM Event__c LIMIT 1];
            
            Account[] artists = new Account[]{
                LNE_TestObjectFactory.createAccount( 'Artist1' ),
                LNE_TestObjectFactory.createAccount( 'Artist2' ),
                LNE_TestObjectFactory.createAccount( 'Artist3' )
            };
                
            insert artists;

            testArtist = artists[2];
            
            Deal__c testDeal2 = new Deal__c(Type__c='Co-Headliner',
                                            Rank__c = 2,
                                            Artist__c = artists[1].Id,
                                            GuaranteeAmount__c = 200,
                                            DealType__c = 'Step Up Gross Deal',
                                            DealCalculation__c = 'Inclusive of Other Talent Amount',
                                            Event__c = testEvent.Id,
                                            BackendPercent__c = 2,
                                            DealApplicationType__c = 'To Be Shared Amount',
                                            StageType__c = 'Plan');

            Deal__c testDeal3 = new Deal__c(Type__c='Primary Headliner',
                                            Rank__c = 3,
                                            Artist__c = artists[2].Id,
                                            GuaranteeAmount__c = 200,
                                            DealType__c = 'Step Up Net Deal',
                                            DealCalculation__c = 'Inclusive of Sound & Lights',
                                            Event__c = testEvent.Id,
                                            BackendPercent__c = 3,
                                            DealApplicationType__c = 'To Be Shared Amount',
                                            StageType__c = 'Settlement');

            insert new List<Deal__c>{testDeal2, testDeal3};
        }
        
        public void typicalSetup(){
                
        }
        
        public void finalize(){
        }
    }
    
    /**
     *  Test: The Co-Headliner records copy the values for the Deal Type, Deal Application Type, Backend %, and Deal Calculation 
     *          from the Primary Headliner record and updates after save of the Primary Headliner
     */ 
    static testMethod void testInsertPrimaryHeadliner() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        
        Test.startTest();

        Deal__c testDeal4 = new Deal__c(Type__c='Co-Headliner',
                                        Rank__c = 3,
                                        Artist__c = ts.testArtist.Id,
                                        GuaranteeAmount__c = 200,
                                        DealType__c = 'Retro Net Deal',
                                        DealCalculation__c = 'Inclusive of Support',
                                        Event__c = ts.testEvent.Id,
                                        BackendPercent__c = 4,
                                        DealApplicationType__c = 'Paid Tickets',
                                        StageType__c = 'Settlement');
        insert testDeal4;

        List<Deal__c> results = [SELECT Type__c,
                                        StageType__c,
                                        DealType__c,
                                        DealApplicationType__c,
                                        BackendPercent__c,
                                        DealCalculation__c
                                 FROM Deal__c
                                 WHERE Event__c = :ts.testEvent.Id AND Type__c IN ('Primary Headliner','Co-Headliner')];
        System.assertEquals(4, results.size());

        for (Deal__c d : results) {
            if (d.Type__c == 'Primary Headliner') {
                if (d.StageType__c == 'Plan') {
                    system.assertEquals('Retro Gross Deal', d.DealType__c);
                    system.assertEquals('Paid Tickets', d.DealApplicationType__c);
                    system.assertEquals(1, d.BackendPercent__c);
                    system.assertEquals('Guarantee Only', d.DealCalculation__c);
                }

                if (d.StageType__c == 'Settlement') {
                    system.assertEquals('Step Up Net Deal', d.DealType__c);
                    system.assertEquals('To Be Shared Amount', d.DealApplicationType__c);
                    system.assertEquals(3, d.BackendPercent__c);
                    system.assertEquals('Inclusive of Sound & Lights', d.DealCalculation__c);
                }
            }

            if (d.Type__c == 'Co-Headliner') {
                if (d.StageType__c == 'Plan') {
                    system.assertEquals('Retro Gross Deal', d.DealType__c);
                    system.assertEquals('Paid Tickets', d.DealApplicationType__c);
                    system.assertEquals(1, d.BackendPercent__c);
                    system.assertEquals('Guarantee Only', d.DealCalculation__c);
                }

                if (d.StageType__c == 'Settlement') {
                    system.assertEquals('Step Up Net Deal', d.DealType__c);
                    system.assertEquals('To Be Shared Amount', d.DealApplicationType__c);
                    system.assertEquals(3, d.BackendPercent__c);
                    system.assertEquals('Inclusive of Sound & Lights', d.DealCalculation__c);
                }
            }
        }

        Test.stopTest();
    }
}