src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_TourRoutingMarketing_C_Test.cls
@IsTest
private class LNE_TourRoutingMarketing_C_Test {
	
	final static Id ACCOUNT_VENUE_RECTYPE_ID;

	static {

		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 
			'Account.Venue'
		});

		ACCOUNT_VENUE_RECTYPE_ID = recordTypeMap.get('Account.Venue');

	}
	
	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
	}

	class TestSettings {

		public Tour__c tour {get;set;}
		public AdPlan__c adplan {get;set;}
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
		}
		
		public TestSettings typicalSetup(){

			// create Account Artist
			Account artist = [select Id from Account where Name = 'Pennyback'];
			Event__c event = [select Id from Event__c limit 1];

			// create a Tour__c
			this.tour = LNE_TestObjectFactory.createTour('Name', artist.Id);
			insert this.tour;

			// create ad plan
			this.adplan = LNE_TestObjectFactory.createAdPlan('Name', 10000, event.Id, this.tour.Id);
			insert this.adplan;

			this.adplan = [select Name from AdPlan__c where Id = :this.adplan.Id];

			return this;
			
		}
		
		public TestSettings finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
			return this;
		}
	}
	
	//-- test test methods here
	static testMethod void test_TourRoutingMarketing_Instance() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();
		
		PageReference pr = Page.LNE_TourRoutingMarketing;
		pr.getParameters().put('id', ts.tour.Id);
		Test.setCurrentPage(pr);

		ApexPages.StandardController sc = new ApexPages.StandardController(ts.tour);
		LNE_TourRoutingMarketing_C cx = new LNE_TourRoutingMarketing_C(sc);

		List<SelectOption> divisions = cx.getDivisions();
		System.assert(!divisions.isEmpty());

		List<SelectOption> venues = cx.getVenueTypes();
		System.assert(!venues.isEmpty());

	}

	static testMethod void test_TourRoutingMarketing_Assoc() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();
		Map<Id,String> result = LNE_TourRoutingMarketing_C.associateAdPlansToTour(new List<Id> { ts.adplan.Id }, ts.tour.Id);

	}

	static testMethod void test_TourRoutingMarketing_Artists() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();
		List<String> artists = LNE_TourRoutingMarketing_C.searchArtists('Penny');

	}

	static testMethod void test_TourRoutingMarketing_SOSL() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();

		List<AdPlan__c> adplans = LNE_TourRoutingMarketing_C.getAdPlans(ts.tour.Id);
		//System.assert(!adplans.isEmpty());

		LNE_TourRoutingMarketing_C.SearchTerms terms = new LNE_TourRoutingMarketing_C.SearchTerms();
		terms.adplanName = 'Name';

		List<AdPlan__c> searchSOSL = LNE_TourRoutingMarketing_C.searchAdPlans(terms, null);
		////System.assert(!searchSOSL.isEmpty());
		
	}

	static testMethod void test_TourRoutingMarketing_SOQL1() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();

		LNE_TourRoutingMarketing_C.SearchTerms terms = new LNE_TourRoutingMarketing_C.SearchTerms();
		terms.adplanId = ts.adplan.Name;

		List<AdPlan__c> searchSOQL0 = LNE_TourRoutingMarketing_C.searchAdPlans(terms, null);

	}

	static testMethod void test_TourRoutingMarketing_SOQL2() {

		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();

		Account venue = [select Type from Account where RecordTypeId = :ACCOUNT_VENUE_RECTYPE_ID];
		LNE_TourRoutingMarketing_C.SearchTerms terms = new LNE_TourRoutingMarketing_C.SearchTerms();
		terms.venueType = venue.Type;

		List<AdPlan__c> searchSOQL1 = LNE_TourRoutingMarketing_C.searchAdPlans(terms, null);

	}

}