src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>AdPlanName__c</fullName>
        <label>Ad Plan Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LNEAdPlanBudget__c</fullName>
        <label>LNE Ad Plan Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StandaloneDate__c</fullName>
        <label>Standalone Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TourBudget__c</fullName>
        <label>Tour Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TourName__c</fullName>
        <formula>Tour__r.TourName__c</formula>
        <label>Tour Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <description>Local record type designated for marketing plans to a specific region</description>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>BuyingGroup__c</fullName>
        <label>Buying Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BuyingGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LNEMarketingBudget__c</fullName>
        <label>LNE Marketing Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TourHeadliner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Headliner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Artist</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tours (Tour Headliner)</relationshipLabel>
        <relationshipName>Tours1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TourName__c</fullName>
        <label>Tour Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/BuyingGroup.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Canada Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Comedy Touring</fullName>
    </customValue>
    <customValue>
        <fullName>EDM Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Global Touring</fullName>
    </customValue>
    <customValue>
        <fullName>NAC Touring</fullName>
    </customValue>
    <customValue>
        <fullName>T&amp;C Touring</fullName>
    </customValue>
    <customValue>
        <fullName>Local Offer</fullName>
    </customValue>
    <masterLabel>Buying Group</masterLabel>
</GlobalValueSet>

src/classes/LNE_AdPlanFieldRollup_T_Test.cls
@IsTest(SeeAllData=false)
private class LNE_AdPlanFieldRollup_T_Test {

	static final String TOUR_NAME = 'TOUR_NAME';
	
	@testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        //LNE_TestObjectFactory.createMarketingUser('mktusr');
    }
	
	class TestSettings {
		public Account testArtist;
		public Tour__c testTour;

		public TestSettings(){
			//User marketingUser = [select id from user where alias = 'mktusr'];
			Account artist = LNE_TestObjectFactory.createAccount('Account.Name');
			//artist.OwnerId = marketingUser.Id;
			insert artist;
			this.testArtist = artist;

			Tour__c tour = new Tour__c(
				TourName__c = TOUR_NAME,
				TourHeadliner__c = artist.Id,
				BuyingGroup__c = 'Local Offer'
			);
			insert tour;
			this.testTour = tour;
		}
	}
	
	static testMethod void test_AdPlanFieldRollup() {

		TestSettings ts = new TestSettings();

		Decimal budgetVal = 10;

		// get tour
		Tour__c tour = ts.testTour;

		// build multiple ad plans
		List<AdPlan__c> adPlans = new List<AdPlan__c>();
		for (Integer i = 0; i < 2; i++) {
			adPlans.add(new AdPlan__c(
				Tour__c = tour.Id,
				TourBudget__c = budgetVal,
				LNEAdPlanBudget__c = budgetVal,
				AdPlanName__c = 'test adplan',
				StandaloneDate__c = Date.today() + 30
			));
		}

		// insert ad plans
		insert adPlans;

		// refetch tour, assert correct value
		tour = [select LNEMarketingBudget__c from Tour__c where Id = :tour.Id];
		
		//TODO: fix this assertion, expected value is not correct
		//System.assertEquals(budgetVal * adPlans.size(), tour.LNEMarketingBudget__c);

		adPlans[0].TourBudget__c = 0;
		update adPlans;

		//TODO: add assertions after this operation

	}

}