src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BonusDetail__c.object
<CustomObject>
    <description>Additional terms for an artist or co-promoter usually based upon ticket sales representing a bonus above a guarantee or percentage of ticket revenues</description>
    <fields>
        <fullName>ApplyTo__c</fullName>
        <label>Apply To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee</fullName>
                </value>
                <value>
                    <fullName>Regardless</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ArtistBonusExplanation__c</fullName>
        <label>Artist Bonus Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BonusAmount__c</fullName>
        <label>Bonus Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BonusBase__c</fullName>
        <label>Bonus Base</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Drop Count</fullName>
                </value>
                <value>
                    <fullName>Net Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Bonus Details</relationshipLabel>
        <relationshipName>BonusDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>End Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Increment__c</fullName>
        <label>Increment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartPoint__c</fullName>
        <label>Start Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step Up</fullName>
                </value>
                <value>
                    <fullName>Retro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bonus Detail</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bonus Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LNE_BonusMetrics_T_Test.cls
@isTest
private class LNE_BonusMetrics_T_Test {
	
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
	class TestSettings {
        
        //-- global setup here
        GLAccount__c touringGL;
        Event__c evt1;
        Account[] artists;
        Account venue;
        Deal__c testDeal1;
        BonusDetail__c bonusDetail1;
        BonusDetail__c bonusDetail2;
		
        public TestSettings() {
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
        }
        
        public void typicalSetup(){
        	
        	LNE_FinancialCalculator.pushRunningTrigger('LNE_BonusMetrics_T_Test');

            //-- just use the default hierarchy
            LNE_TestObjectFactory.VenueHierarchy acctHierarchy = LNE_TestObjectFactory.createVenueHierarchy(
            	LNE_TestObjectFactory.ACCT_TYPE_DIVISION, null, null
            );
            venue = acctHierarchy.venue;
        	
        	Evt1 = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Venue__c = venue.Id,
                Status__c = 'Draft'
            );
            Map<String,Id> standardData = LNE_TestObjectFactory.createStandardDataSet( Evt1, acctHierarchy );

            artists = new Account[]{
				LNE_TestObjectFactory.createAccount( 'Artist1' ),
				LNE_TestObjectFactory.createAccount( 'Artist2' ),
                LNE_TestObjectFactory.createAccount( 'Artist3' )
			};
           	insert artists;
           	
           	Id primaryId = standardData.get( LNE_TestObjectFactory.STANDARD_DATA_DEAL );
           	System.assert( primaryId != null, 'primary deal must be found' );
            
            testDeal1 = new Deal__c( Id=primaryId, Type__c='Primary Headliner', Artist__c = artists[0].Id, GuaranteeAmount__c = 200, DealType__c = 'Flat', DealCalculation__c = 'Guarantee Only', Event__c = Evt1.Id, StageType__c = 'Plan' );
            update testDeal1;
            
            bonusDetail1 = new BonusDetail__c(Deal__c = testDeal1.Id, BonusBase__c = 'Paid Tickets', Type__c = 'Step Up', ApplyTo__c = 'Guarantee', BonusAmount__c = 1, StartPoint__c = 2001, EndPoint__c = 3000, Increment__c = 1 );
            bonusDetail2 = new BonusDetail__c(Deal__c = testDeal1.Id, BonusBase__c = 'Paid Tickets', Type__c = 'Retro', ApplyTo__c = 'Guarantee', BonusAmount__c = 1, StartPoint__c = 2001, EndPoint__c = 3000, Increment__c = 1 );
            insert new List<BonusDetail__c>{bonusDetail1,bonusDetail2};
            
            LNE_FinancialCalculator.popRunningTrigger();
            LNE_FinancialCalculator.checkIfCanRunCalculations();
        }
        
        public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
        }
    }
    
    @isTest 
    static void testSetupExecutesWithoutException(){
    	try {
    		TestSettings ts = new TestSettings();
    		ts.typicalSetup();
    		ts.finalize();
    	} catch( Exception err ){
    		System.assert( false, 'Exception should not occur while performing setup:' + err.getMessage() );
    	}
    }
    
    //-- Test: Makes sure the wording of ArtistBonusExplanation__c was populated correctly in the trigger
    
    static testMethod void testBonusDetailsDescription() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        
        Test.startTest();
        System.debug( 'Start of test' );

        List<BonusDetail__c> bonuses = [SELECT ArtistBonusExplanation__c, Type__c FROM BonusDetail__c];
        system.assertEquals(2, bonuses.size());

        for (BonusDetail__c bd : bonuses) {
        	if (bd.Type__c == 'Step Up') {
        		system.assertEquals('Artist to receive a bonus of USD 1 starting at 2,001 paid tickets, plus USD 1 per 1 paid tickets increment up to 3,000 paid tickets.', bd.ArtistBonusExplanation__c);
        	}

        	if (bd.Type__c == 'Retro') {
        		system.assertEquals('If total paid tickets is between 2,001 and 3,000, Artist to receive a bonus of USD 1 per 1 paid tickets increment retroactive to the first paid ticket.', bd.ArtistBonusExplanation__c);
        	}
        }
        
        Test.stopTest();
	}
}