src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>2</defaultValue>
        <description>Ordinal number that represents the artist&apos;s rank in the event lineup</description>
        <label>Rank</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventAssociatedArtists_T.cls
public class LNE_EventAssociatedArtists_T {
    static final String RT_Deal_Artist = 'Deal__c.Artist';
    
    /**
    *  Build and update Event Artist(s) field contains all the names of the Artists with Deal records for the Event
    *  @param newList Deal__c[]
    *  @param oldMap Map<Id,Deal__c>
    *  @return Deal__c[] - list of ledger entries updated.
    **/
    public static Deal__c[] execute( Deal__c[] newList, Deal__c[] oldList, Map<Id,Deal__c> oldMap ){
		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{ RT_Deal_Artist }
		);
		Id RT_DEAL_ARTIST_ID = recordTypeMap.get( RT_Deal_Artist );
		
		List<Deal__c> triggerList = new List<Deal__c>();
        Set<Id> eventIds = new Set<Id>();
        
        /**
        *    All the deals that were added/changed
        */
        if (Trigger.isDelete) {
            triggerList = oldList;
        } else if( Trigger.isInsert ){
            triggerList = newList;
        } else {
        	triggerList = new Deal__c[]{};
        	Deal__c oldDeal;
        	
        	//-- PR: can we have this work only if something changes on the deal? perhaps no? based on the comment below?
        	//-- all of them will be filtered to only those by the deal artist id below anyway.
        	for( Deal__c newDeal : newList ){
        		if( oldMap.containsKey( newDeal.Id )){
        			oldDeal = oldMap.get( newDeal.Id );
        			if((oldDeal.RecordTypeId != newDeal.RecordTypeId ||
                        oldDeal.Artist__c != newDeal.Artist__c) &&
                        newDeal.RecordTypeId == RT_DEAL_ARTIST_ID) {

        				triggerList.add( newDeal );
        			}
        		}
        	}
        }
        
        //-- short circuit if no changes
        if( triggerList == null || triggerList.size() < 1 ){
        	return null;
        }

        for (Deal__c d : triggerList) {
            if (d.Event__c != null) {
                eventIds.add(d.Event__c);
            }
        }
        
        List<Event__c> events = [SELECT Id, (SELECT Artist__c, Artist__r.Name, Event__c
                                             FROM Deals__r
                                             WHERE Type__c IN ('Primary Headliner','Co-Headliner','Support') 
                                             AND StageType__c = 'Plan'
                                             ORDER BY Rank__c)
                                 FROM Event__c
                                 WHERE Id IN :eventIds];

        for (Event__c e : events) {
            //-- we use a List to keep the original order of the Deals/Artists
            //-- (SOQL query ordered by Rank__c)
            List<String> artists = new List<String>();

            //-- we use a Set to keep the potential duplicates out
            Set<String> artistSet = new Set<String>();

            for (Deal__c d : e.Deals__r) {
                if (!artistSet.contains(d.Artist__r.Name)) {
                    artistSet.add(d.Artist__r.Name);
                    artists.add(d.Artist__r.Name);
                }
            }

            e.Artists__c = String.join(artists, '\n');
        }

        update events;

        return null;
    }
}