src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LNEAPIId__c</fullName>
        <description>Livenation.comAPI Id</description>
        <externalId>true</externalId>
        <label>LNE API Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_API_UpdatePurchaseURL_C_Test.cls
@isTest
private class LNE_API_UpdatePurchaseURL_C_Test {

    @testSetup
    static void setup() {
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    private class TestSettings {
        public Map<String, Id> setupData() {
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{'Account.Venue', 'Event__c.PromotedShow'});   
            Id rtPromotedId = recordTypeMap.get('Event__c.PromotedShow');
            
    		Event__c testEvent = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = 'Pending Likely',
               	RecordTypeId = rtPromotedId,
               	EventLastDate__c = System.today().addDays(-1)
            );
            
            List<Event__c> events = new List<Event__c>{testEvent};
            return LNE_TestObjectFactory.createStandardDataSetList(events);
        }
    }

	private static testMethod void testSetEventLiveNationId() {
	    TestSettings ts = new TestSettings();
	    Map<String, Id> objectToId = ts.setupData();
        
        Test.startTest();
        
        Tour__c tour = LNE_TestObjectFactory.createTour('test tour', objectToId.get('artist'));
        insert tour;
        
        AdPlan__c plan = LNE_TestObjectFactory.createAdPlan('test ad plan', 10000, objectToId.get('event-0'), tour.Id);
        insert plan;      
        
        LNE_API_UpdatePurchaseURL_C.setEventLiveNationId(plan.Id, 'some-fake|;test-data');
        
        AdPlan__c updatedPlan = [SELECT PurchaseURL__c, Event__c FROM AdPlan__c WHERE Id = :plan.Id];
        Event__c updatedEvent = [SELECT PurchaseURL__c, LNEAPIID__c FROM Event__c WHERE Id = :updatedPlan.Event__c];
        
        System.assertEquals('some-fake', updatedPlan.PurchaseURL__c);
        System.assertEquals('some-fake', updatedEvent.PurchaseURL__c);
        System.assertEquals('test-data', updatedEvent.LNEAPIID__c);
        Test.stopTest();
	}
	
	private static testMethod void testSearchEvents() {
	    TestSettings ts = new TestSettings();
	    Map<String, Id> objectToId = ts.setupData();
        
        Test.startTest();
        
        Tour__c tour = LNE_TestObjectFactory.createTour('test tour', objectToId.get('artist'));
        insert tour;
        
        AdPlan__c plan = LNE_TestObjectFactory.createAdPlan('test ad plan', 10000, objectToId.get('event-0'), tour.Id);
        insert plan;  
        
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{'Account.Venue', 'Event__c.PromotedShow', 'Account.Artist'}); 
        Id rtVenueId = recordTypeMap.get('Account.Venue');	    
        Id rtArtistId = recordTypeMap.get('Account.Artist');
        
	    List<Account> venues = [SELECT Id FROM Account WHERE RecordTypeId = :rtVenueId];
	    List<Account> artists = [SELECT Id FROM Account WHERE RecordTypeId = :rtArtistId];
	    
	    venues.get(0).LNEAPIID__c = 'ven_15056';
	    update venues;
	    
	    artists.get(0).LNEAPIID__c = 'art_15056';
	    update artists;        
        
        List<LNE_API_UpdatePurchaseURL_C.EventResult> results = LNE_API_UpdatePurchaseURL_C.searchEvents(plan.Id);
        System.assertNotEquals(0, results.size());	   
        Test.stopTest();
	}
	
	private static testMethod void testCheckIfUserCanEditCurrentRecord() {
	    TestSettings ts = new TestSettings();
	    Map<String, Id> objectToId = ts.setupData();
        
        Test.startTest();
        
        Tour__c tour = LNE_TestObjectFactory.createTour('test tour', objectToId.get('artist'));
        insert tour;
        
        AdPlan__c plan = LNE_TestObjectFactory.createAdPlan('test ad plan', 10000, objectToId.get('event-0'), tour.Id);
        insert plan;  
        
        Boolean result = LNE_API_UpdatePurchaseURL_C.checkIfUserCanEditCurrentRecord(plan.Id);
        System.assertEquals(true, result);	    
        Test.stopTest();
	}

}