src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementReportSetupTab_CX_Test.cls
@isTest
public class LNE_SettlementReportSetupTab_CX_Test {
	
	static final String RT_VENDOR = 'Account.Vendor';
	static final String RT_Rental = 'Event__c.Rental';
    static final String RT_Hold = 'Event__c.Hold';

    class TestSettings {
    	public Event__c event;

    	public TestSettings(){

    		LNE_TestObjectFactory.createStandardDataSet();

	        this.event = Database.query('select ' + String.join(LNE_Util.getFieldsForObject('Event__c'),',') + ' from Event__c limit 1');
	    }
    }

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    @isTest
    static void testSettlementReportSetupTab(){
        TestSettings ts = new TestSettings();
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementReportSetupTab_CX cx = new LNE_SettlementReportSetupTab_CX(sc);
        cx.startSettlement();

        //TODO: Add Assertions
    }

    static testMethod void testScenario() {
        TestSettings ts = new TestSettings();
        Test.startTest();
        
        Event__c testEvent = [select Id from Event__c limit 1];
        Deal__c testDeal = [select Id from Deal__c where Event__c = :testEvent.Id limit 1];

        PageReference pr = Page.LNE_EventOfferSheet;
        pr.getParameters().put('id', testEvent.Id);
        Test.setCurrentPage(pr);

        ApexPages.StandardController sc = new ApexPages.StandardController(testEvent);
        LNE_SettlementReportSetupTab_CX cx = new LNE_SettlementReportSetupTab_CX(sc);

        cx.selectedDealIds = testDeal.Id;
        cx.saveDeals();
        
    }

}