src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Advertisement__c.object
<CustomObject>
    <description>Ads that are planned to be run as part of a marketing plan</description>
    <fields>
        <fullName>AAARate__c</fullName>
        <label>AAA Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AdSize__c</fullName>
        <label>Ad Size</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <label>Announcement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AnnouncementType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ApplyNet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply Net?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BuyType__c</fullName>
        <label>Buy Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Buy</fullName>
                    <default>true</default>
                    <label>Regular Buy</label>
                </value>
                <value>
                    <fullName>Pkg. Deal (date range)</fullName>
                </value>
                <value>
                    <fullName>Pkg. Deal (select dates)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CalculatedGross__c</fullName>
        <formula>CASE(RecordType.DeveloperName,
&quot;Radio&quot;,
IF(ISPICKVAL(BuyType__c, &quot;Regular Buy&quot;),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100) * NumberofSpots__c,
    Rate__c * NumberofSpots__c
  ),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100),
    Rate__c
  )
),

&quot;Digital&quot;,
Gross__c,

&quot;Television&quot;,
IF(ISPICKVAL(BuyType__c, &quot;Regular Buy&quot;),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100) * NumberofSpots__c,
    Rate__c * NumberofSpots__c
  ),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100),
    Rate__c
  )
),

&quot;Print&quot;,
IF(ISPICKVAL(BuyType__c, &quot;Regular Buy&quot;),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100) * NumberofSpots__c,
    Rate__c * NumberofSpots__c
  ),
  IF(ApplyNet__c,
    Rate__c / (1 - EffectiveCommission__c * 100),
    Rate__c
  )
),

&quot;Outdoor&quot;,
IF(ApplyNet__c,
  Rate__c / (1 - EffectiveCommission__c * 100) * NumberofLocations__c,
  Rate__c * NumberofLocations__c
),

&quot;ProductionMiscellaneous&quot;,
Gross__c,

0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculated Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CampaignType__c</fullName>
        <label>Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>App Install</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>AUDIO &amp; BANNER</fullName>
                </value>
                <value>
                    <fullName>AUDIO ONLY</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>DIRECT BUY</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>FBEvent - buyticketslink</fullName>
                </value>
                <value>
                    <fullName>FBEvent - description</fullName>
                </value>
                <value>
                    <fullName>FBX</fullName>
                </value>
                <value>
                    <fullName>NATIVE</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page image</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page link</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page video</fullName>
                </value>
                <value>
                    <fullName>Paid - dark post</fullName>
                </value>
                <value>
                    <fullName>Paid - link post</fullName>
                </value>
                <value>
                    <fullName>Paid - Lncom</fullName>
                </value>
                <value>
                    <fullName>Paid - photo</fullName>
                </value>
                <value>
                    <fullName>Paid - promotion</fullName>
                </value>
                <value>
                    <fullName>Paid - Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Paid - text only</fullName>
                </value>
                <value>
                    <fullName>Paid - video</fullName>
                </value>
                <value>
                    <fullName>PRE ROLL</fullName>
                </value>
                <value>
                    <fullName>Rich Media</fullName>
                </value>
                <value>
                    <fullName>RTB BUY</fullName>
                </value>
                <value>
                    <fullName>RTB DSP</fullName>
                </value>
                <value>
                    <fullName>RTB VID</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Digital Production Expense</fullName>
                </value>
                <value>
                    <fullName>Display Advertising</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Advertising</fullName>
                </value>
                <value>
                    <fullName>National Allocation - Digital</fullName>
                </value>
                <value>
                    <fullName>Radio Streaming</fullName>
                </value>
                <value>
                    <fullName>Search Advertising</fullName>
                </value>
                <value>
                    <fullName>Social Advertising</fullName>
                </value>
                <value>
                    <fullName>Video Advertising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EffectiveCommission__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Effective Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenseType__c</fullName>
        <label>Expense Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MarketingExpenseType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FormatSize__c</fullName>
        <label>Format / Size</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gross__c</fullName>
        <label>Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HasNonLNEBudget__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the Advertisement is associated with a Non LNE Budget
(Used to support roll-up-summary filtering)</description>
        <inlineHelpText>Whether the Advertisement is associated with a Non LNE Budget</inlineHelpText>
        <label>Has Non LNE Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Albany</fullName>
                </value>
                <value>
                    <fullName>Albuquerque</fullName>
                </value>
                <value>
                    <fullName>Amarillo</fullName>
                </value>
                <value>
                    <fullName>Ames</fullName>
                </value>
                <value>
                    <fullName>Anchcorage, AK</fullName>
                </value>
                <value>
                    <fullName>Appleton</fullName>
                </value>
                <value>
                    <fullName>Aspen</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Augusta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Banff</fullName>
                </value>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Beaumont</fullName>
                </value>
                <value>
                    <fullName>Billings</fullName>
                </value>
                <value>
                    <fullName>Biloxi</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Boise</fullName>
                </value>
                <value>
                    <fullName>Bonnyville</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Bozeman</fullName>
                </value>
                <value>
                    <fullName>Brandon</fullName>
                </value>
                <value>
                    <fullName>Branson</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Burlington, VT</fullName>
                </value>
                <value>
                    <fullName>Burnaby</fullName>
                </value>
                <value>
                    <fullName>Calgary</fullName>
                </value>
                <value>
                    <fullName>Charleston, SC</fullName>
                </value>
                <value>
                    <fullName>Charleston, WV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterAdForSplit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The first Advertisement record created which is then split for cost to multiple Ad Plans</description>
        <label>Master Ad for Split</label>
        <referenceTo>Advertisement__c</referenceTo>
        <relationshipLabel>Advertisements</relationshipLabel>
        <relationshipName>SplitWithAds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net__c</fullName>
        <label>Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Advertisement</label>
    <nameField>
        <displayFormat>Adv-{000000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertisements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/AnnouncementType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Announce</fullName>
    </customValue>
    <customValue>
        <fullName>Presale</fullName>
    </customValue>
    <customValue>
        <fullName>Onsale</fullName>
    </customValue>
    <customValue>
        <fullName>Middle</fullName>
    </customValue>
    <customValue>
        <fullName>Closing</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <description>Map advertisements to marketing phases/general timing</description>
    <masterLabel>Announcement Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/globalValueSets/MarketingExpenseType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertising Materials Production</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Flyer &amp; Poster Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Flyer &amp; Poster Production</fullName>
    </customValue>
    <customValue>
        <fullName>Graphic/Digital Design</fullName>
    </customValue>
    <customValue>
        <fullName>National Allocation - Misc</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Press Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Public Relations</fullName>
    </customValue>
    <customValue>
        <fullName>Tour Launch</fullName>
    </customValue>
    <description>Classification for advertising production or miscellaneous costs</description>
    <masterLabel>Marketing Expense Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_AdvertisementSplit_CX.cls
/** 
 *	Controller Extension for the LNE_AdvertisementSplit VF page
 *
 *	@author Scott Will
 *  @group Controller
 **/
 public with sharing class LNE_AdvertisementSplit_CX {

	public Advertisement__c masterAdvertisement { get; private set; }

	/**
	 *  Constructor
	 *  @param sc ApexPages.StandardController
	 *  @return n/a
	**/
	public LNE_AdvertisementSplit_CX(ApexPages.StandardController sc) {

		// we need to work from the Master Advertisement's perspective.  if the sc record has
		// a MasterAdForSplit__c value then use that record instead.
		Advertisement__c ad = (Advertisement__c)sc.getRecord();
		Id recordId = ad.MasterAdForSplit__c == null
			? ad.Id
			: ad.MasterAdForSplit__c;

		this.masterAdvertisement = getMasterAdvertisement(recordId);

	}

	/**
	 *  Returns the "master" advertisement record
	 *  @param recordId Id
	 *  @return Advertisement__c - the Master Advertisement
	**/
	private static Advertisement__c getMasterAdvertisement(Id recordId) {
		return [
			select
				AAARate__c,
				AdSize__c,
				AnnouncementType__c,
				ApplyNet__c,
				BuyType__c,
				CalculatedGross__c,
				CampaignType__c,
				Channel__c,
				Commission__c,
				Date__c,
				EffectiveCommission__c,
				EndDate__c,
				EndTime__c,
				ExpenseType__c,
				Format__c,
				FormatSize__c,
				Gross__c,
				HasNonLNEBudget__c,
				Market__c,
				MediaTypeFormat__c,
				Net__c,
				Notes__c,
				NumberofClicks__c,
				NumberofImpressions__c,
				NumberofLocations__c,
				NumberofSpots__c,
				Program__c,
				Rate__c,
				RecordTypeId,
				Section__c,
				SpotType__c,
				StartDate__c,
				StartTime__c,
				Vendor__c,
				Vendor__r.Name
			from Advertisement__c
			where Id = :recordId
		];
	}

	/**
	 *  Returns a package of related Advertisements
	 *  @param masterAdvertisementId Id
	 *  @return AdvertisementPackage
	**/
	@RemoteAction
	public static AdvertisementPackage getRelatedAdvertisements(Id masterAdvertisementId) {

		Decimal netAmount = 0;
		List<Advertisement> advertisements = new List<Advertisement>();
		for (Advertisement__c ad : [
			select
				AdPlan__c,
				AdPlan__r.AdPlanName__c,
				AdPlan__r.Event__r.Status__c,
				AdPlan__r.EventName__c,
				AdPlan__r.PublicOnSale__c,
				AdPlan__r.Venue__c,
				MasterAdForSplit__c,
				CalculatedNet__c,
				SplitAmount__c,
				SplitPct__c,
				Vendor__c,
				(
					select
						AdPlan__c,
						AdPlan__r.AdPlanName__c,
						AdPlan__r.Event__r.Status__c,
						AdPlan__r.EventName__c,
						AdPlan__r.PublicOnSale__c,
						AdPlan__r.Venue__c,
						MasterAdForSplit__c,
						SplitAmount__c,
						SplitPct__c,
						Vendor__c
					from SplitWithAds__r
					order by AdPlan__r.AdPlanName__c
				)
			from Advertisement__c
			where Id = :masterAdvertisementId
		]) {

			// if no children and splitamount is empty then make it ready
			if (ad.SplitAmount__c == null && ad.SplitWithAds__r.isEmpty()) {
				ad.SplitAmount__c = ad.CalculatedNet__c;
				ad.SplitPct__c = 100;
			}
			// add master ad as first item
			advertisements.add(new Advertisement(ad));
			// set expected total
			netAmount = ad.CalculatedNet__c;
			// add ad splits to list
			for (Advertisement__c child : ad.SplitWithAds__r) {
				advertisements.add(new Advertisement(child));				
			}

		}

		return new AdvertisementPackage(advertisements, netAmount);

	}

	/**
	 *  Returns a list of new instances of Advertisements
	 *  @param adplanIdsList Id[] - list of related adplans to associate
	 *  @param masterAdvertisementId Id - the master advertisement
	 *  @return Advertisement[] - list of new Advertisement instances
	**/
	@RemoteAction
	public static List<Advertisement> createAdvertisements(List<Id> adplanIdsList, Id masterAdvertisementId) {

		Advertisement__c masterAdvertisement = getMasterAdvertisement(masterAdvertisementId);
		
		Set<Id> adplanIds = new Set<Id>(adplanIdsList);
		List<Advertisement> advertisements = new List<Advertisement>();
		for (AdPlan__c adplan : [
			select
				AdPlanName__c,
				Event__r.Status__c,
				EventName__c,
				PublicOnSale__c,
				Venue__c
			from AdPlan__c
			where Id in :adplanIds
			order by AdPlanName__c
		]) {
			advertisements.add(new Advertisement(adplan, masterAdvertisement));
		}

		return advertisements;

	}

	/**
	 *  Saves the list of Advertisements to the database
	 *  @param advertisements Advertisement[] - list of advertisements to upsert or delete
	 *  @param masterAdvertisementId - the master advertisement id
	 *  @return Boolean - success of save
	**/
	@RemoteAction
	public static Boolean saveAdvertisements(List<Advertisement> advertisements, Id masterAdvertisementId) {

		Advertisement__c masterAd = getMasterAdvertisement(masterAdvertisementId);

		List<Advertisement__c> upsertAdvertisements = new List<Advertisement__c>();
		List<Advertisement__c> deleteAdvertisements = new List<Advertisement__c>();

		for (Advertisement ad : advertisements) {

			Advertisement__c advertisement = ad.toAdvertisementSObject();
			// if add is not marked deleted
			if (!ad.isDeleted) {
				// if record id is null then copy from master ad
				if (ad.recordId == null) {
					advertisement.AAARate__c = masterAd.AAARate__c; 
					advertisement.AdSize__c = masterAd.AdSize__c; 
					advertisement.AnnouncementType__c = masterAd.AnnouncementType__c; 
					advertisement.ApplyNet__c = masterAd.ApplyNet__c; 
					advertisement.BuyType__c = masterAd.BuyType__c; 
					advertisement.CampaignType__c = masterAd.CampaignType__c; 
					advertisement.Channel__c = masterAd.Channel__c; 
					advertisement.Commission__c = masterAd.Commission__c; 
					advertisement.Date__c = masterAd.Date__c; 
					advertisement.EffectiveCommission__c = masterAd.EffectiveCommission__c; 
					advertisement.EndDate__c = masterAd.EndDate__c;
					advertisement.EndTime__c = masterAd.EndTime__c; 
					advertisement.ExpenseType__c = masterAd.ExpenseType__c; 
					advertisement.Format__c = masterAd.Format__c; 
					advertisement.FormatSize__c = masterAd.FormatSize__c; 
					advertisement.Gross__c = masterAd.Gross__c; 
					advertisement.HasNonLNEBudget__c = masterAd.HasNonLNEBudget__c; 
					advertisement.Market__c = masterAd.Market__c;  
					advertisement.MediaTypeFormat__c = masterAd.MediaTypeFormat__c; 
					advertisement.Net__c = masterAd.Net__c; 
					advertisement.Notes__c = masterAd.Notes__c; 
					advertisement.NumberofClicks__c = masterAd.NumberofClicks__c; 
					advertisement.NumberofImpressions__c = masterAd.NumberofImpressions__c; 
					advertisement.NumberofLocations__c = masterAd.NumberofLocations__c; 
					advertisement.NumberofSpots__c = masterAd.NumberofSpots__c; 
					advertisement.Program__c = masterAd.Program__c; 
					advertisement.Rate__c = masterAd.Rate__c; 
					advertisement.RecordTypeId = masterAd.RecordTypeId;
					advertisement.Section__c = masterAd.Section__c; 
					advertisement.SpotType__c = masterAd.SpotType__c; 
					advertisement.StartDate__c = masterAd.StartDate__c;
					advertisement.StartTime__c = masterAd.StartTime__c; 
					advertisement.Vendor__c = masterAd.Vendor__c;
				}
				upsertAdvertisements.add(advertisement);
			}
			// only remove if it also has a record id
			else if (ad.recordId != null) {
				deleteAdvertisements.add(advertisement);
			}

		}

		Boolean success = true;
		System.savepoint sp = Database.setSavepoint();

		try {
			if (!upsertAdvertisements.isEmpty()) {
				upsert upsertAdvertisements;
			}

			if (!deleteAdvertisements.isEmpty()) {
				// since the front end already updated the master value then
				// dont allow the trigger to do the same
				LNE_AdvertisementSplits_T.RUN_DELETE_ROLLUP = false;
				delete deleteAdvertisements;
			}
		}
		catch (System.DmlException de) {
			Database.rollback(sp);
			success = false;
		}

		return success;

	}

	/**
	 *  Performs the auto assignment.
	 *  @param term String - the search term
	 *  @param ignoredIdsList Id[] - array of adplan ids to ignore
	 *  @return String[] - a formatted list of found Ad Plans
	**/
	@RemoteAction
	public static List<String> searchAdPlans(String term, List<Id> ignoredIdsList) {

		List<String> results = new List<String>();

		if (String.isNotBlank(term)) {

			String fuzzedTerm = '%' + term + '%';
			Set<Id> ignoredIds = new Set<Id>(ignoredIdsList);

			for (AdPlan__c adplan : [
				select
					AdPlanName__c,
					EventName__c
				from AdPlan__c
				where (AdPlanName__c like :fuzzedTerm or EventName__c like :fuzzedTerm)
				and Id not in :ignoredIds
				order by
					EventName__c,
					AdPlanName__c
			]) {

				// result of "recordID|Event Name - AdPlan Name"
				results.add(String.format('{0}|{1} - {2}', new List<String> {
					adplan.Id,
					adplan.EventName__c,
					adplan.AdPlanName__c
				}));

			}

		}

		return results;

	}

	/**
	 *  Wrapper class for Advertisement__c
	**/
	public class Advertisement {

		public Boolean isDeleted { get; set; }
		public Boolean isMaster { get; set; }
		public Decimal splitAmount { get; set; }
		public Decimal splitPct { get; set; }
		public Id masterId { get; set; }
		public Id parentId { get; set; }
		public Id recordId { get; set; }
		public Id vendorId { get; set; }
		public String adPlanName { get; set; }
		public String eventName { get; set; }
		public String eventStatus { get; set; }
		public String onSaleDate { get; set; }
		public String recUrl { get; set; }
		public String venue { get; set; }

		public Advertisement(Advertisement__c ad) {

			this.adPlanName = ad.AdPlan__r.AdPlanName__c;
			this.eventName = ad.AdPlan__r.EventName__c;
			this.eventStatus = ad.AdPlan__r.Event__r.Status__c;
			this.isDeleted = false;
			this.isMaster = ad.MasterAdForSplit__c == null;
			this.masterId = ad.MasterAdForSplit__c;
			this.onSaleDate = safeDateTimeFormat(ad.AdPlan__r.PublicOnSale__c);
			this.parentId = ad.AdPlan__c;
			this.recordId = ad.Id;
			this.recUrl = new ApexPages.StandardController(new AdPlan__c(Id = ad.AdPlan__c)).view().getUrl();
			this.splitAmount = safeDecimal(ad.SplitAmount__c);
			this.splitPct = safeDecimal(ad.SplitPct__c);
			this.venue = ad.AdPlan__r.Venue__c;

		}

		public Advertisement(AdPlan__c adplan, Advertisement__c masterAd) {

			this.adPlanName = adplan.AdPlanName__c;
			this.eventName = adplan.EventName__c;
			this.eventStatus = adplan.Event__r.Status__c;
			this.isDeleted = false;
			this.isMaster = false;
			this.masterId = masterAd.Id;
			this.onSaleDate = safeDateTimeFormat(adplan.PublicOnSale__c);
			this.parentId = adplan.Id;
			this.recordId = null;
			this.recUrl = '';
			this.splitAmount = 0;
			this.splitPct = 0;
			this.venue = adplan.Venue__c;

		}

		public Advertisement__c toAdvertisementSObject() {

			return new Advertisement__c(
				Id = this.recordId,
				AdPlan__c = this.parentId,
				MasterAdForSplit__c = this.masterId,
				SplitAmount__c = this.splitAmount,
				SplitPct__c = this.splitPct
			);

		}

	}

	/**
	 *  Represents a package of advertisements, along with aggregated metadata
	**/
	public class AdvertisementPackage {

		public List<Advertisement> advertisements { get; set; }
		public Decimal originalTotal { get; set; }

		public AdvertisementPackage(List<Advertisement> advertisements, Decimal netAmount) {

			this.advertisements = advertisements;
			this.originalTotal = netAmount == null ? 0 : netAmount;

		}

	}

	private static String safeDateTimeFormat(Date d) {
		return d == null ? '' : d.format();
	}

	private static Decimal safeDecimal(Decimal d) {
		return d == null ? 0 : d;
	}

}