src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>NoExpectedAncillaries__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Expected Ancillaries</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_AncillaryTab_CX_Test.cls
/**
 *  Test for the Ancillary Tab Control tester.
 *  @author Dominic Aveyard <daveyard@salesforce.com>
 **/
@isTest
private class LNE_AncillaryTab_CX_Test {
    
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet();
    }

	class TestSettings {
		//-- instance values
		GLAccount__c[] newGLAccounts;
		GLAccount__c[] oldGLAccounts;		  
		String[] selectedRoles;
		Map<Id, Account> oldAccountsMap;
		Event__c evnt;
		
		Map<String,GLAccount__c> glAccountMap;
		
		public TestSettings() {
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
			
			//--
			
		    Account office = [select id from account where name = 'US Concerts'];
		    
		    //-- assert there should be only one event created, because it was created from the createStandardDataSet
		    Event__c[] eventsFound = [ select Id, Office__c from Event__c ];
		    System.assert( eventsFound.size() == 1, 'There should only be one event' );
		    this.evnt = eventsFound[0];
		    
		    this.glAccountMap = LNE_Util.getGLAccounts(
		    	new String[]{ LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE, LNE_TestObjectFactory.GL_PARKING_REVENUE }
		    );
		    System.assert( glAccountMap != null && glAccountMap.size() > 0, 'GL Accounts should be created already from the createStandardDataSet method above' );
			Id glAccountId1 = this.glAccountMap.get( LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE ).Id;
			Id glAccountId2 = this.glAccountMap.get( LNE_TestObjectFactory.GL_PARKING_REVENUE ).Id;
			
			LedgerEntry__c ledgerEntry;
			LedgerEntry__c[] newLedgerEntries = new LedgerEntry__c[]{
				//-- first ledger entry
				new LedgerEntry__c(
			        GLAccount__c = glAccountId1,
			        BaseAmount__c = 33343,
			        RateType__c = 'Flat',
			        Event__c = evnt.Id
		        ),
				
				//-- second ledger entry
				new LedgerEntry__c(
			        GLAccount__c = glAccountId2,
			        BaseAmount__c = 33343,
			        RateType__c = 'Flat',
			        Event__c = evnt.Id
		        )
			};
			
			insert newLedgerEntries;
		}
		
		public void typicalSetup(){
		}
		
		public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		}
	}

	static LNE_AncillaryTab_CX setupCtrls(Event__c evnt) {
		ApexPages.currentPage().getParameters().put('id', evnt.Id);
		ApexPages.StandardController standardEventCtlr = new ApexPages.StandardController(evnt);

		LNE_AncillaryTab_CX ancillaryTabCtlr = new LNE_AncillaryTab_CX(standardEventCtlr);

		return ancillaryTabCtlr;
	}

	@isTest static void validateDetermineRelatedAncillariesWNoRel() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();
		LNE_AncillaryTab_CX ancillaryTabCtlr = setupCtrls(ts.evnt);

		Boolean noRelAncillaries = ancillaryTabCtlr.determineRelatedAncillaries();
		Test.stopTest();

		//-- comment out for now
		//System.assertEquals(noRelAncillaries,false);
		System.assert( true, '@TODO: correct above assert' );
	}
	
	@isTest static void validateDetermineRelatedAncillariesWRel() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();
		LNE_AncillaryTab_CX ancillaryTabCtlr = setupCtrls(ts.evnt);

		Boolean noRelAncillaries = ancillaryTabCtlr.determineRelatedAncillaries();
		Test.stopTest();

		System.assert(noRelAncillaries == true);
	}

	@isTest static void validateGetEvent() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();
		LNE_AncillaryTab_CX ancillaryTabCtlr = setupCtrls(ts.evnt);

		Event__c relEvent = ancillaryTabCtlr.getEvent();
		Test.stopTest();

		System.assert( relEvent != null, 'we must get an event when we provide one to the controller setup' );
		System.assert(relEvent.Id == ts.evnt.Id, 'ctrl.getEvent must be equal to the event we supply it' );
		
		System.assertNotEquals( ancillaryTabCtlr.getGridLostFocusPollInterval(), null, 'There should be a focus poll interval' );
		//-- @TODO: and it shouldn't be a string...
	}
	
	@isTest static void validateUpdateEvent() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		
		Test.startTest();
		LNE_AncillaryTab_CX ancillaryTabCtlr = setupCtrls(ts.evnt);
		System.assert(ancillaryTabCtlr.updateEventSuccess == null, 'ancillaryTabCtlr.updateEventSuccess == null.');//-- @TODO: why?

		ancillaryTabCtlr.eventId = ts.evnt.Id;
		ancillaryTabCtlr.eventNoExpectedAncillaries = false;
		ancillaryTabCtlr.updateEvent();
		System.assert(ancillaryTabCtlr.updateEventSuccess == 'true', 'ancillaryTabCtlr.updateEventSuccess = true.');//-- @TODO: why?

		Event__c evntVerify1 = [SELECT Id, NoExpectedAncillaries__c FROM Event__c WHERE Id = :ts.evnt.Id];
		System.assert(evntVerify1.NoExpectedAncillaries__c == false, 'evntVerify1.NoExpectedAncillaries__c == false' );//-- @TODO: why?

		ancillaryTabCtlr.eventNoExpectedAncillaries = true;
		ancillaryTabCtlr.updateEvent();
		System.assert(ancillaryTabCtlr.updateEventSuccess == 'true', 'ancillaryTabCtlr.updateEventSuccess = true. pt B.');//-- @TODO: why?

		Event__c evntVerify2 = [SELECT Id, NoExpectedAncillaries__c FROM Event__c WHERE Id = :ts.evnt.Id];
		System.assert(evntVerify2.NoExpectedAncillaries__c == true, 'evntVerify2.NoExpectedAncillaries__c == true' );//-- @TODO: why?

		Test.stopTest();
	}
}