src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>AdPlanName__c</fullName>
        <label>Ad Plan Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LNEAdPlanBudget__c</fullName>
        <label>LNE Ad Plan Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StandaloneDate__c</fullName>
        <label>Standalone Date</label>
        <type>Date</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Advertisement__c.object
<CustomObject>
    <description>Ads that are planned to be run as part of a marketing plan</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Advertisements</relationshipLabel>
        <relationshipName>Advertisements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BuyType__c</fullName>
        <label>Buy Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Buy</fullName>
                    <default>true</default>
                    <label>Regular Buy</label>
                </value>
                <value>
                    <fullName>Pkg. Deal (date range)</fullName>
                </value>
                <value>
                    <fullName>Pkg. Deal (select dates)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterAdForSplit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The first Advertisement record created which is then split for cost to multiple Ad Plans</description>
        <label>Master Ad for Split</label>
        <referenceTo>Advertisement__c</referenceTo>
        <relationshipLabel>Advertisements</relationshipLabel>
        <relationshipName>SplitWithAds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberofSpots__c</fullName>
        <label># of Spots</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SplitAmount__c</fullName>
        <inlineHelpText>The amount that this advertisement is covering when split with other Ad Plans</inlineHelpText>
        <label>Split Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SplitPct__c</fullName>
        <inlineHelpText>The percentage that this advertisement is covering when split with other Ad Plans</inlineHelpText>
        <label>Split %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advertisements (Vendor)</relationshipLabel>
        <relationshipName>Advertisements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Advertisement</label>
    <nameField>
        <displayFormat>Adv-{000000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertisements</pluralLabel>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <description>Record type for radio advertisements</description>
        <label>Radio</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_AdvertisementSplits_Test.cls
/** 
 *	Test class for the LNE_AdvertisementSplit VF page and LNE_AdvertisementSplit__T class
 *
 *	@author Scott Will
 *  @group Test
 **/
 @IsTest(SeeAllData=false)
private class LNE_AdvertisementSplits_Test {
	
	static final String RT_VENDOR = 'Account.Vendor';
	
	class TestSettings {

		public Advertisement__c masterAd {get;set;}
		public Account vendor {get;set;}
		public AdPlan__c adplan0 {get;set;}
		public AdPlan__c adplan1 {get;set;}
		
		public TestSettings() {

		}
		
		public void typicalSetup(String advertRecordType, Decimal commission){

			//insert vendor
			Map<String,Id> accountRecordTypeMap = LNE_Util.getRecordTypes(
				new String[]{RT_VENDOR}
			);

			ID RT_VENDOR_ID = accountRecordTypeMap.get(RT_VENDOR);

			vendor = LNE_TestObjectFactory.createAccount('Test Vendor');
			vendor.RecordTypeId = RT_VENDOR_ID;
			vendor.Format__c = 'Country';

			insert vendor;

			//insert adplan
			adPlan0 = new AdPlan__c(
				AdPlanName__c = 'Test Ad Plan',
				LNEAdPlanBudget__c = 1000000,
				StandaloneDate__c = Date.today().addDays(7)
			);

			insert adPlan0;

			//insert advertisement

			Id recordTypeId;
			if(advertRecordType != null) recordTypeId =
				[select Name, DeveloperName from RecordType where Name =: advertRecordType and SobjectType = 'Advertisement__c'].Id;
			Date startDate = Date.today();
			Date endDate = startDate.addDays(7);
			
			masterAd = new Advertisement__c(	            
				AdPlan__c =  adPlan0.Id,
				BuyType__c = LNE_Constants.AD_BUY_TYPE_REGULAR,
				StartDate__c = startDate,
				EndDate__c = endDate,
				StartTime__c = '6:00 AM',
				EndTime__c = '10:00 PM',
				Rate__c = 100,
				NumberofSpots__c = 10000,
				Format__c = 'Country',
				Vendor__c = vendor.Id,
				SplitAmount__c = 1000,
				SplitPct__c = 50
			);
			if(recordTypeId != null) masterAd.RecordTypeId = recordTypeId;
			if(commission != null) masterAd.Commission__c = commission;
			insert masterAd;
			
		}

	  public void finalize(){
	  
	  }
	}
	
  //-- test test methods here

	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
	}

	static testMethod void test_AdvertisementSplits_CX() {

		TestSettings ts = new TestSettings();
		ts.typicalSetup('Radio', null);

		PageReference pr = Page.LNE_AdvertisementSplit;
		pr.getParameters().put('id', ts.masterAd.Id);
		Test.setCurrentPage(pr);

		ApexPages.StandardController sc = new ApexPages.StandardController(ts.masterAd);
		LNE_AdvertisementSplit_CX cx = new LNE_AdvertisementSplit_CX(sc);

		LNE_AdvertisementSplit_CX.AdvertisementPackage ap = LNE_AdvertisementSplit_CX.getRelatedAdvertisements(ts.masterAd.Id);
		ap.advertisements.addAll(LNE_AdvertisementSplit_CX.createAdvertisements(new List<Id> { ts.adplan0.Id }, ts.masterAd.Id));
		LNE_AdvertisementSplit_CX.saveAdvertisements(ap.advertisements, ts.masterAd.Id);

		LNE_AdvertisementSplit_CX.searchAdPlans('Test', new List<Id>());

	}

	static testMethod void test_AdvertisementSplits_T() {

		TestSettings ts = new TestSettings();
		ts.typicalSetup('Radio', null);

		//create child ad
		Advertisement__c child = new Advertisement__c(
			AdPlan__c = ts.adplan0.Id,
			MasterAdForSplit__c = ts.masterAd.Id,
			SplitAmount__c = 1000,
			SplitPct__c = 50,
			StartDate__c = System.today(),
			EndDate__c = System.today(),
			Vendor__c = ts.vendor.Id
		);
		insert child;

		//update master
		ts.masterAd.NumberofSpots__c += 1000;
		update ts.masterAd;

		//delete child
		delete child;
		delete ts.masterAd;

	}

}