src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LNEAPIId__c</fullName>
        <description>Livenation.comAPI Id</description>
        <externalId>true</externalId>
        <label>LNE API Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LNEAPITicketMasterId__c</fullName>
        <label>LNE API TicketMaster Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Record type for the artist&apos;s agency to track performance management representation</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <formula>Event__r.Venue__r.VenueName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venue</label>
        <type>Text</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventFirstDate__c</fullName>
        <label>Event First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventTicketAgency__c.object
<CustomObject>
    <description>Links the specific ticket agency event with the event date time(s) through the Event-Ticket junction object</description>
    <fields>
        <fullName>AgencySystemID__c</fullName>
        <label>Agency System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Event-Ticket Agencies</relationshipLabel>
        <relationshipName>EventTicketAgencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Ticket Agency</label>
    <nameField>
        <displayFormat>ETA-{000000}</displayFormat>
        <label>Event-Ticket Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Ticket Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_PurchaseURL_Batch.cls
/** 
 *  Batch Class that populates the Purchase URL field on Events and Ad Plans.
 *  
 *  @Example
 *  LNE_PurchaseURL_Batch b = new LNE_PurchaseURL_Batch();
 *  Id batchProcessId = Database.executeBatch(b, LNE_PurchaseURL_Batch.BATCH_SIZE);
 *  System.debug('batchProcessId:' + batchProcessId);
 *  
 *  @author Phil Rymek <prymek@salesforce.com>
 **/
global with sharing class LNE_PurchaseURL_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global static final Integer BATCH_SIZE = 10;

    global static final String DEFAULT_QUERY = 
        'SELECT Id, ' +
               'Venue__r.LNEAPIID__c, ' +
               'EventFirstDate__c, ' +
               'EventLastDate__c, ' +
               'Venue__r.BillingCountryCode ' +
          'FROM Event__c ' +
         'WHERE (Status__c = \'Pending Likely\' OR Status__c = \'Confirmed\') AND  ' +
               'PurchaseURL__c = null AND ' +
               'Venue__r.LNEAPIID__c != null AND ' +
               'EventLastDate__c >= TODAY';
    
    global String query {get; set;}
    
    private static final String COUNTRY_CODE_CANADA = 'CA';
    private static final String PURCHASE_URL_CANADA = 'http://ticketmaster.ca/event/';
    private static final String PURCHASE_URL_NON_CA = 'http://ticketmaster.com/event/';

    global LNE_PurchaseURL_Batch() {
        this.query = null;
    }
    
    global LNE_PurchaseURL_Batch(String query) {
        this.query = query;
    }
    
    global Database.QueryLocator start(Database.BatchableContext context) {
        if(String.isBlank(query)) {
            query = DEFAULT_QUERY;
        }
        
        return(Database.getQueryLocator(query));
    }
    
    global void execute(Database.BatchableContext context, List<sObject> scope) {
        List<Event__c> events = (List<Event__c>) scope;
        List<Event__c> urlFromAPI = new List<Event__c>();
        List<Event__c> urlFromSFDC = new List<Event__c>();
        Map<Id, Deal__c> eventToPrimaryDeal = getPrimaryDeals(events);
        LNE_API_EventSearchResp response;
        URLSearchInfo info;
        Deal__c primaryDeal;
        
        for(Event__c evt : events) {
            info = new URLSearchInfo(evt);
            primaryDeal = eventToPrimaryDeal.get(evt.Id);
            
            if(primaryDeal != null) {
                response = LNE_EventSearch.getEventsByVenue(
                    primaryDeal.Artist__r.LNEAPIId__c, 
                    '?since=' + info.since + '&until=' + info.until, 
                    info.venueId);  
                
                if(response == null || response.data == null || response.data.isEmpty()) {
                    urlFromSFDC.add(evt);
                    continue;
                }
                    
                String purchaseURL = response.data.get(0).buy_link;
                if(String.isNotBlank(purchaseURL)) {
                    evt.PurchaseURL__c = purchaseURL;
                    urlFromAPI.add(evt);
                } else {
                    urlFromSFDC.add(evt);
                }
            }
        }

        List<Event__c> needsAdPlanUpdated = new List<Event__c>();
        needsAdPlanUpdated.addAll(updateAPIEvents(urlFromAPI));
        needsAdPlanUpdated.addAll(updateUsingAgencyId(urlFromSFDC));
        updateAdPlans(needsAdPlanUpdated);
    }
    
    private void updateAdPlans(List<Event__c> events) {
        List<AdPlan__c> plans = [SELECT Id, Event__c FROM AdPlan__c WHERE Event__c in :events];
        Map<Id, Event__c> idToEvent = new Map<Id, Event__c>(events);
        List<AdPlan__c> toUpdate = new List<AdPlan__c>();
        Event__c evt;
        
        for(AdPlan__c plan : plans) {
            evt = idToEvent.get(plan.Event__c);
            
            if(evt != null && String.isNotBlank(evt.PurchaseURL__c)) {
                plan.PurchaseURL__c = evt.PurchaseURL__c;
                toUpdate.add(plan);
            }
        }
        
        if(!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }
    
    private List<Event__c> updateAPIEvents(List<Event__c> events) {
        if(!events.isEmpty()) {
            update events;
        }        
        
        return events;
    }
    
    private List<Event__c> updateUsingAgencyId(List<Event__c> events) {
        List<Event__c> toUpdate = new List<Event__c>();
        
        if(!events.isEmpty()) {
            Map<Id, String> idToSystemId = new Map<Id, String>();
            String purchaseURL;
            String systemId;
            
            List<EventTicketAgency__c> agencies = 
                [SELECT Id, EventDateTime__r.Event__c, AgencySystemID__c
                   FROM EventTicketAgency__c
                  WHERE EventDateTime__r.Event__c in :events AND 
                        AgencySystemID__c != ''];            
            
            for(EventTicketAgency__c agency : agencies) {
                idToSystemId.put(agency.EventDateTime__r.Event__c, agency.AgencySystemID__c);
            }
            
            for(Event__c evt : events) {
                systemId = idToSystemId.get(evt.Id);
                purchaseURL = generatePurchaseURL(evt, systemId);
                
                if(String.isNotBlank(purchaseURL)) {
                    evt.PurchaseURL__c = purchaseURL;
                    toUpdate.add(evt);
                }
            }
            
            update toUpdate;
        }          
        
        return toUpdate;
    }
    
    public String generatePurchaseURL(Event__c evt, String systemId) {
        if(String.isNotBlank(systemId)) {
            return (evt.Venue__r.BillingCountryCode == COUNTRY_CODE_CANADA ?
                   PURCHASE_URL_CANADA : PURCHASE_URL_NON_CA) + systemId;
        }
        
        return null;
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
    
    private Map<Id, Deal__c> getPrimaryDeals(List<Event__c> events) {
        Map<Id, Deal__c> primaryDeals = new Map<Id, Deal__c>();
        List<Deal__c> deals = 
            [SELECT Id, 
                    Event__c, 
                    Artist__c,
                    Artist__r.LNEAPIId__c,
                    Artist__r.LNEAPITicketMasterId__c
               FROM Deal__c
              WHERE Event__c in :events AND 
                    Type__c = 'Primary Headliner'];
              
        for(Deal__c deal : deals) {
            primaryDeals.put(deal.Event__c, deal);
        }
        
        return primaryDeals;
    }
    
    public class URLSearchInfo {
        public String venueId {get; set;}
        public String since {get; set;}
        public String until {get; set;}
        public Event__c evt {get; set;}
        
        public URLSearchInfo(Event__c evt) {
            this.evt = evt;
        
            venueId = getVenueId();
            since = getSinceDate();
            until = getUntilDate();
        }
        
        private String getVenueId() {
            return evt.Venue__r.LNEAPIID__c;
        }
        
        private String getSinceDate() {
            return String.valueOf(evt.EventFirstDate__c) + 'T00:00:00';
        }
        
        private String getUntilDate() {
            return String.valueOf(evt.EventLastDate__c) + 'T23:59:59';
        }
    }
}