src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdvertisingBudget__c</fullName>
        <label>Advertising Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UsingHouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InHouseRateType__c</fullName>
        <label>In House Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OfferRateType__c</fullName>
        <label>Offer Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SettlementRateType__c</fullName>
        <label>Settlement Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Digital</fullName>
        <active>true</active>
        <description>Represents digital ads</description>
        <label>Digital</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_LedgerEntryUtil_Test.cls
@isTest
private class LNE_LedgerEntryUtil_Test {

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    private class TestSettings {
        public Map<String, Id> objectToId {get; set;}
        public GLAccount__c gl50499 {get; set;}
        public GLAccount__c glX50148X {get; set;}
        
        public void initialize() {
            objectToId = LNE_TestObjectFactory.createStandardDataSet();  
            
            List<GLAccount__c> gls = new List<GLAccount__c>();
            
            gl50499 = LNE_TestObjectFactory.createGLAccount('TEST GL ACCOUNT 50499', '50499');
            gls.add(gl50499);
            
            glX50148X = LNE_TestObjectFactory.createGLAccount('TEST GL ACCOUNT X50148X', 'X50148X');
            gls.add(glX50148X);
            
            insert gls;            
        }
    }

	private static testMethod void testCreate50499() {
        TestSettings settings = new TestSettings();
        settings.initialize();
        
        Test.startTest();
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        update new Event__c(
            Id = settings.objectToId.get('event-0'),
            AdvertisingBudget__c = 100
        ); 
        
        List<LedgerEntry__c> results = 
            [SELECT OfferRateType__c, InHouseRateType__c FROM LedgerEntry__c];
            
        System.assertEquals(1, results.size());
        System.assertEquals('Flat', results.get(0).OfferRateType__c);
        System.assertEquals('Flat', results.get(0).InHouseRateType__c);
        
        Test.stopTest();
	}
	
	private static testMethod void testDelete50499ByAdvertisement() {
        TestSettings settings = new TestSettings();
        settings.initialize();
        
        Test.startTest();
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        update new Event__c(
            Id = settings.objectToId.get('event-0'),
            AdvertisingBudget__c = 100
        ); 
        
        List<LedgerEntry__c> results = 
            [SELECT OfferRateType__c, InHouseRateType__c FROM LedgerEntry__c];
            
        System.assertEquals(1, results.size());
        System.assertEquals('Flat', results.get(0).OfferRateType__c);
        System.assertEquals('Flat', results.get(0).InHouseRateType__c);
        
        Tour__c testTour = LNE_TestObjectFactory.createTour('Test Tour', settings.objectToId.get('artist'));
        insert testTour;
        
        AdPlan__c testAdPlan = LNE_TestObjectFactory.createAdPlan('Test Ad Plan', 10, settings.objectToId.get('event-0'), testTour.Id);
        insert testAdPlan;
        
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{'Account.Vendor'});
    	Id vendorRecordType = recordTypeMap.get('Account.Vendor');        
        
        Account vendor = LNE_TestObjectFactory.createAccount('Test Vendor');
        vendor.RecordTypeId = vendorRecordType;
        vendor.Format__c = 'Country';
        insert vendor;        
        
        insert LNE_TestObjectFactory.createAdvertisement(testAdPlan.Id, vendor.Id, System.today(), System.today().addDays(1), 100);
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        Test.stopTest();
	}
	
	private static testMethod void testDelete50499ByTourCampaignAdPlan() {
        TestSettings settings = new TestSettings();
        settings.initialize();
        
        Test.startTest();
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        update new Event__c(
            Id = settings.objectToId.get('event-0'),
            AdvertisingBudget__c = 100
        ); 
        
        List<LedgerEntry__c> results = 
            [SELECT OfferRateType__c, InHouseRateType__c FROM LedgerEntry__c];
            
        System.assertEquals(1, results.size());
        System.assertEquals('Flat', results.get(0).OfferRateType__c);
        System.assertEquals('Flat', results.get(0).InHouseRateType__c);
        
        Tour__c testTour = LNE_TestObjectFactory.createTour('Test Tour', settings.objectToId.get('artist'));
        insert testTour;
        
        AdPlan__c testAdPlan = LNE_TestObjectFactory.createAdPlan('Test Ad Plan', 10, settings.objectToId.get('event-0'), testTour.Id);
        insert testAdPlan;

        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{'TourCampaign__c.Digital'});
    	Id tourCampaignRecordType = recordTypeMap.get('TourCampaign__c.Digital');      
    	
    	TourCampaign__c testTourCampaign = LNE_TestObjectFactory.createTourCampaign(testTour.Id, tourCampaignRecordType);
    	insert testTourCampaign;
    	
    	TourCampaignAdPlan__c tcap = LNE_TestObjectFactory.createTourCampaignAdPlan(testTourCampaign.Id, testAdPlan.Id, null);
    	insert tcap;
    	
        tcap.AllocatedAmount__c = 200;
        update tcap;
 
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        Test.stopTest();
	}	
	
	private static testMethod void testCreateAndDeleteX50148X() {
        TestSettings settings = new TestSettings();
        settings.initialize();
        
        Test.startTest();
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        update new Event__c(
            Id = settings.objectToId.get('event-0'),
            UsingHouseNut__c = true
        ); 
        
        List<LedgerEntry__c> results = 
            [SELECT OfferRateType__c, SettlementRateType__c FROM LedgerEntry__c];
            
        System.assertEquals(1, results.size());
        System.assertEquals('Flat', results.get(0).OfferRateType__c);
        System.assertEquals('Flat', results.get(0).SettlementRateType__c);
        
        update new Event__c(
            Id = settings.objectToId.get('event-0'),
            UsingHouseNut__c = false
        );         
        
        System.assertEquals(0, [SELECT count() FROM LedgerEntry__c]);
        
        Test.stopTest();
	}
}