src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApplyGlobalTermsTo__c</fullName>
        <label>Apply Global Terms To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Theater</fullName>
                </value>
                <value>
                    <fullName>Club</fullName>
                </value>
                <value>
                    <fullName>Arena</fullName>
                </value>
                <value>
                    <fullName>Stadium</fullName>
                </value>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Boutique Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Comedy Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalTerms__c</fullName>
        <description>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</description>
        <inlineHelpText>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</inlineHelpText>
        <label>Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RelatedContra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contra</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Related Contra (GL Account)</relationshipLabel>
        <relationshipName>GLAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContraAtForecast__c</fullName>
        <label>Contra At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <customValue>
        <fullName>CHICAGO</fullName>
    </customValue>
    <customValue>
        <fullName>PADUCAH-CAPE GIRARD-HARSBG</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_RollupContraForecast_T_Test.cls
@isTest
private class LNE_RollupContraForecast_T_Test {

    class TestSettings {
        String COMBINED_KEY_DELIMITER = '|';            
        Account geoOffice;
        Account divisionOffice;    
        Account buUnitOffice;
        Account amphiOffice;     
        Account[] newAccounts;
        Event__c myEvent;
        GLAccount__c ancillaryGL;
        GLAccount__c contraGL;
        Map<Id,Account> oldAccountsMap;
        DataGenerationSettings__c dataSettings;
        DMA__c[] dmaList;        
        String RT_VENUE_NAME = 'Account.Venue';
        String RT_OFFICE_NAME = 'Account.Office';
        String RT_LEDGER_ANCILLARY = 'LedgerEntry__c.Ancillary';
        String RT_LEDGER_CONTRA = 'LedgerEntry__c.Contra';
        ID RT_VENUE_ID;
        ID RT_OFFICE_ID; 
        ID RT_LEDGER_ANCILLARY_ID;                           
        ID RT_LEDGER_CONTRA_ID;        
        LNE_TestObjectFactory factory;          
        
        public TestSettings() {
        
            //important rule to allow duplicates within the unit tests.
            
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            dataSettings = new DataGenerationSettings__c(CombinedKeyDelimiter__c = COMBINED_KEY_DELIMITER);
            insert dataSettings;
            
            //get recordtypes
            
            dmaList = new DMA__c[]{LNE_TestObjectFactory.createDMA( 'CHICAGO', 'COOK', 'IL', '60402' ),
                LNE_TestObjectFactory.createDMA( 'PADUCAH-CAPE GIRARD-HARSBG', 'JACKSON', 'IL', '62274' )};
            insert dmaList;             
            
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{RT_VENUE_NAME, RT_OFFICE_NAME, RT_LEDGER_ANCILLARY,RT_LEDGER_CONTRA });
            RT_OFFICE_ID = recordTypeMap.get(RT_OFFICE_NAME);
            RT_VENUE_ID = recordTypeMap.get(RT_VENUE_NAME); 
            RT_LEDGER_ANCILLARY_ID =  recordTypeMap.get(RT_LEDGER_ANCILLARY);
            RT_LEDGER_CONTRA_ID = recordTypeMap.get(RT_LEDGER_CONTRA);            
            
            myEvent = new Event__c(ProjectedPaidTickets__c = 20000, ProjectedDropCount__c = 30000);
            
            List<Event__c> events = new List<Event__c>{myEvent};
            Map<String, Id> objectToId = LNE_TestObjectFactory.createStandardDataSetList(events);  
            
            geoOffice = [SELECT Id, Name, Type
                             FROM Account
                            WHERE Id = :objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_VENUE)];
                            
            buUnitOffice = [SELECT Id, Name, Type
                              FROM Account
                             WHERE Id = :objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_OFFICE)];      
            
            ancillaryGL = [SELECT Id, Name, Category__c, RelatedContra__c, GLCode__c 
                             FROM GLAccount__c 
                            WHERE Id = :objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_ANCILLARY)];
                            
            contraGL = new LNE_TestObjectFactory(
                LNE_TestObjectFactory.createGLAccount('Contra Rev - Concession', '11111'))
                    .addProperties(
    			        new Map<String,object>{
    			        	'Category__c' => 'Concession Revenue',
    				        'Type__c' => 'Contra',
    				        'RelatedContra__c' => ancillaryGL.Id
    			        }
    		        ).buildGLAccount();         
            insert contraGL;
            
            divisionOffice = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testDivision' )
            , RT_OFFICE_ID )).addBillingAddress( '1000 west illinois st', 'Chicago', '60402','Illinois', 'IL', 'United States', 'US'
            ).addProperties( new Map<String,Object>{'Phone' => '708-522-5307','Type' => 'Division','ApplyGlobalTermsTo__c' => 'Amphitheatre'
            ,'GlobalTerms__c' => 'Global Terms','ParentId' => geoOffice.Id, 'Status__c' => 'Active'}).buildAccount();
            divisionOffice.Type = 'Office';
            Database.insert(divisionOffice, dml);     
            
            buUnitOffice = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'Chicago' )
            , RT_OFFICE_ID )).addBillingAddress( '1000 west illinois st', 'Chicago', '60402','Illinois', 'IL', 'United States', 'US' 
            ).addProperties( new Map<String,Object>{'Phone' => '708-522-5307','Type' => 'Business Unit','ParentId' => divisionOffice.Id
            , 'Status__c' => 'Active'}).buildAccount();
            buUnitOffice.Type = 'Office';
            Database.insert(buUnitOffice, dml);    
        }
        
        public boolean insertLedger(){
            LedgerEntry__c insertLedger = new LedgerEntry__c (
                GLAccount__c = contraGL.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                Category__c = 'Concession Revenue',
                RecordTypeId = RT_LEDGER_ANCILLARY_ID,
                Event__c = myEvent.Id,
                contraatforecast__c = 20);     
            insert insertLedger ;
                
            LedgerEntry__c[] contraLedger = [Select id, contraatforecast__c from ledgerentry__c where glaccount__c = :contraGL.Id]; 
            return (contraLedger[0].contraatforecast__c == 20?True:False);         

        }
        
        public boolean updateLedger(){
            LedgerEntry__c insertUpdateLedger = new LedgerEntry__c (
                GLAccount__c = contraGL.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                Category__c = 'Concession Revenue',
                RecordTypeId = RT_LEDGER_ANCILLARY_ID,
                Event__c = myEvent.Id,
                contraatforecast__c = 20);     
                insert insertUpdateLedger ;
            
            insertUpdateLedger.contraatforecast__c = 32;
            update  insertUpdateLedger;
                
            LedgerEntry__c[] contraLedger = [Select id, contraatforecast__c from ledgerentry__c where glaccount__c = :contraGL.Id];   
            system.debug('CONTRA = ' + contraLedger);
            return (contraLedger[0].contraatforecast__c == 32?True:False);         

        } 

        public boolean updateToDeleteLedger(){
            LedgerEntry__c UpdateDeleteLedger = new LedgerEntry__c (
                GLAccount__c = ancillaryGL.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                Category__c = 'Concession Revenue',
                RecordTypeId = RT_LEDGER_ANCILLARY_ID,
                Event__c = myEvent.Id,
                contraatforecast__c = 20);     
                insert UpdateDeleteLedger ;
            
            UpdateDeleteLedger.contraatforecast__c = 0;
            update  UpdateDeleteLedger;
             
            List<ledgerentry__c> count =  [Select Id from ledgerentry__c where glaccount__c = :contraGL.Id];  
            return (count.size() == 0?True:False);         

        }  
        
        
        public boolean deleteLedger(){
            LedgerEntry__c deleteLedger = new LedgerEntry__c (
                GLAccount__c = ancillaryGL.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                Category__c = 'Concession Revenue',
                RecordTypeId = RT_LEDGER_ANCILLARY_ID,
                Event__c = myEvent.Id,
                contraatforecast__c = 20);     
                insert deleteLedger ;
            
            delete  deleteLedger;
             
            Integer count =  [Select count() from ledgerentry__c where glaccount__c = :contraGL.Id];  
            return (count == 0?True:False);         

        }       
        
        public void finalize(){
        }
    }
    
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }        

    static testMethod void insertLedgerWithoutException() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.insertLedger();
        ts.finalize();
        System.assert( true, 'No Exceptions were thrown' );
    }    
    
    static testMethod void updateLedgerWithoutException() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.updateLedger();
        Test.stopTest();
        ts.finalize();
        System.assert( true, 'No Exceptions were thrown' );
    }   
    
    static testMethod void updateToDeleteLedgerWithoutException() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.updateToDeleteLedger();
        Test.stopTest();
        ts.finalize();
        System.assert( true, 'No Exceptions were thrown' );
    }    
    
    static testMethod void deleteLedgerWithoutException() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.deleteLedger();
        ts.finalize();
        System.assert( true, 'No Exceptions were thrown' );
    } 
            
    static testMethod void insertLedgertest() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.insertLedger();
        ts.finalize();        
        System.assert(result);
    } 
    
    static testMethod void updateLedgertest() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.updateLedger();
        Test.stopTest();
        ts.finalize();        
        System.assert(result);
    }

    static testMethod void updateToDeleteLedgertest() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.updateToDeleteLedger();
        Test.stopTest();
        ts.finalize();        
        System.assert(result);
    }     

    static testMethod void deleteLedgertest() {
        LNE_FinancialCalculator.currentlyRunning = true;
        TestSettings ts = new TestSettings();
        Test.startTest();
        Boolean result = ts.deleteLedger();
        ts.finalize();     
        System.assert(result);
    }
}