src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApplyGlobalTermsTo__c</fullName>
        <label>Apply Global Terms To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Theater</fullName>
                </value>
                <value>
                    <fullName>Club</fullName>
                </value>
                <value>
                    <fullName>Arena</fullName>
                </value>
                <value>
                    <fullName>Stadium</fullName>
                </value>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Boutique Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Comedy Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalTermsUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether managers should be notified that the Global Terms have updated.</inlineHelpText>
        <label>Global Terms Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GlobalTerms__c</fullName>
        <description>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</description>
        <inlineHelpText>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</inlineHelpText>
        <label>Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OwnershipType__c</fullName>
        <label>Ownership Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Owned/Operated</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Exclusively Booked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreviousGlobalTerms__c</fullName>
        <description>This is defined through a trigger - and when the Global Terms are applied based on the matching Divison Office / Venue Type.</description>
        <inlineHelpText>Global Terms used previously before the last application from the Division</inlineHelpText>
        <label>Previous Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <customValue>
        <fullName>CHICAGO</fullName>
    </customValue>
    <customValue>
        <fullName>PADUCAH-CAPE GIRARD-HARSBG</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_AccountTermsUpdated_T_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_AccountTermsUpdated_T_Test {
	
	class TestSettings {
		
		//-- example combined key delimiter
		String COMBINED_KEY_DELIMITER = '|';
		
		Account geoOffice;
		Account divisionOffice;
		Account[] venues;
		
		//-- instance values
		Account[] newAccounts;
		Map<Id,Account> oldAccountsMap;
		DataGenerationSettings__c dataSettings;
		DMA__c[] dmaList;
		
		String RT_VENUE_NAME = 'Account.Venue';
		String RT_OFFICE_NAME = 'Account.Office';
		ID RT_VENUE_ID;
		ID RT_OFFICE_ID;
		
		String ORIGINAL_TERMS = 'Original Terms';
		String UPDATED_TERMS = 'Updated Terms';
		
		LNE_TestObjectFactory factory;
		
		public TestSettings(){
			//-- initialize common custom settings.
			LNE_TestObjectFactory.prepStandardCustomSettings();
					 
			//-- important rule to allow duplicates within the unit tests.
			Database.DMLOptions dml = new Database.DMLOptions();
			dml.DuplicateRuleHeader.AllowSave = true;
			
			factory = new LNE_TestObjectFactory(null);
			
			//-- get recordtypes
			Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ RT_VENUE_NAME, RT_OFFICE_NAME }
			);
			RT_OFFICE_ID = recordTypeMap.get( RT_OFFICE_NAME );
			RT_VENUE_ID = recordTypeMap.get( RT_VENUE_NAME );
			
			dmaList = new DMA__c[]{
				LNE_TestObjectFactory.createDMA( 'CHICAGO', 'COOK', 'IL', '60402' ),
				LNE_TestObjectFactory.createDMA( 'PADUCAH-CAPE GIRARD-HARSBG', 'JACKSON', 'IL', '62274' )
			};
			insert dmaList;
			
			//-- create the offices
			//-- @TODO: probably should include new createGeoOffice / createDivisionOffices in TestObjectFactory
			geoOffice = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testGeography' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
				'Phone' => '708-522-5307',
				'Type' => 'Geography'
			}).buildAccount();
			insert geoOffice;
			
			divisionOffice = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testDivision' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
				'Phone' => '708-522-5307',
				'Type' => 'Division',
				'ApplyGlobalTermsTo__c' => 'Amphitheatre',
				'GlobalTerms__c' => ORIGINAL_TERMS,
				'ParentId' => geoOffice.Id
			}).buildAccount();
			insert divisionOffice;
		}
		
		/** Refreshes the accounts to include the updated values. **/
		public void refreshVenues(){
			Map<Id, Account> updatedMap = new Map<Id,Account>(
				[
					select id, Name, GlobalTermsUpdated__c, GlobalTerms__c, PreviousGlobalTerms__c
					from Account
					where id in : venues
				]
			);
			
			Account[] updatedAccounts = new Account[]{};
			Account venue = null;
			for( integer i = 0; i < venues.size(); i++ ){
				venue = venues[i];
				System.assert( updatedMap.containsKey( venue.Id ), 'All accounts created should be found again when refreshed' );
				updatedAccounts.add( updatedMap.get( venue.Id ) );
			}
			
			//-- the updatedAccounts should be refreshed and in the same order as the original list.
		}
		
		/** Setup that simply create the Accounts **/
		private void createOwnedOperated(){
			venues = new Account[]{
				new LNE_TestObjectFactory(
					LNE_TestObjectFactory.createAccount( 'TestAccount999', RT_VENUE_ID )
				).addBillingAddress( '200 West Jackson St.', 'Jackson', '62274', 'Illinois', 'IL', 'United States', 'US' )
				.addProperties( new Map<String,Object>{
					'Capacity__c' => 1000,
					'PrimaryOffice__c' => divisionOffice.Id,
					'OwnershipType__c' => 'Owned/Operated',
					'GlobalTerms__c' => ORIGINAL_TERMS,
					'Type' => 'Amphitheatre'
				}).buildAccount()
			};
		}
		
		public void setupOwnedOperated(){
			createOwnedOperated();
			insert venues;
		}
		
		public void setupThirdParty(){
			createOwnedOperated();
			for( Account venue : venues ){
				venue.OwnershipType__c = 'Third Party';
			}
			insert venues;
		}
		
		public void setupGlobalTermsChange(){
			newAccounts = new Account[]{
				divisionOffice
			};
			
			oldAccountsMap = new Map<Id,Account>(
				newAccounts.deepClone( true, true, true )
			);
			
			String updatedTerms = UPDATED_TERMS;
			divisionOffice.GlobalTerms__c = updatedTerms;
			System.assertEquals( updatedTerms, newAccounts[0].GlobalTerms__c, 'newList should retain pointer to divisionOffice' );
		}
		
		/** Finalize step. Should always be called after all setups. **/
		public void finalize(){
		}
	}

	//-- test test methods here
	static testMethod void setupOwnedOperatedNoExceptions() {
		TestSettings ts = new TestSettings();
		ts.setupOwnedOperated();
		ts.setupGlobalTermsChange();
		ts.finalize();
		System.assert( true, 'No Exception has occurred in setting up owned operated' );
	}
	
	static testMethod void setupThirdPartyNoExceptions() {
		TestSettings ts = new TestSettings();
		ts.setupThirdParty();
		ts.setupGlobalTermsChange();
		ts.finalize();
		System.assert( true, 'No Exception has occurred in setting up third party' );
	}
	
	static testMethod void verifyGlobalTermsUpdated(){
		TestSettings ts = new TestSettings();
		ts.setupOwnedOperated();
		ts.setupGlobalTermsChange();
		ts.finalize();
		
		Account[] updatedAccounts = LNE_AccountTermsUpdated_T.execute( ts.newAccounts, ts.oldAccountsMap );
		System.assert( updatedAccounts.size() > 0, 'The terms were updated, so there should be at least something updated' );
		//-- there is disagreement whether both the division and the Account should be included.
		
		//-- refresh with the updated info
		//ts.refreshVenues();
		
		for( Account updatedAccount: updatedAccounts ){
			System.assertEquals( true, updatedAccount.GlobalTermsUpdated__c, 'The global terms should be updated' );
			System.assertEquals( ts.ORIGINAL_TERMS, updatedAccount.PreviousGlobalTerms__c, 'The previous terms should be the original terms' );
			System.assertEquals( ts.UPDATED_TERMS, updatedAccount.GlobalTerms__c, 'The current global terms should be updated' );
		}
	}
	
	//-- @TODO: perform inverse test using ThirdParty - no changes expected
	
	//-- test functionality here
	
	
}