src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Dependent on type</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HOB Club-Club Nights</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Music Hall</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Foundation Room</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Restaurant</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Special Event</fullName>
                </value>
                <value>
                    <fullName>HOB Club-Special Event Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify TBD Venues.  Used in Apex to perform calculations based on business processes.</description>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EventSubtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDConfirmedCount__c</fullName>
        <label>TBD Confirmed Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TBDMonthValue__c</fullName>
        <formula>TEXT(MONTH(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDMonthValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDMonth__c</fullName>
        <label>TBD Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <formula>IF(RecordType.DeveloperName ==&apos;TBDEvents&apos;, False, Venue__r.TBDVenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBDYearValue__c</fullName>
        <formula>TEXT(YEAR(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDYearValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDYear__c</fullName>
        <description>Used in TBD Apex logic</description>
        <label>TBD Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <recordTypes>
        <fullName>TBDEvents</fullName>
        <active>true</active>
        <description>Used for TBD Events</description>
        <label>TBD Events</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/EventSubtype.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Club Night</fullName>
    </customValue>
    <customValue>
        <fullName>Filler Show</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Promoted</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Show</fullName>
    </customValue>
    <customValue>
        <fullName>Rental/Special Events/Venue Holds</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant Show</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event</fullName>
    </customValue>
    <customValue>
        <fullName>Tentpole</fullName>
    </customValue>
    <customValue>
        <fullName>Not Used</fullName>
    </customValue>
    <description>Centralized values for the Event Subtype field</description>
    <masterLabel>Event Subtype</masterLabel>
</GlobalValueSet>

src/classes/LNE_TBDCountUpdateClass_Batch_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class LNE_TBDCountUpdateClass_Batch_Test{
    

    static testMethod void testMethod1() 
    {
         LNE_GeneralSettingsUtil.setLocalBypassSettings(true, true, true);
          
            List<RecordType> rT = new List<RecordType>([SELECT Id, sObjectType, DeveloperName From RecordType Where  (DeveloperName='Rental' OR DeveloperName='Venue' OR DeveloperName='TBDEvents'OR DeveloperName='Office') ] ) ;
            String sRental, sVenue, sTBD;
            String sOffice;
            
            for (RecordType r : rT){
                 if(r.DeveloperName =='Rental' ) {sRental=r.Id;}
                 if(r.DeveloperName =='Venue' ) {sVenue=r.Id;}
                 if(r.DeveloperName =='TBDEvents' ) {sTBD=r.Id;}
                 if(r.DeveloperName =='Office' ) {sOffice=r.Id;}
            
            }
            System.debug(sOffice + ' , ' + sRental + ' , ' +  sVenue + ' , ' +  sTBD);
            
            List<Account> acL = new List<Account>(); 
            Integer i=0;
            Account c ;
            for(i=0;  i< 5 ; i++){
                               
              c = new  Account(TBDVenue__c =True, Name='TBDVENUE' +i , RecordTypeId=sVenue,BillingState='California', BillingPostalCode='92929', BillingCity='Same',BillingStreet='112 SAME' );
             acL.add(c);
            }
            insert acL; 
            
            Account tbdVenue2 = acL[2];
            System.debug(' tbdVenue2  = ' + tbdVenue2.Name);
            System.Assert(acL.size() == 5);
            /*
            System.debug(' sOffice  = ' + sOffice);
            List<Account> aLO = new  List<Account>( [SELECT Id,RecordTypeId,Name from Account Where RecordTypeId=:sOffice]);
            System.debug(aLO.size() +  '   '  + aLO[0]  );
            
            System.Assert(aLO[0].RecordTypeId == sOffice);
            */
             c = new  Account( Name='OFFICE', RecordTypeId=sOffice,BillingState='California', BillingPostalCode='92929', BillingCity='Same',BillingStreet='112 SAME',Type=
             'Office');
            insert c; 
            System.Assert(c.Id != null);
            
                        
                        date k1 = date.newInstance(2017, 01, 21);
                        date k2 = date.newInstance(2017, 02, 21);
                        date k3 = date.newInstance(2017, 03, 21);
                        date k4 = date.newInstance(2017, 04, 21);
                        date k5 = date.newInstance(2017, 05, 21);
                        date k6 = date.newInstance(2017, 06, 21);
                        date k7 = date.newInstance(2017, 07, 21);
                        date k8 = date.newInstance(2017, 08, 21);
                        date k9 = date.newInstance(2017, 09, 21);
                        date k10 = date.newInstance(2017, 10, 21);
                        date k11 = date.newInstance(2017, 11, 21);
                        date k12 = date.newInstance(2017, 12, 21);

                        List<Event__c> eL  = new List<Event__c>();
                        Event__c e;
                        Integer i1 = 0;
                         for (Account a : acL){
                                System.debug('i1  => ' + i1);
                                i1= i1+1;
                                System.debug('i1  => ' + i1);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k1, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k2, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k3, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k4, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k5, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k6, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k7, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k8, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k9, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k10, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k11, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,EventLastDate__c=k12, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                eL.add(e);
                                
                                
                                if (i1==3){
                                    e = new Event__c(Office__c=c.Id,EventLastDate__c=k12, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                    eL.add(e);
                                    e = new Event__c(Office__c=c.Id,EventLastDate__c=k12, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                    eL.add(e);
                                    e = new Event__c(Office__c=c.Id,EventLastDate__c=k12, Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sRental );
                                    eL.add(e);
                                    
                                    System.debug('i1  => ' + i1);
                                
                                
                                }
                        
                        }
                        insert eL;
                        System.Assert(eL.size() == 63);
                        eL  = new List<Event__c>();
                        for (Account a : acL){
                        
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='1', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='2', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='3', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='4', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='5', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='6', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='7', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='8', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='9', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='10', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='11', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                                e = new Event__c(Office__c=c.Id,TBDMonth__c='12', TBDYear__c='2017', Status__c='Confirmed', Venue__c=a.Id,RecordTypeId=sTBD );
                                eL.add(e);
                        
                        }
                             insert eL;
        
        
        Test.startTest();
        String q = 'SELECT Id, Venue__c, TBDConfirmedCount__c,TBDMonth__c, TBDYear__c, TBDVenue__c, TBDMonthValue__c, TBDYearValue__c, EventLastDate__c from Event__c WHERE  RecordTypeName__c!=:TBDEvents  AND SubType__c!=:FillerShow AND TBDVenue__c=True AND TBDMonthValue__c != null AND  TBDYearValue__c =: Year AND (Status__c  =: PendingLikely  OR Status__c  =:Confirmed) ';
       
            LNE_TBDCountUpdateClass_Batch obj = new LNE_TBDCountUpdateClass_Batch(q);
            Database.executeBatch(obj); 
            
        Test.stopTest();
    }
    
}