src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>AdPlanName__c</fullName>
        <label>Ad Plan Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNEAdPlanBudget__c</fullName>
        <label>LNE Ad Plan Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <formula>Event__r.Venue__r.VenueName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venue</label>
        <type>Text</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PromoScale__c.object
<CustomObject>
    <description>Promo information related to the ticket scale</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Promo Scales</relationshipLabel>
        <relationshipName>PromoScales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TicketScale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Scale</label>
        <referenceTo>TicketScale__c</referenceTo>
        <relationshipLabel>Promo Scales</relationshipLabel>
        <relationshipName>Promo_Scales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promo Scale</label>
    <nameField>
        <label>Promo Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>San Francisco</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_MarketingPromotionsTab_CX_Test.cls
/**
 * Created by JK on 1/7/17.
 */
@isTest
public with sharing class LNE_MarketingPromotionsTab_CX_Test {
    
    static final String RT_VENDOR = 'Account.Vendor';
    static final String RT_Rental = 'Event__c.Rental';
    static final String RT_Hold = 'Event__c.Hold';

    class TestSettings {

        public Adplan__c adPlan;
        List<TicketScale__c> ticketScales = new List<TicketScale__c>();
        List<TicketScale__c> planTicketScales = new List<TicketScale__c>();
        List<TicketScale__c> projectionTicketScales = new List<TicketScale__c>();
        List<String> eventPlanStatuses = new List<String>(LNE_Constants.TICKET_SCALE_PLAN_EVENT_STATUSES);
        List<PromoScale__c> promoScales = new List<PromoScale__c>();

        public TestSettings(String eventStatus) {

            //create an event
            //need record types to create an event
            Map<String,Id> eventRecordTypeMap = LNE_Util.getRecordTypes(
                    new String[]{ RT_Rental, RT_Hold}
            );

            //get event record types
            Id RT_Rental_ID = eventRecordTypeMap.get( RT_Rental );
            Id RT_Hold_ID = eventRecordTypeMap.get( RT_Hold );

            //create vendor
            Map<String,Id> accountRecordTypeMap = LNE_Util.getRecordTypes(
                    new String[]{RT_VENDOR}
            );

            ID RT_VENDOR_ID = accountRecordTypeMap.get(RT_VENDOR);

            Account vendor = LNE_TestObjectFactory.createAccount('Test Vendor');
            vendor.RecordTypeId = RT_VENDOR_ID;
            vendor.Format__c = 'Country';
            vendor.Market__c = 'San Francisco';

            insert vendor;

            //insert event
            Event__c event = new Event__c(
                Venue__c = vendor.Id,
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = eventStatus,
                RecordTypeId = RT_Rental_ID
            );

            //insert event;
            LNE_TestObjectFactory.createStandardDataSet( event );

            //create ticket scales for the event
            TicketScale__c ticketScale;
            String priceLevel;
            Boolean isPlan;
            String stageType;

            for(Integer i=0; i<10; i++){

                //plan or projection
                isPlan = Math.round(Math.random()*1)==1;

                if(isPlan){
                    stageType = LNE_Constants.TICKET_SCALE_STAGE_TYPE_PLAN;
                }else{
                    stageType = LNE_Constants.TICKET_SCALE_STAGE_TYPE_PROJECTION;
                }

                priceLevel = 'TEST_' + Math.round(Math.random()*1000);

                ticketScale = new TicketScale__c(
                    Capacity__c = 100000,
                    Event__c = event.Id,
                    PriceLevel__c = priceLevel,
                    Price__c = 100,
                    ProjectedPaidTickets__c = 80000,
                    Notes__c = 'Notes for ' + priceLevel,
                    StageType__c = stageType
                );

                ticketScales.add(ticketScale);

                if(isPlan){
                    planTicketScales.add(ticketScale);
                }else{
                    projectionTicketScales.add(ticketScale);
                }
            }

            insert ticketScales;

            //create an adplan
            //insert adplan
            adPlan = new AdPlan__c(
                AdPlanName__c = 'Test Ad Plan',
                LNEAdPlanBudget__c = 1000000,
                Event__c = event.Id
            );

            insert adPlan;

            //create promo scales for adplan
            PromoScale__c promoScale;

            for(Integer i=0; i<4; i++){
                promoScale = new PromoScale__c(
                    Description__c = ticketScales[i].Notes__c,
                    Name = ticketScales[i].PriceLevel__c,
                    Price__c = ticketScales[i].Price__c,
                    TicketScale__c = ticketScales[i].Id,
                    AdPlan__c = adPlan.Id
                );

                promoScales.add(promoScale);
            }

            insert promoScales;

        }

        public void typicalSetup() {

        }


        public void finalize() {
        }
    }

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    private static void testConstructorBase(String eventStatus){
        TestSettings ts = new TestSettings(eventStatus);
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.adPlan);
        LNE_MarketingPromotionsTab_CX cx = new LNE_MarketingPromotionsTab_CX(sc);

        System.assertNotEquals(null, cx.adPlan, 'The controller does not have an AdPlan__c record.');
        System.assertEquals(ts.adPlan.Id, cx.adPlan.Id, 'The controller contains an incorrect AdPlan__c record.');
        System.assertEquals(ts.promoScales.size(), cx.promoScales.size(), 'The controller contains an incorrect number of promotion scales.');

        if(eventStatus==LNE_Constants.EVENT_STATUS_DRAFT){
            System.assertEquals(ts.planTicketScales.size(), cx.ticketScales.size(), 'The controller contains an incorrect number of ticket scales.');
        }else{
            System.assertEquals(ts.projectionTicketScales.size(), cx.ticketScales.size(), 'The controller contains an incorrect number of ticket scales.');
        }
    }

    @isTest
    static void testConstructorPlanPhase(){
        testConstructorBase(LNE_Constants.EVENT_STATUS_DRAFT);
    }

    @isTest
    static void testConstructorProjectionPhase(){
        testConstructorBase(LNE_Constants.EVENT_STATUS_CONFIRMED);
    }

    @isTest
    static void testSavePromoScale(){
        TestSettings ts = new TestSettings(LNE_Constants.EVENT_STATUS_CONFIRMED);
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.adPlan);
        LNE_MarketingPromotionsTab_CX cx = new LNE_MarketingPromotionsTab_CX(sc);

        PromoScale__c promoScale = cx.promoScales[0];

        promoScale.Name = 'Changed Name';
        promoScale.Description__c = 'Changed Description';

        LNE_MarketingPromotionsTab_CX.savePromoScale(promoScale);

        PromoScale__c savedPromoScale = [Select Name, Description__c from PromoScale__c where Id = :promoScale.Id];

        System.assertEquals(promoScale.Name, savedPromoScale.Name);
        System.assertEquals(promoScale.Description__c, savedPromoScale.Description__c);

    }

}