src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>CityStateConcatenatedKey__c</fullName>
        <description>Used to find unique combinations of city and state.</description>
        <formula>City__c + $Setup.DataGenerationSettings__c.CombinedKeyDelimiter__c + State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Unique combination of City:State.</inlineHelpText>
        <label>City State Concatenated Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <inlineHelpText>Postal / Zip Code that this DMA represents.</inlineHelpText>
        <label>Postal Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>State / Province Abbreviation</inlineHelpText>
        <label>State</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_AccountDMA_Autoassign_T.cls
/** 
 *	Trigger logic to automatically assign the DMA.
 *  <p>Assumes that the trigger will be run on a before update</p>
 *  <p>Also assumes that the cities and the states are also in uppercase</p>
 *	@author Paul Roth <proth@salesforce.com>
 *  @group DMALogic
 **/
public class LNE_AccountDMA_Autoassign_T {
	
	public static final String RT_VENUE = 'Account.Venue';
	
	/**
	 *  Performs the auto assignment.
	 *  @param newList Account[]
	 *  @param oldMap Map<Id,Account>
	 *  @return Account[] - list of accounts updated.
	**/
	public static Account[] execute( Account[] newList, Map<Id,Account> oldMap ){
		Account[] results = new Account[]{};
		
		if( newList == null || newList.size() < 1 ){
			return( results );
		}
		
		Account oldAccount = null;
		Account newAccount = null;
		
		String COMBINED_KEY_DELIMITER = DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;
		
		//-- determine the record types.
		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{ RT_VENUE }
		);
		Id RT_VENUE_ID = recordTypeMap.get( RT_VENUE );
		
		//-- determine the list of accounts that have changed
		String[] usedPostalCodes = new String[]{};
		String[] usedCityStates = new String[]{};
		
		ChangedAccount[] changedAccounts = new ChangedAccount[]{};
		ChangedAccount objChange = null;
		
		Map<String,String> postalCodeMap = null;
		Map<String,String> cityStateMap = null;
		
		if( oldMap == null ){
		    oldMap = new Map<Id,Account>();
		}
		
		Boolean isValid = false;
		Account BLANK_ACCOUNT = new Account();
		String billingCityKey = null;
		
		//System.debug( 'LNE_AccountDMA_Autoassign_T' );
		
		//-- loop through all accounts to only those that qualify
		for( Account newAccount1 : newList ){
		    isValid = false;
			oldAccount = null;
            
            if( RT_VENUE_ID == newAccount1.RecordTypeId ){
                //System.debug( 'is an venue' );
                if( oldMap.containsKey( newAccount1.Id )){
                    //System.debug( 'old venue' );
    				oldAccount = oldMap.get( newAccount1.Id );
    				objChange = new ChangedAccount( oldAccount, newAccount1 );
    				
    				//-- if the record type is correct and the fields have changed.
    				//-- assumes the billing address is required
    				if(
    					objChange.notEqualsStr( 'BillingPostalCode',false ) ||
    					objChange.notEqualsStr( 'BillingStateCode',false ) ||
    					objChange.notEqualsStr( 'BillingCity',false )
    				){
    					isValid = true;
    				} else {
    					System.debug( 'is valid venue but no postal change' );
    				}
    				
    			} else {
                    //System.debug( 'new venue' );
    			    oldAccount = BLANK_ACCOUNT;
    			    objChange = new ChangedAccount( oldAccount, newAccount1 );
    			    
    			    isValid = true;
    			}
    			
                if( isValid ){
                    //System.debug( 'postal code changed' );
    				
    				//-- clear the DMA
    				newAccount1.DMA__c = null;
    				
    				//-- determine the keys
    				objChange.postalKey = newAccount1.BillingPostalCode;
    				
    				if( newAccount1.BillingCity == null ){
    				    billingCityKey = '';
    				} else {
    				    billingCityKey = newAccount1.BillingCity.toUpperCase();
    				}
    				
    				objChange.cityStateKey = billingCityKey +
    					COMBINED_KEY_DELIMITER +
    					newAccount1.BillingStateCode;
    				
    				//-- determine which postalcodes / cityStates were used
    				usedPostalCodes.add( objChange.postalKey );
    				
    				//-- add to the list of things that changed
    				changedAccounts.add( objChange );
    			}
            }
		}
		
		//System.debug( 'changedAccounts:' + changedAccounts.size() );
		
		//-- short circuit if nothing is there.
		if( changedAccounts.size() < 1 ){
		    return( results );
		}
		system.debug('+++ changedAccounts' + changedAccounts);
		//-- Update the DMA for all postal codes
		postalCodeMap = new Map<String,String>();
		system.debug('+++ usedPostalCodes = ' + usedPostalCodes);
		//-- find the DMAs by Zip Code (should catch the majority of the records
		for( DMA__c matchingDMA : [
			select Id, DMA__c, PostalCode__c, City__c, State__c, CityStateConcatenatedKey__c
			from DMA__c
			where PostalCode__c in :usedPostalCodes
			order by createdDate desc
		]){
			postalCodeMap.put( matchingDMA.PostalCode__c, matchingDMA.DMA__c );
		}
		
		//System.debug( 'postalCodeMap:' ); System.debug( 'postalCodeMap' );
		
		for( ChangedAccount changedAcc : changedAccounts ){
			newAccount = changedAcc.getNewAccount();
			//System.debug( 'checking postal code DMA[' + changedAcc.postalKey + ']' );
			
			if( changedAcc.postalKey != null && postalCodeMap.containsKey( changedAcc.postalKey ) ){
				newAccount.DMA__c = postalCodeMap.get( changedAcc.postalKey );
				results.add( newAccount );
			} else {
				//-- find by city
				usedCityStates.add( objChange.cityStateKey );
			}
		}
		
		//-- separate out find by city because it is much more expensive and there can be 100s of results...
		//-- NOTE: CITY/STATE IS ASSUMED UPPER CASE IN DMAs
		if( usedCityStates.size() > 0 ){
		    //System.debug( 'usedCityStates:' ); System.debug( usedCityStates );
		
			cityStateMap = new Map<String,String>();
			system.debug('+++ usedCityStates = ' + usedCityStates);
			for( DMA__c matchingDMA : [
				select Id, DMA__c, PostalCode__c, City__c, State__c, CityStateConcatenatedKey__c
				from DMA__c
				where CityStateConcatenatedKey__c in :usedCityStates
				order by createdDate desc
			]){
				cityStateMap.put( matchingDMA.CityStateConcatenatedKey__c, matchingDMA.DMA__c );
			}
			
			//System.debug( 'cityStateMap' ); System.debug( cityStateMap );
			
			for( ChangedAccount changedAcc : changedAccounts ){
				newAccount = changedAcc.getNewAccount();
				//System.debug( 'assigning DMA[' + changedAcc.postalKey + '][' + changedAcc.cityStateKey + ']' );
				
				if( changedAcc.cityStateKey != null && cityStateMap.containsKey( changedAcc.cityStateKey ) ){
					newAccount.DMA__c = cityStateMap.get( changedAcc.cityStateKey );
					results.add( newAccount );
				}
			}
		}
		
		return( results );
	}
	
	/**
	 *  Internal class to represent the changes from the object.
	**/
	class ChangedAccount extends LNE_SObjectChange {
		
		public String postalKey;
		public String cityStateKey;
		
		ChangedAccount( Account oldObject, Account newObject ){
		    super( oldObject, newObject );
		}
		
		Account getNewAccount(){
			return( (Account)this.newObject );
		}
		
		Account getOldAccount(){
			return( (Account)this.oldObject );
		}
	}
}