src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ActualDropCount__c</fullName>
        <label>Actual Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PromoterAmountRate__c</fullName>
        <label>Promoter Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoterAmount__c</fullName>
        <label>Promoter Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SettlementRateType__c</fullName>
        <label>Settlement Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry Breakout</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PromoterAmountRate__c</fullName>
        <label>Promoter Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoterAmount__c</fullName>
        <label>Promoter Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SettlementRateType__c</fullName>
        <label>Settlement Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PerformingRightsFee__c.object
<CustomObject>
    <fields>
        <fullName>Breakout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CapacityRangeEnd__c</fullName>
        <label>Capacity Range End</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CapacityRangeStart__c</fullName>
        <label>Capacity Range Start</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Performing Rights Fees</relationshipLabel>
        <relationshipName>PerformanceRightsFees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateAmount__c</fullName>
        <label>Rate/Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASCAP</fullName>
                </value>
                <value>
                    <fullName>BMI</fullName>
                </value>
                <value>
                    <fullName>GMR</fullName>
                </value>
                <value>
                    <fullName>SESAC</fullName>
                </value>
                <value>
                    <fullName>SOCAN</fullName>
                </value>
                <value>
                    <fullName>Event Insurance Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Performing Rights Fee</label>
    <nameField>
        <displayFormat>PRF-{000000}</displayFormat>
        <label>Performing Rights Fee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performing Rights Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_SettlementExpensesTab_CX_Test.cls
@isTest
public class LNE_SettlementExpensesTab_CX_Test{
	static final String RT_VENDOR = 'Account.Vendor';
	static final String RT_Rental = 'Event__c.Rental';
    static final String RT_Hold = 'Event__c.Hold';

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    class TestSettings {
    	public Event__c event;
    	public LedgerEntry__c ledger;
    	public LedgerEntryBreakout__c breakout;

    	public TestSettings(){
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
			
			Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ 'LedgerEntry__c.Expenses' }
			);
			Id RT_EXPENSES_ID = recordTypeMap.get( 'LedgerEntry__c.Expenses' );

            List<GLAccount__c> gls = new List<GLAccount__c>();
            GLAccount__c breakoutGL = LNE_TestObjectFactory.createGLAccount('ASCAP/BMI/SESAC/GMR/BUMA Expense', '50202');
            gls.add(breakoutGL);
            GLAccount__c eventInsuranceGL = LNE_TestObjectFactory.createGLAccount('Event Insurance Expense', '50306');
            gls.add(eventInsuranceGL);
            
            insert gls;
            
            List<PerformingRightsFee__c> prfs = new List<PerformingRIghtsFee__c>();
            
			PerformingRightsFee__c prf1 = new PerformingRightsFee__c(
            	ExternalId__c = 'ASCAP',
                Type__c = 'ASCAP',
                GLAccount__c = breakoutGL.Id,
                Breakout__c = true,
                CapacityRangeStart__c = 0,
                CapacityRangeEnd__c = 200000,
                RateType__c = '% of Net Gross',
                RateAmount__c = 0.45,
                StartDate__c =  date.ValueOf('2010-01-01'),
                EndDate__c =  date.ValueOf('2030-12-31')
            );
            
            prfs.add(prf1);
            
            PerformingRightsFee__c prf2 = new PerformingRightsFee__c(
            	ExternalId__c = 'EventInsurance',
                Type__c = 'Event Insurance Expense',
                GLAccount__c = eventInsuranceGL.Id,
                Breakout__c = false,
                RateType__c = 'Flat',
                RateAmount__c = 0.45,
                StartDate__c =  date.ValueOf('2010-01-01'),
                EndDate__c =  date.ValueOf('2030-12-31')
            );
            
            prfs.add(prf2);          
            
            insert prfs;
            
			Event__c Evt1 = new Event__c(
				ProjectedPaidTickets__c = 10000,
				ProjectedDropCount__c = 10000,
                ActualDropCount__c = 10000,
                EventLastDate__c = date.today(),
                SelloutDropCount__c= 3000
                
			);
			
			Map<String, Id> objectToId = 
			    LNE_TestObjectFactory.createStandardDataSetList(new List<Event__c>{Evt1});
			
		   	ledger = new LedgerEntry__c (
				GLAccount__c = objectToId.get('ancillary'),
				BaseAmount__c = 100,
				RateType__c = 'Flat', 
				RecordTypeId = RT_EXPENSES_ID,
				Event__c = Evt1.Id
			); 

			insert ledger;
			
			LNE_FinancialCalculator.currentlyRunning = true;
			
			breakout = new LedgerEntryBreakout__c(LedgerEntry__c=ledger.Id);
			insert breakout;
			
			this.event = Evt1;
	    }
	    
	    public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
	    }
    }

    
    private static testMethod void testSettlementExpensesTab(){
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementExpensesTab_CX cx = new LNE_SettlementExpensesTab_CX(sc);
        cx.startSettlement();

        System.assertNotEquals(3, [SELECT count() FROM Deal__c]);
        
        Test.stopTest();
    }
    
    private static testMethod void testShowHide() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementExpensesTab_CX cx = new LNE_SettlementExpensesTab_CX(sc);
        
        System.assertEquals(cx.VIEW_CALCULATIONS, cx.calculationsButtonValue);
        
        cx.showHideCalculations();
        System.assertEquals(cx.HIDE_CALCULATIONS, cx.calculationsButtonValue);
        
        cx.showHideCalculations();
        System.assertEquals(cx.VIEW_CALCULATIONS, cx.calculationsButtonValue);        
        
        Test.stopTest();
    }
    
    private static testMethod void defaultFees() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementExpensesTab_CX cx = new LNE_SettlementExpensesTab_CX(sc);
        
        LNE_SettlementExpensesTab_CX.defaultFees(ts.event.id);
        
        System.assertEquals(3, [SELECT count() FROM LedgerEntry__c]);
        
        Test.stopTest();        
    }
    
    private static testMethod void testLedgers() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementExpensesTab_CX cx = new LNE_SettlementExpensesTab_CX(sc);
        
        LNE_FinancialCalculator.currentlyRunning = true;
        ts.ledger.PromoterAmount__c = 123;
        update ts.ledger;
        
        LedgerEntry__c b = [SELECT PromoterAmountRate__c, SettlementRateType__c FROM LedgerEntry__c WHERE Id = :ts.ledger.Id];
        system.assertEquals(123, b.PromoterAmountRate__c);
        system.assertEquals('Flat', b.SettlementRateType__c);
        
        Test.stopTest();        
    }
    
    private static testMethod void testBreakouts() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
        LNE_SettlementExpensesTab_CX cx = new LNE_SettlementExpensesTab_CX(sc);
        
        LNE_FinancialCalculator.currentlyRunning = true;
        ts.breakout.PromoterAmount__c = 123;
        update ts.breakout;
        
        LedgerEntryBreakout__c b = [SELECT PromoterAmountRate__c, SettlementRateType__c FROM LedgerEntryBreakout__c WHERE Id = :ts.breakout.Id];
        system.assertEquals(123, b.PromoterAmountRate__c);
        system.assertEquals('Flat', b.SettlementRateType__c);
        
        Test.stopTest();        
    }
}