src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApplyGlobalTermsTo__c</fullName>
        <label>Apply Global Terms To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Theater</fullName>
                </value>
                <value>
                    <fullName>Club</fullName>
                </value>
                <value>
                    <fullName>Arena</fullName>
                </value>
                <value>
                    <fullName>Stadium</fullName>
                </value>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Boutique Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Comedy Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalTerms__c</fullName>
        <description>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</description>
        <inlineHelpText>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</inlineHelpText>
        <label>Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OwnershipType__c</fullName>
        <label>Ownership Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Owned/Operated</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Exclusively Booked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalSupportActExpenses__c</fullName>
        <description>Total Support Act Expenses</description>
        <label>Total Support Act Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_TestObjectFactory_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_TestObjectFactory_Test {
	
	class TestSettings {
		
		//-- instance values
		String RT_OFFICE_NAME = 'Account.Office';
		String RT_VENUE_NAME = 'Account.Venue';
		Id RT_OFFICE_ID = null;
		ID RT_VENUE_ID = null;
		
		String PROFILE_NAME = LNE_TestObjectFactory.PROFILE_LNE_INTERNAL_USER;
		Id PROFILE_ID = null;
		
		String PERMISSION_SET_NAME = LNE_TestObjectFactory.PERM_SET_BOOKING;
		Id PERM_SET_BOOKING_ID = null;
		
		User testUser;
		
		Map<String,Account> offices;
		Account testAccount;
		Contact testContact;
		DMA__c testDMA;
		
		public TestSettings(){
		    this(true);
		}
		public TestSettings( Boolean shouldPrepCustomSettings){
			//-- global setup here
			if( shouldPrepCustomSettings == true ){
			    LNE_TestObjectFactory.prepStandardCustomSettings();
			}
			
			//-- important rule to allow duplicates within the unit tests.
			Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
			
			Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			    new String[]{ RT_VENUE_NAME, RT_OFFICE_NAME }
		    );
		    RT_OFFICE_ID = recordTypeMap.get( RT_OFFICE_NAME );
		    RT_VENUE_ID = recordTypeMap.get( RT_VENUE_NAME );
			
			Map<String,Id> profileMap = LNE_Util.getProfileIds(
			    new String[]{ PROFILE_NAME }
			);
			PROFILE_ID = profileMap.get( PROFILE_NAME );
			System.assertNotEquals( PROFILE_ID, null, 'Profile:' + PROFILE_NAME + ', must be found' );
			
			offices = new Map<String,Account>();
		}
		
		public void setupUser(){
			testUser = LNE_TestObjectFactory.createUser( LNE_TestObjectFactory.makeUnique('lnejdoe'), PROFILE_ID );
    	    insert testUser;
		}
		
		public void setupTestUser(){
		    testUser = LNE_TestObjectFactory.createPromoterUser(
		    	LNE_TestObjectFactory.makeUnique( 'lnejdoe' )
		    );
		}
		
		public void setupAccount(){
			testAccount = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' ))
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addShippingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.buildAccount();
			insert testAccount;
		}
		
		public void setupContact(){
			setupAccount();
			
			testContact = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createContact( testAccount.id, 'John', LNE_TestObjectFactory.makeUnique( 'Doe' ))
			).addMailingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			//-- this line should be removed as it is deprecated
			.buildContact();
			insert testContact;
		}
		
		public void setupDMA(){
		    testDMA = LNE_TestObjectFactory.createDMA( 'Chicago', 'Chicago', 'IL', '60402' );
		    insert testDMA;
		}
		
		
		public void setupGeographyOffice(){
		    Account geoOffice = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testGeography' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
			    'Phone' => '708-522-5307',
			    'Type' => 'Geography'
			}).buildAccount();
			insert geoOffice;
			
			offices.put( 'Geography', geoOffice );
		}
		
		public void setupDivisionOffice(){
		    setupGeographyOffice();
		    Account geoOffice = offices.get( 'Geography' );
		    
		    Account divison = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testDivision' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
			    'Phone' => '708-522-5307',
			    'Type' => 'Division',
			    'ApplyGlobalTermsTo__c' => 'Amphitheatre',
			    'GlobalTerms__c' => 'Global Terms',
			    'ParentId' => geoOffice.Id
			}).buildAccount();
			insert divison;
			
			offices.put( 'Division', divison );
		}
		
		public void setupVenueAccount(){
		    setupDivisionOffice();
		    Account divisionAcct = offices.get( 'Division' );
		    
		    testAccount = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testVenue' ), RT_VENUE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
			    'Capacity__c' => 1000,
			    'PrimaryOffice__c' => divisionAcct.Id,
			    'OwnershipType__c' => 'Owned/Operated',
			    'Type' => 'Amphitheatre'
			}).buildAccount();
//            testAccount.BillingCountryCode = 'US';
			insert testAccount;
		}
		
		public void finalize(){
			
		}
	}
    /*
    //-- test functionality here
    
    //-- UUID functionality
    static testmethod void testUUID(){
    	TestSettings ts = new TestSettings();
    	ts.finalize();
    	
    	Integer int1 = LNE_TestObjectFactory.getUUID();
    	Integer int2 = LNE_TestObjectFactory.getUUID();
    	
    	System.assertNotEquals( int1, int2, 'the point of getUUID is that they are unique. they arent.' );
    }
    
    static testMethod void testMakeUnique(){
    	TestSettings ts = new TestSettings();
    	ts.finalize();
    	
    	String seed = 'TestAccount';
    	String str1 = LNE_TestObjectFactory.makeUnique(seed);
    	String str2 = LNE_TestObjectFactory.makeUnique(seed);
    	
    	System.assertNotEquals( str1, str2, 'the point of makeUnique is that they are unique. they arent.' );
    }
    
    static testMethod void createUserWithoutException(){
    	try {
        	TestSettings ts = new TestSettings();
            ts.setupUser();
    	    ts.finalize();
    	} catch( Exception err ){
    	    System.assert( false, 'An exception shouldnt be thrown:' + err.getMessage() );
    	}
    }
    
    static testMethod void testRunAsUser(){
        TestSettings ts;
        try {
        	ts = new TestSettings(false);
            ts.setupTestUser();
    	    ts.finalize();
    	} catch( Exception err ){
    	    System.assert( false, 'An exception shouldnt be thrown:' + err.getMessage() );
    	}
    	
    	System.runAs( ts.testUser ){
    		//-- @TODO - test inserting as the user, but at this point it isn't really well defined.
    		System.debug( 'currently running as:' + ts.testUser.Name );
    	}
    }
    
    //-- test the builder
    
    //-- just to prove a point
    static testMethod void testBuilderWithAddressMultiple(){
    	TestSettings ts = new TestSettings();
		ts.finalize();
    	
		//-- can be created in so many ways.
		Account[] testAccounts = new Account[]{
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' ))
    	};
    	
    	String billingStreetAddress = '1000 west illinois st';
    	
    	LNE_TestObjectFactory factory = new LNE_TestObjectFactory( null );
    	for( Account testAccount: testAccounts ){
    		factory.importObj( testAccount ).addBillingAddress( billingStreetAddress, 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' );
    	}
    	
    	//-- just as an example, but all of them have their properties set all inline.
    	System.assertEquals( billingStreetAddress, testAccounts[0].billingStreet, 'Street address is expected to be set through addBillingAddress' );
		
		insert testAccounts;
		System.assert( true, 'No exceptions were found when creating the account' );
    }
    
    static testMethod void testBuilderWithProps(){
    	TestSettings ts = new TestSettings();
    	ts.finalize();
    	
    	String billingStreetAddress = '1000 west illinois st';
    	Map<String,Object> allProps = new Map<String,Object>{
    		'BillingStreet' => billingStreetAddress,
    		'BillingCity' => 'Chicago',
    		'BillingPostalCode' => '60402',
    		'BillingState' => 'Illinois',
    		'BillingStateCode' => 'IL',
    		'BillingCountry' => 'United States',
    		'BillingCountryCode' => 'US'
    		//-- any additional props here
    	};
    	
    	Account[] testAccounts = new Account[]{
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' )),
    		LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testAccount' ))
    	};
    	
    	
    	LNE_TestObjectFactory factory = new LNE_TestObjectFactory( null );
    	for( Account testAccount: testAccounts ){
    		factory.importObj( testAccount ).addProperties( allProps );
    		System.assertEquals( billingStreetAddress, testAccount.BillingStreet, 'Street address from props are not the same' );
    	}
		
		insert testAccounts;
		System.assert( true, 'No exceptions were found when creating the account' );
    }
    
    //-- test building objects
    //-- note that the final assert is true, because it would only get there if no unexpected exceptions were thrown beforehand.
    
    static testMethod void testBuildAccount(){
    	TestSettings ts = new TestSettings();
    	ts.setupAccount();
		ts.finalize();
   		System.assert( true, 'No exceptions were found when creating the account' );
    }
    
    static testMethod void testBuildVenueAccount(){
        TestSettings ts = new TestSettings();
        ts.setupVenueAccount();
        ts.finalize();
   		System.assert( true, 'No exceptions were found when creating the venue' );
    }
    
    //-- create contacts
    static testMethod void testCreatingContacts(){
    	TestSettings ts = new TestSettings();
    	ts.setupContact();
    	ts.finalize();
    	System.assert( true, 'No Exceptions were found creating the contact' );
    }
    
    static testMethod void testCreateDMA(){
        TestSettings ts = new TestSettings();
        ts.setupDMA();
        ts.finalize();
        System.assert( true, 'No Exceptions were found creating the DMA' );
    }
    static testMethod void testCreateVenue(){
    	TestSettings ts = new TestSettings();
        ts.setupVenueAccount();
        ts.finalize();
        System.assert( true, 'No Exceptions were found creating the Venue' );
    }
    
    static testMethod void testCreateAdmin(){
    	TestSettings ts = new TestSettings();
        User u = LNE_TestObjectFactory.createAdminUser('admin');
        ts.finalize();
        System.assert( true, 'No Exceptions were found creating the Admin User' );
    }
    
    static testMethod void testCreateMarketingUser(){
    	//TestSettings ts = new TestSettings();
        User u = LNE_TestObjectFactory.createMarketingUser('market');
       // ts.finalize();
        System.assert( true, 'No Exceptions were found creating the Marketing User' );
    }
    
    static testMethod void testCreateGroupMemberships(){
        TestSettings ts = new TestSettings();
        User u = LNE_TestObjectFactory.createAdminUser('admin');
        Group g = new Group();
        g.Name = 'test group';
        insert g;
        GroupMember[] gms = LNE_TestObjectFactory.createGroupMemberships(u.Id, new List<Id>{g.Id});
        ts.finalize();
        System.assert( true, 'No Exceptions were found creating the Venue' );
        
    }
    */
    static testMethod void testCreateStandardDataSet(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet();
        System.assert( true, 'No Exceptions were found creating the Standard Data Set' );
    }
    
    static testMethod void testCreateStandardDataSet2(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        Event__c e = new LNE_TestObjectFactory(
	        LNE_TestObjectFactory.createEvent()
		).addProperties( new Map<String,Object>{
		    'Status__c' => 'Draft',
		    'TotalSupportActExpenses__c' => 0.0
		}).buildEvent();
        LNE_TestObjectFactory.createStandardDataSet(e);
        System.assert( true, 'No Exceptions were found creating the Standard Data Set' );
    }
    
    static testMethod void testCreateStandardDataSet3(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        Event__c e = new LNE_TestObjectFactory(
	        LNE_TestObjectFactory.createEvent()
		).addProperties( new Map<String,Object>{
		    'Status__c' => 'Draft',
		    'TotalSupportActExpenses__c' => 0.0
		}).buildEvent();
		LNE_TestObjectFactory.VenueHierarchy h = LNE_TestObjectFactory.createVenueHierarchy( LNE_TestObjectFactory.ACCT_TYPE_BUSINESS_UNIT, null, null );
        LNE_TestObjectFactory.createStandardDataSet(e, h );
        System.assert( true, 'No Exceptions were found creating the Standard Data Set' );
    }
    
    static testMethod void testCreateQuickLinks(){
        LNE_TestObjectFactory.createQuickLink('test link', '', '', '', 'test');
        System.assert( true, 'No Exceptions were found creating the Quick Link' );
    }
    
}