src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Defines the musical genre of the artist</description>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Genre</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Genre.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Comedy</fullName>
    </customValue>
    <customValue>
        <fullName>Country / Folk</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Dance Music</fullName>
    </customValue>
    <customValue>
        <fullName>Hard Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Jazz / Blues</fullName>
    </customValue>
    <customValue>
        <fullName>Latin</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <customValue>
        <fullName>Other - Music</fullName>
    </customValue>
    <customValue>
        <fullName>Other - NonMusic</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;B</fullName>
    </customValue>
    <customValue>
        <fullName>Rap / Hip Hop</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Sport Event</fullName>
    </customValue>
    <customValue>
        <fullName>Theatre</fullName>
    </customValue>
    <customValue>
        <fullName>Top 40 / Pop</fullName>
    </customValue>
    <description>Defines the musical genre of the artist</description>
    <masterLabel>Genre</masterLabel>
</GlobalValueSet>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/classes/LNE_EventDateTime_CX_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_EventDateTime_CX_Test {
  
  class TestSettings {
    
    //-- instance values
    public Event__c testEvent;
    EventDateTime__c evtDateTime;
    
    public TestSettings(){
          
        //-- global setup here
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue', 'Account.Office', 'Account.Artist', 'Event__c.PromotedShow'});         
        Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
        Id RT_ACCOUNT_OFFICE_ID = recordTypeMap.get( 'Account.Office' );
        Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );
        Id RT_EVENT_PROMOTEDSHOW_ID = recordTypeMap.get( 'Event__c.PromotedShow' );
        
        
        // create artist
        Account artist = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Artist', RT_ACCOUNT_ARTIST_ID)).buildAccount();
        artist.Genre__c = 'Classic Rock';
        insert artist;
        
        // create office
        Account office = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Office', RT_ACCOUNT_OFFICE_ID)).buildAccount();
        office.Type = 'Geography';
        office.BillingStreet = '123 main st.';
        office.BillingCity = 'chicago';
        office.BillingStateCode = 'IL';
        office.BillingPostalCode = '60654';
        office.BillingCountryCode = 'US';
        office.ShippingStreet = '123 main st.';
        office.ShippingCity = 'chicago';
        office.ShippingStateCode = 'IL';
        office.ShippingPostalCode = '60654';
        office.ShippingCountryCode = 'US';
        insert office;
        
        // create venue
        Account venue = new LNE_TestObjectFactory(LNE_TestObjectFactory.createAccount('The Venue', RT_ACCOUNT_VENUE_ID)).buildAccount();
        venue.BillingStreet = '123 main st.';
        venue.BillingCity = 'chicago';
        venue.BillingStateCode = 'IL';
        venue.BillingPostalCode = '60654';
        venue.BillingCountryCode = 'US';
        venue.ShippingStreet = '123 main st.';
        venue.ShippingCity = 'chicago';
        venue.ShippingStateCode = 'IL';
        venue.ShippingPostalCode = '60654';
        venue.ShippingCountryCode = 'US';
        venue.Market__c = 'Chicago';
        venue.Capacity__c = 100;
        venue.PrimaryOffice__c = office.id;
        insert venue;
        
        system.debug('VENUE = ' + [select BillingCountry, BillingCountryCode from Account where id = :venue.Id]);
          
        // create event
        system.debug('EVENT RT ID = ' + RT_EVENT_PROMOTEDSHOW_ID);
        Event__c event = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createEvent()
			).addProperties( new Map<String,Object>{
			    'status__c' => 'Draft',
			    'Venue__c' => venue.Id,
			    'Artists__c' => 'Test Artist',
			    'RecordTypeId' => RT_EVENT_PROMOTEDSHOW_ID
			}).buildEvent();
      //  insert event;
        LNE_TestObjectFactory.createStandardDataSet(event);
        evtDateTime = new EventDateTime__c(
            event__c = event.Id, 
            EventYear__c = String.valueOf(System.now().year() + 2));
        insert evtDateTime;
    }
    
  
    public void typicalSetup(){
      //-- specific setup here
    }
    
    public void finalize(){
      
    }
  }

  @testSetup
  static void setup(){
      LNE_TestObjectFactory.prepStandardCustomSettings();
  }

  //-- test test methods here
  static testMethod void schedulesWithoutException() {
    TestSettings ts = new TestSettings();
    ts.typicalSetup();
    ts.finalize();
    System.assert( true, 'No Exceptions have occurred in getting here' );
  }
  
  //-- test functionality here
  static testMethod void test1() {
    TestSettings ts = new TestSettings();
    ts.typicalSetup();
    ts.finalize();
    LNE_EventDateTime_CX evtDateTimeCtrl = new LNE_EventDateTime_CX( new ApexPages.StandardController(ts.evtDateTime));
    String pollInterval = evtDateTimeCtrl.getGridLostFocusPollInterval();
  }  
  
}