src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <description>Record type for co-promoters related to events and shows</description>
        <label>Co-Promoter</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BonusDetail__c.object
<CustomObject>
    <description>Additional terms for an artist or co-promoter usually based upon ticket sales representing a bonus above a guarantee or percentage of ticket revenues</description>
    <fields>
        <fullName>BonusAmount__c</fullName>
        <label>Bonus Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BonusBase__c</fullName>
        <label>Bonus Base</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Drop Count</fullName>
                </value>
                <value>
                    <fullName>Net Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Bonus Details</relationshipLabel>
        <relationshipName>BonusDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Increment__c</fullName>
        <label>Increment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartPoint__c</fullName>
        <label>Start Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step Up</fullName>
                </value>
                <value>
                    <fullName>Retro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bonus Detail</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bonus Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>AncillaryRevenue__c</fullName>
        <label>Ancillary Revenue</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CoPromoter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Promoter</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Co-Promoter Deals</relationshipLabel>
        <relationshipName>CoPromoterDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DownsideRisk__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Downside Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventLoss__c</fullName>
        <label>Event Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EventProfit__c</fullName>
        <label>Event Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentLoss__c</fullName>
        <label>Expense Adjustment Loss</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentProfit__c</fullName>
        <label>Expense Adjustment Profit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShareInTalentOverhead__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Share In Talent Overhead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DealSettlementLedger__c.object
<CustomObject>
    <description>Junction object linking the Deal with Ledger Entries so settlement values can be planned and settled upon per Deal</description>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentAtSellout__c</fullName>
        <formula>IF(!Share__c, 0,
   IF(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,
      IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c - LedgerEntry__r.PrimaryCoProShareAtSellout__c
      ),
      0
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <formula>text( Deal__r.PrimarySecondaryCoPromoter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>LedgerEntry__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Settlement-Ledger</label>
    <nameField>
        <displayFormat>DSL-{000000}</displayFormat>
        <label>Deal Settlement-Ledger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Settlement-Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustment__c</fullName>
        <label>Expense Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentatSellout__c</fullName>
        <label>Expense Adjustment at Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InHouseatSellout__c</fullName>
        <label>In House at Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferAtSellout__c</fullName>
        <label>Offer At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettleAtActual__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Settle At Actual</label>
        <type>Checkbox</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <recordTypes>
        <fullName>TicketRevenue</fullName>
        <active>true</active>
        <description>Revenue from ticket sales</description>
        <label>Ticket Revenue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_LedgerEntryDSLCreateDelete_T_Test.cls
@isTest
private class LNE_LedgerEntryDSLCreateDelete_T_Test {
    static String RT_ARTIST = 'Account.Artist';
    static String RT_OFFICE = 'Account.Office';
    static String RT_VENUE = 'Account.Venue';
    static String RT_COPROMOTER = 'Account.CoPromoter';
    static String RT_TICKET_REVENUE = 'LedgerEntry__c.TicketRevenue';
	static String RT_EXPENSES = 'LedgerEntry__c.Expenses';
	static String RT_ANCILLARY = 'LedgerEntry__c.Ancillary';
	static String RT_COGS = 'LedgerEntry__c.COGS';
	static String RT_DEAL_COPROMOTER = 'Deal__c.CoPromoter';

	static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
	    new String[]{ RT_TICKET_REVENUE, RT_EXPENSES , RT_COPROMOTER, RT_ARTIST, RT_OFFICE, RT_VENUE, RT_ANCILLARY, RT_COGS, RT_DEAL_COPROMOTER}
    );

    static Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( RT_ARTIST );
    static Id RT_ACCOUNT_OFFICE_ID = recordTypeMap.get( RT_OFFICE );
    static Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( RT_VENUE );
    static Id RT_ACCOUNT_COPROMOTER_ID = recordTypeMap.get( RT_COPROMOTER );
    static Id RT_TICKET_REVENUE_ID = recordTypeMap.get( RT_TICKET_REVENUE );
    static Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
    static Id RT_ANCILLARY_ID = recordTypeMap.get( RT_ANCILLARY );
    static Id RT_COGS_ID = recordTypeMap.get( RT_COGS );
    static Id RT_DEAL_COPROMOTER_ID = recordTypeMap.get( RT_DEAL_COPROMOTER );
    
    static Map<String,GLAccount__c> glAccountsMap = LNE_Util.getGLAccounts(new String[] {'40100','40116', '40205','50103','50302','50339'});
    
     /** Co-Promote Expense GL CODE **/
    public static final String COPRO_EXPENSE_GL_CODE='50302';
     /** Building Co-Promote GL CODE **/
    public static final String COPRO_BOOKING_GL_CODE='50339';
    
    class TestSettings {
		public Event__c testEvent {get; set;}
		public Deal__c testPrimaryCoPromoter {get; set;}
		public Deal__c testSecondaryCoPromoter {get; set;}
		
		public TestSettings() {
		    
		}
		
		public void typicalSetup(){
		    testEvent = [select Id, Venue__c from Event__c limit 1];
		    
		    Deal__c headliner = [select Id from Deal__c where Type__c = 'Primary Headliner' and Event__c = :testEvent.Id];
		    
			//Bonus Detail
			BonusDetail__c bonus = new BonusDetail__c();
			bonus.BonusBase__c = 'Paid Tickets';
			bonus.Type__c = 'Retro';
			bonus.BonusAmount__c = 1;
			bonus.StartPoint__c = 0;
			bonus.Increment__c = 1;
			bonus.Deal__c = headliner.Id;
			LNE_FinancialCalculator.runUpdates = false;
			insert bonus;
		}
		
		public void finalize(){
		}
	}
	
	@testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet();
        
        LNE_Util.refreshGLAccountCache();
        
        glAccountsMap = LNE_Util.getGLAccounts(new String[] {'40100','40116','40205','50103','50302','50339'});
    }
    
    //
    // Test1: DSL Creation on insert of Ledger Entry where SettleAtActual__c = false
    ///
	private static testMethod void test1() {
        TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		
		Account copro1 = [select Id from Account where name = 'Co Pro 1'];
		Deal__c PrimaryInternalDeal = [select Id from Deal__c where Type__c = 'Internal' AND PrimarySecondaryCoPromoter__c = 'Primary'];
		
		test.startTest();
		
		Deal__c deal1 = new Deal__c();
    	deal1.Event__c = tsettings.testEvent.Id;
        deal1.Type__c = '3rd Party';
        deal1.CoPromoter__c = copro1.id;
        deal1.EventProfit__c = 50;
        deal1.EventLoss__c = 50;
        deal1.ExpenseAdjustmentProfit__c = 50;
        deal1.ExpenseAdjustmentLoss__c = 50;
        deal1.AncillaryRevenue__c = 50;
        deal1.PrimarySecondaryCoPromoter__c = 'Primary';
        deal1.ShareInTalentOverhead__c = True;
        deal1.DownsideRisk__c = True;
        deal1.RecordTypeId = RT_DEAL_COPROMOTER_ID;

        PrimaryInternalDeal.EventProfit__c = 50;
        PrimaryInternalDeal.EventLoss__c = 50;
        PrimaryInternalDeal.ExpenseAdjustmentProfit__c = 50;
        PrimaryInternalDeal.ExpenseAdjustmentLoss__c = 50;
        PrimaryInternalDeal.AncillaryRevenue__c = 50;
        
        LNE_FinancialCalculator.runUpdates = true;
        update PrimaryInternalDeal;
        LNE_FinancialCalculator.runUpdates = true;
        insert deal1;

		//Expense
		LedgerEntry__c ledgerEntry1 = new LedgerEntry__c(
            GLAccount__c = glAccountsMap.get('50103').Id,
            Event__c = tsettings.testEvent.Id,
            RecordTypeId = RT_EXPENSES_ID,
            SettleAtActual__c = false,
            ExpenseAdjustment__c = 333,
            OfferAtSellout__c = 200, // OfferAtSellout__c - InHouseatSellout__c = le.ExpenseAdjustmentatSellout__c //calculated in FC
            InHouseatSellout__c = 100
        );
    
        insert new List<LedgerEntry__c>{ledgerEntry1};
        
        DealSettlementLedger__c[] dsls = new DealSettlementLedger__c[]{};
        dsls = [select id from DealSettlementLedger__c where LedgerEntry__c = :ledgerEntry1.Id and Deal__c =:deal1.id];
        
        // did trigger create DSL?
        system.assertEquals(1, dsls.size());
        
        //
        // Test 2: DSL deletion on update when LedgerEntry__c.SettleAtActual__c = true
        //
        ledgerEntry1.SettleAtActual__c = true;
        update ledgerEntry1;
        
        dsls = [select id from DealSettlementLedger__c where LedgerEntry__c = :ledgerEntry1.Id and Deal__c =:deal1.id];
        
        // did trigger delete DSL?
        system.assertEquals(0, dsls.size());
        
		test.stopTest();
	}
	
	//
    // Test 3: DSL Creation on update of Ledger Entry where SettleAtActual__c is updated from true to false
    ///
	private static testMethod void test2() {
        TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		
		Account copro1 = [select Id from Account where name = 'Co Pro 1'];
		Deal__c PrimaryInternalDeal = [select Id from Deal__c where Type__c = 'Internal' AND PrimarySecondaryCoPromoter__c = 'Primary'];
		
		test.startTest();
		
		Deal__c deal1 = new Deal__c();
    	deal1.Event__c = tsettings.testEvent.Id;
        deal1.Type__c = '3rd Party';
        deal1.CoPromoter__c = copro1.id;
        deal1.EventProfit__c = 50;
        deal1.EventLoss__c = 50;
        deal1.ExpenseAdjustmentProfit__c = 50;
        deal1.ExpenseAdjustmentLoss__c = 50;
        deal1.AncillaryRevenue__c = 50;
        deal1.PrimarySecondaryCoPromoter__c = 'Primary';
        deal1.ShareInTalentOverhead__c = True;
        deal1.DownsideRisk__c = True;
        deal1.RecordTypeId = RT_DEAL_COPROMOTER_ID;

        PrimaryInternalDeal.EventProfit__c = 50;
        PrimaryInternalDeal.EventLoss__c = 50;
        PrimaryInternalDeal.ExpenseAdjustmentProfit__c = 50;
        PrimaryInternalDeal.ExpenseAdjustmentLoss__c = 50;
        PrimaryInternalDeal.AncillaryRevenue__c = 50;
        
        LNE_FinancialCalculator.runUpdates = true;
        update PrimaryInternalDeal;
        LNE_FinancialCalculator.runUpdates = true;
        insert deal1;

		//Expense
		LedgerEntry__c ledgerEntry1 = new LedgerEntry__c(
            GLAccount__c = glAccountsMap.get('50103').Id,
            Event__c = tsettings.testEvent.Id,
            RecordTypeId = RT_EXPENSES_ID,
            SettleAtActual__c = true,
            ExpenseAdjustment__c = 333,
            OfferAtSellout__c = 200, // OfferAtSellout__c - InHouseatSellout__c = le.ExpenseAdjustmentatSellout__c //calculated in FC
            InHouseatSellout__c = 100
        );
    
        insert new List<LedgerEntry__c>{ledgerEntry1};
        
        DealSettlementLedger__c[] dsls = new DealSettlementLedger__c[]{};
        
        //
        // Test 3: DSL creation on update when LedgerEntry__c.SettleAtActual__c = false
        //
        ledgerEntry1.SettleAtActual__c = false;
        update ledgerEntry1;
        
        dsls = [select id from DealSettlementLedger__c where LedgerEntry__c = :ledgerEntry1.Id and Deal__c =:deal1.id];
        
        // did trigger delete DSL?
        system.assertEquals(1, dsls.size());
        
		test.stopTest();
	}
	
	//
    // Test 4: test deleting ledger entry trigger financial calculator
    ///
	private static testMethod void test3() {
        TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		
		Account copro1 = [select Id from Account where name = 'Co Pro 1'];

		test.startTest();

		//Expense
		LedgerEntry__c ledgerEntry1 = new LedgerEntry__c(
            GLAccount__c = glAccountsMap.get('50103').Id,
            Event__c = tsettings.testEvent.Id,
            RecordTypeId = RT_EXPENSES_ID,
            SettleAtActual__c = true,
            ExpenseAdjustment__c = 333,
            OfferAtSellout__c = 200, // OfferAtSellout__c - InHouseatSellout__c = le.ExpenseAdjustmentatSellout__c //calculated in FC
            InHouseatSellout__c = 100
        );
    
        insert new List<LedgerEntry__c>{ledgerEntry1};
        
        // Test 4: test deleting ledger entry trigger financial calculator
        LNE_LedgerEntryDSLCreateDelete_T.executeDelete(new List<LedgerEntry__c>{ledgerEntry1});
        
		test.stopTest();
	}

}