src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LNEAPIId__c</fullName>
        <description>Livenation.comAPI Id</description>
        <externalId>true</externalId>
        <label>LNE API Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <formula>Event__r.Venue__r.VenueName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venue</label>
        <type>Text</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_API_UpdatePurchaseURL_C.cls
/**
 *  Controller for the LNE_LiveNationAPI_UpdatePurchaseURL lightning component.
 *  @author Phil Rymek (prymek@salesforce.com)
 **/
public with sharing class LNE_API_UpdatePurchaseURL_C {
    
    /**
     *  Sets the purchase url for the particular event/ad plan
     *  @param recordId (Id)
     *  @param livenationId (String)
     *  @return Boolean - whether succeeded (true) or not (false)
     **/
    @AuraEnabled
    public static Boolean setEventLiveNationId( Id recordId, String liveNationData ){
    	if (!String.isBlank(liveNationData)) {
    		List<String> values = liveNationData.split('\\|;');
    		
    		String buyLink = values.get(0);
            String eventAPIId = values.get(1);
            
            update new AdPlan__c(
                Id = recordId,
                PurchaseURL__c = buyLink
            );
            
            List<AdPlan__c> temp = 
                [SELECT Event__c FROM AdPlan__c WHERE Id = :recordId];
                
            if(!temp.isEmpty()) {
                update new Event__c(
                    Id = temp.get(0).Event__c,
                    PurchaseURL__c = buyLink,
                    LNEAPIId__c = eventAPIId
                );
            }
            
            return true;
    	}

    	return false;
    }    
    
    /**
     *  Performs the rest call to the LiveNation API.
     *  @param searchQuery
     *  @return SelectOption[]
     **/
    @AuraEnabled
    public static List<EventResult> searchEvents( String adPlanId ) {
        List<EventResult> results = new List<EventResult>();
        AdPlan__c current;
        Deal__c primary;
        
        List<AdPlan__c> adPlans = 
            [SELECT Event__c, Event__r.Venue__r.LNEAPIId__c
               FROM AdPlan__c
              WHERE Id = :adPlanId];
        
        if(adPlans.isEmpty()) {
            return results;
        }
        
        current = adPlans.get(0);
        
        List<Deal__c> primaryDeal = 
            [SELECT Artist__r.LNEAPIId__c
               FROM Deal__c
              WHERE Event__c = :current.Event__c AND Type__c = 'Primary Headliner'];        
        
        if(primaryDeal.isEmpty()) {
            return results;
        }        
        
        primary = primaryDeal.get(0);
        
        LNE_API_EventSearchResp response = LNE_EventSearch.getEventsByVenue(
            primary.Artist__r.LNEAPIId__c, 
            '', 
            current.Event__r.Venue__r.LNEAPIId__c);
        
        if(response != null && response.data != null && !response.data.isEmpty()) {
            results = createResponseOptions(response);
        }
        
        return results;
    }

    /**
     * Checks if the current user can edit this Ad Plan and related Event record.
     * Normally we would use a SOQL query on Account:
     * SELECT UserRecordAccess.HasEditAccess FROM AdPlan__c
     * But that won't tell us if any validation rules would stop the current user from
     * editing this record.
     * @param recordId (Id)
     * @return Boolean
     **/
    @AuraEnabled
    public static Boolean checkIfUserCanEditCurrentRecord(Id recordId) {
    	Boolean success = false;
    	Savepoint sp = Database.setSavepoint();

    	try {
    		AdPlan__c plan = new AdPlan__c(Id=recordId,PurchaseURL__c='test23423423test234234242test23423423test234234242');
    		Database.SaveResult sr = Database.update(plan);
    		
    		List<AdPlan__c> plans = [SELECT Id, Event__c FROM AdPlan__c WHERE Id = :recordId AND Event__c != null];
    		
    		if(plans.isEmpty()) {
    		    success = false;
    		} else {
    		    success = LNE_Util.isEventEditable(plans.get(0).Event__c);
    		}
    	} catch (DMLException e) {
    		success = false;
    	}

    	Database.rollback(sp);

    	return success;
    }
    
    /**
     *  Creates a set of options from an LNE_API_EventSearchResponse
     *  @param response (LNE_API_EventSearchResp)
     *  @returns SelectOption[]
     **/
    private static List<EventResult> createResponseOptions( LNE_API_EventSearchResp response ){
        List<EventResult> results = new List<EventResult>();
    
        for( LNE_API_EventSearchResp.Data result : response.data ){
            results.add(new EventResult(result.name, result.local_start_time, result.buy_link, result.id));
        }
        
        return results;
    }

    public class EventResult {
        
    	@AuraEnabled
    	public String name {get;set;}
    	
    	@AuraEnabled
    	public String purchaseURL {get;set;}    	

    	public EventResult(String eventName, String eventDate, String buyLink, String eventAPIId) {
    		name = eventName + ' - ' + getFormattedStartTime(eventDate);
    		purchaseURL = buyLink + '|;' + eventAPIId;
    	}
    	
    	private String getFormattedStartTime(String eventDate) {
    	    if(String.isNotBlank(eventDate)) {
    	        eventDate = eventDate.replace('T', ' ');
    	        DateTime startTime = DateTime.valueOf(eventDate);
    	        return startTime.format();
    	    }
    	    
    	    return '';
    	}


    }
}