src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record type for capturing vendor information for marketing purposes</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>AdPlanName__c</fullName>
        <label>Ad Plan Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LNEAdPlanBudget__c</fullName>
        <label>LNE Ad Plan Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StandaloneDate__c</fullName>
        <label>Standalone Date</label>
        <type>Date</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Advertisement__c.object
<CustomObject>
    <description>Ads that are planned to be run as part of a marketing plan</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Advertisements</relationshipLabel>
        <relationshipName>Advertisements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BuyType__c</fullName>
        <label>Buy Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Buy</fullName>
                    <default>true</default>
                    <label>Regular Buy</label>
                </value>
                <value>
                    <fullName>Pkg. Deal (date range)</fullName>
                </value>
                <value>
                    <fullName>Pkg. Deal (select dates)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MediaFormatType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net__c</fullName>
        <label>Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advertisements (Vendor)</relationshipLabel>
        <relationshipName>Advertisements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Advertisement</label>
    <nameField>
        <displayFormat>Adv-{000000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertisements</pluralLabel>
    <recordTypes>
        <fullName>Digital</fullName>
        <active>true</active>
        <description>Record type for digital advertisements</description>
        <label>Digital</label>
    </recordTypes>
    <recordTypes>
        <fullName>Outdoor</fullName>
        <active>true</active>
        <description>Record type for outdoor advertisements</description>
        <label>Outdoor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Print</fullName>
        <active>true</active>
        <description>Record type for Print advertisements</description>
        <label>Print</label>
    </recordTypes>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <description>Record type for radio advertisements</description>
        <label>Radio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Television</fullName>
        <active>true</active>
        <description>Record type for television advertisements</description>
        <label>Television</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/MediaFormatType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Contemporary</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Standards</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Hits</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Classical</fullName>
    </customValue>
    <customValue>
        <fullName>College Paper</fullName>
    </customValue>
    <customValue>
        <fullName>College Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Contemporary Christian</fullName>
    </customValue>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Dance - CHR</fullName>
    </customValue>
    <customValue>
        <fullName>Format Not Available</fullName>
    </customValue>
    <customValue>
        <fullName>High School Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Hot AC</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Rock</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>News/Talk</fullName>
    </customValue>
    <customValue>
        <fullName>Oldies</fullName>
    </customValue>
    <customValue>
        <fullName>Online Publication</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Print Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Print Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Print Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Public Television</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Mexican</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <description>Types of music broadcast on media channels</description>
    <masterLabel>Media Format Type</masterLabel>
</GlobalValueSet>

src/classes/LNE_AdvertisementAPI_CX_Test.cls
@isTest
public class LNE_AdvertisementAPI_CX_Test {
	static final String RT_VENDOR = 'Account.Vendor';
    
    class TestSettings {
        
        public TestSettings() {

        }
        
        public Advertisement__c typicalSetup(String advertRecordType, Decimal commission){

        	//insert vendor
            Map<String,Id> accountRecordTypeMap = LNE_Util.getRecordTypes(
                    new String[]{RT_VENDOR}
            );

        	ID RT_VENDOR_ID = accountRecordTypeMap.get(RT_VENDOR);

            Account vendor = LNE_TestObjectFactory.createAccount('Test Vendor');
            vendor.RecordTypeId = RT_VENDOR_ID;
            vendor.Format__c = 'Country';

            insert vendor;

        	//insert adplan
            AdPlan__c adPlan = new AdPlan__c(
                AdPlanName__c = 'Test Ad Plan',
                LNEAdPlanBudget__c = 1000000,
                StandaloneDate__c = Date.today().addDays(7)
            );

            insert adPlan;

            //insert advertisement

        	Id recordTypeId;
        	if(advertRecordType != null) recordTypeId =
        		[select Id, name, developername from RecordType where Name =: advertRecordType and SobjectType = 'Advertisement__c'].Id;
	        Date startDate = Date.today();
            Date endDate = startDate.addDays(7);
	        
	        Advertisement__c ad = new Advertisement__c(	            
	            AdPlan__c =  adPlan.Id,
	            BuyType__c = LNE_Constants.AD_BUY_TYPE_REGULAR,
	            StartDate__c = startDate,
	            EndDate__c = endDate,
	            StartTime__c = '6:00 AM',
	            EndTime__c = '10:00 PM',
	            Net__c = 100000,
	            Format__c = 'Country',
	            Vendor__c = vendor.Id
	        );
	        if(recordTypeId != null) ad.RecordTypeId = recordTypeId;
	        if(commission != null) ad.Commission__c = commission;
	        insert ad;
         	return ad;
        }

      public void finalize(){
      
      }
    }
    
  //-- test test methods here

  @testSetup
  static void setup(){
      LNE_TestObjectFactory.prepStandardCustomSettings();
  }

  static testMethod void testAdvertisementAPI_Digital_with_Commission() {
  	//Test null Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup(null,3000);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'null');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }

  static testMethod void testAdvertisementAPI_Digital() {
  	//Test Digital Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup('Digital',null);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'Digital');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }

  static testMethod void testAdvertisementAPI_Outdoor() {
  	//Test Outdoor Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup('Outdoor',null);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'outdoor');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }

  static testMethod void testAdvertisementAPI_Print() {
  	//Test Print Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup('Print',null);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'Print');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }

  static testMethod void testAdvertisementAPI_Radio() {
  	//Test Radio Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup('Radio',null);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'Radio');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }

  static testMethod void testAdvertisementAPI_Television() {
  	//Test Television Advertisement
  	TestSettings ts = new TestSettings();
    Advertisement__c ad = ts.typicalSetup('Television',null);
	   
	PageReference pageRef = Page.LNE_AdvertisementAPI;
	pageRef.getParameters().put('Advertisement__c', JSON.serialize(ad));
	pageRef.getParameters().put('callback', 'testApiCallback2');
	pageRef.getParameters().put('type', 'Television');
	Test.setCurrentPageReference(pageRef);
	LNE_AdvertisementAPI_CX api = new LNE_AdvertisementAPI_CX();
	api.processRequest();
  }
}