src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LNEAPIId__c</fullName>
        <description>Livenation.comAPI Id</description>
        <externalId>true</externalId>
        <label>LNE API Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LNEAPIID__c</fullName>
        <externalId>true</externalId>
        <label>LNE API ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseURL__c</fullName>
        <label>Purchase URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_PurchaseURL_Batch_Test.cls
@isTest
private class LNE_PurchaseURL_Batch_Test {

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    private class TestSettings {
        public Map<String,Id> setupData() {
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{'Account.Venue', 'Event__c.PromotedShow'});   
            Id rtPromotedId = recordTypeMap.get('Event__c.PromotedShow');
            
    		Event__c testEvent = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = 'Pending Likely',
               	RecordTypeId = rtPromotedId,
               	EventLastDate__c = System.today().addDays(1)
            );
            
            List<Event__c> events = new List<Event__c>{testEvent};
            return LNE_TestObjectFactory.createStandardDataSetList(events);  
        }
    }

	private static testMethod void testUpdatePurchaseURLFromAPI() {
	    TestSettings ts = new TestSettings();
	    Map<String,Id> objectToId = ts.setupData();	    
	    
	    Test.startTest();
	    
	    update new List<Account>{
	        new Account(Id = objectToId.get('venue'), LNEAPIID__c = 'ven_15056'),
	        new Account(Id = objectToId.get('artist'), LNEAPIID__c = 'art_15056')
	    };
	    
        Tour__c tour = LNE_TestObjectFactory.createTour('test tour', objectToId.get('artist'));
        insert tour;	    
	    
	    insert LNE_TestObjectFactory.createAdPlan('test ad plan', 10000, objectToId.get('event-0'), tour.Id);  
        
        EventDateTime__c evtDateTime = LNE_TestObjectFactory.createEventDateTime(
            objectToId.get('event-0'), 
            System.today().addDays(1), 
            System.today().addDays(1), 
            String.valueOf(System.now().year()));
            
        insert evtDateTime;            
        
        insert LNE_TestObjectFactory.createEventTicketAgency(evtDateTime.Id, 'seed-with-this');
        
        LNE_PurchaseURL_Batch b = new LNE_PurchaseURL_Batch();
        Id batchProcessId = Database.executeBatch(b, LNE_PurchaseURL_Batch.BATCH_SIZE);
        Test.stopTest();
        
        List<Event__c> testEvents = [SELECT PurchaseURL__c FROM Event__c];
        List<AdPlan__c> testAdPlans = [SELECT PurchaseURL__c FROM AdPlan__c];
        
        System.assertNotEquals(null, batchProcessId);
        System.assertEquals(1, testEvents.size());
        
        System.assertEquals('http://ticketmaster.com/event/1B00522BCEF04D7F', testEvents.get(0).PurchaseURL__c);
        System.assertEquals(1, testAdPlans.size());
        System.assertEquals('http://ticketmaster.com/event/1B00522BCEF04D7F', testAdPlans.get(0).PurchaseURL__c);
	}
	
	private static testMethod void testUpdatePurchaseURLFromTicketAgency() {
	    TestSettings ts = new TestSettings();
	    Map<String,Id> objectToId = ts.setupData();	    
	    
	    Test.startTest();
	    
	    update new List<Account>{
	        new Account(Id = objectToId.get('venue'), LNEAPIID__c = 'ven_fake'),
	        new Account(Id = objectToId.get('artist'), LNEAPIID__c = 'art_fake')
	    };
	    
        Tour__c tour = LNE_TestObjectFactory.createTour('test tour', objectToId.get('artist'));
        insert tour;	    
	    
	    insert LNE_TestObjectFactory.createAdPlan('test ad plan', 10000, objectToId.get('event-0'), tour.Id);  
        
        EventDateTime__c evtDateTime = LNE_TestObjectFactory.createEventDateTime(
            objectToId.get('event-0'), 
            System.today().addDays(1), 
            System.today().addDays(1), 
            String.valueOf(System.now().year()));
            
        insert evtDateTime;            
        
        insert LNE_TestObjectFactory.createEventTicketAgency(evtDateTime.Id, 'seed-with-this');
        
        LNE_PurchaseURL_Batch b = new LNE_PurchaseURL_Batch();
        Id batchProcessId = Database.executeBatch(b, LNE_PurchaseURL_Batch.BATCH_SIZE);
        Test.stopTest();
        
        List<Event__c> testEvents = [SELECT PurchaseURL__c FROM Event__c];
        List<AdPlan__c> testAdPlans = [SELECT PurchaseURL__c FROM AdPlan__c];
        
        System.assertNotEquals(null, batchProcessId);
        System.assertEquals(1, testEvents.size());
        
        System.assertEquals('http://ticketmaster.com/event/seed-with-this', testEvents.get(0).PurchaseURL__c);
        System.assertEquals(1, testAdPlans.size());
        System.assertEquals('http://ticketmaster.com/event/seed-with-this', testAdPlans.get(0).PurchaseURL__c);
	}	

}