src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventStatus__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventTicketAgency__c.object
<CustomObject>
    <description>Links the specific ticket agency event with the event date time(s) through the Event-Ticket junction object</description>
    <fields>
        <fullName>BypassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Event-Ticket Agencies</relationshipLabel>
        <relationshipName>EventTicketAgencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Ticket Agency</label>
    <nameField>
        <displayFormat>ETA-{000000}</displayFormat>
        <label>Event-Ticket Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Ticket Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ManualTicketCount__c.object
<CustomObject>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Manual Ticket Counts</relationshipLabel>
        <relationshipName>ManualTicketCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Holds__c</fullName>
        <label>Holds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <label>Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TicketCount__c</fullName>
        <label>Ticket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TicketSalesDate__c</fullName>
        <label>Ticket Sales Date</label>
        <type>Date</type>
    </fields>
    <label>Manual Ticket Count</label>
    <nameField>
        <displayFormat>MTC-{000000}</displayFormat>
        <label>Manual Ticket Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Ticket Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OnSaleDateTime__c.object
<CustomObject>
    <description>Dates that tickets are on sale or pre sale or other important dates around ticket sales/announcements to identify</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>On Sale Date Times</relationshipLabel>
        <relationshipName>OnSaleDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventTicketAgency__c</fullName>
        <label>Event-Ticket Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EventTicketAgency__c.EventDateTime__c</field>
                <operation>equals</operation>
                <valueField>$Source.EventDateTime__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>EventTicketAgency__c</referenceTo>
        <relationshipLabel>On Sale Date Times</relationshipLabel>
        <relationshipName>OnSaleDateTimes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SaleStartDate__c</fullName>
        <label>Sale Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public On Sale</fullName>
                </value>
                <value>
                    <fullName>Pre Sale</fullName>
                </value>
                <value>
                    <fullName>Fan Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>On Sale Date Time</label>
    <nameField>
        <displayFormat>OSD-{000000}</displayFormat>
        <label>On Sale Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On Sale Date Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>ActualGrossToDate__c</fullName>
        <label>Actual Gross To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ActualSalesToDate__c</fullName>
        <label>Actual Sales To Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Holds__c</fullName>
        <label>Holds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/classes/LNE_MassManualTicketCounts_C_Test.cls
/**
 * Test class for LNE_MassManualTicketCounts_C
 * @author Vinay
 * US199
 * @version - us199 
 **/
@isTest
private class LNE_MassManualTicketCounts_C_Test
{
	
	@testSetup
    static void globalSetup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

	class TestSettings {
        public TestSettings() {
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
			
			LNE_TestObjectFactory.VenueHierarchy acctHierarchy = LNE_TestObjectFactory.createVenueHierarchy(
            	LNE_TestObjectFactory.ACCT_TYPE_DIVISION, null, null
            );
            Account venue = acctHierarchy.venue;
            Account office = acctHierarchy.office;
			
            //-- global setup here
            Event__c[] myEvents = new Event__c[]{
            	//-- first event
            	new LNE_TestObjectFactory(
			        LNE_TestObjectFactory.createEvent()
				).addProperties( new Map<String,Object>{
				    'EventName__c' => 'My Test Event',
				    'Status__c' => 'Draft'
				}).buildEvent(),
				//-- second event
				new LNE_TestObjectFactory(LNE_TestObjectFactory.createEvent()
				).addProperties( new Map<String,Object>{
				    'Status__c' => new List<String>(LNE_Constants.MASS_MANUAL_TICKET_COUNT_EVENT_STATUS)[0],
				    'Venue__c' => venue.id,
				    'Office__c' => office.Id 
				}).buildEvent()
            };
            Event__c event = myEvents[0];
            Event__c event2 = myEvents[1];
            
            Map<String,Id> dataSetIdMap = LNE_TestObjectFactory.createStandardDataSetList( myEvents, accthierarchy );
            
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue',  'Account.Artist'});         
            Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
            Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );
            
			Id artistId = dataSetIdMap.get( LNE_TestObjectFactory.STANDARD_DATA_ARTIST );
            Account artist = [Select Id, Name from Account where Id = :artistId limit 1];

            event.Status__c = new List<String>(LNE_Constants.MASS_MANUAL_TICKET_COUNT_EVENT_STATUS)[0];
            update event;

            venue.Market__c = 'Chicago';
            update venue;

            List<EventDateTime__c> evtDateTimeList = new List<EventDateTime__c>();
            EventDateTime__c evtDateTime1 = new EventDateTime__c(
	            event__c = event.Id, 
	            EventStatus__c = new List<String>(LNE_Constants.MASS_MANUAL_TICKET_COUNT_EVENT_STATUS)[0],
	            EventYear__c = String.valueOf(System.now().year() + 2),
	            Market__c = 'Chicago',
	            Venue__c = venue.Id,
	            Artists__c = artist.Name,
	            EventDate__c = System.today().addDays(2)
            );
            evtDateTimeList.add(evtDateTime1);

            EventDateTime__c evtDateTime2 = new EventDateTime__c(
	            event__c = event2.Id, 
	            EventYear__c = String.valueOf(System.now().year() + 2),
	            Market__c = 'Albany',
                EventDate__c = System.today().addDays(2)
            );
            evtDateTimeList.add(evtDateTime2);

        	insert evtDateTimeList;

        	evtDateTime2.Market__c = 'Albany';
        	update evtDateTime2;

        	//Insert Manual Ticket counts for event date times
        	List<ManualTicketCount__c> manualTicketCountList = new List<ManualTicketCount__c>();
        	for(Integer i = 1; i <= 10; i++){
        		ManualTicketCount__c newManualTicketCount = new ManualTicketCount__c();
        		newManualTicketCount.EventDateTime__c = evtDateTime1.Id;
        		newManualTicketCount.Comps__c = i;
        		newManualTicketCount.Holds__c = i;
        		newManualTicketCount.Kills__c = i;
        		newManualTicketCount.Open__c = i;
        		newManualTicketCount.TicketCount__c = i;
        		newManualTicketCount.TicketSalesDate__c = system.today();

        		manualTicketCountList.add(newManualTicketCount);
        	}
        	insert manualTicketCountList;

        	//Insert EventTicketAgency for event date times
        	List<EventTicketAgency__c> eventTicketAgencyList = new List<EventTicketAgency__c>();
        	
    		EventTicketAgency__c newEventTicketAgency1 = new EventTicketAgency__c();
    		newEventTicketAgency1.EventDateTime__c = evtDateTime1.Id;
    		newEventTicketAgency1.BypassValidation__c = true;
    		eventTicketAgencyList.add(newEventTicketAgency1);

    		EventTicketAgency__c newEventTicketAgency2 = new EventTicketAgency__c();
    		newEventTicketAgency2.EventDateTime__c = evtDateTime2.Id;
    		newEventTicketAgency2.BypassValidation__c = true;
    		eventTicketAgencyList.add(newEventTicketAgency2);

        	insert eventTicketAgencyList;

        	//Insert OnSaleDateTime for event date times
        	List<OnSaleDateTime__c> onSaleDateTimeList = new List<OnSaleDateTime__c>();
        	for(Integer i = 1; i <= 10; i++){
        		OnSaleDateTime__c newOnSaleDateTime1 = new OnSaleDateTime__c();
        		newOnSaleDateTime1.EventDateTime__c = evtDateTime1.Id;
        		newOnSaleDateTime1.SaleStartDate__c = system.today().addDays(-1);
        		newOnSaleDateTime1.EventTicketAgency__c = newEventTicketAgency1.Id;
        		onSaleDateTimeList.add(newOnSaleDateTime1);

        		OnSaleDateTime__c newOnSaleDateTime2 = new OnSaleDateTime__c();
        		newOnSaleDateTime2.EventDateTime__c = evtDateTime2.Id;
        		newOnSaleDateTime2.SaleStartDate__c = system.today().addDays(-1);
        		newOnSaleDateTime2.EventTicketAgency__c = newEventTicketAgency2.Id;
        		onSaleDateTimeList.add(newOnSaleDateTime2);
        	}
        	insert onSaleDateTimeList;

        	//Insert TicketScale for event date times
        	List<TicketScale__c> ticketScaleList = new List<TicketScale__c>();
        	for(Integer i = 1; i <= 10; i++){
        		TicketScale__c newTicketScale1 = new TicketScale__c();
        		newTicketScale1.EventDateTime__c = evtDateTime1.Id;
        		newTicketScale1.ActualSalesToDate__c = 1;
        		newTicketScale1.ActualGrossToDate__c = 2;
        		newTicketScale1.Price__c = 1;
        		newTicketScale1.ProjectedPaidTickets__c = 10;
        		newTicketScale1.Type__c = 'Platinum';
        		newTicketScale1.Event__c = event.Id;
        		newTicketScale1.StageType__c = 'Audit';
        		ticketScaleList.add(newTicketScale1);

        	}
        	insert ticketScaleList;

		}

        //-- whatever your setups, and you can make it as varied as you'd like.
        public void typicalSetup(Integer searchLimit){
            //Set search limit in general settings
            GeneralSettings__c results = new GeneralSettings__c(SearchLimit__c = searchLimit);
            insert results;
        }

        public void finalize(){
            //-- always should be called.
            
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		} 
	}

    //-- test setups here to find out if errors have nothing to do with the test.
    static testMethod void runSetupAWithoutException() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup(10);
        ts.finalize();
        System.assert( true, 'No Exceptions have occurred in getting here' );
    }

    //-- test functionality here
    static testMethod void testSearch() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup(10);
        ts.finalize();
        
        test.startTest();
        	LNE_MassManualTicketCounts_C massManualTicketCountsController = new LNE_MassManualTicketCounts_C();
        	massManualTicketCountsController.runSearch();

        test.stopTest();

        System.assertNotEquals( NULL, massManualTicketCountsController.eventDateTimeWrapperList, 'The EventDateTime Wrapper should not be null' );
        System.assertEquals( 2, massManualTicketCountsController.eventDateTimeWrapperList.size(), '2 records should be returned by search' );
        System.assertEquals( 20, massManualTicketCountsController.eventDateTimeWrapperList[0].feedGrossSales, 'The aggregrate of ActualGrossToDate__c from related TicketScale should be 20' );
        System.assertEquals( 10, massManualTicketCountsController.eventDateTimeWrapperList[0].feedTicketCount, 'The aggregrate of ActualSalesToDate__c from related TicketScale should be 10' );    
    }

    static testMethod void testSelectiveSearch() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup(10);
        ts.finalize();

        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue',  'Account.Artist'});         
        Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
        Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );

        test.startTest();
        	LNE_MassManualTicketCounts_C massManualTicketCountsController = new LNE_MassManualTicketCounts_C();
        	massManualTicketCountsController.eventDateTimeSearch.Market__c = 'Chicago';
        	//massManualTicketCountsController.eventDateTimeSearch.Venue__c = venue.Id;
        	massManualTicketCountsController.eventDateTimeSearch.Artists__c = 'Pennyback';
        	massManualTicketCountsController.eventDateTimeSearch.EventDate__c = system.today();
        	massManualTicketCountsController.eventDateTimeSearch.EventEndDate__c = system.today().addMonths(1);


        	massManualTicketCountsController.runSearch();

        	system.debug(LoggingLevel.ERROR, '@@@ massManualTicketCountsController.eventDateTimeWrapperList - ' + massManualTicketCountsController.eventDateTimeWrapperList);
        	Id eventDateTimeId = massManualTicketCountsController.eventDateTimeWrapperList[0].eventDateTime.Id;
            massManualTicketCountsController.eventDateTimeId = eventDateTimeId;
        	massManualTicketCountsController.getManualTicketCountList();
        	massManualTicketCountsController.saveManualTicketCountList();
            massManualTicketCountsController.instantiateNewManualTicketCount();
            LNE_MassManualTicketCounts_C.searchArtists('Pennyback');
            LNE_MassManualTicketCounts_C.searchVenues('Chicago');

        test.stopTest();

        System.assertNotEquals( NULL, massManualTicketCountsController.eventDateTimeWrapperList, 'The EventDateTime Wrapper should not be null' );
        System.assertEquals( 1, massManualTicketCountsController.eventDateTimeWrapperList.size(), '1 record should be returned by search' );
        System.assertEquals( 20, massManualTicketCountsController.eventDateTimeWrapperList[0].feedGrossSales, 'The aggregrate of ActualGrossToDate__c from related TicketScale should be 20'  );
        System.assertEquals( 10, massManualTicketCountsController.eventDateTimeWrapperList[0].feedTicketCount, 'The aggregrate of ActualSalesToDate__c from related TicketScale should be 10' );   
    }

    static testMethod void testSearchLimit() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup(10);
        ts.finalize();
        
        test.startTest();
        	LNE_MassManualTicketCounts_C massManualTicketCountsController = new LNE_MassManualTicketCounts_C();
        	massManualTicketCountsController.runSearch();
        test.stopTest();

       	//Assert limit exception message
       	List<ApexPages.Message> msgList = ApexPages.getMessages();
		for(ApexPages.Message msg :  ApexPages.getMessages()) {
		    System.assertEquals(LNE_MassManualTicketCounts_C.TOO_MANY_RESULTS, msg.getSummary(), 'The page should return too many search results exception.');
		    break;
		}
    }
}