src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OfficeID__c</fullName>
        <label>Office ID</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventIDStageType__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsEventMultiScale__c</fullName>
        <formula>Event__r.UsingMultiScale__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Event Multi-Scale?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>BypassAutomation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All forms of workflow (Process Builder, Flow, workflow rules), validation rules, and triggers will be prevented from running when changing this value to true/checked. Apply at the org, profile, or user level.</description>
        <inlineHelpText>All forms of workflow (Process Builder, Flow, workflow rules), validation rules, and triggers will be prevented from running when changing this value to true/checked. Apply at the org, profile, or user level.</inlineHelpText>
        <label>Bypass Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassPBFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag that bypasses all Process Builder Flows.</inlineHelpText>
        <label>Bypass PB Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GlobalDataAdministrator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked for a profile or user, enables user to bypass many workflows and validation rules that might otherwise prevent successful editing or loading of data. Generally used for the integration and system admin profiles as well as granting a higher level of access to trusted users.</description>
        <inlineHelpText>When checked for a profile or user, enables user to bypass many workflows and validation rules that might otherwise prevent successful editing or loading of data. May grant a higher level of access to trusted users on an exception basis.</inlineHelpText>
        <label>Global Data Administrator</label>
        <type>Checkbox</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventIDStageTypeDateTime__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type Date Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventIDStageType__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>OfficeAccess__c</fullName>
        <label>Office Access</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VenueOffice__c.object
<CustomObject>
    <description>Junction object linking venues with LNE internal offices, indicating that office may manage events and booking at the venue</description>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Office Venues</relationshipLabel>
        <relationshipName>OfficeVenues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Venue Offices</relationshipLabel>
        <relationshipName>VenueOffices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Venue-Office</label>
    <nameField>
        <displayFormat>VO-{000000}</displayFormat>
        <label>Venue-Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Venue-Offices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_EventDateTimeUtil_T.cls
/**
 *  Utility class for LNE_EventDateTime.trigger.
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 **/
public with sharing class LNE_EventDateTimeUtil_T {

	private static final DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();
	private static final String NO_VENUE_OFFICE_ACCESS = 'You cannot create child records of the event because you do not have authorized access to the venue office/division';

	/**
	 *  Determines if the related Event is using Multi Scale, and if so, clones the Ticket Scales for the
	 *  first (earliest date, earliest time) EventDateTime__c and associates them with the EventDateTime__c
	 *  being inserted
	 **/
	public static void checkForMultiScale(EventDateTime__c[] newEventDateTimes) {
		Set<Id> eventIds = new Set<Id>();

		for (EventDateTime__c edt : newEventDateTimes) {
			if (edt.IsEventMultiScale__c == true && edt.Event__c != null) {
				eventIds.add(edt.Event__c);
			}
		}

		if (eventIds.size() == 0) {
			return;
		}

		List<Event__c> events = [SELECT Id, (SELECT EventDate__c, StartTime__c FROM EventDateTimes__r WHERE NOT Id IN :newEventDateTimes) FROM Event__c WHERE Id IN :eventIds];

		Map<Id,Id> oldToNewEventDateTimeMap = new Map<Id,Id>();
		Map<Id,Id> eventIdToEarliestDateTimeMap = new Map<Id,Id>();

		for (Event__c e : events) {
			List<EventDateTime> dateTimes = new List<EventDateTime>();
			for (EventDateTime__c edt : e.EventDateTimes__r) {
				dateTimes.add(new EventDateTime(edt));
			}

			dateTimes.sort();

			if (dateTimes.size() > 0) {
				eventIdToEarliestDateTimeMap.put(e.Id, dateTimes[0].edt.Id);
			}
		}

		if (eventIdToEarliestDateTimeMap.values().size() > 0) {
			Set<String> ticketScaleFieldNames = getFieldNamesForObject(TicketScale__c.sObjectType.getDescribe());
			List<Id> eventDateTimeIds = eventIdToEarliestDateTimeMap.values();

			String queryFieldNames = String.join(new List<String>(ticketScaleFieldNames), ',');
			String ticketScaleQuery = 'SELECT ';
			ticketScaleQuery += queryFieldNames;
			ticketScaleQuery += ' FROM TicketScale__c';
			ticketScaleQuery += ' WHERE EventDateTime__c IN :eventDateTimeIds';

			List<TicketScale__c> toClone = Database.query(ticketScaleQuery);

			Map<Id, List<TicketScale__c>> earliestEventDateTimeToTicketScalesMap = new Map<Id, List<TicketScale__c>>();

			for (TicketScale__c ts : toClone) {
				if (earliestEventDateTimeToTicketScalesMap.get(ts.EventDateTime__c) == null) {
					earliestEventDateTimeToTicketScalesMap.put(ts.EventDateTime__c, new List<TicketScale__c>());
				}

				earliestEventDateTimeToTicketScalesMap.get(ts.EventDateTime__c).add(ts);
			}

			List<TicketScale__c> toInsert = new List<TicketScale__c>();

			Map<Id, TicketScale> tsMap = new Map<Id, TicketScale>();

			for (EventDateTime__c edt : newEventDateTimes) {
				Id earliestExistingEventDateTime = eventIdToEarliestDateTimeMap.get(edt.Event__c);

				List<TicketScale__c> scalesToClone = earliestEventDateTimeToTicketScalesMap.get(earliestExistingEventDateTime);

				if (scalesToClone != null) {
					for (TicketScale__c ts : scalesToClone) {
						tsMap.put(ts.Id, new TicketScale(ts));
					}

					for (TicketScale__c ts : scalesToClone) {
						TicketScale__c newTicketScale = ts.clone(false, true, false, false);
						newTicketScale.EventDateTime__c = edt.Id;
						populateGridBuddyFilterFields(newTicketScale);
						
						toInsert.add(newTicketScale);
						tsMap.get(ts.Id).clonedScales.add(newTicketScale);
					}
				}
			}

			if (toInsert.size() > 0) {
				LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false);
				LNE_FinancialCalculator.currentlyRunning = true;

				insert toInsert;

				List<sObject> objectsToUpdate = getRelatedLedgersAndDeductions(eventIds);
		
				for (sObject so : objectsToUpdate) {
					addAdditionalIds(so, tsMap);
				}
				
				update objectsToUpdate;

				LNE_FinancialCalculator.currentlyRunning = false;
				LNE_GeneralSettingsUtil.removeCurrentUserOverride();
			}
		}
	}
	
	/**
	 *  Checks if the current user has access to any of the offices (through VenueOffice__c)
	 *  for the current venue on the EventDateTime__c
	 **/
	public static void checkVenueAccess(EventDateTime__c[] newEventDateTimes) {
		GeneralSettings__c settings = GeneralSettings__c.getInstance();
		
		if (settings.GlobalDataAdministrator__c == false && settings.BypassAutomation__c == false && settings.BypassPBFlow__c == false) {
			String officeAccess = [SELECT OfficeAccess__c FROM User WHERE Id = :UserInfo.getUserId()].OfficeAccess__c;
			
			if (String.isNotBlank(officeAccess)) {
				List<String> userOffices = officeAccess.split(',');
				Set<Id> eventIds = new Set<Id>();
		
				for (EventDateTime__c edt : newEventDateTimes) {
					if (edt.Event__c != null) {
						eventIds.add(edt.Event__c);
					}
				}
				
				if (eventIds.size() > 0) {
					List<Event__c> events = [SELECT Venue__c FROM Event__c WHERE Id IN :eventIds];
					Map<Id, Event__c> eventMap = new Map<Id, Event__c>(events);
					
					Set<Id> venueIds = new Set<Id>();
					
					for (Event__c e : events) {
						if (e.Venue__c != null) {
							venueIds.add(e.Venue__c);
						}
					}
					
					if (venueIds.size() > 0) {
						List<VenueOffice__c> venueOffices = [SELECT Venue__c, Office__r.OfficeID__c FROM VenueOffice__c WHERE Venue__c IN :venueIds];
						
						Map<Id, Set<String>> venueToOfficeIds = new Map<Id, Set<String>>();
						
						for (VenueOffice__c vo : venueOffices) {
							if (venueToOfficeIds.get(vo.Venue__c) == null) { venueToOfficeIds.put(vo.Venue__c, new Set<String>()); }
							
							venueToOfficeIds.get(vo.Venue__c).add(vo.Office__r.OfficeID__c);
						}
						
						for (EventDateTime__c edt : newEventDateTimes) {
							if (eventMap.get(edt.Event__c) != null) {
								Id venueId = eventMap.get(edt.Event__c).Venue__c;
								Set<String> venueOfficeIDs = venueToOfficeIds.get(venueId);
								
								if (venueOfficeIDs != null) {
									venueOfficeIDs.retainAll(userOffices);
									
									if (venueOfficeIDs.size() == 0) {
										edt.addError(NO_VENUE_OFFICE_ACCESS);
									}
								}
							}
						}
					}
				}
			} else {
				newEventDateTimes[0].addError(NO_VENUE_OFFICE_ACCESS);
			}
		}
	}

	/**
	 *  Deletes any child TicketScale__c records when a EventDateTime__c is deleted.
	 **/
	public static void deleteTicketScales(Map<Id,EventDateTime__c> deletedRecords) {
		if (deletedRecords != null && deletedRecords.keySet().size() > 0) {
			Set<Id> deletedIds = deletedRecords.keySet();

			List<TicketScale__c> scalesToDelete = [SELECT Id FROM TicketScale__c WHERE EventDateTime__c IN :deletedIds];

			if (scalesToDelete.size() > 0) {
				delete scalesToDelete;
			}
		}
	}

	public static void populateGridBuddyFilterFields(sObject so) {
		String eventId = (String)so.get('Event__c');
		String stageType = (String)so.get('StageType__c');
		String eventDateTime = so.get('EventDateTime__c') == null ? '' : (String)so.get('EventDateTime__c');

		so.put('EventIDStageType__c', eventId.substring(0,15) + DATA_SETTINGS.CombinedKeyDelimiter__c + stageType);

		if (so.getSObjectType() == Schema.TicketScale__c.SObjectType && eventDateTime.length() >= 15) {
			String EventIDStageTypeDateTime = (String)so.get('EventIDStageType__c') + DATA_SETTINGS.CombinedKeyDelimiter__c + eventDateTime.substring(0,15);

			so.put('EventIDStageTypeDateTime__c', EventIDStageTypeDateTime);
		}
	}

	public static Set<Id> getSelectedTicketScales(sObject so) {
    	String encodedDelimeter = EncodingUtil.urlEncode(DATA_SETTINGS.CombinedKeyDelimiter__c, 'UTF-8');
        String encodedString = EncodingUtil.urlEncode((String)so.get('TicketScaleList__c'), 'UTF-8');
		String[] idList = encodedString.split(encodedDelimeter);
		Set<String> stringSet = new Set<String>(idList);
		stringSet.removeAll(new String[]{'',null});
		
		//- This seems to be the easiest way to convert Set<String> to Set<Id> as they don't seem to be compatible
		Set<Id> idSet = (Set<Id>)JSON.deserialize(JSON.serialize(stringSet), Set<Id>.class);
		
		return idSet;
    }

    public static void addAdditionalIds(sObject so, Map<Id, LNE_EventDateTimeUtil_T.TicketScale> tsMap) {
    	if (so.get('TicketScaleList__c') != null) {
    		Set<Id> idSet = LNE_EventDateTimeUtil_T.getSelectedTicketScales(so);
    		Set<Id> newTicketScaleIdList = new Set<Id>();
    		
    		for (Id ticketScaleId : idSet) {
    			newTicketScaleIdList.add(ticketScaleId);
    			if (tsMap.containsKey(ticketScaleId)) {
    				newTicketScaleIdList.addAll(tsMap.get(ticketScaleId).getClonedIds());
    			}
    		}
    		
    		joinAndPopulateSelectedTicketScales(so, newTicketScaleIdList);
    	}
    }

    public static void removeDeletedIds(sObject so, Set<Id> idsToRemove) {
    	if (so.get('TicketScaleList__c') != null) {
    		Set<Id> idSet = LNE_EventDateTimeUtil_T.getSelectedTicketScales(so);
    		idSet.removeAll(idsToRemove);
    		joinAndPopulateSelectedTicketScales(so, idSet);
    	}
    }

    public static void joinAndPopulateSelectedTicketScales(sObject so, Set<Id> newTicketScaleIdList) {
    	List<String> toJoin = new List<String>();
    	for (Id s : newTicketScaleIdList) {
    		if (s != null) {
    			toJoin.add(((String)s).substring(0,15));
    		}
    	}
    	String newTicketScaleList = String.join(toJoin, DATA_SETTINGS.CombinedKeyDelimiter__c);
    	so.put('TicketScaleList__c', newTicketScaleList);
    }

    private static List<sObject> getRelatedLedgersAndDeductions(Set<Id> eventIds) {
    	List<sObject> objectsToReturn = new List<sObject>();
    	objectsToReturn.addAll((List<sObject>)[SELECT TicketScaleList__c FROM LedgerEntry__c WHERE Event__c IN :eventIds]);
    	objectsToReturn.addAll((List<sObject>)[SELECT TicketScaleList__c FROM LedgerEntryBreakout__c WHERE LedgerEntry__c IN :objectsToReturn]);
    	objectsToReturn.addAll((List<sObject>)[SELECT TicketScaleList__c FROM Deduction__c WHERE Event__c IN :eventIds]);
    	
    	return objectsToReturn;
    }

	private static Set<String> getFieldNamesForObject(Schema.DescribeSObjectResult objectDescribe) {
		Map<String, Schema.SObjectField> objectFields = objectDescribe.fields.getMap();
		Set<String> fieldNames = new Set<String>();

		for(Schema.sObjectField field : objectFields.values()){
			Schema.DescribeFieldResult dfr = field.getDescribe();
			if (dfr.isCreateable()) {
				fieldNames.add(dfr.getName());
			}
		}

		return fieldNames;
	}

	public class EventDateTime implements Comparable {
    	public EventDateTime__c edt;
    	public DateTime dt;
    	
    	public EventDateTime(EventDateTime__c e) {
    		this.edt = e;
    		this.dt = getDateTime(e);
    	}
    	
    	public Integer compareTo(Object compareTo) {
    		if (compareTo instanceof EventDateTime) {
    			EventDateTime compareToEdt = (EventDateTime)compareTo;
    			
    			if (compareToEdt.edt.EventDate__c == null || this.edt.EventDate__c == null) {
    				return 0;
    			}
    			
    			return this.dt > compareToEdt.dt ? 1 : -1;
    		}
    		
    		return 0;
    	}
    	
    	private DateTime getDateTime(EventDateTime__c e) {
    		DateTime dt;
    		
    		if (e != null && e.EventDate__c != null) {
    			String dts = e.EventDate__c.format();
				if (String.isBlank(e.StartTime__c)) {
					dts += ' 12:00 AM';
				} else {
					dts += ' ' + e.StartTime__c;
				}
				dt = DateTime.parse(dts);
    		} else {
    			dt = System.now();
    		}
    		
			return dt;
    	}
    }

    public class TicketScale {
    	public TicketScale__c ts;
    	public List<TicketScale__c> clonedScales;
    	public Set<Id> clonedScaleIds;
    	
    	public TicketScale(TicketScale__c t) {
    		this.ts = t;
    		clonedScales = new List<TicketScale__c>();
    	}
    	
    	 public Set<Id> getClonedIds() {
    	 	if (clonedScaleIds == null) {
    	 		if (clonedScales != null) {
    	 			clonedScaleIds = new Map<Id,TicketScale__c>(clonedScales).keySet();
    	 		}
    	 	}
    	 	
    	 	return clonedScaleIds;
    	 }
    }
}