src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <description>Formula to capture the offices&apos; and venues&apos; division if applicable</description>
        <formula>CASE (RecordType.DeveloperName,

&quot;Office&quot;,
IF (ISPICKVAL(Type, &quot;Division&quot;), Name, 
IF (ISPICKVAL(Parent.Type, &quot;Division&quot;), Parent.Name, 
IF (ISPICKVAL(Parent.Parent.Type, &quot;Division&quot;), Parent.Parent.Name,
&quot;&quot;))),

&quot;Venue&quot;,
IF (ISPICKVAL(PrimaryOffice__r.Type, &quot;Division&quot;), PrimaryOffice__r.Name, 
IF (ISPICKVAL(PrimaryOffice__r.Parent.Type, &quot;Division&quot;), PrimaryOffice__r.Parent.Name, 
IF (ISPICKVAL(PrimaryOffice__r.Parent.Parent.Type, &quot;Division&quot;), PrimaryOffice__r.Parent.Parent.Name,
&quot;&quot;))),

&quot;&quot;)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the account (active, inactive)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Division__c</fullName>
        <description>Drives sharing rules to provide read-only access to other division members</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>ApplyToBuySellEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Buy Sell Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToGospelBrunchEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Gospel Brunch Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToHOBEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To HOB Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToNAMusicEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To NA Music Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToPromotedEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Promoted Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToRentalEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Rental Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>Drives sharing rules to provide read-only access to other division members</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_CheckFlashStarted_T.cls
/**
 * Trigger logic that checks if the Flash Process started and creates the necesary Ledger Entry placeholders
 * @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
 **/
public class LNE_CheckFlashStarted_T {
    
    private static String DIVISION_TC = 'Theaters & Clubs';
    private static String DIVISION_CANADA = 'Canada Concerts';
    private static String DIVISON_US = 'US Concerts';
    
    private static String TYPE_ANCILLARY = 'Ancillary';
    private static String TYPE_COGS = 'COGS';
    private static String TYPE_TICKETREVENUE = 'Ticket Revenue';
    private static String TYPE_EXPENSES = 'Expenses';
    private static String TYPE_CONTRA = 'Contra';
    private static String TYPE_DIVISION = 'Division';
    private static String TYPE_COPROMOTE_EXPENSE = 'Co Promote Expense';
    private static String TYPE_COPROMOTE_REVENUE = 'Co Promote Revenue';
    private static String TYPE_OTHER = 'Other';
    private static String TYPE_TALENT_FEES = 'Talent Fees';
    
    private static String EVENT_FLASH_STARTED = 'Flash Started';

    public static Event__c[] execute( Event__c[] newList, Map<Id,Event__c> oldMap ){
        
        if ( newList == null || newList.size() == 0){    //short circuit evaulation of empty input
        	//return empty list for empty input
            return( new list<Event__c>() );
        }
       
        Event__c[] newEvents = null;
        
        GLAccount__c[] listOfGlAccount = new GLAccount__c[]{};
        LedgerEntry__c[] ledgerEntryPlaceHolder = new LedgerEntry__c[]{};

        if( oldMap == null ){ //handle insert trigger where oldMap == null
        	oldMap = new Map<Id,Event__c>();
        }
        
        Event__c[] validEvents = new Event__c[]{};
        Event__c oldEvent = null;
        for( Event__c newEvent : newList ){
        	if ( newEvent.Status__c.equalsIgnoreCase( EVENT_FLASH_STARTED ) ) {
	        	if( oldMap.containsKey( newEvent.Id )){
	        		//-- it is an update
	        		oldEvent = oldMap.get( newEvent.Id );
	        		if( !newEvent.Status__c.equals( oldEvent.Status__c )){    //filter only events that have changed
	        			validEvents.add( newEvent );
	        		}
	        	} else {
	        		//-- it is an insert
	    			validEvents.add( newEvent );
	        	}
        	}
        }
        
        //-- short circuit if there are not events that have changed or inserted.
        if( validEvents.isEmpty() ){
        	return( validEvents );
        }
        
        newEvents = [
        	Select Id, Status__c, RecordTypeId, Office__r.Division__c, 
        		(Select Id, RecordTypeId, GLAccount__c From LedgerEntries__r) 
        	From Event__c 
        	WHERE Id IN :validEvents
        ];

        //-- @TODO: iterate over only the GL accounts that we care about within the event.
        //-- ...
        
        
        listOfGlAccount = [
        	Select Id, Type__c, ApplyToBuySellEvent__c, ApplyToGospelBrunchEvent__c, ApplyToHOBEvent__c, 
        		ApplyToNAMusicEvent__c, ApplyToPromotedEvent__c, ApplyToRentalEvent__c
        	FROM GLAccount__c 
        	WHERE (ApplyToBuySellEvent__c = true OR ApplyToGospelBrunchEvent__c = true OR ApplyToPromotedEvent__c = true OR ApplyToRentalEvent__c = true) 
        	AND (ApplyToHOBEvent__c = true OR ApplyToNAMusicEvent__c = true)
        ];
        
        Map<Id,GLAccount__c> buySellEventGLs = new Map<Id,GLAccount__c>();
        Map<Id,GLAccount__c> rentalEventGLs = new Map<Id,GLAccount__c>();
        Map<Id,GLAccount__c> promotedEventGLs = new Map<Id,GLAccount__c>();
        Map<Id,GLAccount__c> gospelBrunchEventGLs = new Map<Id,GLAccount__c>();
        Map<Id,GLAccount__c> hobEventGLs = new Map<Id,GLAccount__c>();
        Map<Id,GLAccount__c> naEventGLs = new Map<Id,GLAccount__c>();
        
        //sort GL Accounts into list based on attributes
        for( GLAccount__c glAcct : listOfGlAccount){          
        	if( glAcct.ApplyToBuySellEvent__c ){
        		buySellEventGLs.put( glAcct.Id, glAcct );
        	}
        	if( glAcct.ApplyToRentalEvent__c ){
        		rentalEventGLs.put( glAcct.Id, glAcct );
        	}
        	if( glAcct.ApplyToPromotedEvent__c ){
        		promotedEventGLs.put( glAcct.Id, glAcct );
        	}
        	if( glAcct.ApplyToGospelBrunchEvent__c ){
        		gospelBrunchEventGLs.put( glAcct.Id, glAcct );
        	}
        	if( glAcct.ApplyToHOBEvent__c){
        	    hobEventGLs.put( glAcct.Id, glAcct );
        	}
        	if( glAcct.ApplyToNAMusicEvent__c){
        	    naEventGLs.put( glAcct.Id, glAcct );
        	}
        }
        
        Set<Id> buySellEventGLIds = buySellEventGLs.keySet();
        Set<Id> rentalEventGLIds = rentalEventGLs.keySet();
        Set<Id> promotedEventGLIds = promotedEventGLs.keySet();
        Set<Id> gospelBrunchEventGLIds = gospelBrunchEventGLs.keySet();
        Set<Id> hobEventGLIds = hobEventGLs.keySet();
        Set<Id> naEventGLIds = naEventGLs.keySet();
        
        Map<Id, GLAccount__c[]> applicableGLPerEvent = new Map<Id, GLAccount__c[]>();
        for( Event__c evt : newEvents){
        	if(evt.RecordTypeId == LNE_RT.RT_BUYSELL_ID){
        		setupBuySell(evt, listOfGlAccount, applicableGLPerEvent, buySellEventGLIds, hobEventGLIds, naEventGLIds);
        	} else if(evt.RecordTypeId == LNE_RT.RT_RENTAL_ID){
        	    setupRental(evt, listOfGlAccount, applicableGLPerEvent, rentalEventGLIds, hobEventGLIds, naEventGLIds);
        	} else if(evt.RecordTypeId == LNE_RT.RT_PROMOTEDSHOW_ID || evt.RecordTypeId == LNE_RT.RT_FESTIVAL_ID){
        	    setupPromotedShowFestival(evt, listOfGlAccount, applicableGLPerEvent, promotedEventGLIds, hobEventGLIds, naEventGLIds);
        	} else if(evt.RecordTypeId == LNE_RT.RT_GOSPELBRUNCH_ID){
        		setupGospelBrunch(evt, listOfGlAccount, applicableGLPerEvent, gospelBrunchEventGLIds, hobEventGLIds, naEventGLIds);
        	}
        }
        
        Map<Id, Set<Id>> usedGLPerEvent = new Map<Id, Set<Id>>();
        for(Event__c evt : newEvents){
            for(LedgerEntry__c le : evt.LedgerEntries__r){
                if(usedGLPerEvent.get(evt.Id) == null){
                    usedGLPerEvent.put(evt.Id, new Set<Id>());
                }
                usedGLPerEvent.get(evt.Id).add(le.GLAccount__c);
            }
        }
        
        for(Id evtId : applicableGLPerEvent.keySet()){
           for(GLAccount__c gl : applicableGLPerEvent.get(evtId)){
               if(usedGLPerEvent.get(evtId) == null || !usedGLPerEvent.get(evtId).contains(gl.Id) ){
					ledgerEntryPlaceholder.add( setupLEPlaceHolder(gl, GLMapToLERTId.get(gl.Type__c), evtId));
                   	
                }               
            }
        }
    	
    	//all or nothing insert
    	System.debug(ledgerEntryPlaceholder);
        insert ledgerEntryPlaceholder;
        return (newList);
    }
    
    private static LedgerEntry__c setupLEPlaceHolder(GLAccount__c gl, id RTId, Id evtId) {
    	LedgerEntry__c result = 
    		new LedgerEntry__c(
	            GLAccount__c = gl.Id,
	            BaseAmount__c = 0,
	            RateType__c = 'Flat', 
	            RecordTypeId = RTId,
	            Event__c = evtId
	      	);
    	return result;
    }
    
    private static void setupBuySell(Event__c evt, list<GLAccount__c> listOfGlAccount, 
    	Map<Id, GLAccount__c[]> applicableGLPerEvent, set<id> buySellEventGLIds, set<id> hobEventGLIds,
    	set<Id> naEventGLIds) {
    		
        if(evt.Office__r.Division__c == DIVISION_TC){
		    for(GLAccount__c gl : listOfGlAccount){
		        if(buySellEventGLIds.contains(gl.Id) && hobEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
	     } else if(evt.Office__r.Division__c == DIVISON_US || evt.Office__r.Division__C == DIVISION_CANADA){
	     	for(GLAccount__c gl : listOfGlAccount){
		        if(buySellEventGLIds.contains(gl.Id) && naEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
		 }
    }
    
    private static void setupRental(Event__c evt, list<GLAccount__c> listOfGlAccount, 
    	Map<Id, GLAccount__c[]> applicableGLPerEvent, set<id> rentalEventGLIds, set<id> hobEventGLIds,
    	set<Id> naEventGLIds) {
    		
	    if(evt.Office__r.Division__c == DIVISION_TC){
		    for(GLAccount__c gl : listOfGlAccount){
		        if(rentalEventGLIds.contains(gl.Id) && hobEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
	     } else if(evt.Office__r.Division__c == DIVISON_US || evt.Office__r.Division__C == DIVISION_CANADA){
	           for(GLAccount__c gl : listOfGlAccount){
		        if(rentalEventGLIds.contains(gl.Id) && naEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
		}
    }
    
    private static void setupPromotedShowFestival(Event__c evt, list<GLAccount__c> listOfGlAccount, 
    	Map<Id, GLAccount__c[]> applicableGLPerEvent, set<id> promotedEventGLIds, set<id> hobEventGLIds,
    	set<Id> naEventGLIds) {
    		
    	if(evt.Office__r.Division__c == DIVISION_TC){
        	for(GLAccount__c gl : listOfGlAccount){
        		if(promotedEventGLIds.contains(gl.Id) && hobEventGLIds.contains(gl.Id)){
        			if(applicableGLPerEvent.get(evt.Id) == null){
						applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
    				}
					applicableGLPerEvent.get(evt.Id).add(gl);
				}
       		}
		} else if(evt.Office__r.Division__c == DIVISON_US || evt.Office__r.Division__C == DIVISION_CANADA){
			for(GLAccount__c gl : listOfGlAccount){
				if(promotedEventGLIds.contains(gl.Id) && naEventGLIds.contains(gl.Id)){
					if(applicableGLPerEvent.get(evt.Id) == null){
 						applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
					}
					applicableGLPerEvent.get(evt.Id).add(gl);
				}
			}
		}
    }
    
    
    
    private static void setupGospelBrunch(Event__c evt, list<GLAccount__c> listOfGlAccount, 
    	Map<Id, GLAccount__c[]> applicableGLPerEvent, set<id> gospelBrunchEventGLIds, set<id> hobEventGLIds,
    	set<Id> naEventGLIds) {
    		
        if(evt.Office__r.Division__c == DIVISION_TC){
		    for(GLAccount__c gl : listOfGlAccount){
		        if(gospelBrunchEventGLIds.contains(gl.Id) && hobEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
	     } else if(evt.Office__r.Division__c == DIVISON_US || evt.Office__r.Division__C == DIVISION_CANADA){
	           for(GLAccount__c gl : listOfGlAccount){
		        if(gospelBrunchEventGLIds.contains(gl.Id) && naEventGLIds.contains(gl.Id)){
		            if(applicableGLPerEvent.get(evt.Id) == null){
		                applicableGLPerEvent.put(evt.Id, new GLAccount__c[]{});
		            }
		            applicableGLPerEvent.get(evt.Id).add(gl);
		        }
		    }
		 }
    }
    
    
    private static Map<String, ID> pGLMapToLERTId = null;
	public static Map<String, ID> GLMapToLERTId {
		get {
			if ( pGLMapToLERTId == null) {
				pGLMapToLERTId = new Map<String, ID>();
		        pGLMapToLERTId.put(TYPE_ANCILLARY, LNE_RT.RT_ANCILLARY_ID);
		        pGLMapToLERTId.put(TYPE_COGS, LNE_RT.RT_COGS_ID);
		        pGLMapToLERTId.put(TYPE_TICKETREVENUE, LNE_RT.RT_TICKETREVENUE_ID);
		        pGLMapToLERTId.put(TYPE_EXPENSES, LNE_RT.RT_EXPENSES_ID);
		        pGLMapToLERTId.put(TYPE_COPROMOTE_EXPENSE, LNE_RT.RT_COPROMOTE_EXPENSE_ID);
                pGLMapToLERTId.put(TYPE_COPROMOTE_REVENUE, LNE_RT.RT_COPROMOTE_REVENUE_ID);
                pGLMapToLERTId.put(TYPE_OTHER , LNE_RT.RT_OTHER_ID);
                pGLMapToLERTId.put(TYPE_TALENT_FEES , LNE_RT.RT_TALENT_FEES_ID);
                pGLMapToLERTId.put(TYPE_CONTRA, LNE_RT.RT_CONTRA_ID);
			}
			return pGLMapToLERTId;
		}
	}
    
}