src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>ActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToBuySellEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Buy Sell Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToGospelBrunchEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Gospel Brunch Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToHOBEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To HOB Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToNAMusicEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To NA Music Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToPromotedEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Promoted Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToRentalEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Rental Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableForForecast__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available For Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CategorySort__c</fullName>
        <label>Category Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeactivationDate__c</fullName>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinancialCategorySAPBPC__c</fullName>
        <label>Financial Category - SAPBPC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Barter</fullName>
                </value>
                <value>
                    <fullName>Co-Promoter</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Promoter Profits</fullName>
                </value>
                <value>
                    <fullName>PSS/LSM</fullName>
                </value>
                <value>
                    <fullName>Rome Metrics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ImportRateType__c</fullName>
        <label>Import Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelatedContra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contra</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Related Contra (GL Account)</relationshipLabel>
        <relationshipName>GLAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RevenueFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Needed for Oracle Integration</description>
        <label>Revenue Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SourceSystemId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SourceSystemId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_Util.cls
/**
 *  Set of very high level utility methods that deal with Profiles,
 *  PermissionSets, RecordTypes, SObjects (not Accounts or specific subclasses)
 *  etc.
 *  
 *  <p>This class should be as sparse as possible and only should be used
 *  if logic applies across large functionality.</p>
 * 
 *  <p>Please note, if considering modifying sharing access on this class:
 *  the majority of this class does not depend on sharing
 *  but the 'isEventEditable' method down below - does.</p>
 *  
 *  @author Paul Roth <proth@salesforce.com>
**/
public with sharing class LNE_Util {
	
	/**
	 * Static variable to disable all triggers - to allow disabling for the current user only.
	 * 
	 * At present the only valid case is that triggers should be disabled
	 * while cloning. Other use cases to be vetted, but it must be careful
	 * that this is not abused (turning it off and on within the middle of triggers
	 * as this would lead us to likely invalid states quite quickly.
	 * 
	 * The alternatives are to set the disable flags on the custom setting side
	 * but this applies to multiple users (not just this one)
	 * and should be used for those other cases for now.
	 * 
	 **/
	public static boolean IS_CURRENTLY_CLONING = false;
	
	/** sample test value for an eventName **/
	public static final String DEFAULT_EVENT_NAME_CHECK = 'EVENTNAMECHECK';
	
	//-- notice this is a regex
	public static final String PATH_DELIMITER = '.';
	public static final String PATH_DELIMITER_REGEX = '[.]';
	
	private static final Map<String, Id> RECORD_TYPES_BY_NAME = getRecordTypesByName();
	private static Map<String, GLAccount__c> GL_ACCOUNTS_BY_ID = null;
	
	private static final String ERROR_RETRIEVING_GL_ACCOUNTS = 'ERROR occurred while retrieivng all GL Accounts';
	
	private static Map<String, Id> getRecordTypesByName(){
	    Map<String,Id> results = new Map<String,Id>();
		string downloadedPath = null;
		
		for( RecordType rt : [select id, DeveloperName, SObjectType from RecordType]){
			downloadedPath = rt.SObjectType + PATH_DELIMITER + rt.DeveloperName;
			results.put( downloadedPath, rt.Id );
		}
		
		return( results );
	}
	
	public static Map<String,Id> getRecordTypes( String[] recordTypePaths ){
		Map<String,Id> results = new Map<String,Id>();
		
		for( String recordTypePath : recordTypePaths ){
			if( RECORD_TYPES_BY_NAME.containsKey( recordTypePath )){
				results.put( recordTypePath, RECORD_TYPES_BY_NAME.get(recordTypePath) );
			}
		}
		
		return( results );
	}
	
	/**
	 *  Creates a map of Profile Names by Profile Ids.
	 *  @pram profileNames String[] - list of profile names to be returned.
	 *  @return Map<String,Id>
	**/
	public static Map<String,Id> getProfileIds( String[] profileNames ){
		Map<String,Id> results = new Map<String,Id>();
		
		for( Profile p : [ select id, name
			from Profile
			where name in :profileNames
		]){
			results.put( p.name, p.id );
		}
		return( results );
	}
	
	/**
	 *  Creates a map of Permission set names by ids.
	 *  @param permSetNames String[] - list of permission set names to be returned
	 *  @return Map<String,id>
	**/
	public static Map<String,Id> getPermissionSetIds( String[] permissionSetNames ){
		Map<String,Id> results = new Map<String,Id>();
		
		for( PermissionSet p : [ select id, name
			from PermissionSet
			where name in :permissionSetNames
		]){
			results.put( p.name, p.id );
		}
		return( results );
	}
	
	/**
	 *  Retrieves all GL Accounts.
	 *  called on first demand of getGLAccounts, or any other time after all GL Accounts have been loaded.
	 *  @INVARIANT - GL_ACCOUNTS_BY_ID is fill with the GL Accounts by the GL Account Id (ex: 60001)
	 **/
	public static Map<String,GLAccount__c> refreshGLAccountCache(){
		try {
			GL_ACCOUNTS_BY_ID = new Map<String,GLAccount__c>();
			for( GLAccount__c glAccount : [
				select ActiveFlag__c, ApplyToBuySellEvent__c, 
				ApplyToGospelBrunchEvent__c, ApplyToHOBEvent__c, ApplyToNAMusicEvent__c, 
				ApplyToPromotedEvent__c, ApplyToRentalEvent__c, AvailableForForecast__c, 
				Category__c, CategorySort__c, CurrencyIsoCode, DeactivationDate__c, 
				FinancialCategorySAPBPC__c, GLCode__c, Id, ImportRateType__c, Name, 
				RelatedContra__c, RevenueFlag__c, SourceSystemId__c, Type__c
				from GLAccount__c
			]){
				GL_ACCOUNTS_BY_ID.put( glAccount.GLCode__c, glAccount );
			}
		} catch( Exception err ){
			System.debug( ERROR_RETRIEVING_GL_ACCOUNTS + ':' + err.getMessage() );
			throw( err );
		}
		
		return( GL_ACCOUNTS_BY_ID );
	}
	
	/**
	 *  Defines a list of GLAccounts by gl account id
	 *  @param String[] - list of gl accounts ids
	 *  @return Map<String,GLAccount__c> - list of gl accounts by the gl account number
	 **/
	public static Map<String,GLAccount__c> getGLAccounts( String[] glAccountNumbers ){
		Map<String,GLAccount__c> results = new Map<String,GLAccount__c>();
		
		if( GL_ACCOUNTS_BY_ID == null ){
			GL_ACCOUNTS_BY_ID = refreshGLAccountCache();
		}
		
		for( String glAccountId : glAccountNumbers ){
			if( GL_ACCOUNTS_BY_ID.containsKey( glAccountId )){
				results.put( glAccountId, GL_ACCOUNTS_BY_ID.get( glAccountId ));
			}
		}
		
		return( results );
	}

	/**
	 *  Gets all field names for sobject by name
	 *  @param String - object name
	 *  @return List<String> - list of field names
	 **/
	public static List<String> getFieldsForObject(String objectName) {
		Map<String,Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
		return new List<String>(globalDescribe.get(objectName).getDescribe().fields.getMap().keySet());
	}
	
	/**
	 *  Verifies that a given event is editable by the current person.
	 *  @param eventId (Id)
	 *  @return (Boolean) - whether the current person can edit an event - true - or it is not currently editable (false)
	 **/
	public static Boolean isEventEditable( Id eventId ){
	    
	    Boolean canEdit = false;
	    
	    //-- disable all triggers and other logic for the current user as best as possible.
        LNE_FinancialCalculator.currentlyRunning = true;
        LNE_Util.IS_CURRENTLY_CLONING = true;
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            Event__c eventToCheck = [ select Id, EventName__c from Event__c where id = :eventId limit 1 ];
            
            eventToCheck.EventName__c = DEFAULT_EVENT_NAME_CHECK;
            
            update eventToCheck;
            
            canEdit = true;
            
        } catch( Exception err ){
            System.debug( 'user does not have access to edit event:' + eventId );
            
            //-- implied from above but makes it clear.
            canEdit = false;
        } finally {
            Database.rollback( sp );
        }
        
        return( canEdit );
	}
	
	/**
	 *  Creates a map of RecordTypes by RecordType Developer names
	 *  @param recordTypePaths (String[]) - list of SObject.DeveloperNames (Object . DeveloperName)
	 *  @return Map<String,Id> - collection of recordTypes 
	 *  @example
	 *  	String recordTypes = new String[]{
	 *  		'Account.Venue','Account.Office'
	 *  	};
	 *  	Map<String,Id> recordTypes = LNE_Util.getRecordTypes( recordTypes );
	 *  	Id RT_VENUE_ID = recordTypes.get( 'Account.Venue' );
	 *  	Id RT_OFFICE_ID = recordTypes.get( 'Account.Office' );
	**/
	/*public static Map<String,Id> getRecordTypes( String[] recordTypePaths ){
		Map<String,Id> results = new Map<String,Id>();
		
		Set<String> sObjects = new Set<String>();
		Set<String> developerNames = new Set<String>();
		String[] pathSplits = null;
		
		Set<String> retrievedPaths = new Set<String>();
		
		for( String recordTypePath : recordTypePaths ){
			pathSplits = recordTypePath.split( PATH_DELIMITER_REGEX );
			sObjects.add( pathSplits[0] );
			developerNames.add( pathSplits[1] );
			
			results.put( recordTypePath, null );
		}
		
		String downloadedPath = null;
		for( RecordType rt : [
			select id, DeveloperName, SObjectType
			from RecordType
			where SObjectType in :sObjects
			and developerName in :developerNames
		]){
			downloadedPath = rt.SObjectType + PATH_DELIMITER + rt.DeveloperName;
			
		    if( results.containsKey( downloadedPath )){
				results.put( downloadedPath, rt.Id );
			}
		}
		
		return( results );
	}*/
}