src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>VenueName__c</fullName>
        <label>Venue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublicOnSale__c</fullName>
        <label>Public On Sale</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UsingTicketFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Using Ticket Feed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventEndDate__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventStatus__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PublicOnSale__c</fullName>
        <label>Public On Sale</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UsingTicketFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Using Ticket Feed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VenueName__c</fullName>
        <formula>Venue__r.Name</formula>
        <label>Venue Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Venue does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>SearchLimit__c</fullName>
        <defaultValue>500</defaultValue>
        <inlineHelpText>The most number of records to be returned from a &apos;Search&apos; that would not require further filtering/narrowing of search.</inlineHelpText>
        <label>Search Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/ManualTicketCount__c.object
<CustomObject>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Manual Ticket Counts</relationshipLabel>
        <relationshipName>ManualTicketCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GrossSales__c</fullName>
        <label>Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TicketCount__c</fullName>
        <label>Ticket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TicketSalesDate__c</fullName>
        <label>Ticket Sales Date</label>
        <type>Date</type>
    </fields>
    <label>Manual Ticket Count</label>
    <nameField>
        <displayFormat>MTC-{000000}</displayFormat>
        <label>Manual Ticket Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Ticket Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OnSaleDateTime__c.object
<CustomObject>
    <description>Dates that tickets are on sale or pre sale or other important dates around ticket sales/announcements to identify</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>On Sale Date Times</relationshipLabel>
        <relationshipName>OnSaleDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SaleStartDate__c</fullName>
        <label>Sale Start Date</label>
        <type>Date</type>
    </fields>
    <label>On Sale Date Time</label>
    <nameField>
        <displayFormat>OSD-{000000}</displayFormat>
        <label>On Sale Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On Sale Date Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>ActualGrossToDate__c</fullName>
        <label>Actual Gross To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ActualSalesToDate__c</fullName>
        <label>Actual Sales To Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrossSales__c</fullName>
        <formula>SellableCapacity__c *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Anchcorage, AK</fullName>
    </customValue>
    <customValue>
        <fullName>Appleton</fullName>
    </customValue>
    <customValue>
        <fullName>Aspen</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Augusta</fullName>
    </customValue>
    <customValue>
        <fullName>Austin</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baton Rouge</fullName>
    </customValue>
    <customValue>
        <fullName>Bay Area</fullName>
    </customValue>
    <customValue>
        <fullName>Beaumont</fullName>
    </customValue>
    <customValue>
        <fullName>Billings</fullName>
    </customValue>
    <customValue>
        <fullName>Biloxi</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham</fullName>
    </customValue>
    <customValue>
        <fullName>Boise</fullName>
    </customValue>
    <customValue>
        <fullName>Bonnyville</fullName>
    </customValue>
    <customValue>
        <fullName>Boston</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman</fullName>
    </customValue>
    <customValue>
        <fullName>Brandon</fullName>
    </customValue>
    <customValue>
        <fullName>Branson</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington, VT</fullName>
    </customValue>
    <customValue>
        <fullName>Burnaby</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston, WV</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

src/classes/LNE_MassManualTicketCounts_C.cls
/**
 * Controller for the mass edit.
 * @author Vinay
 * US199 - Controller class to review and enter manual ticket count data across events via a searchable interface 
 *			so that the routine task is faster to complete for all events within a venue, by artist, or other common criteria.
 * @version - us199 
 **/
global with sharing class LNE_MassManualTicketCounts_C {
	/* -- Constants -- */
	private static final Set<String> eventStatus = LNE_Constants.MASS_MANUAL_TICKET_COUNT_EVENT_STATUS;
	public static final String TOO_MANY_RESULTS = 'Too Many Results found. Please further narrow your search.';
	public static final String ERROR_MANUAL_TICKET_COUNT_NOT_VALID = 'Manual ticket count not valid';
	
	public static final TIME MIDNIGHT = Time.newInstance( 0,0,0,0 );

	/* -- Variables -- */
    public EventDateTime__c eventDateTimeSearch {get; set;} 
    public EventDateTime__c eventDateTimeSelected {get; set;} 
    public String  selectedVenueName {get; set;} 
    public Id eventDateTimeId {get; set;}
    public List<EventDateTimeWrapper> eventDateTimeWrapperList {get; set;} 
    public List<ManualTicketCount__c> manualTicketCountList {get; set;} 
    private Map<Id, List<ManualTicketCount__c>> eventDateTimeIdToManualTicketCountMap {get; set;} 
    public Date eventStartDate {get; set;} 
    public Date eventEndDate {get; set;} 
    public ManualTicketCount__c newManualTicketCount {get; set;} 
    private static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue',  'Account.Artist'});         
    private static Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
    private static Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );

    public LNE_MassManualTicketCounts_C() {
		//instantiate the variables
		eventDateTimeSearch = new EventDateTime__c();
		eventDateTimeWrapperList = new List<EventDateTimeWrapper>();
		eventDateTimeIdToManualTicketCountMap = new Map<Id, List<ManualTicketCount__c>>();


        //default start date to today on initial load
        eventDateTimeSearch.EventDate__c = System.today();
        
	}

	/**
	* @description Run a dynamic search and sets list of EventDateTime meeting the search criteria - US199
	* @return PageReference
	**/
    public PageReference runSearch(){
    	Integer numTicketCounts;
		Id eventDateTimeId;
		Id[] eventDateTimeIds;
		
		EventDateTimeWrapper edtWrapper;
        eventDateTimeWrapperList = new List<EventDateTimeWrapper>(); 
        eventDateTimeIdToManualTicketCountMap = new Map<Id, List<ManualTicketCount__c>>();

    	String queryString = buildQuery();
        System.debug(logginglevel.error,'@@@ queryString - '+ queryString);
        List<EventDateTime__c> eventDateTimeList = Database.Query( queryString );
        System.debug(logginglevel.error,'@@@ eventDateTimeList - '+ eventDateTimeList.size() + ' -- ' + eventDateTimeList);

        if(eventDateTimeList != null && !eventDateTimeList.isEmpty()){
        	if(eventDateTimeList.size() > GeneralSettings__c.getInstance().SearchLimit__c){
        		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, TOO_MANY_RESULTS );
            	ApexPages.addMessage(myMsg);
        	}else{

        		Map<Id, EventDateTimeWrapper> eventDateTimeWrapperMap = new Map<Id, EventDateTimeWrapper>();
        		for(EventDateTime__c eventDateTime : eventDateTimeList){
        			/* check for additional critieria based on related object
					* Earliest of (Event Date Time.On Sale Date <= today - 7) OR (Event Date Time.On Sale Date Times.Sale Date <= today)
					*/
					//-- if the eventDateTime.PublicOnSale__c <= system.today() + 7days;
					if(
						( eventDateTime.PublicOnSale__c <= system.today().addDays(7) ) ||
						( eventDateTime.OnSaleDateTimes__r != null && !eventDateTime.OnSaleDateTimes__r.isEmpty() && eventDateTime.OnSaleDateTimes__r[0].SaleStartDate__c <= system.today())
					){
	        			eventDateTimeWrapperMap.put(eventDateTime.Id, new EventDateTimeWrapper(eventDateTime));
	        			eventDateTimeIdToManualTicketCountMap.put(eventDateTime.Id, eventDateTime.ManualTicketCounts__r);
        			}
        		}

        		//Run aggregate query on TicketScale to get the feed counts
				AggregateResult[] groupedResults = [SELECT EventDateTime__c
															, Sum(ActualSalesToDate__c)feedTicketCount
															, Sum(ActualGrossToDate__c)feedGrossCount
															, Max(LastModifiedDate)lastFeedDate 
															FROM TicketScale__c 
															WHERE EventDateTime__c IN :eventDateTimeWrapperMap.keySet()
															AND ( StageType__c = 'Audit' OR (StageType__c = 'Projection' AND Event__r.UsingTicketFeed__c = true))
															GROUP BY EventDateTime__c
														];
				if(groupedResults != null && !groupedResults.isEmpty()){
					ManualTicketCount__c[] manualTicketCounts;
					
					for(AggregateResult ar : groupedResults){
						
						eventDateTimeId = (ID)ar.get('EventDateTime__c');

						EventDateTime__c eventDateTime = eventDateTimeWrapperMap.get(eventDateTimeId).eventDateTime;
						eventDateTimeWrapperMap.put((Id)ar.get('EventDateTime__c'), 
							new EventDateTimeWrapper(eventDateTime,(Decimal)ar.get('feedTicketCount'),(Decimal)ar.get('feedGrossCount'),(DateTime)ar.get('lastFeedDate')));
					}
				}

				eventDateTimeWrapperList.addAll(eventDateTimeWrapperMap.values());
				
				//-- clear the list of manual ticket counts;
				eventDateTimeSelected = null;
				if( manualTicketCountList != null ){
					manualTicketCountList.clear();
				}

                //set the eventDateTimeId to the first of the list.
                if(eventDateTimeWrapperList != null && !eventDateTimeWrapperList.isEmpty()){
                    eventDateTimeId = eventDateTimeWrapperList[0].eventDateTime.Id; 
                }
			}
        }
         System.debug(logginglevel.error,'@@@ eventDateTimeWrapperList - '+ eventDateTimeWrapperList.size() + ' -- ' + eventDateTimeWrapperList);
        return null;
    }

    /**
	* @description builds the dynamic query string for EventDateTime query - US199
	* @return String
	**/
    public String buildQuery(){
    	String queryString = 'SELECT Id, PublicOnSale__c ';
		
    	/* get the fields can be configured as field set to add to query */
    	for(Schema.FieldSetMember f: SObjectType.EventDateTime__c.FieldSets.LNE_MassTicketCount_EventDTListFields.getFields()){ 
    		queryString += ', ' + f.getFieldPath();
        }

        /* get the field for Ticket Count configured as field set and build inner query */
        queryString += ', (SELECT Id, lastModifiedBy.Name ';
        for(Schema.FieldSetMember f: SObjectType.ManualTicketCount__c.FieldSets.LNE_MassTicketCount_Fields.getFields()){ 
    		queryString += ', ' + f.getFieldPath();
        }
        queryString += ' FROM ManualTicketCounts__r order by TicketSalesDate__c desc limit 5 ) ';

        // Add to query to get On Sales Dates
        queryString += ' , (Select Id, SaleStartDate__c from OnSaleDateTimes__r ORDER BY SaleStartDate__c DESC limit 1) ';

        queryString += ' FROM EventDateTime__c ';

        /* Apply predefined filters */
        queryString += ' WHERE EventStatus__c IN :eventStatus' ;

        /* Apply filter criteria based on search filter */
        if(eventDateTimeSearch.Market__c != null){
        	 queryString += ' AND Market__c = \''+ eventDateTimeSearch.Market__c + '\' '  ;
        }
        system.debug(logginglevel.error,'eventDateTimeSearch.Venue__c - '+ eventDateTimeSearch.Venue__c);
        if(eventDateTimeSearch.Venue__c != null){
        	 queryString += ' AND Venue__c = \''+ eventDateTimeSearch.Venue__c + '\' '  ;
        }

        if(selectedVenueName != null && selectedVenueName != ''){
             queryString += ' AND Venue__r.venueName__c = \''+ selectedVenueName + '\' '  ;
        }

        if(eventDateTimeSearch.Artists__c != null && eventDateTimeSearch.Artists__c != ''){
        	 queryString += ' AND Artists__c like \'%'+ eventDateTimeSearch.Artists__c + '%\' '  ;
        }
        if(eventDateTimeSearch.EventDate__c != null){
        	 Date eventStartDate = eventDateTimeSearch.EventDate__c ;
        	 queryString += ' AND EventDate__c >='+ DateTime.newInstance(eventStartDate.year(),eventStartDate.month(),eventStartDate.day()).format('yyyy-MM-dd')  ;
        }
        if(eventDateTimeSearch.EventEndDate__c != null){
        	 Date eventEndDate = eventDateTimeSearch.EventEndDate__c ;
        	 queryString += ' AND EventDate__c <='+ DateTime.newInstance(eventEndDate.year(),eventEndDate.month(),eventEndDate.day()).format('yyyy-MM-dd')  ;
        }

        queryString += ' ORDER BY Venue__r.venueName__c,EventDate__c ASC';

        System.debug(logginglevel.error,'@@@ queryString - '+ queryString);
        return queryString;
    }

    /**
	* @description Returns the list of ManualTicketCounts associated to eventDateTime Id - US199
	* @param (Id) EventDateTimeID
	* @return PageReference
	**/
    public PageReference getManualTicketCountList(){
    	manualTicketCountList = new List<ManualTicketCount__c>();
    	if(eventDateTimeId != null && eventDateTimeIdToManualTicketCountMap.containsKey(eventDateTimeId)){
    		manualTicketCountList = eventDateTimeIdToManualTicketCountMap.get(eventDateTimeId);
    		
    		manualTicketCountList = sortManualTicketCounts( manualTicketCountList );
    		
            //Set the event Date time selected details
            eventDateTimeSelected = [SELECT Id, Name, EventDate__c, StartTime__c FROM EventDateTime__c WHERE Id =: eventDateTimeId ];
            system.debug(LoggingLevel.ERROR, 'manualTicketCountList - '+ manualTicketCountList);
    	}
        instantiateNewManualTicketCount();
        manualTicketCountList.add(newManualTicketCount);
        System.debug( 'eventDateTimeSelected:' ); System.debug( eventDateTimeSelected );
        system.debug(LoggingLevel.ERROR, 'manualTicketCountList after blank row - ' );
        System.debug( manualTicketCountList);
    	return null;
	}

	/**
	* @description instantiate new 
	* @param (Id) EventDateTimeID
	* @return PageReference
	**/
    public ManualTicketCount__c instantiateNewManualTicketCount(){
    	if(eventDateTimeId != null){
    		newManualTicketCount = new ManualTicketCount__c();
    		newManualTicketCount.EventDateTime__c = eventDateTimeId;  
    	}
    	return newManualTicketCount;
	}
	
	/**
	 *  Determines if a new manual ticket count is valid
	 *  @return boolean
	 **/
	public static Boolean isTicketCountValid( ManualTicketCount__c manualTicketCount ){
		//System.debug( 'isNull:' + (manualTicketCount != null) );
		//System.debug( 'TicketSalesDate__c:' + (manualTicketCount.TicketSalesDate__c != null) );
		//System.debug( 'manualTicketCount.TicketCount__c:' + (manualTicketCount.TicketCount__c != null) );
		//System.debug( 'manualTicketCount.GrossSales__c:' + (manualTicketCount.GrossSales__c != null) );
		
		Boolean isValid = (
			manualTicketCount != null && 
			manualTicketCount.TicketSalesDate__c != null &&
			manualTicketCount.TicketCount__c != null &&
			manualTicketCount.GrossSales__c != null
		);
		System.debug( 'isValid:' + isValid );
		return( isValid );
	}
	
	/**
	 * Whether the manual ticket count has been touched in any way
	 * @return boolean
	 **/
	public static Boolean isTicketCountBlank( ManualTicketCount__c manualTicketCount ){
		//System.debug( 'isNull:' + (manualTicketCount != null) );
		//System.debug( 'TicketSalesDate__c:' + (manualTicketCount.TicketSalesDate__c != null) );
		//System.debug( 'manualTicketCount.TicketCount__c:' + (manualTicketCount.TicketCount__c != null) );
		//System.debug( 'manualTicketCount.GrossSales__c:' + (manualTicketCount.GrossSales__c != null) );
		
		Boolean isBlank = (
			manualTicketCount != null && !(
				( manualTicketCount.TicketSalesDate__c != null ) ||
				( manualTicketCount.TicketCount__c != null ) ||
				( manualTicketCount.GrossSales__c != null )
			)
		);
		System.debug( 'isBlank:' + isBlank );
		return( isBlank );
	}
	
	/**
	 * Creates a list of valid manual ticket counts
	 * @param ManualTicketCount__c[] manualTicketCounts
	 * @return ManualTicketCount__c[] - manual ticket counts filtered to only those that are 'valid'
	 **/
	public static ManualTicketCount__c[] getValidManualTicketCounts( ManualTicketCount__c[] manualTicketCounts ){
		ManualTicketCount__c[] results = new ManualTicketCount__c[]{};
		
		if( manualTicketCounts != null && manualTicketCounts.size() > 0 ){
			for( ManualTicketCount__c mtc : manualTicketCounts ){
				if( isTicketCountValid( mtc )){
					results.add( mtc );
				}
			}
		}
		return( results );
	}


	/**
	* @description save ManualTicketCounts associated to eventDateTime Id - US199
	* @return PageReference
	**/
    public PageReference saveManualTicketCountList(){
    	
    	//-- check if the new ticket count is blank
    	//System.debug( 'is new blank:' + isTicketCountBlank( this.newManualTicketCount ) );
    	//System.debug( 'is new valid:' + isTicketCountValid( this.newManualTicketCount ) );
    	
    	//-- validate all the records
    	for( ManualTicketCount__c mtc: this.manualTicketCountList ){
    		if( !isTicketCountBlank( mtc ) && !isTicketCountValid( mtc )){
    			System.debug( 'mtc is not valid:' ); System.debug( mtc );
    			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ERROR_MANUAL_TICKET_COUNT_NOT_VALID );
            	ApexPages.addMessage(myMsg);
	    	}
    	}
    	
    	ManualTicketCount__c[] updateList = getValidManualTicketCounts( this.manualTicketCountList );
    	
    	if( updateList != null && !updateList.isEmpty()){
    		
    		System.debug( 'list to insert:' ); System.debug( updateList );
	    	try{
	    		upsert updateList;
	    		
	    		//-- recalculate formulas WILL NOT WORK in this case.
	    		
	    		//-- update the cache
	    		eventDateTimeIdToManualTicketCountMap.put( eventDateTimeId, updateList );
	    		
	    		if( isTicketCountValid( this.newManualTicketCount ) ){
	    			//-- its in use, so we'll add a new one.
	    			manualTicketCountList.add( instantiateNewManualTicketCount() );
	    		}
	    	}
	    	catch(Exception ex){
	    		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage() );
            	ApexPages.addMessage(myMsg);
	    	}
    	}
    	return null;
	}

	/** 
	 * Remote action to find the venues that match a similar name.
	 * @param venueSearch
	 * @return String[] list of venue names
	 **/
	@RemoteAction
	global static String[] searchVenues( String venueSearch ){
		String[] results = new String[]{};
		String venueSearch2 = '%' + venueSearch + '%';
		
		for( Account venue: [
			select id, name, venueName__c
			from account
			where venueName__c like :venueSearch2 and RecordTypeId =: RT_ACCOUNT_VENUE_ID
		]){
			results.add( venue.VenueName__c );
		}
		
		return( results );
	}

	/** 
	 * Remote action to find the artist that match a similar name.
	 * @param artistSearch
	 * @return String[] list of artist names
	 **/
	@RemoteAction
	global static String[] searchArtists( String artistSearch ){
		String[] results = new String[]{};
		String artistSearch2 = '%' + artistSearch + '%';
		
		for( Account artist: [
			select id, name
			from account
			where name like :artistSearch2 and RecordTypeId =: RT_ACCOUNT_ARTIST_ID
		]){
			results.add( artist.name );
		}
		
		return( results );
	}
	
	/**
	 * Sorts a list of manual ticket counts
	 * @param manualTicketCounts (ManualTicketCount__c[] )
	 * @return ManualTicketCount__c[] - sorted list
	 **/
	public static ManualTicketCount__c[] sortManualTicketCounts( ManualTicketCount__c[] manualTicketCounts ){
		ManualTicketCount__c[] results = new ManualTicketCount__c[]{};
		
		if( manualTicketCounts != null ){
			SortableManualTicketCountWrapper[] sortableList= new SortableManualTicketCountWrapper[]{};
			for( ManualTicketCount__c mtc : manualTicketCounts ){
				sortableList.add( new SortableManualTicketCountWrapper( mtc ));
			}
			sortableList.sort();
			
			for( Integer i = 0; i < sortableList.size(); i++ ){
				results.add( sortableList[i].manualTicketCount );
			}
		}
		
		return( results );
	}
	
	/**
	 * Sortable list of manual ticket counts
	 **/
	public class SortableManualTicketCountWrapper implements Comparable {
		public ManualTicketCount__c manualTicketCount;
		public Integer epochLifetime;
		
		public SortableManualTicketCountWrapper( ManualTicketCount__c manualTicketCount ){
			this.manualTicketCount = manualTicketCount;
			
			this.epochLifetime = 0;
			if( manualTicketCount.TicketSalesDate__c != null ){
			//	DateTime dt = DateTime.newInstance( manualTicketCount.TicketSalesDate__c, MIDNIGHT );
			//	this.epochLifetime = dt.getTime();
				this.epochLifetime = (manualTicketCount.TicketSalesDate__c.year() * 365) + manualTicketCount.TicketSalesDate__c.dayOfYear();
			}
		}
		
		public Integer compareTo( Object compareTo ){
			SortableManualTicketCountWrapper compareToMTC = (SortableManualTicketCountWrapper)compareTo;
			
			Integer returnVal = Integer.valueOf( this.epochLifetime - compareToMTC.epochLifetime);
			System.debug( 'comparing times[' + this.epochLifetime + '] thatTime[' + compareToMTC.epochLifetime + ']:' + returnVal );
			return( returnVal );
		}
	}

	/**
	* @author Vinay Kanuganti
	* @created 2017-01-27
	* @description Wrapper class to display the Event Date time and coresponding the ticket counts.
	**/
    public class EventDateTimeWrapper{
    	public EventDateTime__c eventDateTime {get; set;} 
    	public Decimal feedTicketCount {get; set;} 
    	public Decimal feedGrossSales {get; set;} 
    	public DateTime lastFeedDate {get; set;} 

    	public EventDateTimeWrapper( EventDateTime__c  cEventDateTime){
    		this.eventDateTime = cEventDateTime;
    		this.feedTicketCount = 0;
    		this.feedGrossSales = 0.0;
    		this.lastFeedDate = null;		
    	}

    	public EventDateTimeWrapper( EventDateTime__c  cEventDateTime, Decimal cFeedTicketCount, Decimal cFeedGrossSales, DateTime cLastFeedDate){
    		this.eventDateTime = cEventDateTime;
    		this.feedTicketCount = cFeedTicketCount;
    		this.feedGrossSales = cFeedGrossSales;
    		this.lastFeedDate = cLastFeedDate;		
    	}
    }

}