src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_TestTemplate_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_TestTemplate_Test {
	
	public static GLAccount__c myGL_Account;
	
	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
	}

	class TestSettings {
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
		}
		
		public void typicalSetup(){
			
		}
		
		public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		}
	}
	
	
	//-- test test methods here
	
	static testMethod void runSetupAWithoutException() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		System.assert( true, 'No Exceptions have occurred in getting here' );
	}
	
   	//-- test functionality here
	
	static testMethod void testScenario() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		
		//-- your logic off of any info from TS here
		System.assert( true, 'ts.account.DMA__c is not null, etc.' );
	}

}