src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApplyGlobalTermsTo__c</fullName>
        <label>Apply Global Terms To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Theater</fullName>
                </value>
                <value>
                    <fullName>Club</fullName>
                </value>
                <value>
                    <fullName>Arena</fullName>
                </value>
                <value>
                    <fullName>Stadium</fullName>
                </value>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Boutique Amphitheatre</fullName>
                </value>
                <value>
                    <fullName>Comedy Club</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <label>DMA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DMA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalTermsUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether managers should be notified that the Global Terms have updated.</inlineHelpText>
        <label>Global Terms Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GlobalTerms__c</fullName>
        <description>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</description>
        <inlineHelpText>These are the terms &amp; conditions that apply to venues underneath the combination division-venue type</inlineHelpText>
        <label>Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OwnershipType__c</fullName>
        <label>Ownership Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Owned/Operated</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Exclusively Booked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreviousGlobalTerms__c</fullName>
        <description>This is defined through a trigger - and when the Global Terms are applied based on the matching Divison Office / Venue Type.</description>
        <inlineHelpText>Global Terms used previously before the last application from the Division</inlineHelpText>
        <label>Previous Global Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PrimaryOffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Primary Venues</relationshipLabel>
        <relationshipName>Venues</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Role type of the related contact</description>
        <inlineHelpText>Initial role definition for the contact for the parent account.</inlineHelpText>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Accounts Payable</fullName>
                </value>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>Artist Agent</fullName>
                </value>
                <value>
                    <fullName>Artist Contact</fullName>
                </value>
                <value>
                    <fullName>Artist Manager</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Business Contact</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>On-Air Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Press Representative</fullName>
                </value>
                <value>
                    <fullName>Primary Artist Contact</fullName>
                </value>
                <value>
                    <fullName>Programming</fullName>
                </value>
                <value>
                    <fullName>Promoter</fullName>
                </value>
                <value>
                    <fullName>Promotion Manager</fullName>
                </value>
                <value>
                    <fullName>Promotions/Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales Management</fullName>
                </value>
                <value>
                    <fullName>Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Tech Contact</fullName>
                </value>
                <value>
                    <fullName>Traffic Coordinator</fullName>
                </value>
                <value>
                    <fullName>Venue Box Office</fullName>
                </value>
                <value>
                    <fullName>Venue GM</fullName>
                </value>
                <value>
                    <fullName>Venue Operations</fullName>
                </value>
                <value>
                    <fullName>Venue Production</fullName>
                </value>
                <value>
                    <fullName>Venue Special Events Coordinator</fullName>
                </value>
                <value>
                    <fullName>Venue Talent Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>BypassAutomation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All forms of workflow (Process Builder, Flow, workflow rules), validation rules, and triggers will be prevented from running when changing this value to true/checked. Apply at the org, profile, or user level.</description>
        <inlineHelpText>All forms of workflow (Process Builder, Flow, workflow rules), validation rules, and triggers will be prevented from running when changing this value to true/checked. Apply at the org, profile, or user level.</inlineHelpText>
        <label>Bypass Automation</label>
        <type>Checkbox</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/globalValueSets/DMA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABILENE-SWEETWATER</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY, GA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANY-SCHENECTADY-TROY</fullName>
    </customValue>
    <customValue>
        <fullName>ALBUQUERQUE-SANTA FE</fullName>
    </customValue>
    <customValue>
        <fullName>ALEXANDRIA, LA</fullName>
    </customValue>
    <customValue>
        <fullName>ALPENA</fullName>
    </customValue>
    <customValue>
        <fullName>AMARILLO</fullName>
    </customValue>
    <customValue>
        <fullName>ANCHORAGE</fullName>
    </customValue>
    <customValue>
        <fullName>ATLANTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUGUSTA-AIKEN</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTIN</fullName>
    </customValue>
    <customValue>
        <fullName>BAKERSFIELD</fullName>
    </customValue>
    <customValue>
        <fullName>BALTIMORE</fullName>
    </customValue>
    <customValue>
        <fullName>BANGOR</fullName>
    </customValue>
    <customValue>
        <fullName>BATON ROUGE</fullName>
    </customValue>
    <customValue>
        <fullName>BEAUMONT-PORT ARTHUR</fullName>
    </customValue>
    <customValue>
        <fullName>BEND, OR</fullName>
    </customValue>
    <customValue>
        <fullName>BILLINGS</fullName>
    </customValue>
    <customValue>
        <fullName>BILOXI-GULFPORT</fullName>
    </customValue>
    <customValue>
        <fullName>BINGHAMTON</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMINGHAM (ANN AND TUSC)</fullName>
    </customValue>
    <customValue>
        <fullName>BLUEFIELD-BECKLEY-OAK HILL</fullName>
    </customValue>
    <customValue>
        <fullName>BOISE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSTON (MANCHESTER)</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>BUFFALO</fullName>
    </customValue>
    <customValue>
        <fullName>BURLINGTON-PLATTSBURGH</fullName>
    </customValue>
    <customValue>
        <fullName>BUTTE-BOZEMAN</fullName>
    </customValue>
    <customValue>
        <fullName>CASPER-RIVERTON</fullName>
    </customValue>
    <customValue>
        <fullName>CEDAR RAPIDS-WTRLO-IWC&amp;DUB</fullName>
    </customValue>
    <customValue>
        <fullName>CHICAGO</fullName>
    </customValue>
    <customValue>
        <fullName>PADUCAH-CAPE GIRARD-HARSBG</fullName>
    </customValue>
    <description>Nielsen&apos;s Designated Market Area (DMA)</description>
    <masterLabel>DMA</masterLabel>
</GlobalValueSet>

src/classes/LNE_AccountTermsUpdated_Batch_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LNE_AccountTermsUpdated_Batch_Test {

	class TestSettings {
		
		//-- example combined key delimiter
		String COMBINED_KEY_DELIMITER = '|';
		
		Account geoOffice;
		Account divisionOffice;
		Account[] venues;
		Contact venueGM;
		
		//-- instance values
		Account[] newAccounts;
		Map<Id,Account> oldAccountsMap;
		DataGenerationSettings__c dataSettings;
		DMA__c[] dmaList;
		
		String RT_VENUE_NAME = 'Account.Venue';
		String RT_OFFICE_NAME = 'Account.Office';
		ID RT_VENUE_ID;
		ID RT_OFFICE_ID;
		
		String ORIGINAL_TERMS = 'Original Terms';
		String UPDATED_TERMS = 'Updated Terms';
		
		LNE_AccountTermsUpdated_Batch batch;
		
		LNE_TestObjectFactory factory;
		
		String ROLE_VENUE_GM = 'Venue GM';
		
		public TestSettings(){
			//-- initialize common custom settings.
			LNE_TestObjectFactory.prepStandardCustomSettings();
					
			//-- important rule to allow duplicates within the unit tests.
			Database.DMLOptions dml = new Database.DMLOptions();
			dml.DuplicateRuleHeader.AllowSave = true;
			
			factory = new LNE_TestObjectFactory(null);
			
			//-- get recordtypes
			Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ RT_VENUE_NAME, RT_OFFICE_NAME }
			);
			RT_OFFICE_ID = recordTypeMap.get( RT_OFFICE_NAME );
			RT_VENUE_ID = recordTypeMap.get( RT_VENUE_NAME );
			
			dmaList = new DMA__c[]{
				LNE_TestObjectFactory.createDMA( 'CHICAGO', 'COOK', 'IL', '60402' ),
				LNE_TestObjectFactory.createDMA( 'PADUCAH-CAPE GIRARD-HARSBG', 'JACKSON', 'IL', '62274' )
			};
			insert dmaList;
			
			//-- create the offices
			//-- @TODO: probably should include new createGeoOffice / createDivisionOffices in TestObjectFactory
			geoOffice = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testGeography' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
				'Phone' => '708-522-5307',
				'Type' => 'Geography'
			}).buildAccount();
			insert geoOffice;
			
			divisionOffice = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createAccount( LNE_TestObjectFactory.makeUnique( 'testDivision' ), RT_OFFICE_ID )
			).addBillingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
				'Phone' => '708-522-5307',
				'Type' => 'Division',
				'ApplyGlobalTermsTo__c' => 'Amphitheatre',
				'GlobalTerms__c' => ORIGINAL_TERMS,
				'ParentId' => geoOffice.Id
			}).buildAccount();
			insert divisionOffice;
			
			venues = new Account[]{
				new LNE_TestObjectFactory(
					LNE_TestObjectFactory.createAccount( 'TestAccount999', RT_VENUE_ID )
				).addBillingAddress( '200 West Jackson St.', 'Jackson', '62274', 'Illinois', 'IL', 'United States', 'US' )
				.addProperties( new Map<String,Object>{
					'Capacity__c' => 1000,
					'PrimaryOffice__c' => divisionOffice.Id,
					'OwnershipType__c' => 'Owned/Operated',
					'GlobalTermsUpdated__c' => true,
					'PreviousGlobalTerms__c' => ORIGINAL_TERMS,
					'GlobalTerms__c' => UPDATED_TERMS,
					'Type' => 'Amphitheatre'
				}).buildAccount()
			};
			insert venues;
			
			venueGM = new LNE_TestObjectFactory(
				LNE_TestObjectFactory.createContact( venues[0].Id, 'John', LNE_TestObjectFactory.makeUnique( 'Doe' ))
			)
			.addMailingAddress( '1000 west illinois st', 'Chicago', '60402', 'Illinois', 'IL', 'United States', 'US' )
			.addProperties( new Map<String,Object>{
				'Email' => 'test@example.com',
				'Roles__c' => ROLE_VENUE_GM
			}).buildContact();
			insert venueGM;
			
			batch = new LNE_AccountTermsUpdated_Batch();
		}
		
		public void typicalSetup(){
			//-- nothing for now
		}
		
		/** Finalize step. Should always be called after all setups. **/
		public void finalize(){
			//-- nothing for now
		}
	}
	
	
	//-- test test methods here
	
	static testMethod void runSetupAWithoutException() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		System.assert( true, 'No Exceptions have occurred in getting here' );
		
		Id venueId = ts.venues[0].Id;
		Id gmId = ts.venueGM.Id;
		AccountContactRelation venueGM_ACR = [
			select id, accountId, contactId, Roles
			from AccountContactRelation
			where AccountId = :venueId and ContactId = :gmId
		];
		System.assertNotEquals( null, venueGM_ACR, 'There must be a relation' );
		System.assertNotEquals( null, venueGM_ACR.Roles, 'There must be roles assigned - from LNE_ContactCreate_T' );
		System.assert( venueGM_ACR.Roles.indexOf( ts.ROLE_VENUE_GM ) > -1, 'The Venue GM role must be defined' );
	}
	
	//-- test functionality here
	
	static testMethod void testEmailsSent() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		
		//-- this shouldn't be needed but there is something up with a workflow and its nulling the state. Not sure why.
		GeneralSettings__c generalSettings = [SELECT Id FROM GeneralSettings__c];
		generalSettings.BypassAutomation__c = true;
		update generalSettings;
		
		Integer emailInvocations = 0;
		
		//-- START THE TEST
		Test.startTest();
		Database.executeBatch( ts.batch );
		emailInvocations = Limits.getEmailInvocations();
		System.debug( 'first emailInvocations:' + emailInvocations );
		Test.stopTest();
		//-- END THE TEST
		
		emailInvocations = Limits.getEmailInvocations();
		System.debug( 'second emailInvocations:' + emailInvocations );
		
		//-- your logic off of any info from TS here
		//System.assert( emailInvocations > 0, 'An email should have been sent' );
		System.assert( true, 'no exceptions should have been found by reaching this point' );
	}

}