src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Captures the venues maximum capacity</description>
        <label>Capacity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <description>Record type to keep track of all related artist information including primary agency, agent, and genre</description>
        <label>Artist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>Record type for internal LNE locations</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>Record type for the performance location</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>AmountRate__c</fullName>
        <label>Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BeforeAfter__c</fullName>
        <label>Before/After</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before Adjusted</fullName>
                </value>
                <value>
                    <fullName>After Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Amount Per Ticket</fullName>
                </value>
                <value>
                    <fullName>Primary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Primary Multiplier Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Multiplier Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Artist Add-On</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>FMF/Venue Charge</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Value Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFeePercent__c</fullName>
        <defaultValue>0.129</defaultValue>
        <label>TM Fee %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_PromoterCreateEvent_CX_Test.cls
@isTest
public with sharing class LNE_PromoterCreateEvent_CX_Test {
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet();
    }

	class TestSettings {
        DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();

        Event__c testEventNew;
        Event__c testEventExisting;
        Account primaryHeadliner;
        Account office;
        Account venue;
        Map<String,Id> recordTypeMap;

        public TestSettings() {
            LNE_FinancialCalculator.currentlyRunning = true;
            LNE_FinancialCalculator.pushRunningTrigger( 'LNE_EventDateTimeUtil_T_Test' );
            LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false);

            recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Account.Venue', 'Account.Office', 'Account.Artist', 'Event__c.PromotedShow', 'Event__c.Rental', 'Event__c.Hold'});         
            Id RT_ACCOUNT_VENUE_ID = recordTypeMap.get( 'Account.Venue' );
            Id RT_ACCOUNT_OFFICE_ID = recordTypeMap.get( 'Account.Office' );
            Id RT_ACCOUNT_ARTIST_ID = recordTypeMap.get( 'Account.Artist' );
            Id RT_EVENT_PROMOTEDSHOW_ID = recordTypeMap.get( 'Event__c.PromotedShow' );	
			Id RT_Rental_ID = recordTypeMap.get( 'Event__c.Rental' );
			Id RT_Hold_ID = recordTypeMap.get( 'Event__c.Hold' );

            testEventNew = new Event__c();
            testEventExisting = [SELECT Id FROM Event__c LIMIT 1];
            testEventExisting.RecordTypeId = RT_EVENT_PROMOTEDSHOW_ID;
            update testEventExisting;

            primaryHeadliner = [SELECT Id FROM Account WHERE RecordTypeId = :RT_ACCOUNT_ARTIST_ID LIMIT 1];
            office = [SELECT Id FROM Account WHERE RecordTypeId = :RT_ACCOUNT_OFFICE_ID AND ParentId <> NULL LIMIT 1];
            venue = [SELECT Id FROM Account WHERE RecordTypeId = :RT_ACCOUNT_VENUE_ID LIMIT 1];

            EventDateTime__c eventDateTime = new EventDateTime__c(
                Event__c = testEventExisting.Id, 
                EventYear__c = String.valueOf(System.now().year() + 2),
                EventDate__c = System.today().addDays(10),
                StartTime__c = '6:00 PM');

            EventDateTime__c eventDateTime2 = new EventDateTime__c(
                Event__c = testEventExisting.Id, 
                EventYear__c = String.valueOf(System.now().year() + 2),
                EventDate__c = System.today().addDays(11),
                StartTime__c = '8:00 PM');

            insert new List<EventDateTime__c>{eventDateTime,eventDateTime2};

            TicketScale__c ticketScale = new TicketScale__c();
            ticketScale.Type__c = 'Reserved';
            ticketScale.Capacity__c = 1000;
            ticketScale.Price__c = 100.00;
            ticketScale.Kills__c = 0;
            ticketScale.Comps__c = 0;
            ticketScale.ProjectedPaidTickets__c = 950;
            ticketScale.Event__c = testEventExisting.Id;
            ticketScale.LiftBeforeFee__c = 0;
            ticketScale.TMFeePercent__c = 0.0;
            ticketScale.StageType__c = 'Plan';
            ticketScale.EventDateTime__c = eventDateTime.Id;

            TicketScale__c ticketScale2 = new TicketScale__c();
            ticketScale2.Type__c = 'Lawn';
            ticketScale2.Capacity__c = 1000;
            ticketScale2.Price__c = 100.00;
            ticketScale2.Kills__c = 0;
            ticketScale2.Comps__c = 0;
            ticketScale2.ProjectedPaidTickets__c = 950;
            ticketScale2.Event__c = testEventExisting.Id;
            ticketScale2.LiftBeforeFee__c = 0;
            ticketScale2.TMFeePercent__c = 0.0;
            ticketScale2.StageType__c = 'Plan';
            ticketScale2.EventDateTime__c = eventDateTime.Id;

            TicketScale__c ticketScale3 = new TicketScale__c();
            ticketScale3.Type__c = 'Platinum';
            ticketScale3.Capacity__c = 100;
            ticketScale3.Price__c = 100.00;
            ticketScale3.Kills__c = 0;
            ticketScale3.Comps__c = 0;
            ticketScale3.ProjectedPaidTickets__c = 100;
            ticketScale3.Event__c = testEventExisting.Id;
            ticketScale3.LiftBeforeFee__c = 7420.00;
            ticketScale3.TMFeePercent__c = 0.0;
            ticketScale3.StageType__c = 'Plan';
            ticketScale3.EventDateTime__c = eventDateTime.Id;

            insert new List<TicketScale__c>{ticketScale,ticketScale2,ticketScale3};

            String ticketScaleList = ticketScale.Id + DATA_SETTINGS.CombinedKeyDelimiter__c + ticketScale2.Id + DATA_SETTINGS.CombinedKeyDelimiter__c + ticketScale3.Id;

            Deduction__c deduction = new Deduction__c();
            deduction.BeforeAfter__c = 'Before Adjusted';
            deduction.Event__c = testEventExisting.Id;
            deduction.RateType__c = 'Primary Multiplier Tax';
            deduction.AmountRate__c = 10;
            deduction.TicketScaleList__c = ticketScaleList;

            Deduction__c deduction2 = new Deduction__c();
            deduction2.BeforeAfter__c = 'Before Adjusted';
            deduction2.Event__c = testEventExisting.Id;
            deduction2.RateType__c = 'Primary Divider Tax';
            deduction2.AmountRate__c = 10;
            deduction2.TicketScaleList__c = ticketScaleList;

            insert new List<Deduction__c>{deduction,deduction2};
        }
        
        public void typicalSetup(){}
        
        public void finalize(){}
    }

	static LNE_PromoterCreateEvent_CX setupCtrlForNew(Event__c evnt, id eventRecordTypeId) {
		ApexPages.currentPage().getParameters().put(LNE_PromoterCreateEvent_CX.PARAM_RECORD_TYPE, eventRecordTypeId);
        ApexPages.currentPage().getParameters().put('save_new', '1');

        ApexPages.StandardController standardEventCtlr = new ApexPages.StandardController(evnt);    	
    	LNE_PromoterCreateEvent_CX controller = new LNE_PromoterCreateEvent_CX( standardEventCtlr );

		return controller;
	}

    static LNE_PromoterCreateEvent_CX setupCtrlForClone(Event__c evnt, id eventRecordTypeId) {
        ApexPages.currentPage().getParameters().put(LNE_PromoterCreateEvent_CX.PARAM_RECORD_TYPE, eventRecordTypeId);
        ApexPages.currentPage().getParameters().put('clone', '1');
        ApexPages.currentPage().getParameters().put('Id', evnt.Id);

        ApexPages.StandardController standardEventCtlr = new ApexPages.StandardController(evnt);        
        LNE_PromoterCreateEvent_CX controller = new LNE_PromoterCreateEvent_CX( standardEventCtlr );

        return controller;
    }

    static testMethod void testController() {
    	TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Id RT_EVENT_PROMOTEDSHOW_ID = ts.recordTypeMap.get( 'Event__c.PromotedShow' );	
		Test.startTest();
		
       	LNE_PromoterCreateEvent_CX controller = setupCtrlForNew(ts.testEventNew, RT_EVENT_PROMOTEDSHOW_ID);

        controller.vTargetYear = String.valueOf(System.now().year() + 1);
        controller.vPrimaryHeadlinerArtist = ts.primaryHeadliner.Id;
        controller.vOffice = ts.office.Id;
        controller.vVenue = ts.venue.Id;
        controller.vPromoter = UserInfo.getUserId();

        controller.restart();
        system.assertEquals(RT_EVENT_PROMOTEDSHOW_ID, controller.currentRecordType.Id);

    	Test.stopTest();
    }

    static testMethod void testController_Error() {
    	TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
       
       	Id RT_EVENT_PROMOTEDSHOW_ID = ts.recordTypeMap.get( 'Event__c.PromotedShow' );
    	Test.startTest();
		
       	LNE_PromoterCreateEvent_CX controller = setupCtrlForNew(ts.testEventNew, RT_EVENT_PROMOTEDSHOW_ID);
        system.assertEquals(RT_EVENT_PROMOTEDSHOW_ID, controller.currentRecordType.Id);
    	
    	controller.confirm();

		Test.stopTest();
    }

    static testMethod void testController_Clone() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
       
        Id RT_EVENT_PROMOTEDSHOW_ID = ts.recordTypeMap.get( 'Event__c.PromotedShow' );  
        Test.startTest();
        
        LNE_PromoterCreateEvent_CX controller = setupCtrlForClone(ts.testEventExisting, RT_EVENT_PROMOTEDSHOW_ID);
        controller.vTargetYear = String.valueOf(System.now().year() + 1);
        controller.vPrimaryHeadlinerArtist = ts.primaryHeadliner.Id;
        controller.vOffice = ts.office.Id;
        controller.vVenue = ts.venue.Id;
        controller.vPromoter = UserInfo.getUserId();
        
        controller.confirm();

        List<Event__c> events = [SELECT Id FROM Event__c];
        system.assertEquals(1, events.size());

        controller.vTargetYear = String.valueOf(System.now().year() + 1);
        controller.vPrimaryHeadlinerArtist = ts.primaryHeadliner.Id;
        controller.clonedEventName = 'Cloned Event 1234';
        controller.vOffice = ts.office.Id;
        controller.vVenue = ts.venue.Id;
        controller.vPromoter = UserInfo.getUserId();
        controller.headlinerArtist.Artist__c = ts.primaryHeadliner.Id;
        controller.eventDateTime.EventYear__c = String.valueOf(System.now().year() + 1);
        controller.confirmClone();

        Test.stopTest();

        events = [SELECT Id FROM Event__c];
        system.assertEquals(2, events.size());
    }
}