src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>DigitalSpend__c</fullName>
        <label>Digital Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OutdoorSpend__c</fullName>
        <label>Outdoor Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Outdoor</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PrintSpend__c</fullName>
        <label>Print Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Print</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProductionMiscellaneousSpend__c</fullName>
        <label>Production/Miscellaneous Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Production/Miscellaneous</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RadioSpend__c</fullName>
        <label>Radio Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Radio</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NonLNETourBudget__c.object
<CustomObject>
    <description>Tour marketing budgets funded by 3rd-party sponsors</description>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Non-LNE Tour Budgets</relationshipLabel>
        <relationshipName>NonLNETourBudgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sponsor does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Sponsor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Non-LNE Tour Budgets</relationshipLabel>
        <relationshipName>NonLNETourBudgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-LNE Tour Budget</label>
    <nameField>
        <displayFormat>NLTB-{000000}</displayFormat>
        <label>Non-LNE Tour Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-LNE Tour Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>DigitalSpend__c</fullName>
        <label>Digital Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Non-LNE Tour Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NonLNETourBudget__c.Tour__c</field>
                <operation>equals</operation>
                <valueField>$Source.Tour__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NonLNETourBudget__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>TourCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FBEvent - buyticketslink</fullName>
                </value>
                <value>
                    <fullName>FBEvent - description</fullName>
                </value>
                <value>
                    <fullName>FBX</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page image</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page link</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page video</fullName>
                </value>
                <value>
                    <fullName>Paid - dark post</fullName>
                </value>
                <value>
                    <fullName>Paid - link post</fullName>
                </value>
                <value>
                    <fullName>Paid - Lncom</fullName>
                </value>
                <value>
                    <fullName>Paid - photo</fullName>
                </value>
                <value>
                    <fullName>Paid - promotion</fullName>
                </value>
                <value>
                    <fullName>Paid - Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Paid - text only</fullName>
                </value>
                <value>
                    <fullName>Paid - video</fullName>
                </value>
                <value>
                    <fullName>Advertising Materials Production</fullName>
                </value>
                <value>
                    <fullName>Agency Commission</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Distribution</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Production</fullName>
                </value>
                <value>
                    <fullName>Graphic/Digital Design</fullName>
                </value>
                <value>
                    <fullName>National Allocation - Misc</fullName>
                </value>
                <value>
                    <fullName>Press Conference</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Tour Launch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Rich Media</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HasNonLNETourBudget__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the Tour Campaign Ad Plan is associated with a tour campaign that has a Non-LNE Tour Budget.
assigned through apex
and used because a roll up summary cannot use formula fields.</description>
        <label>Has Non-LNE Tour Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <formula>TourCampaign__r.NonLNETourBudget__r.Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-LNE Tour Budget</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <label>Sponsor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaignType__c</fullName>
        <description>Filled through apex, as the RecordType name of the associated Tour Campaign.
Used because RollUpSummaries cannot use formula fields</description>
        <label>Tour Campaign Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(TourCampaign__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_AdPlanLogic_T.cls
/** 
 *  Trigger logic to check for managing Tour Campaign-Ad Plan records 
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 *  @author Paul Roth <proth@salesforce.com>
 *  @see US689 / US146
 **/
public class LNE_AdPlanLogic_T {

    /**
    *  Automatically creates new Tour Campaign-Ad Plan records when an AdPlan__c is
    *  associated with a Tour
    *  @param newList AdPlan__c[]
    **/
    public static void createTourCampaignAdPlanRecordsOnInsert(AdPlan__c[] newList){
        Set<Id> newTourIDs = new Set<Id>();

        for (AdPlan__c ap : newList) {
            if (ap.Tour__c != null) {
                newTourIDs.add(ap.Tour__c);
            }
        }

        if (!newTourIDs.isEmpty()) {
            createTourCampaignAdPlans(newTourIDs, newList);
        }
    }

    /**
    *  Automatically creates manages Tour Campaign-Ad Plan records when Tour__c
    *  is updated on an Ad Plan
    *  @param newList AdPlan__c[]
    *  @param oldMap AdPlan__c[]
    **/
    public static void manageTourCampaignAdPlanRecordsOnUpdate(AdPlan__c[] newList, Map<Id, AdPlan__c> oldMap){
        Set<Id> changedTourIDs = new Set<Id>();
        Set<Id> changedAdPlans = new Set<Id>();

        for (AdPlan__c ap : newList) {
            if (oldMap.get(ap.Id) != null) {
                if (oldMap.get(ap.Id).Tour__c != ap.Tour__c) {
                    if (ap.Tour__c != null) {
                        changedTourIDs.add(ap.Tour__c);
                    }
                    changedAdPlans.add(ap.Id);
                }
            }
        }

        if (!changedTourIDs.isEmpty()) {
            createTourCampaignAdPlans(changedTourIDs, newList);
        }

        if (!changedAdPlans.isEmpty()) {
            List<TourCampaignAdPlan__c> toCleanUp = [SELECT AdPlan__r.Tour__c, TourCampaign__r.Tour__c FROM TourCampaignAdPlan__c WHERE AdPlan__c IN :changedAdPlans];
            List<TourCampaignAdPlan__c> toDelete = new List<TourCampaignAdPlan__c>();

            for (TourCampaignAdPlan__c tcap : toCleanUp) {
                if (tcap.TourCampaign__r.Tour__c != tcap.AdPlan__r.Tour__c) {
                    toDelete.add(tcap);
                }
            }

            if (!toDelete.isEmpty()) {
                delete toDelete;
            }
        }
    }

    private static void createTourCampaignAdPlans(Set<Id> tourIDs, AdPlan__c[] newList) {
        //-- @TODO: investigate if there is a better way to do this.
        List<TourCampaignAdPlan__c> toInsert = new List<TourCampaignAdPlan__c>();
        Map<Id, Tour__c> tourMap = new Map<Id, Tour__c>([SELECT Id, (SELECT Tour__c, RecordType.Name, NonLNETourBudget__c, NonLNETourBudget__r.Type__r.Name FROM Tour_Campaigns__r) FROM Tour__c WHERE Id IN :tourIDs]);
        
        //-- Create a TourCampaignAdPlan (junction between touring and ad plan)
        //-- Once an ad plan is associated to a tour
        //-- create a junction object (TourCampaignAdPlan__c) between the tour campaign and associated ad plans

        for (AdPlan__c ap : newList) {
            for (TourCampaign__c tc : tourMap.get(ap.Tour__c).Tour_Campaigns__r) {
                TourCampaignAdPlan__c tcap = new TourCampaignAdPlan__c(
                    AdPlan__c=ap.Id,
                    TourCampaign__c=tc.Id,
                    TourCampaignType__c = tc.RecordType.Name,
                    HasNonLNETourBudget__c = (tc.NonLNETourBudget__c != null),
                    Sponsor__c = tc.NonLNETourBudget__r.Type__r.Name
                );
                toInsert.add(tcap);
            }
        }

        if (!toInsert.isEmpty()) {
            insert toInsert;
        }
    }

    /**
     *  US 691 - Checks if any fields changed that would require a recalculation of Ledger Entries.
     *  @param newList AdPlan__c[]
     *  @param oldMap Map<Id,AdPlan__c>
     *  @return AdPlan__c[] - list of AdPlans updated.
    **/
    
    public static AdPlan__c[] execute( AdPlan__c[] newList, Map<Id,AdPlan__c> oldMap ){
        List<AdPlan__c> changedLedgers = new List<AdPlan__c>();
        Set<Id> listOfRelatedEventIds = new Set<Id>();
        ChangedAdPlan objChange = null;

        if (oldMap == null){
            oldMap = new Map<Id, AdPlan__c>();
        }

        for (AdPlan__c newAdPlan : newList ){
            if(oldMap.containsKey(newAdPlan.Id)){
                
                AdPlan__c oldAdPlan = oldMap.get(newAdPlan.Id);
                objChange = new ChangedAdPlan(oldAdPlan, newAdPlan);
                
                if(
                    objChange.notEquals('RadioSpend__c') ||
                    objChange.notEquals('DigitalSpend__c') ||
                    objChange.notEquals('OutdoorSpend__c') ||
                    objChange.notEquals('PrintSpend__c') ||
                    objChange.notEquals('ProductionMiscellaneousSpend__c') ||
                    objChange.notEquals('TelevisionSpend__c') ||
                    objChange.notEquals('TourDigitalSpend__c') ||
                    objChange.notEquals('TourOtherSpend__c') || 
                    objChange.notEquals('LNEAdPlanBudget__c')
                ) {          
                  if(newAdPlan.Event__c != null){
                    if(LNE_FinancialCalculator.runAdPLanLECalculation == False){
                        LNE_FinancialCalculator.runAdPLanLECalculation = True;
                    }
                    listOfRelatedEventIds.add(newAdPlan.Event__c);
                  }
                }
            }
            LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);
        }
        return changedLedgers;
        
    }

    /**
     *  US 691 - Recalculates for deleted AdPlans
     *  @param AdPlan[] - list of deleted AdPlans.
     *  @return AdPlan[] - list of AdPlans updated.
    **/
    
     public static AdPlan__c[] execute( AdPlan__c[] deletedList ){
        List<AdPlan__c> ChangedAdPlans = new List<AdPlan__c>();
        Set<Id> listOfRelatedEventIds = new Set<Id>();

        for (AdPlan__c deletedAdPlan : deletedList){
            if (deletedAdPlan.Event__c != null) {
                listOfRelatedEventIds.add(deletedAdPlan.Event__c);    
            }
            ChangedAdPlans.add(deletedAdPlan);
        }
        
        LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

        return ChangedAdPlans;
    }
    
    /**
     *  US 691 - Internal class to represent the changes from the object.
    **/
    class ChangedAdPlan extends LNE_SObjectChange {
        
        ChangedAdPlan( AdPlan__c oldObject, AdPlan__c newObject ){
            super( oldObject, newObject );
        }
        
        AdPlan__c getNewAdPlan(){
            return( (AdPlan__c)this.newObject );
        }
    }
}