src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>DigitalSpendPercent__c</fullName>
        <formula>DigitalSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DigitalSpend__c</fullName>
        <label>Digital Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LNEAdPlanBudget__c</fullName>
        <label>LNE Ad Plan Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LNESpend__c</fullName>
        <label>LNE Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNEBudget__c</fullName>
        <label>Non-LNE Budget</label>
        <summarizedField>NonLNEBudget__c.Budget__c</summarizedField>
        <summaryForeignKey>NonLNEBudget__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNESpend__c</fullName>
        <label>Non-LNE Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OutdoorSpendPercent__c</fullName>
        <formula>OutdoorSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outdoor Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OutdoorSpend__c</fullName>
        <label>Outdoor Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Outdoor</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PrintSpendPercent__c</fullName>
        <formula>PrintSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Print Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PrintSpend__c</fullName>
        <label>Print Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Print</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProductionMiscellaneousSpendPercent__c</fullName>
        <formula>ProductionMiscellaneousSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production/Miscellaneous Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProductionMiscellaneousSpend__c</fullName>
        <label>Production/Miscellaneous Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Production/Miscellaneous</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RadioSpendPercent__c</fullName>
        <formula>RadioSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Radio Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RadioSpend__c</fullName>
        <label>Radio Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Radio</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RemainingLNEBudget__c</fullName>
        <formula>LNEAdPlanBudget__c -  TotalLNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RemainingNonLNEBudget__c</fullName>
        <formula>NonLNEBudget__c -  NonLNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Non-LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TelevisionSpendPercent__c</fullName>
        <formula>TelevisionSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Television Spend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TelevisionSpend__c</fullName>
        <label>Television Spend</label>
        <summarizedField>Advertisement__c.NetCostToAdPlan__c</summarizedField>
        <summaryFilterItems>
            <field>Advertisement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Television</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Advertisement__c.HasNonLNEBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Advertisement__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TourDigitalSpendPercent__c</fullName>
        <formula>TourDigitalSpend__c / (LNESpend__c + TourSpend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tour Digital Spend %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TourDigitalSpend__c</fullName>
        <label>Tour Digital Spend</label>
        <summarizedField>TourCampaignAdPlan__c.AllocatedAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaignAdPlan__c.TourCampaignType__c</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaignAdPlan__c.HasNonLNETourBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaignAdPlan__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TourSpend__c</fullName>
        <label>Tour Spend</label>
        <summarizedField>TourCampaignAdPlan__c.AllocatedAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaignAdPlan__c.HasNonLNETourBudget__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaignAdPlan__c.AdPlan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NonLNEBudget__c.object
<CustomObject>
    <description>Marketing budgets funded by 3rd-party sponsors</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Non-LNE Budgets</relationshipLabel>
        <relationshipName>Non_LNE_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non-LNE Budget</label>
    <nameField>
        <displayFormat>NLB-{000000}</displayFormat>
        <label>Non-LNE Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-LNE Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>DigitalSpendPercent__c</fullName>
        <formula>DigitalSpend__c/ LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Spend %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DigitalSpend__c</fullName>
        <label>Digital Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LNESpend__c</fullName>
        <label>LNE Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNEBudget__c</fullName>
        <label>Non-LNE Budget</label>
        <summarizedField>NonLNETourBudget__c.Budget__c</summarizedField>
        <summaryForeignKey>NonLNETourBudget__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNESpend__c</fullName>
        <label>Non-LNE Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RemainingLNEBudget__c</fullName>
        <formula>LNEMarketingBudget__c -  LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RemainingNonLNEBudget__c</fullName>
        <formula>NonLNEBudget__c -  NonLNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Non-LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_LocalPlanTab_CX.cls
/**
 *  Controller for the LNE_LocalPlanTab page - shown at the settlement app, plan tab.
 *  @author Vinay Kanuganti
 *  @see US146
 **/
public class LNE_LocalPlanTab_CX {
    private final SObject parent;

    public String adPlanId {get;set;}
    public AdPlan__c adPlanMetrics {get;set;}

    public LNE_LocalPlanTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        adPlanId = parent.Id;
        getAdPlan();
    }
    
    public PageReference getAdPlan(){
        adPlanMetrics = [select Id, LNEAdPlanBudget__c, LNESpend__c, TourSpend__c, RemainingLNEBudget__c, NonLNESpend__c, NonLNEBudget__c
                                , RemainingNonLNEBudget__c, RadioSpend__c, RadioSpendPercent__c, DigitalSpend__c
                                , DigitalSpendPercent__c, TelevisionSpend__c, TelevisionSpendPercent__c, PrintSpend__c
                                , PrintSpendPercent__c, OutdoorSpend__c, OutdoorSpendPercent__c, ProductionMiscellaneousSpend__c
                                , ProductionMiscellaneousSpendPercent__c, Tour__c, TourDigitalSpend__c, TourDigitalSpendPercent__c
                                , TourOtherSpend__c, TourOtherSpendPercent__c 
            from AdPlan__c where Id = :adPlanId][0];
        return null;
    }
}