src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Advertisement__c.object
<CustomObject>
    <description>Ads that are planned to be run as part of a marketing plan</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Advertisements</relationshipLabel>
        <relationshipName>Advertisements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Advertisement</label>
    <nameField>
        <displayFormat>Adv-{000000}</displayFormat>
        <label>Advertisement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertisements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdvertisingBudget__c</fullName>
        <label>Advertising Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BookingHouseNut__c</fullName>
        <label>Booking House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementHouseNut__c</fullName>
        <label>Settlement House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RelatedContra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contra</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Related Contra (GL Account)</relationshipLabel>
        <relationshipName>GLAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>COGSAtFlash__c</fullName>
        <label>COGS at Flash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAtFlash__c</fullName>
        <formula>/* if there are roll up contra at flash values, use that, otherwise, calculate it
   Flash Contra Amount + ((Flash Contra % + Flash 3rd Party %) * Flash Gross Revenue)
 */
if( RollUpCount__c &gt; 0,
	RollUpContraAtFlash__c,
	FlashContraAmount__c * ((  FlashContraPercent__c  *   Flash3rdPartyPercent__c ) *  FlashGrossRevenue__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contra at Flash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentFlash__c</fullName>
        <label>Current Flash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FlashGrossRevenue__c</fullName>
        <label>Flash Gross Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FlashNetRevenue__c</fullName>
        <formula>FlashGrossRevenue__c -  ContraAtFlash__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flash Net Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InHouseRateType__c</fullName>
        <label>In House Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfferRateType__c</fullName>
        <label>Offer Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoterAmountRate__c</fullName>
        <label>Promoter Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PromoterAmount__c</fullName>
        <label>Promoter Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettleAtActual__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Settle At Actual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SettlementRateType__c</fullName>
        <label>Settlement Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(TourCampaign__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_LedgerEntryUtil.cls
/**
 *  Logic for creating various ledger entries
 *  @author Phil Rymek
 **/

public with sharing class LNE_LedgerEntryUtil {
    
    private static final String LEDGER_50499 = '50499';
    private static final String LEDGER_X50148X = 'X50148X';
    private static final String RATE_TYPE_FLAT = 'Flat';

    private static final Id RT_ANCILLARY_ID;
    private static final Id RT_COGS_ID;
    private static final Id RT_CONTRA_ID;
    private static final Id RT_EXPENSES_ID;

    static {

        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new List<String> {
            'LedgerEntry__c.Ancillary',
            'LedgerEntry__c.COGS',
            'LedgerEntry__c.Contra',
            'LedgerEntry__c.Expenses'
        });

        RT_ANCILLARY_ID = recordTypeMap.get('LedgerEntry__c.Ancillary'); 
        RT_COGS_ID = recordTypeMap.get('LedgerEntry__c.COGS'); 
        RT_CONTRA_ID = recordTypeMap.get('LedgerEntry__c.Contra'); 
        RT_EXPENSES_ID = recordTypeMap.get('LedgerEntry__c.Expenses'); 

    }
    
    public static List<LedgerEntry__c> create50499(List<Id> eventIds) {
        List<Event__c> events = getEvents(eventIds);
        return create50499(events);
    }
    
    public static List<LedgerEntry__c> create50499(List<Event__c> events) {

		List<LedgerEntry__c> entries = new List<LedgerEntry__c>();
        GLAccount__c glAccount = getGLAccount(LEDGER_50499);
        Set<Id> cannot50499 = get50499Omissions(events);
        String externalIdDelimiter = 
            DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;
        
        if(glAccount != null) {
            for(Event__c evt : events) {
                if(!cannot50499.contains(evt.Id)) {
                    entries.add(getEntry50499(evt, glACcount, RT_EXPENSES_ID, externalIdDelimiter));
                }
            }          
        }

        upsert entries ExternalId__c;
        return entries;
    }
    
    public static void delete50499(List<Id> eventIds) {
        GLAccount__c glAccount = getGLAccount(LEDGER_50499);
        
        if(glAccount != null) {
            delete [SELECT Id 
                      FROM LedgerEntry__c 
                     WHERE GLAccount__c = :glAccount.Id AND 
                           Event__c in :eventIds];   
        }
    }
    
    public static List<LedgerEntry__c> createX50148X(List<Id> eventIds) {
        List<Event__c> events = getEvents(eventIds);
        return createX50148X(events);
    }
    
    public static List<LedgerEntry__c> createX50148X(List<Event__c> events) {

        GLAccount__c glAccount = getGLAccount(LEDGER_X50148X);
        List<LedgerEntry__c> entries = new List<LedgerEntry__c>();
        String externalIdDelimiter = 
            DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;      
        
        if(glAccount != null) {
            for(Event__c evt : events) {
                entries.add(getEntryX50148X(evt, glACcount, RT_EXPENSES_ID, externalIdDelimiter));
            }          
        }

        upsert entries ExternalId__c;
        return entries;
    }
    
    public static void deleteX50148X(List<Id> eventIds) {
        GLAccount__c glAccount = getGLAccount(LEDGER_X50148X);
        
        if(glAccount != null) {
            List<LedgerEntry__c> toDelete = new List<LedgerEntry__c>();
            List<LedgerEntry__c> toUpdate = new List<LedgerEntry__c>();
            List<LedgerEntry__c> entries =
                [SELECT Id, Event__r.SettlementStarted__c
                   FROM LedgerEntry__c 
                  WHERE GLAccount__c = :glAccount.Id AND Event__c in :eventIds];  
                  
            for(LedgerEntry__c entry : entries) {
                if(entry.Event__r.SettlementStarted__c) {
                    entry.PromoterAmount__c = 0;
                    entry.PromoterAmountRate__c = 0;
                    entry.OfferRate__c = 0;
                    toUpdate.add(entry);
                } else {
                    toDelete.add(entry);
                }
            }
            
            update toUpdate;
            delete toDelete;
        }
    }

    private static LedgerEntry__c getEntryX50148X(Event__c evt, GLAccount__c glAccount, Id recordTypeId, String externalIdDelimiter) {
        return new LedgerEntry__c(
			GLAccount__c = glAccount.Id,
			OfferRateType__c = RATE_TYPE_FLAT,
			SettlementRateType__c = RATE_TYPE_FLAT,
			OfferRate__c = evt.BookingHouseNut__c,
			HouseNut__c = true,
			PromoterAmountRate__c = evt.SettlementHouseNut__c,
			RecordTypeId = recordTypeId,
			Event__c = evt.Id,
            SettleAtActual__c = false,
			ExternalId__c = evt.Name + externalIdDelimiter + glAccount.GLCode__c
        );
    }   
    
    private static LedgerEntry__c getEntry50499(Event__c evt, GLAccount__c glAccount, Id recordTypeId, String externalIdDelimiter) {
        return new LedgerEntry__c(
			GLAccount__c = glAccount.Id,
			OfferRateType__c = RATE_TYPE_FLAT,
			OfferRate__c = evt.AdvertisingBudget__c,
			InHouseRateType__c = RATE_TYPE_FLAT,
            InHouseRate__c = evt.AdvertisingBudget__c,
			RecordTypeId = recordTypeId,
			Event__c = evt.Id,
			ExternalId__c = evt.Name + externalIdDelimiter + glAccount.GLCode__c
        );
    }    
    
    private static List<Event__c> getEvents(List<Id> eventIds) {
        return [SELECT Id,
                       Name,
                       AdvertisingBudget__c,
                       BookingHouseNut__c,
                       SettlementHouseNut__c
                  FROM Event__c
                 WHERE Id in :eventIds];
    }
    
    private static GLAccount__c getGLAccount(String glCode) {
        Map<String,GLAccount__c> codeToAccount = LNE_Util.refreshGLAccountCache();
            
        if(codeToAccount.isEmpty()) {
            return null;
        }
        
        return codeToAccount.get(glCode);
    }
    
    private static Set<Id> get50499Omissions(List<Event__c> events) {
        Set<Id> cannot50499 = new Set<Id>();
        
        List<Advertisement__c> ads = 
            [SELECT AdPlan__r.Event__c 
               FROM Advertisement__c
              WHERE AdPlan__r.Event__c in :events];
              
        List<TourCampaignAdPlan__c> tcaps =
            [SELECT AdPlan__r.Event__c 
               FROM TourCampaignAdPlan__c
              WHERE AdPlan__r.Event__c in :events];
              
        for(Advertisement__c ad : ads) {
            cannot50499.add(ad.AdPlan__r.Event__c);
        }
        
        for(TourCampaignAdPlan__c tcap : tcaps) {
            cannot50499.add(tcap.AdPlan__r.Event__c);
        }
              
        return cannot50499;
    }

    /**
    * Copies various amounts to the Current Flash
    *
    * @param eventId ID - the Id of the parent Event__c record
    **/
    public static void copyToFlash(Id eventId) {

        List<LedgerEntry__c> entries = new List<LedgerEntry__c>();
        for (LedgerEntry__c entry : [
            select 
                COGSAtFlash__c,
                ContraAtFlash__c,
                CurrentFlash__c,
                FlashGrossRevenue__c,
                FlashNetRevenue__c,
                GLAccount__r.Type__c,
                RecordTypeId
            from LedgerEntry__c
            where Event__c = :eventId
            and RecordTypeId in (:RT_ANCILLARY_ID, :RT_COGS_ID, :RT_CONTRA_ID)
        ]) {

            if (entry.RecordTypeId == RT_ANCILLARY_ID) {
                entry.CurrentFlash__c = entry.GLAccount__r.Type__c == 'Contra'
                    ? entry.FlashGrossRevenue__c
                    : entry.FlashNetRevenue__c;
                entries.add(entry);
            }
            else if (entry.RecordTypeId == RT_COGS_ID && hasNonZeroValue(entry.COGSAtFlash__c)) {
                entry.CurrentFlash__c = entry.COGSAtFlash__c;
                entries.add(entry);
            }
            else if (entry.RecordTypeId == RT_CONTRA_ID && hasNonZeroValue(entry.ContraAtFlash__c)) {
                entry.CurrentFlash__c = entry.ContraAtFlash__c;
                entries.add(entry);
            }

        }

        if (!entries.isEmpty()) {
            Database.update(entries, false);
        }

    }

    private static Boolean hasNonZeroValue(Decimal d) {
        return d != null && d != 0;
    }

}