src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PromoScale__c.object
<CustomObject>
    <description>Promo information related to the ticket scale</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Promo Scales</relationshipLabel>
        <relationshipName>PromoScales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TicketScale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Scale</label>
        <referenceTo>TicketScale__c</referenceTo>
        <relationshipLabel>Promo Scales</relationshipLabel>
        <relationshipName>Promo_Scales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promo Scale</label>
    <nameField>
        <label>Promo Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_MarketingPromotionsTab_CX.cls
/**
 * Created by JK on 12/11/16.
 */

global with sharing class LNE_MarketingPromotionsTab_CX {

    @testVisible
    private AdPlan__c adPlan{get; set;}
    @testVisible
    private List<TicketScale__c> ticketScales{get; set;}
    @testVisible
    private List<PromoScale__c> promoScales{get; set;}

    public LNE_MarketingPromotionsTab_CX(ApexPages.StandardController controller){

        adPlan = [Select Id, Event__c, Event__r.Status__c from AdPlan__c where Id = :controller.getRecord().Id];
        promoScales = [Select Name, Description__c, Price__c, TicketScale__c from PromoScale__c where AdPlan__c = :adPlan.Id];

        String stageType;

        if(LNE_Constants.TICKET_SCALE_PLAN_EVENT_STATUSES.contains(adPlan.Event__r.Status__c)){
            stageType = LNE_Constants.TICKET_SCALE_STAGE_TYPE_PLAN;
        }else if(LNE_Constants.TICKET_SCALE_PROJECTION_EVENT_STATUSES.contains(adPlan.Event__r.Status__c)){
            stageType = LNE_Constants.TICKET_SCALE_STAGE_TYPE_PROJECTION;
        }

        ticketScales = [Select Id, Name, Price__c, PriceLevel__c, Notes__c, Event__c, StageType__c from TicketScale__c where Event__c != null And Event__c = :adPlan.Event__c And StageType__c = :stageType];

    }

    public String getAdPlan_json() {
        return JSON.serialize(adPlan);
    }

    public String getTicketScales_json() {
        return JSON.serialize(ticketScales);
    }

    public String getPromoScales_json() {
        return JSON.serialize(promoScales);
    }

    /**
     * Saves a promoScale
     * @param promoScale (PromoScale__c) - promo scale to save
     * @throws DMLException
     **/
    @RemoteAction
    global static PromoScale__c savePromoScale(PromoScale__c promoScale){
        upsert promoScale;
        return(promoScale);
    }
}