src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>AdPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_TourCampaignAdPlan_T.cls
/**
 *  TourCampaignAdPlan__c trigger helper
 *  @author Phil Rymek <prymek@salesforce.com>
 **/
public class LNE_TourCampaignAdPlan_T {

    public static void onInsert(List<TourCampaignAdPlan__c> tcaps) {
        List<TourCampaignAdPlan__c> needsLedgerRemoval = new List<TourCampaignAdPlan__c>();
        
        for(TourCampaignAdPlan__c tcap : tcaps) {
            if(tcap.AllocatedAmount__c != null) {
                needsLedgerRemoval.add(tcap);
            }
        }
        
        if(!needsLedgerRemoval.isEmpty()) {
            removeLedgerEntry50499(needsLedgerRemoval);
        }        
    }
    
    public static void onUpdate(Map<Id, TourCampaignAdPlan__c> old, List<TourCampaignAdPlan__c> tcaps) {
        List<TourCampaignAdPlan__c> needsLedgerRemoval = new List<TourCampaignAdPlan__c>();
        TourCampaignAdPlan__c previous;
        
        for(TourCampaignAdPlan__c tcap : tcaps) {
            previous = old.get(tcap.Id);
            
            if(tcap.AllocatedAmount__c != previous.AllocatedAmount__c && tcap.AllocatedAmount__c != null) {
                needsLedgerRemoval.add(tcap);
            }
        }
        
        if(!needsLedgerRemoval.isEmpty()) {
            removeLedgerEntry50499(needsLedgerRemoval);
        }         
    }

    private static void removeLedgerEntry50499(List<TourCampaignAdPlan__c> tcaps) {
        List<Id> eventIds = new List<Id>();
        
        List<TourCampaignAdPlan__c> withEvents = 
            [SELECT AdPlan__r.Event__c 
               FROM TourCampaignAdPlan__c
              WHERE Id in :tcaps AND AdPlan__r.Event__c != null];
            
        for(TourCampaignAdPlan__c tcap : withEvents) {
            eventIds.add(tcap.AdPlan__r.Event__c);
        }
        
        LNE_LedgerEntryUtil.delete50499(eventIds);
    }

}