src/objects/AdPlan__c.object
<CustomObject>
    <description>Marketing plan for events</description>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Ad Plans</relationshipLabel>
        <relationshipName>Ad_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NonLNETourBudget__c.object
<CustomObject>
    <description>Tour marketing budgets funded by 3rd-party sponsors</description>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Non-LNE Tour Budgets</relationshipLabel>
        <relationshipName>NonLNETourBudgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sponsor does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Sponsor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Non-LNE Tour Budgets</relationshipLabel>
        <relationshipName>NonLNETourBudgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-LNE Tour Budget</label>
    <nameField>
        <displayFormat>NLTB-{000000}</displayFormat>
        <label>Non-LNE Tour Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-LNE Tour Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Non-LNE Tour Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NonLNETourBudget__c.Tour__c</field>
                <operation>equals</operation>
                <valueField>$Source.Tour__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NonLNETourBudget__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>TourCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FBEvent - buyticketslink</fullName>
                </value>
                <value>
                    <fullName>FBEvent - description</fullName>
                </value>
                <value>
                    <fullName>FBX</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page image</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page link</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page video</fullName>
                </value>
                <value>
                    <fullName>Paid - dark post</fullName>
                </value>
                <value>
                    <fullName>Paid - link post</fullName>
                </value>
                <value>
                    <fullName>Paid - Lncom</fullName>
                </value>
                <value>
                    <fullName>Paid - photo</fullName>
                </value>
                <value>
                    <fullName>Paid - promotion</fullName>
                </value>
                <value>
                    <fullName>Paid - Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Paid - text only</fullName>
                </value>
                <value>
                    <fullName>Paid - video</fullName>
                </value>
                <value>
                    <fullName>Advertising Materials Production</fullName>
                </value>
                <value>
                    <fullName>Agency Commission</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Distribution</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Production</fullName>
                </value>
                <value>
                    <fullName>Graphic/Digital Design</fullName>
                </value>
                <value>
                    <fullName>National Allocation - Misc</fullName>
                </value>
                <value>
                    <fullName>Press Conference</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Tour Launch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Rich Media</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AdPlan__c</fullName>
        <label>Ad Plan</label>
        <referenceTo>AdPlan__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plans</relationshipLabel>
        <relationshipName>TourCampaignAdPlans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HasNonLNETourBudget__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the Tour Campaign Ad Plan is associated with a tour campaign that has a Non-LNE Tour Budget.
assigned through apex
and used because a roll up summary cannot use formula fields.</description>
        <label>Has Non-LNE Tour Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <formula>TourCampaign__r.NonLNETourBudget__r.Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-LNE Tour Budget</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <label>Sponsor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaignType__c</fullName>
        <description>Filled through apex, as the RecordType name of the associated Tour Campaign.
Used because RollUpSummaries cannot use formula fields</description>
        <label>Tour Campaign Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(TourCampaign__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_TourLogic_T.cls
/** 
 *  Trigger logic to check for managing Tour Campaign-Ad Plan records 
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 *  @author Paul Roth <proth@salesforce.com>
 *  @see US689 / US146
 **/
public class LNE_TourLogic_T {
    
    /**
    *  Automatically creates new Tour Campaign-Ad Plan records on TourCampaign__c insert.
    *  This needs to run ONLY on AFTER insert of TourCampaign__c
    *  @param newList TourCampaign__c[]
    **/
    public static void createTourCampaignAdPlanRecords(TourCampaign__c[] newList){
        Set<Id> tourIDs = new Set<Id>();

        for (TourCampaign__c tc : newList) {
            if (tc.Tour__c != null) {
                tourIDs.add(tc.Tour__c);
            }
        }

        if (!tourIDs.isEmpty()) {
            
            //-- map the recordType Id to the name of the recordType for all tour campaigns
            Map<Id,String> tourCampaignRecordTypes = new Map<Id,String>();
            for( RecordType tourCampaignRT : [
                SELECT id, name
                FROM recordType
                WHERE SObjectType = 'TourCampaign__c'
            ]){
                tourCampaignRecordTypes.put( tourCampaignRT.Id, tourCampaignRT.Name );
            }
            
            //-- @TODO: investigate this further
            List<TourCampaignAdPlan__c> toInsert = new List<TourCampaignAdPlan__c>();
            Map<Id, Tour__c> tourMap = new Map<Id, Tour__c>([SELECT Id, (SELECT Tour__c FROM Ad_Plans__r) FROM Tour__c WHERE Id IN :tourIDs]);
            
            //-- Create a TourCampaignAdPlan (junction between touring and ad plan)
            //-- Once a tour campaign is associated to a tour
            //-- create a junction object (TourCampaignAdPlan__c) between the tour campaign and associated ad plans
            
            String tourCampaignType;
            for (TourCampaign__c tc : newList) {
                //-- determine the recordTypeName for the tourCampaign
                if( tc.RecordTypeId != null && tourCampaignRecordTypes.containsKey( tc.RecordTypeId )){
                    tourCampaignType = tourCampaignRecordTypes.get( tc.RecordTypeId );
                }
                for (AdPlan__c ap : tourMap.get(tc.Tour__c).Ad_Plans__r) {
                    TourCampaignAdPlan__c tcap = new TourCampaignAdPlan__c(
                        AdPlan__c=ap.Id,
                        TourCampaign__c=tc.Id,
                        TourCampaignType__c=tourCampaignType,
                        HasNonLNETourBudget__c = (tc.NonLNETourBudget__c != null),
                        Sponsor__c = tc.NonLNETourBudget__r.Type__r.Name
                    );
                    toInsert.add(tcap);
                }
            }

            if (!toInsert.isEmpty()) {
                insert toInsert;
            }
        }
    }
}