src/objects/ArtistRetroStepUpDetail__c.object
<CustomObject>
    <fields>
        <fullName>BackendPotentialNonFormula__c</fullName>
        <label>Backend Potential (Non Formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BackendPotential__c</fullName>
        <formula>CASE(Deal__r.DealType__c,
&quot;Retro Gross Deal&quot;,
  IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

    IF(Deal__r.Event__r.SelloutPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SelloutPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.NetGrossPotential__c * BackEndPct__c,

      0),


    IF(Deal__r.Event__r.NetGrossPotential__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.NetGrossPotential__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.NetGrossPotential__c * BackEndPct__c,

      0)),

&quot;Retro Net Deal&quot;,
  IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

    IF(Deal__r.Event__r.SelloutPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SelloutPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.NetPotPotential__c * BackEndPct__c,

      0),


    IF(Deal__r.Event__r.NetPotPotential__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.NetPotPotential__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.NetPotPotential__c * BackEndPct__c,

      0)),


&quot;Step Up Gross Deal&quot;,
  IF(Deal__r.Event__r.NetGrossPotential__c &gt;= StartingRange__c,

    (IF(Deal__r.Event__r.NetGrossPotential__c &lt;= EndingRange__c || EndingRange__c = 0,
       Deal__r.Event__r.NetGrossPotential__c,
       EndingRange__c
     ) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

    0),


&quot;Step Up Net Deal&quot;,
  IF(Deal__r.Event__r.NetPotPotential__c &gt;= StartingRange__c,

    (IF(Deal__r.Event__r.NetPotPotential__c &lt;= EndingRange__c || EndingRange__c = 0,
       Deal__r.Event__r.NetPotPotential__c,
       EndingRange__c
     ) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

    0),


0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Backend Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Artist Retro/Step Up Details</relationshipLabel>
        <relationshipName>Artist_Retro_Step_Up_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectedBackendNonFormula__c</fullName>
        <label>Projected Backend (Non Formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedBackend__c</fullName>
        <formula>CASE(Deal__r.DealType__c,
&quot;Retro Gross Deal&quot;,
  IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

    IF(Deal__r.Event__r.ProjectedPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.ProjectedPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.ProjectedNetGross__c * BackEndPct__c,

      0),


    IF(Deal__r.Event__r.ProjectedNetGross__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.ProjectedNetGross__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.ProjectedNetGross__c * BackEndPct__c,

      0)),


&quot;Retro Net Deal&quot;,
  IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

    IF(Deal__r.Event__r.ProjectedPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.ProjectedPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.ProjectedNetPot__c * BackEndPct__c,

      0),


    IF(Deal__r.Event__r.ProjectedNetPot__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.ProjectedNetPot__c &lt;= EndingRange__c || EndingRange__c = 0),

      Deal__r.Event__r.ProjectedNetPot__c * BackEndPct__c,

      0)),


&quot;Step Up Gross Deal&quot;,
  IF(Deal__r.Event__r.ProjectedNetGross__c &gt;= StartingRange__c,

    (IF(Deal__r.Event__r.ProjectedNetGross__c &lt;= EndingRange__c || EndingRange__c = 0,
       Deal__r.Event__r.ProjectedNetGross__c,
       EndingRange__c
     ) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

    0),


&quot;Step Up Net Deal&quot;,
  IF(Deal__r.Event__r.ProjectedNetPot__c &gt;= StartingRange__c,

    (IF(Deal__r.Event__r.ProjectedNetPot__c &lt;= EndingRange__c || EndingRange__c = 0,
       Deal__r.Event__r.ProjectedNetPot__c,
       EndingRange__c
     ) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

    0),


0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Projected Backend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementBackendNonFormula__c</fullName>
        <label>Settlement Backend (Non Formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementBackend__c</fullName>
        <formula>CASE(Deal__r.DealType__c,
&quot;Retro Gross Deal&quot;,
IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

IF(Deal__r.Event__r.SettlementPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SettlementPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

Deal__r.Event__r.SettlementNetGross__c * BackEndPct__c,

0),


IF(Deal__r.Event__r.SettlementNetGross__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SettlementNetGross__c &lt;= EndingRange__c || EndingRange__c = 0),

Deal__r.Event__r.SettlementNetGross__c * BackEndPct__c,

0)),


&quot;Retro Net Deal&quot;,
IF(ISPICKVAL(Deal__r.DealApplicationType__c, &quot;Paid Tickets&quot;),

IF(Deal__r.Event__r.SettlementPaidTickets__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SettlementPaidTickets__c &lt;= EndingRange__c || EndingRange__c = 0),

Deal__r.Event__r.SettlementNetPot__c * BackEndPct__c,

0),


IF(Deal__r.Event__r.SettlementNetPot__c &gt;= StartingRange__c &amp;&amp; (Deal__r.Event__r.SettlementNetPot__c &lt;= EndingRange__c || EndingRange__c = 0),

Deal__r.Event__r.SettlementNetPot__c * BackEndPct__c,

0)),


&quot;Step Up Gross Deal&quot;,
IF(Deal__r.Event__r.SettlementNetGross__c &gt;= StartingRange__c,

(IF(Deal__r.Event__r.SettlementNetGross__c &lt;= EndingRange__c || EndingRange__c = 0,
Deal__r.Event__r.SettlementNetGross__c,
EndingRange__c
) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

0),


&quot;Step Up Net Deal&quot;,
IF(Deal__r.Event__r.SettlementNetPot__c &gt;= StartingRange__c,

(IF(Deal__r.Event__r.SettlementNetPot__c &lt;= EndingRange__c || EndingRange__c = 0,
Deal__r.Event__r.SettlementNetPot__c,
EndingRange__c
) - StartingRange__c + IF(StartingRange__c = 0, 0, 1)) * BackEndPct__c,

0),


0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Settlement Backend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Artist Retro/Step Up Detail</label>
    <nameField>
        <displayFormat>ARSUD-{000000}</displayFormat>
        <label>Artist Retro/Step Up Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Artist Retro/Step Up Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>BackendPotential__c</fullName>
        <label>Backend Potential</label>
        <summarizedField>ArtistRetroStepUpDetail__c.BackendPotentialNonFormula__c</summarizedField>
        <summaryForeignKey>ArtistRetroStepUpDetail__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectedBackend__c</fullName>
        <label>Projected Backend</label>
        <summarizedField>ArtistRetroStepUpDetail__c.ProjectedBackendNonFormula__c</summarizedField>
        <summaryForeignKey>ArtistRetroStepUpDetail__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SettlementBackend__c</fullName>
        <label>Settlement Backend</label>
        <summarizedField>ArtistRetroStepUpDetail__c.SettlementBackendNonFormula__c</summarizedField>
        <summaryForeignKey>ArtistRetroStepUpDetail__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_ArtistRetroCopy_T.cls
/**
 *  Copys formula fields to non formula fields to use in rollup summaries on the Deal__c object.
 *  @author John Casimiro <jcasimiro@salesforce.com>
 **/
 
public class LNE_ArtistRetroCopy_T {
    public static ArtistRetroStepUpDetail__c[] execute( ArtistRetroStepUpDetail__c[] newList){
    	ArtistRetroStepUpDetail__c[] results = new ArtistRetroStepUpDetail__c[]{};
   
		if ( newList == null ){
			return( results );
		}
		
		for (ArtistRetroStepUpDetail__c ar : newList){
		    ar.BackendPotentialNonFormula__c = ar.BackendPotential__c;
		    ar.ProjectedBackendNonFormula__c = ar.ProjectedBackend__c;
		    ar.SettlementBackendNonFormula__c = ar.SettlementBackend__c;
		    results.add(ar);
		}
	    
	    return results;
    }
}