src/objects/ArtistRetroStepUpDetail__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Artist Retro/Step Up Details</relationshipLabel>
        <relationshipName>Artist_Retro_Step_Up_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Artist Retro/Step Up Detail</label>
    <nameField>
        <displayFormat>ARSUD-{000000}</displayFormat>
        <label>Artist Retro/Step Up Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Artist Retro/Step Up Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>DealApplicationType__c</fullName>
        <label>Deal Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DealType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>To Be Shared Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>CoPromoter</fullName>
        <active>true</active>
        <label>Co-Promoter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DealSettlementLedger__c.object
<CustomObject>
    <description>Junction object linking the Deal with Ledger Entries so settlement values can be planned and settled upon per Deal</description>
    <fields>
        <fullName>CurrentAmountAtProjectionNF__c</fullName>
        <label>Current Amount At Projection (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentAmountAtSelloutNF__c</fullName>
        <label>Current Amount At Sellout (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentAmountAtSellout__c</fullName>
        <formula>IF(!Share__c, 0,
   CASE(LedgerEntry__r.RecordType.DeveloperName,
      &quot;COGS&quot;,
         IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;, LedgerEntry__r.COGSAtSellout__c * -1,LedgerEntry__r.COGSAtSellout__c * -1 - LedgerEntry__r.PrimaryCoProShareAtSellout__c),
      &quot;Ancillary&quot;,
         IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,LedgerEntry__r.NetRevenueatSellout__c, LedgerEntry__r.NetRevenueatSellout__c- LedgerEntry__r.PrimaryCoProShareAtSellout__c),
      null
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Amount At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentAmountatProjection__c</fullName>
        <formula>IF(!Share__c, 0,
   CASE(LedgerEntry__r.RecordType.DeveloperName,
      &quot;COGS&quot;,
         IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;, LedgerEntry__r.COGSAtForecast__c * -1,LedgerEntry__r.COGSAtForecast__c * -1 - LedgerEntry__r.PrimaryCoProShareAtProjection__c),
      &quot;Ancillary&quot;,
         IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,LedgerEntry__r.NetRevenue__c, LedgerEntry__r.NetRevenue__c- LedgerEntry__r.PrimaryCoProShareAtProjection__c),
      null
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Amount at Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DealTypeNF__c</fullName>
        <label>Deal Type (NF)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <formula>TEXT(Deal__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Settlement Entries</relationshipLabel>
        <relationshipName>DealSettlementLedgers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventVenueOwnershipTypeNF__c</fullName>
        <label>Event Venue Ownership Type (NF)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventVenueOwnershipType__c</fullName>
        <formula>TEXT(LedgerEntry__r.Event__r.Venue__r.OwnershipType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Venue Ownership Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentAtProjectionNF__c</fullName>
        <label>Expense Adjustment At Projection (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentAtSelloutNF__c</fullName>
        <label>Expense Adjustment At Sellout (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentAtSellout__c</fullName>
        <formula>IF(!Share__c, 0,
   IF(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,
      IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c,
         LedgerEntry__r.ExpenseAdjustmentatSellout__c - LedgerEntry__r.PrimaryCoProShareAtSellout__c
      ),
      0
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentatProjection__c</fullName>
        <formula>IF(!Share__c, 0,
   IF(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,
      IF(PrimarySecondaryCoPromoter__c = &quot;Primary&quot;,
         LedgerEntry__r.ExpenseAdjustment__c,
         LedgerEntry__r.ExpenseAdjustment__c - LedgerEntry__r.PrimaryCoProShareAtProjection__c
      ),
      0
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment at Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryCoProShareAtProjectionNF__c</fullName>
        <label>Co-Pro Share At Projection (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryCoProShareAtProjection__c</fullName>
        <formula>IF(!Share__c, 0,
   IF(OR(LedgerEntry__r.RecordType.DeveloperName = &quot;Ancillary&quot;, LedgerEntry__r.RecordType.DeveloperName = &quot;COGS&quot;),
      Deal__r.AncillaryRevenue__c * CurrentAmountatProjection__c,
      IF(AND(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,  ExpenseAdjustmentatProjection__c &gt; 0),
         Deal__r.ExpenseAdjustmentProfit__c * ExpenseAdjustmentatProjection__c,
         IF(AND(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,  ExpenseAdjustmentatProjection__c &lt; 0),
            Deal__r.ExpenseAdjustmentLoss__c * ExpenseAdjustmentatProjection__c,
            0
         )
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Pro Share At Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryCoProShareAtSelloutNF__c</fullName>
        <label>Co-Pro Share At Sellout (NF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryCoProShareAtSellout__c</fullName>
        <formula>IF(!Share__c, 0,
IF(OR(LedgerEntry__r.RecordType.DeveloperName = &quot;Ancillary&quot;, LedgerEntry__r.RecordType.DeveloperName = &quot;COGS&quot;),
   /* True */
   Deal__r.AncillaryRevenue__c * CurrentAmountAtSellout__c,
   /* False */
   IF(AND(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,  ExpenseAdjustmentAtSellout__c &gt; 0),
      /* True */
      Deal__r.ExpenseAdjustmentProfit__c * ExpenseAdjustmentAtSellout__c,
      /* False */
      IF(AND(LedgerEntry__r.RecordType.DeveloperName = &quot;Expenses&quot;,  ExpenseAdjustmentAtSellout__c &lt; 0),
         /* True */
         Deal__r.ExpenseAdjustmentLoss__c * ExpenseAdjustmentAtSellout__c,
         /* False */
         0
      )
   )
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Pro Share At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoterNF__c</fullName>
        <label>Primary/Secondary Co-Promoter (NF)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimarySecondaryCoPromoter__c</fullName>
        <formula>text( Deal__r.PrimarySecondaryCoPromoter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary/Secondary Co-Promoter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeNF__c</fullName>
        <label>Type (NF)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>LedgerEntry__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Settlement-Ledger</label>
    <nameField>
        <displayFormat>DSL-{000000}</displayFormat>
        <label>Deal Settlement-Ledger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Settlement-Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_DSLFieldCopy_T.cls
/**
 *  Copys formula fields to non formula fields to use in rollup summaries on the Deal__c object.
 *  @author John Casimiro <jcasimiro@salesforce.com>
 **/
 
public class LNE_DSLFieldCopy_T {
    public static DealSettlementLedger__c[] execute( DealSettlementLedger__c[] newList){
    	DealSettlementLedger__c[] results = new DealSettlementLedger__c[]{};
   
		if ( newList == null ){
			return( results );
		}
		
		for (DealSettlementLedger__c dsl : newList){
		    dsl.CurrentAmountAtProjectionNF__c = dsl.CurrentAmountatProjection__c;
		    dsl.CurrentAmountAtSelloutNF__c = dsl.CurrentAmountAtSellout__c;
		    dsl.ExpenseAdjustmentAtProjectionNF__c = dsl.ExpenseAdjustmentatProjection__c;
		    dsl.ExpenseAdjustmentAtSelloutNF__c = dsl.ExpenseAdjustmentAtSellout__c;
		    dsl.TypeNF__c = dsl.Type__c;
		    dsl.PrimaryCoProShareAtProjectionNF__c = dsl.PrimaryCoProShareAtProjection__c;
		    dsl.PrimaryCoProShareAtSelloutNF__c = dsl.PrimaryCoProShareAtSellout__c;
		    dsl.DealTypeNF__c = dsl.DealType__c;
		    dsl.EventVenueOwnershipTypeNF__c = dsl.EventVenueOwnershipType__c;
		    dsl.PrimarySecondaryCoPromoterNF__c = dsl.PrimarySecondaryCoPromoter__c;
		    results.add(dsl);
		}
	    
	    return results;
    }
    
    /**
     *  Make dirty child objects of the Deal so rollup summary fields are updated.
     *    DealSettlementLedger__c - when every Deal is updated, update related DSLs
     *    ArtistRetroStepUpDetail__c - when Deal__c.DealType__c OR Deal__c.DealApplicationType__c are changed.
     *  @author John Casimiro <jcasimiro@salesforce.com>
     **/
    public static void recalculateDealChildren(Deal__c[] newList, Map<Id, Deal__c> oldMap){
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'Deal__c.CoPromoter'});         
        Id RT_COPROMOTER = recordTypeMap.get( 'Deal__c.CoPromoter' );  //recordtypeid for ancillary ledger entry      
    	
        set<id> dslDealIds = new set<id>();
        set<id> arsudDealIds = new set<id>();
        
        ChangedDeal cDeal;
        
        if (newList != null){
        	Deal__c oldDeal;
    		for(Deal__c d : newList){
    			if( oldMap != null && oldMap.containsKey( d.Id )){
    				cDeal = new ChangedDeal( oldMap.get( d.Id ), d );
    			} else {
    				cDeal = null;
    			}
    			
    		    if (
    		    	(cDeal == null || cDeal.notEquals( 'RecordTypeId' ) || cDeal.notEqualsStr( 'Type__c', true )) &&
    		    	d.recordtypeid == RT_COPROMOTER && !('Internal').equals( d.Type__c )
    		    ){
    		        dslDealIds.add(d.id);
    		    } else if ( cDeal == null || cDeal.notEquals( 'DealType__c' ) || cDeal.notEquals( 'DealApplicationType__c' ) ){
    		        arsudDealIds.add(d.id);
    		    }
    		}
    		
    		if (dslDealIds.size() > 0){
        		List<DealSettlementLedger__c> dsls = [select Id from DealSettlementLedger__c where Deal__c in :dslDealIds];
        		
        		if (dsls.size() > 0)
        		    update dsls;
    		}
    		
    		if(arsudDealIds.size() > 0){
    		    ArtistRetroStepUpDetail__c[] arsuds = [select Id from ArtistRetroStepUpDetail__c where Deal__c in :arsudDealIds];
    		    
    		    if (arsuds.size() > 0)
    		        update arsuds;
    		}
        }
	    
    }
    

    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedDeal extends LNE_SObjectChange {
        
        ChangedDeal( Deal__c oldObject, Deal__c newObject ){
            super( oldObject, newObject );
        }
        
        Deal__c getNewDeal(){
            return( (Deal__c)this.newObject );
        }
    }
}