src/objects/BonusDetail__c.object
<CustomObject>
    <description>Additional terms for an artist or co-promoter usually based upon ticket sales representing a bonus above a guarantee or percentage of ticket revenues</description>
    <fields>
        <fullName>BonusAmount__c</fullName>
        <label>Bonus Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BonusBase__c</fullName>
        <label>Bonus Base</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Drop Count</fullName>
                </value>
                <value>
                    <fullName>Net Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Bonus Details</relationshipLabel>
        <relationshipName>BonusDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Increment__c</fullName>
        <label>Increment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartPoint__c</fullName>
        <label>Start Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step Up</fullName>
                </value>
                <value>
                    <fullName>Retro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bonus Detail</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bonus Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>AmountRate__c</fullName>
        <label>Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BeforeAfter__c</fullName>
        <label>Before/After</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before Adjusted</fullName>
                </value>
                <value>
                    <fullName>After Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Amount Per Ticket</fullName>
                </value>
                <value>
                    <fullName>Primary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Primary Multiplier Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Multiplier Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Artist Add-On</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>FMF/Venue Charge</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Value Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Hold</fullName>
        <active>true</active>
        <description>Tentative placeholder for potential event</description>
        <label>Hold</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFeePercent__c</fullName>
        <defaultValue>0.129</defaultValue>
        <label>TM Fee %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventDeletionUtil_Test.cls
@isTest
private class LNE_EventDeletionUtil_Test {
	final static Id RT_EVENT_HOLD_ID;

	static {

		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 
			'Event__c.Hold'
		});

		RT_EVENT_HOLD_ID = recordTypeMap.get('Event__c.Hold');
	}

	@testSetup
	static void setup(){
		LNE_FinancialCalculator.currentlyRunning = true;

		LNE_TestObjectFactory.prepStandardCustomSettings();

		Event__c event = new Event__c(
	        RecordTypeId = RT_EVENT_HOLD_ID
	    );

		LNE_TestObjectFactory.createStandardDataSet(event);
	}

	class TestSettings {
		public Event__c testEvent;
		
		public TestSettings() {
			LNE_FinancialCalculator.currentlyRunning = true;
			testEvent = [SELECT Id FROM Event__c LIMIT 1];
		}
		
		public TestSettings typicalSetup(){
			return this;
			
		}
		
		public TestSettings finalize(){
			LNE_FinancialCalculator.currentlyRunning = false;
			return this;
		}
	}

	static void setupData(Event__c event) {

		LNE_FinancialCalculator.runUpdates = true;
		
		Deal__c deal = [select id from Deal__c where Type__c = 'Primary Headliner'];

		BonusDetail__c bonus = new BonusDetail__c();
		bonus.Deal__c = deal.Id;
		bonus.BonusBase__c = 'Paid Tickets';
		bonus.StartPoint__c = 1000;
		bonus.Increment__c = 10;
		bonus.BonusAmount__c = 100;
		insert bonus;
		System.assertNotEquals(null, bonus.id);
		
		EventDateTime__c evtDateTime = new EventDateTime__c(
            event__c = event.Id, 
            EventYear__c = String.valueOf(System.now().year() + 2));
        insert evtDateTime;

		LNE_FinancialCalculator.runUpdates = true;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.Event__c = event.Id;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Plan';

		TicketScale__c ticketScale2 = new TicketScale__c();
		ticketScale2.Type__c = 'Lawn';
		ticketScale2.Capacity__c = 1000;
		ticketScale2.Price__c = 100.00;
		ticketScale2.Kills__c = 0;
		ticketScale2.Comps__c = 0;
		ticketScale2.ProjectedPaidTickets__c = 950;
		ticketScale2.Event__c = event.Id;
		ticketScale2.LiftBeforeFee__c = 0;
		ticketScale2.TMFeePercent__c = 0.0;
		ticketScale2.StageType__c = 'Plan';

		TicketScale__c ticketScale3 = new TicketScale__c();
		ticketScale3.Type__c = 'Platinum';
		ticketScale3.Capacity__c = 100;
		ticketScale3.Price__c = 100.00;
		ticketScale3.Kills__c = 0;
		ticketScale3.Comps__c = 0;
		ticketScale3.ProjectedPaidTickets__c = 100;
		ticketScale3.Event__c = event.Id;
		ticketScale3.LiftBeforeFee__c = 7420.00;
		ticketScale3.TMFeePercent__c = 0.0;
		ticketScale3.StageType__c = 'Plan';

		insert new List<TicketScale__c>{ticketScale,ticketScale2,ticketScale3};

		LNE_FinancialCalculator.runUpdates = true;

		Deduction__c deduction = new Deduction__c();
		deduction.BeforeAfter__c = 'Before Adjusted';
		deduction.Event__c = event.Id;
		deduction.RateType__c = 'Primary Multiplier Tax';
		deduction.AmountRate__c = 10;

		Deduction__c deduction2 = new Deduction__c();
		deduction2.BeforeAfter__c = 'Before Adjusted';
		deduction2.Event__c = event.Id;
		deduction2.RateType__c = 'Primary Divider Tax';
		deduction2.AmountRate__c = 10;

		Deduction__c deduction3 = new Deduction__c();
		deduction3.BeforeAfter__c = 'Before Adjusted';
		deduction3.Event__c = event.Id;
		deduction3.RateType__c = 'Amount Per Ticket';
		deduction3.AmountRate__c = 10;
		deduction3.ApplyTicketScale__c = 'All Paid Tickets';

		Deduction__c deduction4 = new Deduction__c();
		deduction4.BeforeAfter__c = 'Before Adjusted';
		deduction4.Event__c = event.Id;
		deduction4.RateType__c = 'Secondary Multiplier Tax';
		deduction4.AmountRate__c = 10;

		Deduction__c deduction5 = new Deduction__c();
		deduction5.BeforeAfter__c = 'Before Adjusted';
		deduction5.Event__c = event.Id;
		deduction5.RateType__c = 'Secondary Divider Tax';
		deduction5.AmountRate__c = 10;

		Deduction__c deduction6 = new Deduction__c();
		deduction6.BeforeAfter__c = 'After Adjusted';
		deduction6.Event__c = event.Id;
		deduction6.RateType__c = 'Primary Multiplier Tax';
		deduction6.AmountRate__c = 10;

		Deduction__c deduction7 = new Deduction__c();
		deduction7.BeforeAfter__c = 'After Adjusted';
		deduction7.Event__c = event.Id;
		deduction7.RateType__c = 'Secondary Multiplier Tax';
		deduction7.AmountRate__c = 10;

		Deduction__c deduction8 = new Deduction__c();
		deduction8.BeforeAfter__c = 'After Adjusted';
		deduction8.Event__c = event.Id;
		deduction8.RateType__c = 'Amount Per Ticket';
		deduction8.AmountRate__c = 10;
		deduction8.ApplyTicketScale__c = 'All Paid Tickets';

		Deduction__c deduction9 = new Deduction__c();
		deduction9.BeforeAfter__c = 'After Adjusted';
		deduction9.Event__c = event.Id;
		deduction9.RateType__c = 'Primary Divider Tax';
		deduction9.AmountRate__c = 10;

		Deduction__c deduction10 = new Deduction__c();
		deduction10.BeforeAfter__c = 'After Adjusted';
		deduction10.Event__c = event.Id;
		deduction10.RateType__c = 'Secondary Divider Tax';
		deduction10.AmountRate__c = 10;

		insert new List<Deduction__c>{deduction,deduction2,deduction3,deduction4,deduction5,
									  deduction6,deduction7,deduction8,deduction9,deduction10};
	}

	static testMethod void testDeletion() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();

		Test.startTest();
		setupData(ts.testEvent);

		List<Event__c> events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(1, events.size());

		List<EventDateTime__c> datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(1, datetimes.size());

		List<Deduction__c> deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(10, deductions.size());

		List<TicketScale__c> ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(3, ticketScales.size());

		LNE_EventDeletionUtil.deleteEvents(events);

		events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(0, events.size());

		datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, datetimes.size());

		deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, deductions.size());

		ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, ticketScales.size());
	}

	static testMethod void testDeletion_Aura() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();

		Test.startTest();
		setupData(ts.testEvent);

		List<Event__c> events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(1, events.size());

		List<EventDateTime__c> datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(1, datetimes.size());

		List<Deduction__c> deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(10, deductions.size());

		List<TicketScale__c> ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(3, ticketScales.size());

		LNE_EventDeletionUtil.deleteHoldEvent(ts.testEvent.Id);

		events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(0, events.size());

		datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, datetimes.size());

		deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, deductions.size());

		ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, ticketScales.size());
	}

	static testMethod void testDeletion_Trigger() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();

		Test.startTest();
		setupData(ts.testEvent);

		List<Event__c> events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(1, events.size());

		List<EventDateTime__c> datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(1, datetimes.size());

		List<Deduction__c> deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(10, deductions.size());

		List<TicketScale__c> ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(3, ticketScales.size());

		delete datetimes;

		events = [SELECT Id FROM Event__c WHERE Id = :ts.testEvent.Id];
		system.assertEquals(0, events.size());

		datetimes = [SELECT Id FROM EventDateTime__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, datetimes.size());

		deductions = [SELECT Id FROM Deduction__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, deductions.size());

		ticketScales = [SELECT Id FROM TicketScale__c WHERE Event__c = :ts.testEvent.Id];
		system.assertEquals(0, ticketScales.size());
	}
}