src/objects/CatereaseEventStaging__c.object
<CustomObject>
    <description>Object to hold Event data from Caterease DB.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>actguests__c</fullName>
        <label>actguests</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gtdguests__c</fullName>
        <label>gtdguests</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>plnguests__c</fullName>
        <label>plnguests</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caterease Event - Staging</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caterease Events - Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LNE_CatereaseEventStaging_T.cls
/** 
 * <p>Assumes that the trigger will be run on a before update or before insert</p>
 *  @author Henry Akpala 
 *   
 **/
public class LNE_CatereaseEventStaging_T {
  
    
  /**
   *  Look for any existing LNE_CatereaseEventStaging__c records
   *  @param newList CatereaseEventStaging__c[]
   *  @param oldMap Map<Id,CatereaseEventStaging__c>
   *  @return CatereaseEventStaging__c[] - list of CatereaseEventStaging records.
  **/
  
    public static CatereaseEventStaging__c[] execute(List<CatereaseEventStaging__c> newList, Map<Id, CatereaseEventStaging__c> oldMap){
        if(newList.size()>0) {
            for (CatereaseEventStaging__c c : newList){
                    if (oldMap != null){
                        CatereaseEventStaging__c ces = oldMap.get(c.Id);
                        Integer agst = Integer.valueOf(c.actguests__c);
                        
                        //Integer ggst = Integer.valueOf(c.gtdguests__c);
                        //Integer pgst = Integer.valueOf(c.plnguests__c);
                        
                        c.actguests__c = (agst == 0 && ces.actguests__c!=0) ? c.actguests__c : ces.actguests__c;
                        /*   
                            if(c.actguests__c!=0 && ces.actguests__c==0){}
                            if(c.gtdguests__c!=0 && ces.gtdguests__c==0){}
                            if(c.plnguests__c!=0 && ces.plnguests__c==0){} 
                        
                        if (c.Status__c =='Cancelled'){
                        
                                                   
                        }   
                         */                
                    }   
            
            }
       }
       return newList;
    }
}

/*
actguests__c != 0 
gtdguests__c
plnguests__c 
*/