src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>Grid_Lost_Focus_Poll_Interval__c</fullName>
        <description>Used in ExpensesTab and AncillaryTab VF pages javascript to set how often the code polls to check the current in focus element. Used to show warning if grid has focus removed but has unsaved changes. Please enter a numeric value for the desired milliseconds.</description>
        <label>Grid Lost Focus Poll Interval</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementBoxOfficeTab_CX_Test.cls
@isTest
private class LNE_SettlementBoxOfficeTab_CX_Test {

	class TestSettings {
		public Event__c testEvent;
		DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();
		EventDateTime__c eventDateTime;
		
		public TestSettings() {
			testEvent = [SELECT Id FROM Event__c LIMIT 1];
			
			eventDateTime = new EventDateTime__c(
                Event__c = testEvent.Id, 
                EventYear__c = String.valueOf(System.now().year() + 2),
                EventDate__c = System.today().addDays(10),
                StartTime__c = '6:00 PM');
        	insert eventDateTime;
		}
		public void typicalSetup(){}
		public void finalize(){}
	}

	@TestSetup static void setupTestData() {
    	LNE_TestObjectFactory.prepStandardCustomSettings();
    	LNE_TestObjectFactory.createStandardDataSet();
    }

    static LNE_SettlementBoxOfficeTab_CX setupController(Event__c event) {
        ApexPages.currentPage().getParameters().put('id', event.Id);
        ApexPages.StandardController standardEventCtlr = new ApexPages.StandardController(event);
        LNE_SettlementBoxOfficeTab_CX tabController = new LNE_SettlementBoxOfficeTab_CX(standardEventCtlr);

        return tabController;
    }

    static void setupPlatinumScales(Event__c event, Id eventDateTimeId) {
    	
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = event.id,
            Type__c = 'Platinum',
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Price__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            StageType__c = 'Settlement',
            EventDateTime__c = eventDateTimeId
        );
        insert ticketScale1;

        TicketScale__c ticketScale2 = new TicketScale__c(
            Event__c = event.id,
            Type__c = 'Platinum',
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 5000,
            Price__c = 250,
            Comps__c = 2500,
            Capacity__c = 8000,
            StageType__c = 'Settlement'
        );
        insert ticketScale2;
    }

    @isTest static void validateCheckPlatinumTicketScalesWNoScales() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        Test.startTest();
        LNE_SettlementBoxOfficeTab_CX tabController = setupController(ts.testEvent);
        tabController.checkPlatinumTicketScales();
        tabController.showBoxOfficeTab();
        System.assertEquals('box_office', tabController.tabToShow);
        tabController.showPlatinumAndDeductionsTab();
        System.assertEquals('platinum_and_deductions', tabController.tabToShow);
        Test.stopTest();

        System.assert(tabController.numPlatinumTicketScales == 0);
    }

    @isTest static void validateCheckPlatinumTicketScalesWScales() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        GeneralSettings__c gs = [SELECT Grid_Lost_Focus_Poll_Interval__c FROM GeneralSettings__c];
        gs.Grid_Lost_Focus_Poll_Interval__c = '234';
        update gs;

        setupPlatinumScales(ts.testEvent, ts.eventDateTime.Id);

        Test.startTest();

        LNE_SettlementBoxOfficeTab_CX tabController = setupController(ts.testEvent);
        tabController.checkPlatinumTicketScales();

        Test.stopTest();

        System.assert(tabController.numPlatinumTicketScales == 2);
        tabController.dropCountGridSave();
        System.assertEquals('234', tabController.getGridLostFocusPollInterval());
        system.assertEquals(ts.DATA_SETTINGS.CombinedKeyDelimiter__c, tabController.delimiter);
        system.assertEquals(1, LNE_SettlementBoxOfficeTab_CX.checkPlatinum(ts.eventDateTime.Id));
    }
}