src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <label>Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AmountRate__c</fullName>
        <label>Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventIDStageType__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncludeInAuditPrice__c</fullName>
        <label>Include In Audit Price</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Included Fee</fullName>
                </value>
                <value>
                    <fullName>Included Tax</fullName>
                </value>
                <value>
                    <fullName>Excluded/Fee On Top</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Amount Per Ticket</fullName>
                </value>
                <value>
                    <fullName>Primary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Primary Multiplier Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Multiplier Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_BeforeAfterDeductionTotals_T.cls
/**
 *	Trigger logic to check for changes on any fields that would case a Before/After
 *	deduction calculation to fire off
 *	@author Daniel Nakonieczny
 **/
public with sharing class LNE_BeforeAfterDeductionTotals_T {

    private static final DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();

	/**
     *  Checks if any fields changed that would require a recalculation of deduction totals
     *  @param newList Deduction__c[]
     *  @param oldMap Map<Id,Deduction__c>
     *  @return Deduction__c[] - list of deductions updated.
    **/
    
    public static Deduction__c[] execute( Deduction__c[] newList, Map<Id,Deduction__c> oldMap ){
    	List<Deduction__c> changedDeductions = new List<Deduction__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();
 		ChangedDeduction objChange = null;

 		if (oldMap == null){
            oldMap = new Map<Id, Deduction__c>();
        }

		for (Deduction__c newDeduction : newList ){
			if(oldMap.containsKey(newDeduction.Id)){
                
                Deduction__c oldDeduction = oldMap.get(newDeduction.Id);
                objChange = new ChangedDeduction(oldDeduction, newDeduction);
                
                if(
                    objChange.notEqualsStr('RateType__c', false) ||
                    objChange.notEquals('AmountRate__c') ||
                    objChange.notEquals('Adjustment__c') ||
                    objChange.notEqualsStr('ApplyTicketScale__c', false) ||
                    objChange.notEqualsStr('TicketScaleList__c', false) ||
                    objChange.notEqualsStr('StageType__c', false) ||
                    objChange.notEqualsStr('IncludeInAuditPrice__c', false)
                ) {
                	if (objChange.getNewDeduction().Event__c != null) {
                		listOfRelatedEventIds.add(objChange.getNewDeduction().Event__c);	
                	}
                	changedDeductions.add(objChange.getNewDeduction());
                  }
                
            } else {
                if (newDeduction.Event__c != null) {
                	listOfRelatedEventIds.add(newDeduction.Event__c);	
                }
                changedDeductions.add(newDeduction);
            }
		}

		LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

		return changedDeductions;
    }

    /**
     *  Populates the Event__c lookup (if blank) by parsing the EventIDStageType__c.
     *  This should run only on before insert
     *  @param newList Deduction__c[]
    **/
    public static void populateEventIfBlank(Deduction__c[] newList) {

        for (Deduction__c d : newList) {
            if (d.Event__c == null && !String.isBlank(d.EventIDStageType__c)) {

                String encodedField = EncodingUtil.urlEncode(d.EventIDStageType__c, 'UTF-8');
                String encodedDelimeter = EncodingUtil.urlEncode(DATA_SETTINGS.CombinedKeyDelimiter__c, 'UTF-8');

                List<String> l = encodedField.split(encodedDelimeter);

                if (!l.isEmpty()) {
                    d.Event__c = l[0];

                    if (l.size()>1) {
                        d.StageType__c = l[1];
                    }
                }
            }
        }
    }
    
    /**
     *  Recalculates for deleted Deductions
     *  @param Deductions[] - list of deleted Deductions.
     *  @return Deductions[] - list of Deductions updated.
    **/
    
     public static Deduction__c[] execute( Deduction__c[] deletedList ){
    	List<Deduction__c> ChangedDeductions = new List<Deduction__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();

 		for (Deduction__c deletedDeduction : deletedList){
 		    if (deletedDeduction.Event__c != null) {
            	listOfRelatedEventIds.add(deletedDeduction.Event__c);	
            }
            ChangedDeductions.add(deletedDeduction);
 		}
 		
 		LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

		return ChangedDeductions;
    }
    
    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedDeduction extends LNE_SObjectChange {
        
        ChangedDeduction( Deduction__c oldObject, Deduction__c newObject ){
            super( oldObject, newObject );
        }
        
        Deduction__c getNewDeduction(){
            return( (Deduction__c)this.newObject );
        }
    }
}