src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdjustedGrossPotential__c</fullName>
        <label>Adjusted Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossPotential__c</fullName>
        <label>Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HidePreviouslyForecastedLiftBfrTxs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hides the Previously Forecasted Lift Before Taxes field from the Ticket Revenue tab on Event.</description>
        <inlineHelpText>Hides the Previously Forecasted Lift Before Taxes field from the Ticket Revenue tab on Event.</inlineHelpText>
        <label>Hide Previously Forecasted Lift Bfr Txs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HidePreviouslyForecastedProjPdTkt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hides the Previously Forecasted Projected Paid Tickets field from the Ticket Revenue tab on Event.</description>
        <inlineHelpText>Hides the Previously Forecasted Projected Paid Tickets field from the Ticket Revenue tab on Event.</inlineHelpText>
        <label>Hide Previously Forecasted Proj Pd Tkt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NetGrossPotential__c</fullName>
        <label>Net Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PlatinumLift__c</fullName>
        <label>Platinum Lift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrevioulsyForecastedLiftBeforeTaxes__c</fullName>
        <label>Previoulsy Forecasted Lift Before Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PreviouslyForecastedProjPaidTickets__c</fullName>
        <label>Previously Forecasted Proj Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedAdjustedGross__c</fullName>
        <label>Projected Adjusted Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedGrossSales__c</fullName>
        <label>Projected Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedGross__c</fullName>
        <label>Projected Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedNetGross__c</fullName>
        <label>Projected Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutGrossSales__c</fullName>
        <label>Sellout Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementDeductions__c</fullName>
        <label>Settlement Deductions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementGrossSales__c</fullName>
        <label>Settlement Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementPaidTickets__c</fullName>
        <label>Settlement Paid Tickets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementPlatinumLift__c</fullName>
        <label>Settlement Platinum Lift</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowCount__c</fullName>
        <label>Show Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StatusStage__c</fullName>
        <formula>CASE(TEXT(Status__c),
&quot;Draft&quot;, &quot;Plan&quot;,
&quot;Pending Unlikely&quot;, &quot;Plan&quot;,
&quot;Pending Likely&quot;, &quot;Plan&quot;,
&quot;Confirmed&quot;, &quot;Projection&quot;,
&quot;Flash Started&quot;, &quot;Projection&quot;,
&quot;Flash Complete&quot;, &quot;Projection&quot;,
&quot;Artist Passed&quot;, &quot;Plan&quot;,
&quot;LNE Passed&quot;, &quot;Plan&quot;,
&quot;Postponed&quot;, &quot;Projection&quot;,
&quot;Cancelled&quot;, &quot;Projection&quot;,
&quot;Inactive&quot;, &quot;Plan&quot;,
&quot;Plan&quot;)</formula>
        <label>Status Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsingTicketFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Using Ticket Feed</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HidePreviouslyForecastedLiftBfrTxs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Previously Forecasted Lift Bfr Txs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HidePreviouslyForecastedProjPdTkt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Previously Forecasted Proj Pd Tkt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PreviouslyForecastedProjPaidTickets__c</fullName>
        <label>Previously Forecasted Proj Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UsingTicketFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Using Ticket Feed</label>
        <type>Checkbox</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>Grid_Lost_Focus_Poll_Interval__c</fullName>
        <description>Used in ExpensesTab and AncillaryTab VF pages javascript to set how often the code polls to check the current in focus element. Used to show warning if grid has focus removed but has unsaved changes. Please enter a numeric value for the desired milliseconds.</description>
        <label>Grid Lost Focus Poll Interval</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectedGrossSales__c</fullName>
        <formula>ProjectedPaidTickets__c *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Projected Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementBoxOfficeTab_CX.cls
global class LNE_SettlementBoxOfficeTab_CX {
    
    public Event__c eventRecord {get;set;}
    public String eventId {get;set;}
    public Event__c eventMetrics {get;set;}
    public String gridLostFocusPollInterval;
    public String gridBuddyRecordsToShow {get;set;}
    public Integer showGridsAsReadOnly {get;set;}
    public String tabToShow {get;set;}
    public Integer numPlatinumTicketScales {get;set;}
    public Boolean multipleEventDateTimes {get;set;}
    public Boolean showEventDateTimeTabs {get;set;}
    public List<AggregateResult> dateTimeSummary {get;set;}
    public Map<Id, EventDateTime__c> dateTimeMap {get;set;}
    public List<LNE_EventDateTimeUtil_T.EventDateTime> sortedEventDates {get;set;}
    public static final String BOX_OFFICE_TAB = 'box_office';
    public static final String PLATINUM_AND_DEDUCTIONS_TAB = 'platinum_and_deductions';
    public String delimiter {get {
        return DATA_SETTINGS.CombinedKeyDelimiter__c;
    }}
    
    private final SObject parent;
    private static final GeneralSettings__c GENERAL_SETTINGS = GeneralSettings__c.getInstance();
    private static final DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();
    
    private static String RT_ANCILLARY = 'LedgerEntry__c.Ancillary';
    private static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
        new String[]{ RT_ANCILLARY }
    );

    private static Id RT_ANCILLARY_ID = recordTypeMap.get( RT_ANCILLARY );

    public LNE_SettlementBoxOfficeTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        eventId = parent.Id;
        init();
    }
    
    public void init() {
        tabToShow = BOX_OFFICE_TAB;
        checkPlatinumTicketScales();
        eventRecord = [SELECT SettlementStarted__c FROM Event__c WHERE Id = :parent.Id];
        gridBuddyRecordsToShow = getGridBuddyDataTypeToShow('Settlement');
        getBoxOfficeGrid();
        //- This is used in GridBuddy "ro" URL parameter. 0 = Editable, 1 = Read Only
        showGridsAsReadOnly = 0;
        getDateTimeSummary();
    }

    public void checkPlatinumTicketScales() {
        numPlatinumTicketScales = [SELECT COUNT() FROM TicketScale__c WHERE Event__c = :eventId AND Type__c = 'Platinum' AND StageType__c = 'Settlement'];
    }

    public PageReference dropCountGridSave(){
        update parent;
        
        return( null );
    }

    public String getGridLostFocusPollInterval() {
        String res = GENERAL_SETTINGS.Grid_Lost_Focus_Poll_Interval__c;
        return res;
    }
    
    public PageReference getBoxOfficeGrid(){
        eventMetrics = [SELECT  ShowCount__c, SelloutGrossSales__c, PlatinumLift__c, GrossPotential__c, AdjustedGrossPotential__c, NetGrossPotential__c,
                                ProjectedGrossSales__c, ProjectedGross__c,ProjectedAdjustedGross__c, ProjectedNetGross__c, Status__c, StatusStage__c, UsingTicketFeed__c,
                                ProjectedPaidTickets__c, HidePreviouslyForecastedLiftBfrTxs__c, HidePreviouslyForecastedProjPdTkt__c,
                                PrevioulsyForecastedLiftBeforeTaxes__c, PreviouslyForecastedProjPaidTickets__c,SettlementPaidTickets__c,SettlementGrossSales__c,
                                SettlementPlatinumLift__c, SettlementDeductions__c, SettlementNetGross__c,
                                (SELECT EventDate__c, StartTime__c, PreviouslyForecastedGrossSales__c,PreviouslyForecastedProjPaidTickets__c,
                                                            PrevForecastedPlatinumLiftbeforeFee__c, HidePreviouslyForecastedProjPdTkt__c,
                                                            HidePreviouslyForecastedLiftBfrTxs__c
                                 FROM EventDateTimes__r ORDER BY EventDate__c ASC NULLS LAST)
                        FROM Event__c WHERE Id = :eventId][0]; 

        dateTimeMap = new Map<Id, EventDateTime__c>(eventMetrics.EventDateTimes__r);
        multipleEventDateTimes = eventMetrics.EventDateTimes__r.size() > 1;
        showEventDateTimeTabs = multipleEventDateTimes;

        sortedEventDates = new List<LNE_EventDateTimeUtil_T.EventDateTime>();
        
        for (EventDateTime__c edt : eventMetrics.EventDateTimes__r) {
            sortedEventDates.add(new LNE_EventDateTimeUtil_T.EventDateTime(edt));
        }
        
        sortedEventDates.sort();

        return null;
    }

     public void getDateTimeSummary() {
        List<AggregateResult> ar =   [SELECT SUM(Capacity__c) totalCapacity,
                                      SUM(Kills__c) kills,
                                      SUM(Holds__c) holds,
                                      SUM(NetCapacity__c) netCapacity,
                                      SUM(Comps__c) comps,
                                      SUM(Unsold__c) unsold,
                                      SUM(ActualSalesToDate__c) actualSalesToDate,
                                      SUM(ActualGrossToDate__c) actualGrossToDate,
                                      EventDateTime__c Id
                               FROM TicketScale__c
                               WHERE Event__c = :eventId
                               AND StageType__c = 'Settlement'
                               AND EventDateTime__c <> NULL
                               GROUP BY EventDateTime__c];
                           
        Map<Id, AggregateResult> arMap = new Map<Id, AggregateResult>(ar);
        dateTimeSummary = new List<AggregateResult>();
        
        for (LNE_EventDateTimeUtil_T.EventDateTime e : sortedEventDates) {
            if (arMap.get(e.edt.Id) != null) {
                dateTimeSummary.add(arMap.get(e.edt.Id));
            }
        }
    }
 
    public void startSettlement() {
        LNE_SettlementUtil.startSettlementProcess(eventRecord.Id);
    }

    public void showBoxOfficeTab() {
        tabToShow = BOX_OFFICE_TAB;
        checkPlatinumTicketScales();
        getDateTimeSummary();
    }

    public void showPlatinumAndDeductionsTab() {
        tabToShow = PLATINUM_AND_DEDUCTIONS_TAB;
        checkPlatinumTicketScales();
        getDateTimeSummary();
    }

    @RemoteAction
    global static Integer checkPlatinum(String edtId){
        return [SELECT COUNT() FROM TicketScale__c WHERE EventDateTime__c = :edtId AND Type__c = 'Platinum' AND StageType__c = 'Settlement'];
    }
    
    private String getGridBuddyDataTypeToShow(String type) {
        return eventId.substring(0,15) + DATA_SETTINGS.CombinedKeyDelimiter__c + type;
    }
}