src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/DMA__c.object
<CustomObject>
    <description>Designated Market Areas defined by Postal Code, City and State.</description>
    <fields>
        <fullName>DMA__c</fullName>
        <inlineHelpText>The Actual Designated Market Area.</inlineHelpText>
        <label>DMA</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <inlineHelpText>Postal / Zip Code that this DMA represents.</inlineHelpText>
        <label>Postal Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <label>DMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LNE_DMA_NameDefinition_T.cls
/**
 *  Implementation of the trigger that keeps the name of the DMA record
 *  in sync with the value and postal code.
 *  @author Paul Roth <proth@salesforce.com>
 **/
public with sharing class LNE_DMA_NameDefinition_T {
    
    /**
     *  Defines the name of the DMA based on the Zip Code and the DMA value.
     *  <p>Assumes Before Update / Before Insert</p>
     *  @param DMA__c[] newRecords
     *  @param Map<Id,DMA__c> oldMap
     *  @return DMA__c[] - list of DMA Records updated.
     **/
    public static DMA__c[] execute( DMA__c[] newList, Map<Id,DMA__c> oldMap ){
        DMA__c[] results = new DMA__c[]{};
        
        if( newList == null ){
            return( results );
        }
        
        String delimiter = DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;
        
        //DMA__c dma = null;
        DMA__c oldDMA = null;
        
        
        if( oldMap == null ){
            //System.debug( "Before Insert mode" );
            for( DMA__c dma : newList ){
                results.add( dma );
            }
        } else {
            //System.debug( "Before Update Mode" );
            for( DMA__c dma : newList ){
                if( oldMap.containsKey( dma.Id ) ){
                    oldDMA = oldMap.get( dma.Id );
                    
                    //-- if they are different
                    if( !dma.DMA__c.equals( oldDMA.DMA__c ) ||
                        !dma.PostalCode__c.equals( oldDMA.PostalCode__c )
                    ){
                        results.add( dma );
                    }
                }
            }
        }
        
        //-- update the name
        for( DMA__c dma : results ){
            dma.Name = dma.DMA__c + delimiter + dma.PostalCode__c;
        }
        
        return( results );
    }
}