src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>ActualGrossToDate__c</fullName>
        <label>Actual Gross To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ActualSalesToDate__c</fullName>
        <label>Actual Sales To Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AverageLiftPerTicket__c</fullName>
        <label>Average Lift Per Ticket</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventIDStageTypeDateTime__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type Date Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventIDStageType__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFee__c</fullName>
        <formula>IF(LiftBeforeFee__c &gt; 0, TotalPlatinumSeatProceeds__c *  TMFeePercent__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TM Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_TicketScaleMetrics_T.cls
/**
 *	Trigger logic to check for changes on any fields that would case a Before/After
 *	Ticket Scale calculations to fire off
 *	@author John Casimiro
 **/
public with sharing class LNE_TicketScaleMetrics_T {

    private static final DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();

	/**
     *  Checks if any fields changed that would require a recalculation of TicketScale totals
     *  @param newList TicketScale__c[]
     *  @param oldMap Map<Id,TicketScale__c>
     *  @return TicketScale__c[] - list of TicketScales updated.
    **/
    
    public static TicketScale__c[] execute( TicketScale__c[] newList, Map<Id,TicketScale__c> oldMap ){
    	List<TicketScale__c> ChangedTicketScales = new List<TicketScale__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();
 		ChangedTicketScale objChange = null;

 		if (oldMap == null){
            oldMap = new Map<Id, TicketScale__c>();
        }
        
        Boolean recalculateEventIdStage;
		for (TicketScale__c newTicketScale : newList ){
			recalculateEventIdStage = false;
			
			if(oldMap.containsKey(newTicketScale.Id)){
                
                TicketScale__c oldTicketScale = oldMap.get(newTicketScale.Id);
                objChange = new ChangedTicketScale(oldTicketScale, newTicketScale);
                
                if(
                    objChange.notEquals('Capacity__c') ||
                    objChange.notEquals('Comps__c') ||
                    objChange.notEquals('Kills__c') ||
                    objChange.notEquals('Price__c') ||
                    objChange.notEquals('ProjectedPaidTickets__c') ||
                    objChange.notEquals('AverageLiftPerTicket__c') ||
                    objChange.notEquals('ActualSalesToDate__c') ||
                    objChange.notEquals('ActualGrossToDate__c') ||
                    objChange.notEquals('TMFee__c') ||
                    objChange.notEquals('LiftBeforeFee__c') ||
                    objChange.notEqualsStr('StageType__c', false) 
                ) {
                	if (objChange.getNewTicketScale().Event__c != null) {
                		listOfRelatedEventIds.add(objChange.getNewTicketScale().Event__c);	
                	}
                	ChangedTicketScales.add(objChange.getNewTicketScale());
                }
                
                if(
                	objChange.notEquals( 'StageType__c' ) ||
                	objChange.notEquals( 'Event__c' ) ||
                	objChange.notEquals( 'EventDateTime__c' )
                ){
                	recalculateEventIdStage = true;
                }
                
            } else {
                if (newTicketScale.Event__c != null) {
                	listOfRelatedEventIds.add(newTicketScale.Event__c);	
                }
                recalculateEventIdStage = true;
                ChangedTicketScales.add(newTicketScale);
            }
            
            if (newTicketScale.StageType__c != null && recalculateEventIdStage ) {
                newTicketScale.EventIDStageType__c = ((String)newTicketScale.Event__c).substring(0,15) + DATA_SETTINGS.CombinedKeyDelimiter__c + newTicketScale.StageType__c;
                if (newTicketScale.EventDateTime__c != null) {
                    newTicketScale.EventIDStageTypeDateTime__c = newTicketScale.EventIDStageType__c + DATA_SETTINGS.CombinedKeyDelimiter__c + ((String)newTicketScale.EventDateTime__c).substring(0,15);
                }
            }
		}

		LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

		return ChangedTicketScales;
    }
    
    /**
     *  Recalculates for deleted TicketScales
     *  @param TicketScale__c[] - list of deleted TicketScales.
     *  @return TicketScale__c[] - list of TicketScales updated.
    **/
    
    public static TicketScale__c[] execute( TicketScale__c[] deletedList ){
    	List<TicketScale__c> ChangedTicketScales = new List<TicketScale__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();
 		ChangedTicketScale objChange = null;

 		for (TicketScale__c deletedTicketScale : deletedList){
 		    if (deletedTicketScale.Event__c != null) {
            	listOfRelatedEventIds.add(deletedTicketScale.Event__c);	
            }
            ChangedTicketScales.add(deletedTicketScale);
 		}
 		
 		LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

		return ChangedTicketScales;
    }

    /**
     *  Populates the Event__c lookup (if blank) by parsing the EventIDStageType__c.
     *  This should run only on before insert
     *  @param newList TicketScale__c[]
    **/
    public static void populateEventIfBlank(TicketScale__c[] newList) {
        for (TicketScale__c ts : newList) {
            if (ts.Event__c == null) {
                List<String> splitEventIDStageType = splitString(ts.EventIDStageType__c);
                List<String> splitEventIDStageTypeDateTime = splitString(ts.EventIDStageTypeDateTime__c);

                populateFields(ts, splitEventIDStageType);
                populateFields(ts, splitEventIDStageTypeDateTime);
            }
        }
    }

    private static List<String> splitString(String s) {
        List<String> result = new List<String>();

        if (String.isNotBlank(s)) {
            String encodedDelimeter = EncodingUtil.urlEncode(DATA_SETTINGS.CombinedKeyDelimiter__c, 'UTF-8');
            String encodedString = EncodingUtil.urlEncode(s, 'UTF-8');
            result = encodedString.split(encodedDelimeter);
        }
        
        return result;
    }

    private static void populateFields(TicketScale__c ts, List<String> values) {
        if (!values.isEmpty()) {
            ts.Event__c = values[0];

            if (values.size()>1) {
                ts.StageType__c = values[1];
            }

            if (values.size()>2) {
                ts.EventDateTime__c = values[2];
            }
        }
    }

    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedTicketScale extends LNE_SObjectChange {
        
        ChangedTicketScale( TicketScale__c oldObject, TicketScale__c newObject ){
            super( oldObject, newObject );
        }
        
        TicketScale__c getNewTicketScale(){
            return( (TicketScale__c)this.newObject );
        }
    }
}