src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventYear__c</fullName>
        <label>Event Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventIDStageTypeDateTime__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type Date Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventIDStageType__c</fullName>
        <description>This field is being used in GridBuddy filters. Should not be on any page layouts.</description>
        <label>Event ID Stage Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFeePercent__c</fullName>
        <defaultValue>0.129</defaultValue>
        <label>TM Fee %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_TicketScaleMetrics_T_Test.cls
@isTest
private class LNE_TicketScaleMetrics_T_Test {
	@testSetup
	static void setup(){
		LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
	}

	class TestSettings {
		Event__c event;
		DataGenerationSettings__c DATA_SETTINGS = DataGenerationSettings__c.getInstance();
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_EventDateTimeUtil_T_Test' );
			LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false);

			event = [SELECT Id FROM Event__c];

        	TicketScale__c ticketScale = new TicketScale__c();
			ticketScale.Type__c = 'Reserved';
			ticketScale.Capacity__c = 1000;
			ticketScale.Price__c = 100.00;
			ticketScale.Kills__c = 0;
			ticketScale.Comps__c = 0;
			ticketScale.ProjectedPaidTickets__c = 950;
			ticketScale.Event__c = event.Id;
			ticketScale.LiftBeforeFee__c = 0;
			ticketScale.TMFeePercent__c = 0.0;
			ticketScale.StageType__c = 'Plan';

			insert ticketScale;
		}
		
		public void typicalSetup(){
			
		}
		
		public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		}
	}

	static testMethod void testFieldPopulation() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();

		EventDateTime__c eventDateTime = new EventDateTime__c(
            	Event__c = ts.event.Id, 
            	EventYear__c = String.valueOf(System.now().year() + 2),
            	EventDate__c = System.today().addDays(12),
            	StartTime__c = '9:00 PM');
        insert eventDateTime;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Plan';
		ticketScale.EventIDStageType__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan';
		ticketScale.EventIDStageTypeDateTime__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan' + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + eventDateTime.Id;

		insert ticketScale;

		ticketScale = [SELECT Event__c, EventDateTime__c FROM TicketScale__c WHERE Id = :ticketScale.Id];
		system.assertEquals(ts.event.Id, ticketScale.Event__c);
		system.assertEquals(eventDateTime.Id, ticketScale.EventDateTime__c);
	}

	static testMethod void testUpdate() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();

		EventDateTime__c eventDateTime = new EventDateTime__c(
            	Event__c = ts.event.Id, 
            	EventYear__c = String.valueOf(System.now().year() + 2),
            	EventDate__c = System.today().addDays(12),
            	StartTime__c = '9:00 PM');
        insert eventDateTime;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Plan';
		ticketScale.EventIDStageType__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan';
		ticketScale.EventIDStageTypeDateTime__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan' + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + eventDateTime.Id;

		insert ticketScale;

		ticketScale.StageType__c = 'Projection';
		update ticketScale;

		ticketScale = [SELECT EventIDStageType__c FROM TicketScale__c WHERE Id = :ticketScale.Id];
		system.assertEquals(((String)ts.event.Id).substring(0,15) + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Projection', ticketScale.EventIDStageType__c);
	}

	static testMethod void testDelete() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		Test.startTest();

		EventDateTime__c eventDateTime = new EventDateTime__c(
            	Event__c = ts.event.Id, 
            	EventYear__c = String.valueOf(System.now().year() + 2),
            	EventDate__c = System.today().addDays(12),
            	StartTime__c = '9:00 PM');
        insert eventDateTime;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Plan';
		ticketScale.EventIDStageType__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan';
		ticketScale.EventIDStageTypeDateTime__c = ts.event.Id + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + 'Plan' + ts.DATA_SETTINGS.CombinedKeyDelimiter__c + eventDateTime.Id;

		insert ticketScale;

		List<TicketScale__c> tList = [SELECT Id FROM TicketScale__c WHERE Id = :ticketScale.Id];
		system.assertEquals(1, tList.size());

		delete ticketScale;

		tList = [SELECT Id FROM TicketScale__c WHERE Id = :ticketScale.Id];
		system.assertEquals(0, tList.size());
	}
}