src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>AverageLiftPerTicket__c</fullName>
        <label>Average Lift Per Ticket</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedGrossSales__c</fullName>
        <formula>ProjectedPaidTickets__c *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Projected Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_PlatinumLiftCalculationLogic.cls
/**
*  Class that contains the Logic to calculate fields on the LedgerEntry__c Object
*     Fields: Gross Revenue, Gross Per Paid, Contra at Forecast, Contra % at Forecast, Net Revenue and Net Per Paid
*  <p>This class should have the least amount of code possible to reduce security concerns.</p>
*  @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
**/

public class LNE_PlatinumLiftCalculationLogic {
    
    
    public static final string DELIMITER = DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;

    
    public static final string ERR_NO_RELATED_EVENT = 'No Related Event';
    public static final string ERR_PROJECTED_PAID_TICKETS_NULL = 'Projected Paid Tickets on Related Event is not set';
    public static final string ERR_PROJECTED_DROP_COUNT_NULL = 'Projected Drop Count on Related Event is not set';
    
    class CustomException extends Exception{}
    
    
/**
*  Method to return a Ticket Scale with all updated fields to Grid Buddy
*  @param TicketScale__c
*  @return TicketScale__c
**/
    public static TicketScale__c calculateFieldsOnGrid(TicketScale__c ticketScale){
        System.debug(ticketScale);
        
        TicketScale__c savedTicketScale = 
            [SELECT Id, 
                    AverageLiftPerTicket__c, 
                    ProjectedGrossSales__c, 
                    ProjectedPaidTickets__c, 
                    Price__c, 
                    LiftBeforeFee__c  
               FROM TicketScale__c
              WHERE Id = :ticketScale.Id];
        
        if(ticketScale.AverageLiftPerTicket__c == null) {
            ticketScale.AverageLiftPerTicket__c = ticketScale.LiftBeforeFee__c / savedTicketScale.ProjectedPaidTickets__c;
        } else if(ticketScale.LiftBeforeFee__c == null) {
            ticketScale.LiftBeforeFee__c = ticketScale.AverageLiftPerTicket__c * savedTicketScale.ProjectedPaidTickets__c;
        }
        
        ticketScale.Price__c = savedTicketScale.Price__c;
        ticketScale.ProjectedPaidTickets__c = savedTicketScale.ProjectedPaidTickets__c;
        
        System.debug(ticketScale);
        return ticketScale;
    }
}