src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ActualDropCount__c</fullName>
        <label>Actual Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PaidAttendance__c</fullName>
        <formula>LawnPaidAttendance__c +  ReservedPaidAttendance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Paid Attendance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SettlementAdjustedGross__c</fullName>
        <label>Settlement Adjusted Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementGross__c</fullName>
        <label>Settlement Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementNetGross__c</fullName>
        <label>Settlement Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementPaidTickets__c</fullName>
        <label>Settlement Paid Tickets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RelatedContra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contra</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Related Contra (GL Account)</relationshipLabel>
        <relationshipName>GLAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry Breakout</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PerformingRightsFee__c.object
<CustomObject>
    <fields>
        <fullName>Breakout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CapacityRangeEnd__c</fullName>
        <label>Capacity Range End</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CapacityRangeStart__c</fullName>
        <label>Capacity Range Start</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CapacityRange__c</fullName>
        <formula>IF(CapacityRangeStart__c &lt;&gt; 0,

IF(ABS(CapacityRangeStart__c) &gt;= 1000000, TEXT(FLOOR(ABS(CapacityRangeStart__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(CapacityRangeStart__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(CapacityRangeStart__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(CapacityRangeStart__c))), 3)

&amp;

IF(CapacityRangeEnd__c = 0, &quot;+&quot;, &quot; - &quot; +

IF(ABS(CapacityRangeEnd__c) &gt;= 1000000, TEXT(FLOOR(ABS(CapacityRangeEnd__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(CapacityRangeEnd__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(CapacityRangeEnd__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(CapacityRangeEnd__c))), 3)
),

&quot;&quot;)

/* Note this is modified from template below

IF(Amount &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Amount) &gt;= 1000000, TEXT(FLOOR(ABS(Amount) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Amount) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Amount) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Amount))), 3) &amp; &quot;.&quot; &amp;
IF(MOD(ABS(Amount) , 1) * 100 &lt; 10, &quot;0&quot; &amp; TEXT(ROUND(MOD(ABS(Amount) , 1), 2) * 100), TEXT(MIN(ROUND(MOD(ABS(Amount) , 1), 2) * 100, 99))) &amp;
IF(Amount &lt; 0, &quot;)&quot;, &quot;&quot;)

*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Capacity Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Performing Rights Fees</relationshipLabel>
        <relationshipName>PerformanceRightsFees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateAmount__c</fullName>
        <label>Rate/Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASCAP</fullName>
                </value>
                <value>
                    <fullName>BMI</fullName>
                </value>
                <value>
                    <fullName>GMR</fullName>
                </value>
                <value>
                    <fullName>SESAC</fullName>
                </value>
                <value>
                    <fullName>SOCAN</fullName>
                </value>
                <value>
                    <fullName>Event Insurance Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Performing Rights Fee</label>
    <nameField>
        <displayFormat>PRF-{000000}</displayFormat>
        <label>Performing Rights Fee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performing Rights Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AX - Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>DZ - Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AI - Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>AQ - Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AW - Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BS - Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BY - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BZ - Belize</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BM - Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>BT - Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>BQ - Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BW - Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>BV - Bouvet Island</fullName>
    </customValue>
    <description>Replicates Countries standard picklist</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/LNE_LedgerEntryDefaultFees.cls
/**
 * Logic to default the Performing Right Fees on Finance > Event Metrics subtab
 * @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
 **/
 
 public class LNE_LedgerEntryDefaultFees {
     
    public static final string DELIMITER = DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;
    public static final String FOR_SETTLEMENT_EXPENSES = 'for_se';

    public static void defaultFees(String evtId) {
        defaultFees(evtId, null);
    }

    public static void defaultFees(String evtId, String defaultFor) {
        System.debug(evtId);
        
        if(evtId != null && evtId != ''){
            Event__c event = [SELECT EventLastDate__c, 
                                     Name, 
                                     SettlementNetGross__c, 
                                     SettlementAdjustedGross__c,
                                     SettlementGross__c,
                                     SettlementPaidTickets__c,
                                     PaidAttendance__c, 
                                     ActualDropCount__c, 
                                     SelloutDropCount__c, 
                                     Venue__r.BillingCountryCode, 
                                     Venue__r.BillingCountry 
                                FROM Event__c 
                               WHERE Id =:evtId];
                               
            Map<Id,PerformingRightsFee__c> usedPrfIds = new Map<Id,PerformingRightsFee__c>();
            Date eventLastDate = event.EventLastDate__c;
            List<LedgerEntry__c> leToUpsert = new List<LedgerEntry__c>();
            List<LedgerEntryBreakout__c> lebToUpsert = new List<LedgerEntryBreakout__c>();
            Map<String,LedgerEntry__c> breakoutExternalIds = new Map<String,LedgerEntry__c>();
            List<PerformingRightsFee__c> addedPrfs = new List<PerformingRightsFee__c>();
            
            Map<Id, PerformingRightsFee__c> performingRightFeesMap = new Map<Id, PerformingRightsFee__c>(
                [SELECT Id, 
                        Type__c, 
                        RateType__c, 
                        RateAmount__c, 
                        Breakout__c, 
                        Country__c, 
                        CapacityRange__c, 
                        CapacityRangeStart__c,
                        CapacityRangeEnd__c, 
                        GLAccount__r.GLCode__c, 
                        GLAccount__c
                   FROM PerformingRightsFee__c 
                  WHERE StartDate__c <= :eventLastDate AND EndDate__c >= :eventLastDate]);
                  
            Set<String> glAccountCodes = new Set<String>();
            for(PerformingRightsFee__c prf : performingRightFeesMap.values()){
                
                if(prf.Country__c != null && prf.Country__c == event.Venue__r.BillingCountryCode + ' - ' + event.Venue__r.BillingCountry){
     
                    usedPrfIds.put(prf.Id, prf);
                    glAccountCodes.add(usedPrfIds.get(prf.Id).GLAccount__r.GLCode__c);
                    
                }
                
                if(!usedPrfIds.keySet().contains(prf.Id) && prf.CapacityRangeStart__c != null && prf.CapacityRangeStart__c <= event.SelloutDropCount__c && 
                    ( prf.CapacityRangeEnd__c == null || event.SelloutDropCount__c <= prf.CapacityRangeEnd__c)){
                
                    usedPrfIds.put(prf.Id, prf);
                    glAccountCodes.add(usedPrfIds.get(prf.Id).GLAccount__r.GLCode__c);

                }
        
        
                if(!usedPrfIds.keySet().contains(prf.Id) && prf.Country__c == null && prf.CapacityRangeStart__c == null && prf.CapacityRangeEnd__c == null){
                
                    usedPrfIds.put(prf.Id, prf);
                    glAccountCodes.add(usedPrfIds.get(prf.Id).GLAccount__r.GLCode__c);

                }
                
                
                
            }
                                                                                                          
            List<LedgerEntry__c> setExternalIds = 
                [Select Id, 
                        Event__r.Name, 
                        GLAccount__r.GLCode__c, 
                        ExternalId__c, 
                        Description__c 
                   from LedgerEntry__c 
                  where Event__c = :evtId and GLAccount__r.GLCode__c in :glAccountCodes];
                  
            for(LedgerEntry__c le : setExternalIds){
                if(le.ExternalId__c != null)
                    le.ExternalId__c =  le.Event__r.Name + DELIMITER + le.GLAccount__r.GLCode__c;
            }
            
            update setExternalIds;
        
            Set<String> createdLedgers = new Set<String>();
            for(Id prfId : usedPrfIds.keySet()){
                  
                if(usedPrfIds.get(prfId).Breakout__c){
                    LedgerEntry__c addedLe = new LedgerEntry__c(
                        Event__c = evtId, 
                        GLAccount__c = usedPrfIds.get(prfId).GLAccount__c, 
                        ExternalId__c = event.Name + DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c, 
                        RecordTypeId = LNE_RT.RT_EXPENSES_ID);
                        
                    if(!createdLedgers.contains(addedLe.ExternalId__c)){
                        leToUpsert.add(addedLe);
                        breakoutExternalIds.put(event.Name + DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c, addedLe );
                        createdLedgers.add(addedLe.ExternalId__c);
                    }
                } else {
                    LedgerEntry__c addedLe;
                    
                    if(defaultFor == FOR_SETTLEMENT_EXPENSES) {
                        addedLe = getSettlementExpenseLedgerEntry(evtId, prfId, usedPrfIds, event);
                    } else {
                        addedLe = getFlashLedgerEntry(evtId, prfId, usedPrfIds, event);
                    }
                    
                    leToUpsert.add(addedLe);
                }
            }
            
            System.debug(leToUpsert);
            upsert leToUpsert ExternalId__c;
            
            for(Id prfId : usedPrfIds.keySet()){
                if(usedPrfIds.get(prfId).Breakout__c) {
                    LedgerEntryBreakout__c addedLeb;
                    
                    if(defaultFor == FOR_SETTLEMENT_EXPENSES) {
                        addedLeb = getSettlementExpenseLedgerEntryBreakout(evtId, prfId, usedPrfIds, event, breakoutExternalIds);
                    } else {
                        addedLeb = getFlashLedgerEntryBreakout(evtId, prfId, usedPrfIds, event, breakoutExternalIds);
                    }

                    lebToUpsert.add(addedLeb);
                }   
            }
            
            upsert lebToUpsert ExternalId__c;
        }
    }
    
    private static LedgerEntry__c getFlashLedgerEntry(String evtId, 
                                               Id prfId,
                                               Map<Id,PerformingRightsFee__c> usedPrfIds, 
                                               Event__c event) {
                                                   
        LedgerEntry__c addedLe = new LedgerEntry__c(
            Event__c = evtId, 
            GLAccount__c = usedPrfIds.get(prfId).GLAccount__c, 
            FlashRateType__c = usedPrfIds.get(prfId).RateType__c, 
            FlashRateAmount__c  = usedPrfIds.get(prfId).RateAmount__c, 
            FlashCapacityRange__c = usedPrfIds.get(prfId).CapacityRange__c, 
            FlashOverridden__c = false, 
            ExternalId__c = event.Name + DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c, 
            CurrentFlash__c = null, 
            RecordTypeId = LNE_RT.RT_EXPENSES_ID);
        
        return LNE_LedgerCalculateCurrentFlash.calculateCurrentFlashLE(addedLe,event);
    }
    
    
    private static LedgerEntry__c getSettlementExpenseLedgerEntry(String evtId, 
                                                           Id prfId,
                                                           Map<Id,PerformingRightsFee__c> usedPrfIds, 
                                                           Event__c event) {
                                                   
        LedgerEntry__c addedLe = new LedgerEntry__c(
            Event__c = evtId, 
            GLAccount__c = usedPrfIds.get(prfId).GLAccount__c, 
            SettlementRateType__c = usedPrfIds.get(prfId).RateType__c, 
            PromoterAmountRate__c  = usedPrfIds.get(prfId).RateAmount__c, 
            ExternalId__c = event.Name + DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c, 
            RecordTypeId = LNE_RT.RT_EXPENSES_ID);
        
        addedLe.PromoterAmount__c = LNE_LedgerCalculateCurrentFlash.getSettlementExpensePromoterAmount(
            event, 
            addedLe.SettlementRateType__c, 
            addedLe.PromoterAmountRate__c);
            
        return LNE_LedgerCalculateCurrentFlash.calculateCurrentFlashLE(addedLe,event);
    }    
    
    private static LedgerEntryBreakout__c getFlashLedgerEntryBreakout(String evtId, 
                                                               Id prfId,
                                                               Map<Id,PerformingRightsFee__c> usedPrfIds, 
                                                               Event__c event,
                                                               Map<String,LedgerEntry__c> breakoutExternalIds) {
                                                                   
        LedgerEntryBreakout__c addedLeb = new LedgerEntryBreakout__c(
            LedgerEntry__c = breakoutExternalIds.get(event.Name +DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c).Id, 
            ExternalId__c = event.Name + DELIMITER + usedPrfIds.get(prfId).Type__c,  
            Description__c = usedPrfIds.get(prfId).Type__c, 
            FlashRateType__c = usedPrfIds.get(prfId).RateType__c, 
            FlashRateAmount__c  = usedPrfIds.get(prfId).RateAmount__c, 
            FlashCapacityRange__c = usedPrfIds.get(prfId).CapacityRange__c, 
            CurrentFlash__c = null, 
            FlashOverridden__c = false);
            
        addedLeb.PromoterAmount__c = LNE_LedgerCalculateCurrentFlash.getSettlementExpensePromoterAmount(
            event, 
            addedLeb.SettlementRateType__c, 
            addedLeb.PromoterAmountRate__c);
            
        return addedLeb;
    }    
    
    private static LedgerEntryBreakout__c getSettlementExpenseLedgerEntryBreakout(String evtId, 
                                                                                  Id prfId,
                                                                                  Map<Id,PerformingRightsFee__c> usedPrfIds, 
                                                                                  Event__c event,
                                                                                  Map<String,LedgerEntry__c> breakoutExternalIds) {
                                                                   
        LedgerEntryBreakout__c addedLeb = new LedgerEntryBreakout__c(
            LedgerEntry__c = breakoutExternalIds.get(event.Name +DELIMITER + usedPrfIds.get(prfId).GLAccount__r.GLCode__c).Id, 
            ExternalId__c = event.Name + DELIMITER + usedPrfIds.get(prfId).Type__c,  
            Description__c = usedPrfIds.get(prfId).Type__c, 
            SettlementRateType__c = usedPrfIds.get(prfId).RateType__c, 
            PromoterAmountRate__c  = usedPrfIds.get(prfId).RateAmount__c);
            
        addedLeb.PromoterAmount__c = LNE_LedgerCalculateCurrentFlash.getSettlementExpensePromoterAmount(
            event, 
            addedLeb.SettlementRateType__c, 
            addedLeb.PromoterAmountRate__c);
            
        return addedLeb;
    }
    
    
}