src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>COGSAtForecast__c</fullName>
        <label>COGS At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_CogsExpensesFieldCalculation.cls
/**
*  Class that contains the Logic to calculate fields on the LedgerEntry__c Object
*     Fields: Gross Revenue, Gross Per Paid, Contra at Forecast, Contra % at Forecast, Net Revenue and Net Per Paid
*  <p>This class should have the least amount of code possible to reduce security concerns.</p>
*  @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
**/

public class LNE_CogsExpensesFieldCalculation {
    
    
    public static final string DELIMITER = DataGenerationSettings__c.getInstance().CombinedKeyDelimiter__c;
    
    public static final string RATE_TYPE_FLAT = 'Flat';
    public static final string RATE_TYPE_PER_CAP = 'Per Cap';
    
    public static final string TICKET_SCALE_ALL_PAID_TICKETS = 'All Paid Tickets';
    public static final string TICKET_SCALE_ALL_DROP_COUNT = 'All Drop Count';
    public static final string TICKET_SCALE_SELECTED_TICKETS = 'Selected Tickets';
    
    public static final string ERR_NO_RELATED_EVENT = 'No Related Event';
    public static final string ERR_PROJECTED_PAID_TICKETS_NULL = 'Projected Paid Tickets on Related Event is not set';
    public static final string ERR_PROJECTED_DROP_COUNT_NULL = 'Projected Drop Count on Related Event is not set';
    
    class CustomException extends Exception{}
    
    
/**
*  Method to return a Ledger Entry with all updated fields to Grid Buddy
*  @param LedgerEntry__c
*  @return LedgerEntry__c
**/
    public static LedgerEntry__c calculateFieldsOnGrid(LedgerEntry__c ledgerEntry){

        System.debug(ledgerEntry);
        
        //-- handle any fields that are required, but were not blocked prior to coming here.
        if(
            ledgerEntry.BaseAmount__c == null
        ){
            return( ledgerEntry );
        }
        
        LedgerEntry__c savedLedgerEntry = [SELECT Id, TicketScaleList__c, Event__c FROM LedgerEntry__c WHERE Id =:ledgerEntry.Id];
        List<TicketScale__c> listOfTicketScales = new List<TicketScale__c>();
        if(savedLedgerEntry.TicketScaleList__c != null){
           String[] listOfTicketScaleIds = savedLedgerEntry.TicketScaleList__c.split('\\' + DELIMITER);
            //if(Test.isRunningTest()){
            //    listOfTicketScaleIds = savedLedgerEntry.TicketScaleList__c.split('\\|');
            //}
            listOfTicketScales = [SELECT Id, ProjectedPaidTickets__c, Comps__c, Event__c FROM TicketScale__c WHERE Id IN :listOfTicketScaleIds];     
        }
        Event__c relatedEvent = [SELECT Id, ProjectedPaidTickets__c, ProjectedDropCount__c FROM Event__c WHERE Id =:savedLedgerEntry.Event__c ];
        
        if( relatedEvent == null ){
            throw( new CustomException( ERR_NO_RELATED_EVENT ));
        } else if( relatedEvent.ProjectedPaidTickets__c == null ){
            throw( new CustomException( ERR_PROJECTED_PAID_TICKETS_NULL ));
        } else if( relatedEvent.ProjectedDropCount__c == null ){
            throw( new CustomException( ERR_PROJECTED_DROP_COUNT_NULL ));
        }
        
        //System.debug('query result ' + listOfTicketScales);
        ledgerEntry = calculateForecast(ledgerEntry, listOfTicketScales, relatedEvent);

        System.debug(ledgerEntry);
        return ledgerEntry;
    }

/**
*  Method to calculate the forecast field on LedgerEntry__c Object.
*  @param LedgerEntry__c, List<TicketScale__c>, Event__c
*  @return LedgerEntry__c
**/
    public static LedgerEntry__c calculateForecast(LedgerEntry__c ledgerEntry, List<TicketScale__c> listOfTicketScales, Event__c relatedEvent){
        
        Decimal ticketRule = 0;
        //If the Rate Type of the Ledger Entry is FLat, then the Gross Revenue is equals to Base Amount.
        if(ledgerEntry.RateType__c == RATE_TYPE_FLAT){
            ledgerEntry.COGSAtForecast__c = ledgerEntry.BaseAmount__c;
            
        }
        //If the Rate Type of the Ledger Entry is Per Cap, then the Gross Revenue is calculated applying the ticket scale rule.
        else{
            if(ledgerEntry.ApplyTicketScale__c == TICKET_SCALE_ALL_PAID_TICKETS){
                ledgerEntry.COGSAtForecast__c = ledgerEntry.BaseAmount__c * relatedEvent.ProjectedPaidTickets__c;
            }else if(ledgerEntry.ApplyTicketScale__c == TICKET_SCALE_ALL_DROP_COUNT ){
                ledgerEntry.COGSAtForecast__c = ledgerEntry.BaseAmount__c * relatedEvent.ProjectedDropCount__c;
            }else if(ledgerEntry.ApplyTicketScale__c == TICKET_SCALE_SELECTED_TICKETS){
                ticketRule = 0;
                for(TicketScale__c ticketScale : listOfTicketScales){
                    if( ticketScale.ProjectedPaidTickets__c != null ){
                        ticketRule += ticketScale.ProjectedPaidTickets__c;
                    }
                }
                ledgerEntry.COGSAtForecast__c = ledgerEntry.BaseAmount__c * ticketRule;
            }else{
                ledgerEntry.COGSAtForecast__c = ledgerEntry.BaseAmount__c;
            }
            
        }
        
        // If the resulting Gross Revenue is below the min or above the max, it takes the value of those fields.
        if((ledgerEntry.Min__c != null && ledgerEntry.Min__c > 0) && ledgerEntry.COGSAtForecast__c < ledgerEntry.Min__c){
            ledgerEntry.COGSAtForecast__c = ledgerEntry.Min__c;
        }
        if((ledgerEntry.Max__c != null && ledgerEntry.Max__c > 0) && ledgerEntry.COGSAtForecast__c > ledgerEntry.Max__c){
            ledgerEntry.COGSAtForecast__c = ledgerEntry.Max__c;
        }
        
        return ledgerEntry;
    }

}