src/objects/DataGenerationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Wide settings that provides configuration for data being generated. These are expected to remain constant for all users.</description>
    <fields>
        <fullName>CombinedKeyDelimiter__c</fullName>
        <defaultValue>&quot;|&quot;</defaultValue>
        <description>Delimiter used when combining multiple keys.</description>
        <inlineHelpText>Delimiter used when combining multiple keys. Should be an irregularly used glyph (such as &apos;|&apos; or &apos;~&apos;)</inlineHelpText>
        <label>Combined Key Delimiter</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Generation Settings</label>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>RelatedContra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contra</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Related Contra (GL Account)</relationshipLabel>
        <relationshipName>GLAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAtForecast__c</fullName>
        <label>Contra At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccountRelatedContra__c</fullName>
        <description>System field. Used only in Apex triggers.</description>
        <formula>GLAccount__r.RelatedContra__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GL Account Related Contra</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RollUpCount__c</fullName>
        <label>Roll-Up Count</label>
        <summaryFilterItems>
            <field>LedgerEntryBreakout__c.SettlementOnly__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>LedgerEntryBreakout__c.LedgerEntry__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAtForecast__c</fullName>
        <label>Contra At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry Breakout</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_RollupContraForecast_T.cls
/** 
 *  Trigger logic to rollup the Contra at Forecast for all Ancillary Ledger Entries that have the same GL Account.Related Contra
 *  <p>Assumes that the trigger will be run on an after update, after insert or after delete</p>
 *  @author Anubhav Gupta <agupta2733@altimetrik.com>
 **/
public class LNE_RollupContraForecast_T {    

  /**
   *  Create/ Update a Child shadow Ledger Entry Breakout Record when Ancillary Ledger Entry is created/ updated
   *  @param newLedgerEntries List<LedgerEntry__c>
   *  @param oldLedgerEntries List<LedgerEntry__c>  
   *  @return void
  **/
    
    public static void execute( List<LedgerEntry__c> newLedgerEntries, Map<Id,LedgerEntry__c> oldLedgerEntries){
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(new String[]{ 'LedgerEntry__c.Ancillary', 'LedgerEntry__c.Contra'});         
        Id RT_LEDGER_ENTRY_ANCILLARY = recordTypeMap.get( 'LedgerEntry__c.Ancillary' );  //recordtypeid for ancillary ledger entry        
        Id RT_LEDGER_ENTRY_CONTRA = recordTypeMap.get( 'LedgerEntry__c.Contra' );    //recordtypeid for contra ledger entry 
        String COMBINED_KEY_DELIMITER  = DataGenerationSettings__c.getOrgDefaults().CombinedKeyDelimiter__c;    
        List<LedgerEntry__c> validLedgerEntries = new List<LedgerEntry__c>();       
        Map<Id, Id> ledgerContraGLMap = new Map<Id, Id>();
        Map<Id, List<LedgerEntry__c>> contraGLLedgerMap = new Map<Id, List<LedgerEntry__c>>();
        Set<Id> eventIdSet = new Set<Id>();
        List<LedgerEntry__c> contraLedgerEntries = new List<LedgerEntry__c>();
        Map<String, LedgerEntry__c> lEntryToUpsert = new Map<String, LedgerEntry__c>();
        List<LedgerEntryBreakout__c> lEBreakoutToUpsert = new List<LedgerEntryBreakout__c>();
        
        List<LedgerEntry__c> validLedgerEntriesDelete = new List<LedgerEntry__c>();
        Set<String> externalIdLEBreakout = new Set<String>();
        List<LedgerEntryBreakout__c> lEBreakoutToDelete = new List<LedgerEntryBreakout__c>();
        Set<Id> ledgerEntryRollup = new Set<Id>();
        List<LedgerEntry__c> ledgerEntryRollupCheck = new List<LedgerEntry__c>();
        List<LedgerEntry__c> ledgerEntryToDelete = new List<LedgerEntry__c>();
        
        
        List<LedgerEntry__c> newLedgerEntriesInsert = [Select Id, recordtypeId, Event__c, GLAccount__c, GLAccount__r.RelatedContra__c,ContraAtForecast__c, GLAccountRelatedContra__c
                                                      ,RollUpCount__c, ExternalId__c, RateType__c, BaseAmount__c from LedgerEntry__c where id in :newLedgerEntries];
                                                      

        //List<LedgerEntry__c> newLedgerEntriesInsert = newLedgerEntries;                                       
        //filtering the ledger entries based on Contra at Forecast
        if(oldLedgerEntries != null && !oldLedgerEntries.isEmpty()){
            for(LedgerEntry__c nLedger : newLedgerEntriesInsert){
                LedgerEntry__c nLedgerold = oldLedgerEntries.get(nLedger.Id);
                if((nLedger.recordtypeId == RT_LEDGER_ENTRY_ANCILLARY) && (String.isNotBlank(nLedger.GLAccountRelatedContra__c))
                    &&(nLedger.ContraAtForecast__c != nLedgerOld.ContraAtForecast__c)){
                    
                    if((nLedger.ContraAtForecast__c != 0) && (nLedger.ContraAtForecast__c != null)){
                        validLedgerEntries.add(nLedger);        
                        System.debug('-- Valid for Rollup');
                    }
                    
                    else if((nLedger.ContraAtForecast__c == 0) || (nLedger.ContraAtForecast__c == null)){
                        validLedgerEntriesDelete.add(nLedger);    
                        System.debug('-- Valid for Delete');                
                    }
                    else{
                        System.debug('--Ledger Entry does not satisfy criteria');
                    }
                }
            }
        }
        else {
            for(LedgerEntry__c nLedger : newLedgerEntriesInsert){
                if((nLedger.recordtypeId == RT_LEDGER_ENTRY_ANCILLARY) && (String.isNotBlank(nLedger.GLAccountRelatedContra__c))){
                    
                    if((nLedger.ContraAtForecast__c != 0) && (nLedger.ContraAtForecast__c != null)){
                        validLedgerEntries.add(nLedger);        
                        System.debug('-- Valid for Rollup');
                    }

                    else{
                        System.debug('--Ledger Entry does not satisfy criteria');
                    }
                }
            }               
        }

        if(!validLedgerEntries.isEmpty()){
            for(LedgerEntry__c nLedger : validLedgerEntries){     
                if(!ledgerContraGLMap.containsKey(nLedger.Id)){
                    ledgerContraGLMap.put(nLedger.Id, nLedger.GLAccountRelatedContra__c);
                } 
                eventIdSet.add(nLedger.Event__c);   
            }
            System.debug('--ledgerContraGLMap ' + ledgerContraGLMap);
            System.debug('--ledgerContraGLMap.keyset() ' + ledgerContraGLMap.keyset());
            System.debug('--eventIdSet ' + eventIdSet);
            contraLedgerEntries = [Select Id, recordtypeId, Event__c, GLAccount__c,ContraAtForecast__c,ExternalId__c
                                  , RateType__c, BaseAmount__c from LedgerEntry__c where GLAccount__c in :ledgerContraGLMap.values()
                                  and recordtypeid = :RT_LEDGER_ENTRY_CONTRA and event__c in :eventIdSet];
            System.debug('--contraLedgerEntries '+ contraLedgerEntries);
            for(LedgerEntry__c nLedger : contraLedgerEntries){
                if(!contraGLLedgerMap.containsKey(nLedger.GLAccount__c)){
                    contraGLLedgerMap.put(nLedger.GLAccount__c, new List<LedgerEntry__c>{nLedger});
                }
                else {
                    if(!contraGLLedgerMap.get(nLedger.GLAccount__c).isEmpty()){
                        contraGLLedgerMap.get(nLedger.GLAccount__c).add(nLedger);   
                    }
                    else {
                        contraGLLedgerMap.put(nLedger.GLAccount__c, new List<LedgerEntry__c>{nLedger}); 
                    }   
                }   
            }
            System.debug('--contraGLLedgerMap ' + contraGLLedgerMap);
            System.debug('--contraGLLedgerMap.keyset() ' + contraGLLedgerMap.keyset());         
              
            for(LedgerEntry__c nLedger : validLedgerEntries){
                if(!contraGLLedgerMap.containsKey(ledgerContraGLMap.get(nLedger.Id))){
                    System.debug('-- Create a Contra Ledger Entry');
                    LedgerEntry__c lEntry = new LedgerEntry__c();
                    lEntry.recordTypeId = RT_LEDGER_ENTRY_CONTRA;
                    lEntry.event__c = nLedger.event__c;
                    lEntry.GLAccount__c = ledgerContraGLMap.get(nLedger.Id);
                    lEntry.ExternalId__c = String.valueOf(nLedger.Event__c) + COMBINED_KEY_DELIMITER +String.valueOf(ledgerContraGLMap.get(nLedger.Id));
                    //lEntry.ExternalId__c = String.valueOf(nLedger.Event__c) + String.valueOf(ledgerContraGLMap.get(nLedger.Id));
                    System.debug('--lEntry.ExternalId__c '+lEntry.ExternalId__c);
                    lEntry.RateType__c = 'Flat';
                    lEntry.BaseAmount__c = nLedger.BaseAmount__c;
                    lEntry.ContraAtForecast__c = nLedger.ContraAtForecast__c;
                    if(lEntryToUpsert.isEmpty()){
                        lEntryToUpsert.put(lEntry.ExternalId__c, lEntry);
                    }
                    else if(!lEntryToUpsert.containsKey(lEntry.ExternalId__c)){
                        lEntryToUpsert.put(lEntry.ExternalId__c, lEntry);       
                    }
                    System.debug('-- lEntryToUpsert '+lEntryToUpsert);
                }
            }    
            if(!lEntryToUpsert.isEmpty()){
                List<Database.UpsertResult> srList = Database.upsert(lEntryToUpsert.values(),ledgerEntry__c.Fields.externalid__c, false);    
                String errMessage;
                for(Database.UpsertResult sr:srList){
                    if(!sr.isSuccess()){
                        errMessage = sr.getErrors()[0].getMessage();
                    }
                    System.debug('--errMessage '+ errMessage);
                    System.debug('-- After Upsert');
                    }
            }  
            
            contraLedgerEntries = [Select Id, recordtypeId, Event__c, GLAccount__c,ContraAtForecast__c,ExternalId__c
                                  , RateType__c, BaseAmount__c from LedgerEntry__c where GLAccount__c in :ledgerContraGLMap.values()
                                  and recordtypeid = :RT_LEDGER_ENTRY_CONTRA and event__c in :eventIdSet];
            System.debug('--contraLedgerEntries '+ contraLedgerEntries);                                  
            contraGLLedgerMap.clear();
            for(LedgerEntry__c nLedger : contraLedgerEntries){
                if(!contraGLLedgerMap.containsKey(nLedger.GLAccount__c)){
                    contraGLLedgerMap.put(nLedger.GLAccount__c, new List<LedgerEntry__c>{nLedger});
                }
                else {
                    if(!contraGLLedgerMap.get(nLedger.GLAccount__c).isEmpty()){
                        contraGLLedgerMap.get(nLedger.GLAccount__c).add(nLedger);   
                    }
                    else {
                        contraGLLedgerMap.put(nLedger.GLAccount__c, new List<LedgerEntry__c>{nLedger}); 
                    }   
                }               
            }  
            
            System.debug('--contraGLLedgerMap ' + contraGLLedgerMap);
            System.debug('--contraGLLedgerMap.keyset() ' + contraGLLedgerMap.keyset());             

            for(LedgerEntry__c nLedger : validLedgerEntries){
                LedgerEntryBreakout__c lEBreakout = new LedgerEntryBreakout__c();     
                lEBreakout.ExternalId__c = String.valueOf(nLedger.Event__c) + COMBINED_KEY_DELIMITER  + String.valueOf(nLedger.GLAccount__c);  
                //lEBreakout.ExternalId__c = String.valueOf(nLedger.Event__c) + String.valueOf(nLedger.GLAccount__c); 
                List<LedgerEntry__c> ledgerEntryContra = contraGLLedgerMap.get(ledgerContraGLMap.get(nLedger.Id)); 
                if(ledgerEntryContra!= null){
                    for(LedgerEntry__c lEntryContra : ledgerEntryContra){
                        if(lEntryContra.event__c == nLedger.event__c){
                            lEBreakout.LedgerEntry__c =  lEntryContra.Id;
                        }   
                    }
                }
                lEBreakout.RateType__c = 'Flat';
                lEBreakout.BaseAmount__c = nLedger.BaseAmount__c;                
                lEBreakout.ContraAtForecast__c =  nLedger.ContraAtForecast__c; 
                lEBreakoutToUpsert.add(lEBreakout);
            }  
            if(!lEBreakoutToUpsert.isEmpty()){
                list<Database.UpsertResult> srList = Database.upsert(lEBreakoutToUpsert, ledgerEntryBreakout__c.Fields.externalid__c,false);    
                String errMessage;
                for(Database.UpsertResult sr:srList){
                    if(!sr.isSuccess()){
                        errMessage = sr.getErrors()[0].getMessage();
                    }
                    System.debug('--errMessage '+ errMessage);
                    System.debug('-- After Ledger Entry Breakout Upsert');
                    }           
                    
            }                 
        }

        if(!validLedgerEntriesDelete.isEmpty()){
            for(LedgerEntry__c nLedger : validLedgerEntriesDelete){
                String extId = String.valueOf(nLedger.Event__c)  + COMBINED_KEY_DELIMITER  + String.valueOf(nLedger.GLAccount__c);
                //String extId = String.valueOf(nLedger.Event__c) + String.valueOf(nLedger.GLAccount__c);
                System.debug('--extId '+extId);
                externalIdLEBreakout.add(extId);
            }
            System.debug('--externalIdLEBreakout '+externalIdLEBreakout);
            lEBreakoutToDelete = [Select Id, ledgerEntry__c, externalId__c from ledgerEntrybreakout__c where externalId__c in :externalIdLEBreakout];
            System.debug('--lEBreakoutToDelete '+lEBreakoutToDelete);
            if(!lEBreakoutToDelete.isEmpty()){
                Database.delete(lEBreakoutToDelete, false); 
                for(ledgerEntrybreakout__c lEBreakout : lEBreakoutToDelete){
                    ledgerEntryRollup.add(lEBreakout.ledgerEntry__c);
                }
                System.debug('--ledgerEntryRollup '+ledgerEntryRollup);
                ledgerEntryRollupCheck = [Select id, RollUpCount__c from ledgerEntry__c where id in :ledgerEntryRollup];
                for(LedgerEntry__c nLedger : ledgerEntryRollupCheck){
                    if(nLedger.RollUpCount__c == 0){
                        ledgerEntryToDelete.add(nLedger);
                    }
                }
                System.debug('--ledgerEntryToDelete '+ledgerEntryToDelete);
                if(!ledgerEntryToDelete.isEmpty()){
                    Database.delete(ledgerEntryToDelete, false);    
                }
            }
        }   

    }
    
    
  /**
   *  Delete the Child Shadow Ledger Entry Breakout record when the Ancillary Ledger Entry is deleted
   *  @param oldLedgerEntries List<LedgerEntry__c>
   *  @return void
  **/   
    public static void executeDelete( List<LedgerEntry__c> oldLedgerEntries){
        
        String COMBINED_KEY_DELIMITER  = DataGenerationSettings__c.getOrgDefaults().CombinedKeyDelimiter__c;
        Set<String> externalIdLEBreakout = new Set<String>();
        List<LedgerEntryBreakout__c> lEBreakoutToDelete = new List<LedgerEntryBreakout__c>();
        Set<Id> ledgerEntryRollup = new Set<Id>();
        List<LedgerEntry__c> ledgerEntryRollupCheck = new List<LedgerEntry__c>();
        List<LedgerEntry__c> ledgerEntryToDelete = new List<LedgerEntry__c>();  
        
         if(!oldLedgerEntries.isEmpty()){
            for(LedgerEntry__c nLedger : oldLedgerEntries){
                String extId = String.valueOf(nLedger.Event__c)  + COMBINED_KEY_DELIMITER  + String.valueOf(nLedger.GLAccount__c);
                //String extId = String.valueOf(nLedger.Event__c) + String.valueOf(nLedger.GLAccount__c);
                System.debug('--extId '+extId);
                externalIdLEBreakout.add(extId);
            }
            System.debug('--externalIdLEBreakout '+externalIdLEBreakout);
            lEBreakoutToDelete = [Select Id, ledgerEntry__c, externalId__c from ledgerEntrybreakout__c where externalId__c in :externalIdLEBreakout];
            System.debug('--lEBreakoutToDelete '+lEBreakoutToDelete);
            if(!lEBreakoutToDelete.isEmpty()){
                Database.delete(lEBreakoutToDelete, false); 
                for(ledgerEntrybreakout__c lEBreakout : lEBreakoutToDelete){
                    ledgerEntryRollup.add(lEBreakout.ledgerEntry__c);
                }
                System.debug('--ledgerEntryRollup '+ledgerEntryRollup);
                ledgerEntryRollupCheck = [Select id, RollUpCount__c from ledgerEntry__c where id in :ledgerEntryRollup];
                for(LedgerEntry__c nLedger : ledgerEntryRollupCheck){
                    if(nLedger.RollUpCount__c == 0){
                        ledgerEntryToDelete.add(nLedger);
                    }
                }
                System.debug('--ledgerEntryToDelete '+ledgerEntryToDelete);
                if(!ledgerEntryToDelete.isEmpty()){
                    Database.delete(ledgerEntryToDelete, false);    
                }
            }
        }       
    }
  
    
}