src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>BackendPercent__c</fullName>
        <label>Backend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DealApplicationType__c</fullName>
        <label>Deal Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DealType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>To Be Shared Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OtherTalentDescription__c</fullName>
        <label>Other Talent Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_CopyPrimaryHeadlinerToCoHeadliners_T.cls
/** 
 *  Trigger logic to copy Primary Headliner values to any Co-Headliner records ( parent Deal__c ).
 *  Copies Deal Type, Deal Application Type, Backend %, and Deal Calculation
 *  @author Dominic Aveyard
 **/
 public class LNE_CopyPrimaryHeadlinerToCoHeadliners_T {
    
    static final String RT_Artist = 'Deal__c.Artist';
    
    /**
    *  Updates coheadliners with values from primary headliner when primary changes.
    *  @param newList Deal__c[]
    *  @param oldMap Map<Id,Deal__c>
    *  @return Deal__c[] - list of ledger entries updated.
    **/
    public static Deal__c[] execute( Deal__c[] newList, Map<Id,Deal__c> oldMap ){
		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{ RT_Artist }
		);
		Id RT_ARTIST_ID = recordTypeMap.get( RT_Artist );
		
		Boolean changed = false;
        Id[] actionDealEventIds = new List<Id>();
        List<Deal__c> coheadliners = new List<Deal__c>();
        Map<String, Deal__c> eventPrimaryHeadlinersMap = new Map<String, Deal__c>();
        Map<Id, Deal__c> eventPrimaryHeadlinersMap2 = new Map<Id, Deal__c>();
        
        List<Deal__c> updatedCoHeadliners = new List<Deal__c>();
		
		//-- @TODO: pr 2/24 check for fields changing first, look into other opportunities for improvements.
		
		if( oldMap == null ){
			oldMap = new Map<Id,Deal__c>();
		}
		
		ChangedDeal cDeal;
		Deal__c oldDeal;
		for ( Deal__c nd : newList ) {
			
			if( oldMap.containsKey( nd.Id )){
	        	oldDeal = oldMap.get( nd.Id );
				cDeal = new ChangedDeal( oldDeal, nd );

			    //-- only continue if something has changed
			    
			    if(
			    	!(  cDeal.notEquals( 'RecordTypeId' ) ||
			    		cDeal.notEquals( 'BackendPercent__c') ||
			    		cDeal.notEqualsStr( 'Type__c', false ) ||
			    		cDeal.notEqualsStr( 'DealType__c', false ) ||
			    		cDeal.notEqualsStr( 'DealApplicationType__c', false ) ||
			    		cDeal.notEqualsStr( 'DealCalculation__c', false )
			    	 )
			    ){
			    	//-- neither the record type or the type field changed.
			    	continue;
			    }
			}
			
			if (
				nd.RecordTypeId == RT_ARTIST_ID &&
				(nd.Type__c == 'Primary Headliner' || nd.Type__c == 'Co-Headliner')
			){
                actionDealEventIds.add(nd.Event__c);
            }
        }
        
        if( actionDealEventIds == null || actionDealEventIds.size() < 1 ){
        	//-- no point in continuing
        	return(updatedCoHeadliners);
        }

        List<Deal__c> allDealList = new List<Deal__c>();
        if (actionDealEventIds.size() > 0){
            allDealList = [
                SELECT Event__c,
                       OtherTalentDescription__c,
                       DealApplicationType__c,
                       DealCalculation__c,
                       DealType__c,
                       BackendPercent__c,
                       Type__c,
                       StageType__c
                FROM Deal__c 
                WHERE Event__c IN :actionDealEventIds
                AND Type__c IN ('Primary Headliner', 'Co-Headliner')
            ];
        }
        
        for (Deal__c adl : allDealList ) {
            if (adl.Type__c == 'Primary Headliner') {
                eventPrimaryHeadlinersMap.put(adl.Event__c+adl.StageType__c, adl);
            }  
            if (adl.Type__c == 'Co-Headliner') {
                coheadliners.add(adl);
            }
        }

        for ( Deal__c ch : coheadliners ) {   
            Deal__c p = eventPrimaryHeadlinersMap.get(ch.Event__c+ch.StageType__c);

            if (p != null) {
                //-- copy: Deal Type, Deal Application Type, Backend %, and Deal Calculation
                changed = false;
                
                if (ch.DealType__c != p.DealType__c) {
                    ch.DealType__c = p.DealType__c;
                    changed = true;
                }
                if (ch.DealApplicationType__c != p.DealApplicationType__c) {
                    ch.DealApplicationType__c = p.DealApplicationType__c;
                    changed = true;
                }
                if (ch.BackendPercent__c != p.BackendPercent__c) {
                    ch.BackendPercent__c = p.BackendPercent__c;
                    changed = true;
                }
                if (ch.DealCalculation__c != p.DealCalculation__c) {
                    ch.DealCalculation__c = p.DealCalculation__c;
                    changed = true;
                }
                
                if (changed) {
                    updatedCoHeadliners.add(ch);
                }
            }
        }
        
        //   update all the coheadliners
        update (updatedCoHeadliners);

        return updatedCoHeadliners;
    }
    

    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedDeal extends LNE_SObjectChange {
        
        ChangedDeal( Deal__c oldObject, Deal__c newObject ){
            super( oldObject, newObject );
        }
        
        Deal__c getNewDeal(){
            return( (Deal__c)this.newObject );
        }
    }
}