src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Artist Deals</relationshipLabel>
        <relationshipName>ArtistDeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncludeArtistBonus__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Artist Bonus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeArtistEarnings__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Artist Earnings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeBonusWording__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Bonus Wording</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeBreakeven__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Breakeven</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeCoHeadliner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Co-Headliner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeCoPromoters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Co-Promoters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeDeductions__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Deductions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeEarningsPotentialSection__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Earnings Potential Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeExpenseBreakouts__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Expense Breakouts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeExpenses__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Expenses</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeMarketingNotes__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Marketing Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeMerchDeal__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Merch Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeNetGrossPotential__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Net Gross Potential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeOfferNotes__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Offer Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeOfferWording__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Offer Wording</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludePromoterEarnings__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Promoter Earnings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludePromotersAddress__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Promoter&apos;s Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeSummarySection__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Summary Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeTalentGuarantee__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Talent Guarantee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeTicketScalingMergedTotals__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Ticket Scaling Merged Totals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeTicketScaling__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Ticket Scaling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeToBeSharedAmount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include To Be Shared Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeTotalTalent__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Total Talent, S&amp;L, &amp; Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeVenueNotes__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Venue Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeSort__c</fullName>
        <description>Used to help sorting on the Event Offer Sheet tab.</description>
        <formula>CASE(Type__c,
&apos;Primary Headliner&apos;, -1,
&apos;Co-Headliner&apos;, BLANKVALUE(Rank__c, 999),
&apos;Support&apos;, 1000,
1001)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RomeFieldSetSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings and developer names of field sets used in the Rome Application.</description>
    <fields>
        <fullName>ArtistOfferPrimaryEarnings__c</fullName>
        <defaultValue>&quot;ArtistOfferPrimaryEarnings&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Primary Earnings</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferPrimarySummary__c</fullName>
        <defaultValue>&quot;ArtistOfferPrimarySummary&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Primary Summary</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferPrimaryTopLeft__c</fullName>
        <defaultValue>&quot;ArtistOfferPrimaryTopLeft&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Primary Top Left</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferPrimaryTopRight__c</fullName>
        <defaultValue>&quot;ArtistOfferPrimaryTopRight&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Primary Top Right</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferSupportEarnings__c</fullName>
        <defaultValue>&quot;ArtistOfferSupportEarnings&quot;</defaultValue>
        <label>Artist Offer Support Earnings</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferSupportTopLeft__c</fullName>
        <defaultValue>&quot;ArtistOfferSupportTopLeft&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Support Top Left</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArtistOfferSupportTopRight__c</fullName>
        <defaultValue>&quot;ArtistOfferSupportTopRight&quot;</defaultValue>
        <inlineHelpText>Field set used for Artist Offer parameter form</inlineHelpText>
        <label>Artist Offer Support Top Right</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rome Field Set Settings</label>
</CustomObject>

src/classes/LNE_EventOfferSheet_CX.cls
public with sharing class LNE_EventOfferSheet_CX {

	public String selectedDealIds {get;set;}
	public List<Deal__c> deals {get;private set;}

	public List<Schema.FieldSetMember> primaryEarnings {get;private set;}
	public List<Schema.FieldSetMember> primarySummary {get;private set;}
	public List<Schema.FieldSetMember> primaryTopLeft {get;private set;}
	public List<Schema.FieldSetMember> primaryTopRight {get;private set;}
	public List<Schema.FieldSetMember> supportEarnings {get;private set;}
	public List<Schema.FieldSetMember> supportTopLeft {get;private set;}
	public List<Schema.FieldSetMember> supportTopRight {get;private set;}
	
	public LNE_EventOfferSheet_CX(ApexPages.StandardController sc) {
		
		this.selectedDealIds = '';
		this.deals = new List<Deal__c>([
			select
				Artist__r.Name,
				IncludeArtistBonus__c,
				IncludeArtistEarnings__c,
				IncludeBonusWording__c,
				IncludeBreakeven__c,
				IncludeCoHeadliner__c,
				IncludeCoPromoters__c,
				IncludeDeductions__c,
				IncludeEarningsPotentialSection__c,
				IncludeExpenseBreakouts__c,
				IncludeExpenses__c,
				IncludeMarketingNotes__c,
				IncludeMerchDeal__c,
				IncludeNetGrossPotential__c,
				IncludeOfferNotes__c,
				IncludeOfferWording__c,
				IncludePromoterEarnings__c,
				IncludePromotersAddress__c,
				IncludeSummarySection__c,
				IncludeTalentGuarantee__c,
				IncludeTicketScaling__c,
				IncludeTicketScalingMergedTotals__c,
				IncludeToBeSharedAmount__c,
				IncludeTotalTalent__c,
				IncludeVenueNotes__c,
				Type__c
			from Deal__c
			where Event__c = :sc.getId()
			and Type__c in ('Primary Headliner', 'Co-Headliner', 'Support')
			and StageType__c = 'Plan'
			order by 
				TypeSort__c,
				Artist__r.Name
		]);

		initFieldSets();

	}

	public void saveDeals() {

		if (String.isNotBlank(this.selectedDealIds)) {

			Set<Id> dealIds = new Set<Id>((List<Id>)this.selectedDealIds.split(','));
			Map<Id,Deal__c> dealsMap = new Map<Id,Deal__c>(this.deals);
			List<Deal__c> selectedDeals = new List<Deal__c>();

			for (Id dealId : dealIds) {
				if (dealsMap.containsKey(dealId)) {
					selectedDeals.add(dealsMap.get(dealId));
				}
			}

			Database.update(selectedDeals, false);

		}

	}

	private void initFieldSets() {

		RomeFieldSetSettings__c settings = RomeFieldSetSettings__c.getInstance();
		Map<String,Schema.FieldSet> fieldSets = Schema.SObjectType.Deal__c.FieldSets.getMap();

		this.primaryEarnings = fieldSets.get(settings.ArtistOfferPrimaryEarnings__c).getFields();
		this.primarySummary = fieldSets.get(settings.ArtistOfferPrimarySummary__c).getFields();
		this.primaryTopLeft = fieldSets.get(settings.ArtistOfferPrimaryTopLeft__c).getFields();
		this.primaryTopRight = fieldSets.get(settings.ArtistOfferPrimaryTopRight__c).getFields();
		this.supportEarnings = fieldSets.get(settings.ArtistOfferSupportEarnings__c).getFields();
		this.supportTopLeft = fieldSets.get(settings.ArtistOfferSupportTopLeft__c).getFields();
		this.supportTopRight = fieldSets.get(settings.ArtistOfferSupportTopRight__c).getFields();

	}

}