src/objects/Deal__c.object
<CustomObject>
    <description>The terms and relationships of artists, co-promoters, and possibly 3rd-party venues or other partners in an event who are required to participate in event revenues and/or expenses</description>
    <fields>
        <fullName>AncillaryShareAmountAtProjection__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEAncillaryShareAmountAtProjection__c,
   /* F */
   IF ((ProfitShareAmtAtProjFC__c + ExpenseAdjustShareAmtAtProjFC__c + AncillaryShareAmtAtProjFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      AncillaryRevenue__c *  AncillaryShareAmtAtProjFC__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ancillary Share Amount At Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AncillaryShareAmountAtSellout__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEAncillaryShareAmountAtSellout__c,
   /* F */
   IF ((ProfitShareAmtAtSellFC__c + ExpenseAdjustShareAmtAtSellFC__c + AncillaryShareAmtAtSellFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      AncillaryRevenue__c *  AncillaryShareAmtAtSellFC__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ancillary Share Amount At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ArtistSuppliedSL__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Artist Supplied S&amp;L</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BackendPercent__c</fullName>
        <label>Backend %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BackendPotential__c</fullName>
        <label>Backend Potential</label>
        <summarizedField>ArtistRetroStepUpDetail__c.BackendPotentialNonFormula__c</summarizedField>
        <summaryForeignKey>ArtistRetroStepUpDetail__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CoPromoterBonusAtProjection__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   0,
   IF((ProfitShareAmtAtProjFC__c + ExpenseAdjustShareAmtAtProjFC__c + AncillaryShareAmtAtProjFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      0,
      ProjectedBonus__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Promoter Bonus At Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CoPromoterBonusAtSellout__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   0,
   IF ((ProfitShareAmtAtSellFC__c + ExpenseAdjustShareAmtAtSellFC__c + AncillaryShareAmtAtSellFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      0,
      BonusPotential__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Promoter Bonus At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CoPromoterWalkoutAtProjection__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   LNECoPromoterWalkoutAtProjection__c ,
   IF((ProfitShareAmtAtProjFC__c + ExpenseAdjustShareAmtAtProjFC__c + AncillaryShareAmtAtProjFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      0,
      ProfitShareAmountAtProjection__c +  ExpenseAdjustmentShareAmountAtProj__c + AncillaryShareAmountAtProjection__c + CoPromoterBonusAtProjection__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Promoter Walkout At Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CoPromoterWalkoutAtSellout__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   LNECoPromoterWalkoutAtSellout__c ,
   IF ((ProfitShareAmtAtSellFC__c + ExpenseAdjustShareAmtAtSellFC__c + AncillaryShareAmtAtSellFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      0,
      ProfitShareAmountAtSellout__c +  ExpenseAdjustmentShareAmountAtSell__c + AncillaryShareAmountAtSellout__c + CoPromoterBonusAtSellout__c
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Promoter Walkout At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DealCalculation__c</fullName>
        <label>Deal Calculation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guarantee Only</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Sound &amp; Lights &amp; Support &amp; Other Talent Amount</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support</fullName>
                </value>
                <value>
                    <fullName>Inclusive of Support And Other Talent Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealType__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Gross Split Point</fullName>
                </value>
                <value>
                    <fullName>Percentage of Gross</fullName>
                </value>
                <value>
                    <fullName>Percentage of Net</fullName>
                </value>
                <value>
                    <fullName>Promoter Profit</fullName>
                </value>
                <value>
                    <fullName>Retro Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Retro Net Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Gross Deal</fullName>
                </value>
                <value>
                    <fullName>Step Up Net Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentShareAmountAtProj__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEExpenseAdjShareAmountAtProj__c ,
   /* F */
   IF ((ProfitShareAmtAtProjFC__c + ExpenseAdjustShareAmtAtProjFC__c + AncillaryShareAmtAtProjFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      IF (ProfitShareAmtAtProjFC__c &gt;= 0,
         /* T */
         ExpenseAdjustmentProfit__c *  ExpenseAdjustShareAmtAtProjFC__c ,
         /* F */
         ExpenseAdjustmentLoss__c * ExpenseAdjustShareAmtAtProjFC__c
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment Share Amount At Proj</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpenseAdjustmentShareAmountAtSell__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEExpenseAdjShareAmountAtSell__c ,
   /* F */
   IF ((ProfitShareAmtAtSellFC__c + ExpenseAdjustShareAmtAtSellFC__c + AncillaryShareAmtAtSellFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      IF (ProfitShareAmtAtSellFC__c &gt;= 0,
         /* T */
         ExpenseAdjustmentProfit__c *  ExpenseAdjustShareAmtAtSellFC__c ,
         /* F */
         ExpenseAdjustmentLoss__c * ExpenseAdjustShareAmtAtSellFC__c
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Adjustment Share Amount At Sell</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GuaranteeAmount__c</fullName>
        <label>Guarantee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OtherTalentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Other Talent Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProfitShareAmountAtProjection__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEProfitShareAmountAtProjection__c ,
   /* F */
   IF ((ProfitShareAmtAtProjFC__c + ExpenseAdjustShareAmtAtProjFC__c + AncillaryShareAmtAtProjFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      IF (ProfitShareAmtAtProjFC__c &gt;= 0,
         /* T */
         EventProfit__c * ProfitShareAmtAtProjFC__c,
         /* F */
         EventLoss__c * ProfitShareAmtAtProjFC__c
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profit Share Amount At Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProfitShareAmountAtSellout__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Internal&apos;),
   /* T */
   LNEProfitShareAmountAtSellout__c ,
   /* F */
   IF ((ProfitShareAmtAtSellFC__c + ExpenseAdjustShareAmtAtSellFC__c + AncillaryShareAmtAtSellFC__c &lt; 0) &amp;&amp;  DownsideRisk__c = False,
      /* T */
      0,
      /* F */
      IF (ProfitShareAmtAtSellFC__c &gt;= 0,
         /* T */
         EventProfit__c * ProfitShareAmtAtSellFC__c,
         /* F */
         EventLoss__c * ProfitShareAmtAtSellFC__c
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profit Share Amount At Sellout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RollUpTalentOverheadAmount__c</fullName>
        <label>Roll-Up Talent Overhead Amount</label>
        <summarizedField>TalentOverhead__c.Amount__c</summarizedField>
        <summaryForeignKey>TalentOverhead__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ShareInTalentOverhead__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Share In Talent Overhead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SplitPercentage__c</fullName>
        <label>Split %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Headliner</fullName>
                </value>
                <value>
                    <fullName>Co-Headliner</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Dea-{000000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Artist</fullName>
        <active>true</active>
        <label>Artist</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_DealMetrics_T.cls
/**
 *	Trigger logic to check for changes on any fields that would cause the
 *	financial calculator to fire off
 *	@author Sebastian Gutierrez
 **/
public with sharing class LNE_DealMetrics_T {
	static final String RT_DEAL_ARTIST = 'Deal__c.Artist';

    static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
        new String[]{ RT_DEAL_ARTIST }
    );
    static Id RT_DEAL_ARTIST_ID = recordTypeMap.get( RT_DEAL_ARTIST );
    
	/**
     *  Checks if any fields changed that would require a recalculation of event totals
     *  @param newList Deal__c[]
     *  @param oldMap Map<Id,Deal__c>
     *  @return Dealt__c[] - list of deals updated.
    **/
    
    public static Deal__c[] execute( Deal__c[] newList, Map<Id,Deal__C> oldMap ){
    	List<Deal__c> changedDeals = new List<Deal__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();
        ChangedDeal objChange = null;

 		if (oldMap == null){
            oldMap = new Map<Id, Deal__c>();
        }

        for (Deal__c newDeal : newList ){
            if(oldMap.containsKey(newDeal.Id)){
                
                Deal__c oldDeal = oldMap.get(newDeal.Id);
                objChange = new ChangedDeal(oldDeal, newDeal);
                
                if(
                    objChange.notEquals('GuaranteeAmount__c') ||
                    objChange.notEquals('BackendPotential__c') ||
                    objChange.notEquals('BackendPercent__c') ||
                    objChange.notEquals('OtherTalentAmount__c') ||
                    objChange.notEquals('ArtistSuppliedSL__c') ||
                    objChange.notEquals('DealType__c') ||
                    objChange.notEquals('DealCalculation__c') ||
                    objChange.notEquals('ShareInTalentOverhead__c') ||
                    objChange.notEquals('RollUpTalentOverheadAmount__c') ||
                    objChange.notEquals('ProfitShareAmountAtSellout__c') ||
                    objChange.notEquals('ProfitShareAmountAtProjection__c') ||
                    objChange.notEquals('ExpenseAdjustmentShareAmountAtSell__c') ||
                    objChange.notEquals('ExpenseAdjustmentShareAmountAtProj__c') ||
                    objChange.notEquals('CoPromoterBonusAtSellout__c') ||
                    objChange.notEquals('CoPromoterBonusAtProjection__c') ||
                    objChange.notEquals('CoPromoterWalkoutAtSellout__c') ||
                    objChange.notEquals('CoPromoterWalkoutAtProjection__c') ||
                    objChange.notEquals('AncillaryShareAmountAtSellout__c') ||
                    objChange.notEquals('AncillaryShareAmountAtProjection__c') ||
                    objChange.notEquals('StageType__c') ||
                    objChange.notEquals('SplitPercentage__c') ||
                    objChange.notEquals('ProjectedArtistEarnings__c') ||
                    objChange.notEquals('Type__c') 
                ) {
                  
                  listOfRelatedEventIds.add(newDeal.Event__c);
            	}
            }
            LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);
        }
		return changedDeals;
        
    }

    /**
     *  Recalculates for deleted Deals
     *  @param Deals[] - list of deleted Deals.
     *  @return Deals[] - list of Deals updated.
    **/
    
     public static Deal__c[] execute( Deal__c[] deletedList ){
    	List<Deal__c> ChangedDeals = new List<Deal__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();

 		for (Deal__c deletedDeal : deletedList){
 		    if (deletedDeal.Event__c != null) {
            	listOfRelatedEventIds.add(deletedDeal.Event__c);	
            }
            ChangedDeals.add(deletedDeal);
 		}
 		
 		LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);

		return ChangedDeals;
    }
    
    public static void findPreviousEventInMarket(Deal__c[] newList, Map<Id,Deal__C> oldMap) {
    	
    	Set<Id> eventIds = new Set<Id>();
    	
    	if (oldMap == null) {
    		for (Deal__c d : newList) {
    			if (d.RecordTypeId == RT_DEAL_ARTIST_ID && d.Type__c == 'Primary Headliner') {
    				eventIds.add(d.Event__c);
    			}
    		}
    	} else if (oldMap != null && newList != null) {
    		for (Deal__c d : newList) {
    			if (oldMap.get(d.Id) != null) {
    				Deal__c oldDeal = oldMap.get(d.Id);
    				
    				if (oldDeal.RecordTypeId != d.RecordTypeId || oldDeal.Artist__c != d.Artist__c) {
    					if (d.RecordTypeId == RT_DEAL_ARTIST_ID && d.Type__c == 'Primary Headliner') {
		    				eventIds.add(d.Event__c);
		    			}
    				}
    			}
    		}
    	} else if (oldMap != null && newList == null) {
    		for (Deal__c d : oldMap.values()) {
    			if (d.RecordTypeId == RT_DEAL_ARTIST_ID && d.Type__c == 'Primary Headliner') {
    				eventIds.add(d.Event__c);
    			}
    		}
    	}
    	
    	if (eventIds.size() > 0) {
    		LNE_FinancialCalculator.runUpdates = false;
    		Set<String> statusesForVenueChanged = new Set<String>{'Draft', 'Pending Unlikely', 'Pending Likely', 'Cancelled', 'Postponed'};
    		
    		List<Event__c> toUpdate = LNE_EventMetrics_T.findPreviousEvent([SELECT EventFirstDate__c, Market__c FROM Event__c WHERE Id IN :eventIds AND Status__c IN :statusesForVenueChanged]);
    		
    		if (toUpdate != null && toUpdate.size() > 0) {
    			update toUpdate;
    		}
    		
    		LNE_FinancialCalculator.runUpdates = true;
    	}
    }
    
    
    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedDeal extends LNE_SObjectChange {
        
        ChangedDeal( Deal__c oldObject, Deal__c newObject ){
            super( oldObject, newObject );
        }
        
        Deal__c getNewDeal(){
            return( (Deal__c)this.newObject );
        }
    }
    
}