src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Artist Add-On</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>FMF/Venue Charge</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Value Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>LedgerEntry__r.Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>ActualSalesToDate__c</fullName>
        <label>Actual Sales To Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_TicketScalesToLedgerController_Test.cls
/**
 * Test for LNE_TicketScalesToLedgerController.
 * @see US491
 * @see DE70
 * @see DE68
 * @see DE21
 * @see TA433
 **/
@isTest(SeeAllData=false)
public class LNE_TicketScalesToLedgerController_Test {
	
	static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';

    @TestSetup
    static void setup() {
		LNE_TestObjectFactory.prepStandardCustomSettings();

		//-- pr: can any of the items in the typical setup / global init be available here?
		
        //new TestSettings().typicalSetup();
        //// create event
        //Event__c e = new Event__c(
        //    Status__c = 'Draft'
        //);
        //insert e;

        //// create ticket scales
        //List<TicketScale__c> ticketScales = new List<TicketScale__c>();
        //for (Integer i = 0; i < 4; i++) {
        //    ticketScales.add(new TicketScale__c(
        //        Event__c = e.Id,
        //        ActualSalesToDate__c = 1,
        //        PriceLevel__c = 'PriceLevel__c',
        //        ProjectedPaidTickets__c = 1,
        //        StageType__c = 'Plan'
        //    ));
        //}
        //insert ticketScales;

        //// create ledger entry
        //LedgerEntry__c ledger = new LedgerEntry__c(
        //    Event__c = e.Id
        //);
        //insert ledger;
    }
    
    private class TestSettings {
    	
        public Event__c myEvent { get; private set; }
        public LedgerEntry__c testLedgerEntry { get; private set; }
        public LedgerEntryBreakout__c testLedgerEntryBreakout { get; private set; }
        public Deduction__c testDeduction { get; private set; }
        
        public TestSettings() {
        	
        	//-- we don't need the financial calculator to run until we're done with all this
        	LNE_FinancialCalculator.currentlyRunning = true;
        	LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
        	
        	//-- assert there should only be one event.
			this.myEvent = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = 'Draft'
            );
			
			LNE_TestObjectFactory.createStandardDataSet( this.myEvent );
        }
        
        
        public TestSettings typicalSetup(){
        	
        	//-- is any of this background, something we can assume will be there always?
            
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
                new String[]{ RT_Ancillary }
            );
            Id RT_ANCILLARY_ID = recordTypeMap.get( RT_Ancillary );
            
            LNE_Util.refreshGLAccountCache();
            
            Map<String,GLAccount__c> glAccountMap = LNE_Util.getGLAccounts(
            	new String[]{ LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE }
            );
            Id glAlcoholicRevenueId = glAccountMap.get( LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE ).Id;
        
            //GLAccount__c testGlaAcct1 = new GLAccount__c (
            //    Type__c = 'Ancillary',
            //    Name = 'Parking Revenue',
            //    Category__c = 'Other Event Revenue',
            //    GLCode__c = '12345'
            //);
            //insert testGlaAcct1;

            TicketScale__c ticketScale = new TicketScale__c(
                ActualSalesToDate__c = 10000,
                Event__c = this.myEvent.Id,
                PriceLevel__c = '1000',
                ProjectedPaidTickets__c = 10000,
                StageType__c = 'Plan'
            );
            insert ticketScale;
            
            LedgerEntry__c ledger1 = new LedgerEntry__c (
                GLAccount__c = glAlcoholicRevenueId,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                Event__c = this.myEvent.Id,
                TicketScaleList__c = '|' + ticketScale.Id + '|'
            ); 

            insert ledger1;

            LedgerEntryBreakout__c leb = new LedgerEntryBreakout__c();
            leb.LedgerEntry__c = ledger1.Id;
            insert leb;

            Deduction__c deduction = new Deduction__c();
            deduction.BeforeAfter__c = 'Before Adjusted';
            deduction.Event__c = this.myEvent.Id;
            deduction.RateType__c = 'Primary Multiplier Tax';
            deduction.AmountRate__c = 10;
            insert deduction;
           
            testLedgerEntry = ledger1;
            testLedgerEntryBreakout = leb;
            testDeduction = deduction;

            return this;

        }
        
        public TestSettings finalize(){
        	//-- now we're done with updating everything, have the financial calculator run.
        	LNE_FinancialCalculator.currentlyRunning = false;
        	LNE_FinancialCalculator.popRunningTrigger();
            return this;
        }
    }
    
    static testMethod void runSetupWithoutException() {
        try {
            TestSettings ts = new TestSettings();
            ts.typicalSetup();
            ts.finalize();
        } catch( Exception err ){
            //System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
        }
    }
    
    //-- test test methods here
    static testMethod void test_TicketScalesToLedgerController() {

        TestSettings ts = new TestSettings().typicalSetup().finalize();

        Event__c event = [select Id, ShowCount__c, UsingMultiScale__c, StatusStage__c from Event__c where id = :ts.myEvent.Id];
        System.debug(event);
    	
        PageReference pr = Page.LNE_AssignTicketScalesToLedgerEntries;
        pr.getParameters().putAll(new Map<String,String> {
            'id' => ts.myEvent.Id,
            'ledgerEntryId' => ts.testLedgerEntry.Id
        });
        Test.setCurrentPage(pr);

        ApexPages.StandardController sc = new ApexPages.StandardController(event);
        LNE_TicketScalesToLedgerController con = new LNE_TicketScalesToLedgerController(sc);

        LNE_TicketScalesToLedgerController.updateLedgerEntry(ts.testLedgerEntry.Id, '');

    }
  
    //@testSetup
    //static void setup(){
    //    LNE_TestObjectFactory.prepStandardCustomSettings();
    //}

    ////static testMethod void runSetupAWithoutException() {
    ////    try {
    ////        TestSettings ts = new TestSettings();
    ////        ts.typicalSetup();
    ////        ts.finalize();
    ////    } catch( Exception err ){
    ////        //System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
    ////    }
    ////}
    
    // //-- test functionality here
  
    //static testMethod void testAPI() {
    //    TestSettings ts = new TestSettings();
    //    ts.typicalSetup();
    //    LedgerEntry__c ledgerEntry = ts.testLedgerEntry;
    //    LedgerEntryBreakout__c ledgerEntryBreakout = ts.testLedgerEntryBreakout;
    //    Deduction__c deduction = ts.testDeduction;
             
    //    PageReference pageRef = Page.LNE_AssignTicketScalesToLedgerEntries;
    //    pageRef.getParameters().put('ledgerEntryId', ledgerEntry.Id);
    //    pageRef.getParameters().put('eventId', ledgerEntry.Event__c);
    //    Test.setCurrentPageReference(pageRef);
    //    LNE_TicketScalesToLedgerController api = new LNE_TicketScalesToLedgerController();
    //    api.updatedLedgerEntryId = ledgerEntry.Id;
    //    api.updateLedgerEntry();
    //    api.getMyUrl();
    //    system.assertEquals('true', api.updateLedgerSuccess);
    //    system.assertEquals(ledgerEntry.Event__c, api.getEventId());
    //    system.assertEquals(ledgerEntry.Id, api.getLedgerEntryId());

    //    List<TicketScale__c> ticketScaleList = api.getTicketScaleList();
    //    system.assertEquals(0, ticketScaleList.size());

    //    pageRef.getParameters().put('ledgerEntryId', ledgerEntryBreakout.Id);
    //    api = new LNE_TicketScalesToLedgerController();
    //    api.updatedLedgerEntryId = ledgerEntryBreakout.Id;
    //    api.updateLedgerEntry();

    //    pageRef.getParameters().put('ledgerEntryId', deduction.Id);
    //    api = new LNE_TicketScalesToLedgerController();
    //    api.updatedLedgerEntryId = deduction.Id;
    //    api.updateLedgerEntry();

    //    system.assertEquals('true', api.updateLedgerSuccess);
    //    system.assertEquals(ledgerEntry.Event__c, api.getEventId());
    //    system.assertEquals(deduction.Id, api.getLedgerEntryId());
    //}
}