src/objects/Deduction__c.object
<CustomObject>
    <description>Ticket revenue deductions from the ticket pricing/scaling</description>
    <fields>
        <fullName>AmountRate__c</fullName>
        <label>Amount/Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BeforeAfter__c</fullName>
        <label>Before/After</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before Adjusted</fullName>
                </value>
                <value>
                    <fullName>After Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Amount Per Ticket</fullName>
                </value>
                <value>
                    <fullName>Primary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Primary Multiplier Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Divider Tax</fullName>
                </value>
                <value>
                    <fullName>Secondary Multiplier Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Artist Add-On</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>FMF/Venue Charge</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Value Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>Ded-{000000}</displayFormat>
        <label>Deduction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>BookingHouseNut__c</fullName>
        <label>Booking House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossPotential__c</fullName>
        <label>Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetGrossPotential__c</fullName>
        <label>Net Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberofTrucks__c</fullName>
        <label># of Trucks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedGross__c</fullName>
        <label>Projected Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedNetGross__c</fullName>
        <label>Projected Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutPaidTickets__c</fullName>
        <label>Sellout Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SettlementHouseNut__c</fullName>
        <label>Settlement House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <recordTypes>
        <fullName>TicketRevenue</fullName>
        <active>true</active>
        <description>Revenue from ticket sales</description>
        <label>Ticket Revenue</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFeePercent__c</fullName>
        <defaultValue>0.129</defaultValue>
        <label>TM Fee %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementUtil_Test.cls
@isTest
private class LNE_SettlementUtil_Test {
	static String RT_TICKET_REVENUE = 'LedgerEntry__c.TicketRevenue';
	static String RT_EXPENSES = 'LedgerEntry__c.Expenses';

	static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
	    new String[]{ RT_TICKET_REVENUE, RT_EXPENSES }
    );

    static Id RT_TICKET_REVENUE_ID = recordTypeMap.get( RT_TICKET_REVENUE );
    static Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );

	class TestSettings {
		public Event__c testEvent;
		
		public TestSettings() {
		}
		
		public void typicalSetup(){
			testEvent = [SELECT Id FROM Event__c WHERE BookingHouseNut__c = 5555 LIMIT 1];
		}
		
		public void finalize(){
		}
	}

	static void setupData(Event__c event) {

		LNE_FinancialCalculator.runUpdates = true;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.Event__c = event.Id;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Projection';

		TicketScale__c ticketScale2 = new TicketScale__c();
		ticketScale2.Type__c = 'Lawn';
		ticketScale2.Capacity__c = 1000;
		ticketScale2.Price__c = 100.00;
		ticketScale2.Kills__c = 0;
		ticketScale2.Comps__c = 0;
		ticketScale2.ProjectedPaidTickets__c = 950;
		ticketScale2.Event__c = event.Id;
		ticketScale2.LiftBeforeFee__c = 0;
		ticketScale2.TMFeePercent__c = 0.0;
		ticketScale2.StageType__c = 'Projection';

		TicketScale__c ticketScale3 = new TicketScale__c();
		ticketScale3.Type__c = 'Platinum';
		ticketScale3.Capacity__c = 100;
		ticketScale3.Price__c = 100.00;
		ticketScale3.Kills__c = 0;
		ticketScale3.Comps__c = 0;
		ticketScale3.ProjectedPaidTickets__c = 100;
		ticketScale3.Event__c = event.Id;
		ticketScale3.LiftBeforeFee__c = 7420.00;
		ticketScale3.TMFeePercent__c = 0.0;
		ticketScale3.StageType__c = 'Projection';

		insert new List<TicketScale__c>{ticketScale,ticketScale2,ticketScale3};

		LNE_FinancialCalculator.runUpdates = true;

		Deduction__c deduction = new Deduction__c();
		deduction.BeforeAfter__c = 'Before Adjusted';
		deduction.Event__c = event.Id;
		deduction.RateType__c = 'Primary Multiplier Tax';
		deduction.AmountRate__c = 10;
		deduction.StageType__c = 'Projection';

		Deduction__c deduction2 = new Deduction__c();
		deduction2.BeforeAfter__c = 'Before Adjusted';
		deduction2.Event__c = event.Id;
		deduction2.RateType__c = 'Primary Divider Tax';
		deduction2.AmountRate__c = 10;

		Deduction__c deduction3 = new Deduction__c();
		deduction3.BeforeAfter__c = 'Before Adjusted';
		deduction3.Event__c = event.Id;
		deduction3.RateType__c = 'Amount Per Ticket';
		deduction3.AmountRate__c = 10;
		deduction3.ApplyTicketScale__c = 'All Paid Tickets';

		Deduction__c deduction4 = new Deduction__c();
		deduction4.BeforeAfter__c = 'Before Adjusted';
		deduction4.Event__c = event.Id;
		deduction4.RateType__c = 'Secondary Multiplier Tax';
		deduction4.AmountRate__c = 10;

		Deduction__c deduction5 = new Deduction__c();
		deduction5.BeforeAfter__c = 'Before Adjusted';
		deduction5.Event__c = event.Id;
		deduction5.RateType__c = 'Secondary Divider Tax';
		deduction5.AmountRate__c = 10;

		Deduction__c deduction6 = new Deduction__c();
		deduction6.BeforeAfter__c = 'After Adjusted';
		deduction6.Event__c = event.Id;
		deduction6.RateType__c = 'Primary Multiplier Tax';
		deduction6.AmountRate__c = 10;

		Deduction__c deduction7 = new Deduction__c();
		deduction7.BeforeAfter__c = 'After Adjusted';
		deduction7.Event__c = event.Id;
		deduction7.RateType__c = 'Secondary Multiplier Tax';
		deduction7.AmountRate__c = 10;

		Deduction__c deduction8 = new Deduction__c();
		deduction8.BeforeAfter__c = 'After Adjusted';
		deduction8.Event__c = event.Id;
		deduction8.RateType__c = 'Amount Per Ticket';
		deduction8.AmountRate__c = 10;
		deduction8.ApplyTicketScale__c = 'All Paid Tickets';

		Deduction__c deduction9 = new Deduction__c();
		deduction9.BeforeAfter__c = 'After Adjusted';
		deduction9.Event__c = event.Id;
		deduction9.RateType__c = 'Primary Divider Tax';
		deduction9.AmountRate__c = 10;

		Deduction__c deduction10 = new Deduction__c();
		deduction10.BeforeAfter__c = 'After Adjusted';
		deduction10.Event__c = event.Id;
		deduction10.RateType__c = 'Secondary Divider Tax';
		deduction10.AmountRate__c = 10;

		insert new List<Deduction__c>{deduction,deduction2,deduction3,deduction4,deduction5,
									  deduction6,deduction7,deduction8,deduction9,deduction10};
	}

	static void setupComps(Event__c event) {

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Reserved';
		ticketScale.Capacity__c = 1000;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 100;
		//sellable capacity = capacity - kills - comps = 900
		ticketScale.ProjectedPaidTickets__c = 950;
		ticketScale.Event__c = event.Id;
		ticketScale.LiftBeforeFee__c = 0;
		ticketScale.TMFeePercent__c = 0.0;
		insert ticketScale;

		TicketScale__c ticketScale2 = new TicketScale__c();
		ticketScale2.Type__c = 'Lawn';
		ticketScale2.Capacity__c = 1000;
		ticketScale2.Price__c = 100.00;
		ticketScale2.Kills__c = 0;
		ticketScale2.Comps__c = 100;
		//sellable capacity = capacity - kills - comps = 900
		ticketScale2.ProjectedPaidTickets__c = 950;
		ticketScale2.Event__c = event.Id;
		ticketScale2.LiftBeforeFee__c = 0;
		ticketScale2.TMFeePercent__c = 0.0;
		insert ticketScale2;

		TicketScale__c ticketScale3 = new TicketScale__c();
		ticketScale3.Type__c = 'Platinum';
		ticketScale3.Capacity__c = 100;
		ticketScale3.Price__c = 100.00;
		ticketScale3.Kills__c = 0;
		ticketScale3.Comps__c = 10;
		//sellable capacity = capacity - kills - comps = 90
		ticketScale3.ProjectedPaidTickets__c = 100;
		ticketScale3.Event__c = event.Id;
		ticketScale3.LiftBeforeFee__c = 7420.00;
		ticketScale3.TMFeePercent__c = 0.0;
		insert ticketScale3;
	}

	@TestSetup static void setupTestData() {
    	LNE_TestObjectFactory.prepStandardCustomSettings();
    //	LNE_TestObjectFactory.createStandardDataSet();

    	Event__c event = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createEvent()
			).addProperties( new Map<String,Object>{
			    'SelloutDropCount__c' => 2100,
			    'ProjectedDropCount__c' => 1940,
			    'SelloutPaidTickets__c' => 2100,
			    'ProjectedPaidTickets__c' => 2000,
			    'GrossPotential__c' => 217420,
			    'ProjectedGross__c' => 207420,
			    'NetGrossPotential__c' => 95074.68,
			    'ProjectedNetGross__c' => 90729.47,
			    'NumberOfTrucks__c' => 5,
			    'Status__c' => 'Draft',
			    'BookingHouseNut__c' => 5555
			}).buildEvent();
		//insert event;
		 LNE_TestObjectFactory.createStandardDataSet( event );
    }

	@isTest static void testStartSettlement() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();
		setupData(tsettings.testEvent);

		Test.startTest();

		LNE_SettlementUtil.startSettlementProcess(tsettings.testEvent.Id);

		Test.stopTest();

		Event__c finalEvent = [SELECT SettlementStarted__c, SettlementHouseNut__c FROM Event__c WHERE Id = :tsettings.testEvent.Id];
		system.assertEquals(true, finalEvent.SettlementStarted__c);
		system.assertEquals(5555, finalEvent.SettlementHouseNut__c);
		List<Deduction__c> settlementDeductions = [SELECT Id FROM Deduction__c WHERE StageType__c = 'Settlement' AND Event__c = :tsettings.testEvent.Id];
		system.assertEquals(1, settlementDeductions.size());
	}

	@isTest static void testReStartSettlement() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();
		setupData(tsettings.testEvent);
		Id eventId = tsettings.testEvent.Id;

		Test.startTest();

		LNE_SettlementUtil.startSettlementProcess(eventId);

		Event__c finalEvent = [SELECT SettlementStarted__c, SettlementHouseNut__c FROM Event__c WHERE Id = :eventId];
		system.assertEquals(true, finalEvent.SettlementStarted__c);
		system.assertEquals(5555, finalEvent.SettlementHouseNut__c);
		List<Deduction__c> settlementDeductions = [SELECT Id FROM Deduction__c WHERE StageType__c = 'Settlement' AND Event__c = :eventId];
		system.assertEquals(1, settlementDeductions.size());

		

		system.debug(LoggingLevel.INFO, 'BEFORE RESTART');
		LNE_SettlementUtil.restartSettlement(eventId);
		system.debug(LoggingLevel.INFO, 'AFTER RESTART');

		Test.stopTest();

		settlementDeductions = [SELECT BeforeAfter__c, RateType__c, AmountRate__c FROM Deduction__c WHERE StageType__c = 'Settlement' AND Event__c = :eventId];

		//Make sure there is still just one deduction. The initial settlement one was deleted, and 
		//the one in Projection stage was cloned into Settlement
		system.assertEquals(1, settlementDeductions.size());

		List<String> fieldsToErase = LNE_SettlementUtil.ledgerFieldsToErase;

		String query = 'SELECT ';
		query += String.join(fieldsToErase, ',');
		query += ' FROM LedgerEntry__c WHERE Event__c = :eventId';

		List<LedgerEntry__c> ledgers = Database.query(query);

		for (sObject so : ledgers) {
			for (String fieldName : fieldsToErase) {
				system.assertEquals(null, so.get(fieldName));
			}
		}
	}
}