src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Drives sharing rules to provide read-only access to touring group members</description>
        <label>Geography</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrossRevenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetRevenue__c</fullName>
        <label>Net Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_CogsExpensesFieldCalculation_Test.cls
/**
* 
*
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
public class LNE_CogsExpensesFieldCalculation_Test {
    
    static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';
    
    class TestSettings {
        
	    public Map<String, Id> objectToId {get; set;}
		private Id glAccountId;            
        
        public TestSettings() {
            List<Event__c> evntList = new List<Event__c>();   
            
            Event__c Evt1 = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            evntList.add(Evt1);
            
            Event__c Evt2 = new Event__c(
                ProjectedDropCount__c = 30000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            evntList.add(Evt2);
            
            Event__c Evt3 = new Event__c(
                ProjectedPaidTickets__c = 20000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            
            evntList.add(Evt3);   
            objectToId = LNE_TestObjectFactory.createStandardDataSetList(evntList);
        }
        
        
        public List<LedgerEntry__c> typicalSetup(){
            
            List<GLAccount__c> glAccounts = new List<GLAccount__c>();
            //List<Event__c> evntList = new List<Event__c>();         
            List<LedgerEntry__c> savedLedgerEntries = new List<LedgerEntry__c>();
            
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
                new String[]{ RT_Ancillary }
            );
            
            Id RT_ANCILLARY_ID = recordTypeMap.get( RT_Ancillary );
            
            /*
            GLAccount__c testGlaAcct1 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12345'
            );
            glAccounts.add(testGlaAcct1);
            
            GLAccount__c testGlaAcct2 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Alcoholic Beverage Revenue',
                Category__c = 'Concession Revenue',
                GLCode__c = '12340'
            );
            glAccounts.add(testGlaAcct2); 
            */
            GLAccount__c testGlaAcct3 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Non-Alcoholic Beverage Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12349'
            );
            glAccounts.add(testGlaAcct3);
            
            GLAccount__c testGlaAcct4 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Facility Maintenance Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12348'
            );
            glAccounts.add(testGlaAcct4);           
            
            GLAccount__c testGlaAcct5 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Premier Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12347'
            );
            glAccounts.add(testGlaAcct5); 
            Database.insert(glAccounts, false);
            /*
            Event__c Evt1 = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            evntList.add(Evt1);
            
            Event__c Evt2 = new Event__c(
                ProjectedDropCount__c = 30000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            evntList.add(Evt2);
            
            Event__c Evt3 = new Event__c(
                ProjectedPaidTickets__c = 20000,
                Geography__c = 'North America',
                status__c = 'Draft'
            );
            evntList.add(Evt3);
            Database.insert(evntList, false);
             */
             
            LedgerEntry__c Ledger1 = new LedgerEntry__c (
                GLAccount__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_PARKING),//testGlaAcct1.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 0)//evntList.get(0).Id
            ); 
            savedLedgerEntries.add(Ledger1);
            
            LedgerEntry__c Ledger2 = new LedgerEntry__c (
                GLAccount__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_ANCILLARY),//testGlaAcct2.Id,
                BaseAmount__c = 33345,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,                
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 0)//evntList.get(0).Id
            ); 
            savedLedgerEntries.add(Ledger2);
                        
            LedgerEntry__c Ledger3 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct3.Id,
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,            
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 0)//was null
            );
            savedLedgerEntries.add(Ledger3);            
            
            LedgerEntry__c Ledger4 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct4.Id,
                BaseAmount__c = 0,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,         
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 1)//evntList.get(1).Id
            ); 
            savedLedgerEntries.add(Ledger4);
            
            LedgerEntry__c Ledger5 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct5.Id,
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,                
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 2)//evntList.get(2).Id
            ); 
            savedLedgerEntries.add(Ledger5);
            
            LedgerEntry__c Ledger6 = new LedgerEntry__c (
                GLAccount__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_PARKING),//testGlaAcct1.Id,
                RateType__c = 'Flat', 
                RecordTypeId = RT_ANCILLARY_ID,
                GrossRevenue__c = 0,
                NetRevenue__c = 0,     
                BaseAmount__c = 0,
                Event__c = objectToId.get(LNE_TestObjectFactory.STANDARD_DATA_EVENT + 0)//evntList.get(0).Id
            );
            
            savedLedgerEntries.add(Ledger6);
            insert savedLedgerEntries;
            return savedLedgerEntries;
        }
        
        public void finalize(){
        }
    }
    
    //-- test test methods here

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    static testMethod void runSetupAWithoutException() {
        try {
            TestSettings ts = new TestSettings();
            
            Test.startTest();
            ts.typicalSetup();
            ts.finalize();
            Test.stopTest();
        } catch( Exception err ){
            System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
        }
    }
    //-- test functionality here
    
    static testMethod void testCalculatedFields1() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 123.90
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        update ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
       /*
        System.assertEquals(100000, updatedLedgerEntry.GrossRevenue__c);
        */
        Test.stopTest();
    }
    
    static testMethod void testCalculatedFields2() {
        
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 121.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        
        Test.stopTest();
    }    
 
    
    static testMethod void testCalculatedFields3() {
        
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        
        Test.stopTest();
    }
    
    static testMethod void testCalculatedFields4() {
        
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(3).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(3).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(3);
        ledgerEntries.get(3).BaseAmount__c = 10;
        ledgerEntries.get(3).RateType__c = 'Per Cap';
        ledgerEntries.get(3).Min__c = 0;
        ledgerEntries.get(3).Max__c = 0;
        ledgerEntries.get(3).ApplyTicketScale__c = 'Selected Tickets';
        
        try{
            LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(3));
        }
        catch(Exception e){
        }
        
        Test.stopTest();
    }    
    
    static testMethod void testCalculatedFields5() {
        
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(4).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(4).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(4);
        ledgerEntries.get(4).BaseAmount__c = 10;
        ledgerEntries.get(4).RateType__c = 'Per Cap';
        ledgerEntries.get(4).Min__c = 0;
        ledgerEntries.get(4).Max__c = 0;
        ledgerEntries.get(4).ApplyTicketScale__c = 'Selected Tickets';
        
        try{
            LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(4));
        }
        catch(Exception e){
        }
        
        Test.stopTest();
    }
    
    static testMethod void testCalculatedFields6() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();        
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Flat';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        
        Test.stopTest();
    }   
    
    static testMethod void testCalculatedFields7() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'All Paid Tickets';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        
        Test.stopTest();
    }   
    
    static testMethod void testCalculatedFields8() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'All Drop Count';
        
        LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        
        Test.stopTest();
    }                
    
    static testMethod void testCalculatedFields9() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'All';
        
        try{
            LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        }
        catch(Exception e){
        }        
        
        Test.stopTest();
    }    
     static testMethod void testCalculatedFields10() {
        TestSettings ts = new TestSettings();
        
        Test.startTest();
        
        List<LedgerEntry__c> ledgerEntries = ts.typicalSetup();
        TicketScale__c ticketScale1 = new TicketScale__c(
            Event__c = ledgerEntries.get(0).Event__c,
            PriceLevel__c = 'Reserved',
            ProjectedPaidTickets__c = 10000,
            Kills__c = 500,
            Comps__c = 5000,
            Capacity__c = 16000,
            Price__c = 321.09
        );
        
        insert ticketScale1;
        ledgerEntries.get(0).TicketScaleList__c = ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = null;
        
        try{
            LedgerEntry__c updatedLedgerEntry = LNE_CogsExpensesFieldCalculation.calculateFieldsOnGrid(ledgerEntries.get(0));
        }
        catch(Exception e){
        }        
        
        Test.stopTest();
    } 
}