src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ActualDropCount__c</fullName>
        <label>Actual Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaidAttendance__c</fullName>
        <formula>LawnPaidAttendance__c +  ReservedPaidAttendance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Paid Attendance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SettlementAdjustedGross__c</fullName>
        <label>Settlement Adjusted Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementGross__c</fullName>
        <label>Settlement Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementNetGross__c</fullName>
        <label>Settlement Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementPaidTickets__c</fullName>
        <label>Settlement Paid Tickets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>CurrentFlash__c</fullName>
        <label>Current Flash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlashRateAmount__c</fullName>
        <label>Flash Rate Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FlashRateType__c</fullName>
        <label>Flash Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>CurrentFlash__c</fullName>
        <label>Current Flash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FlashRateAmount__c</fullName>
        <label>Flash Rate Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FlashRateType__c</fullName>
        <label>Flash Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_LedgerCalculateCurrentFlash.cls
/**
*  Class that contains the Logic to calculate the Current Flash on the LedgerEntry__c and LedgerEntryBreakout__c Object
*  <p>This class should have the least amount of code possible to reduce security concerns.</p>
*  @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
**/
public class LNE_LedgerCalculateCurrentFlash {

    public static final string RATE_TYPE_FLAT = 'Flat';
    public static final string RATE_TYPE_PER_DROP_COUNT = 'Per Drop Count';
    public static final string RATE_TYPE_PER_PAID_TICKET = 'Per Paid Ticket';
    public static final string RATE_TYPE_PERCENTAGE_OF_GROSS = '% of Net Gross';
    public static final string RATE_TYPE_PERCENTAGE_BASE_GROSS = '% of Gross';
    public static final string RATE_TYPE_PERCENTAGE_ADJ_GROSS = '% of Adjusted Gross';
    
    public static final string ERR_NO_RELATED_EVENT = 'No Related Event';
    
    class CustomException extends Exception{}
       
    public static LedgerEntry__c calculateFieldsOnGridLE (LedgerEntry__c ledgerEntry){
        if(ledgerEntry.FlashRateAmount__c == null){
            return ledgerEntry;
        }
        LedgerEntry__c savedLedgerEntry = [SELECT Id, Event__c FROM LedgerEntry__c WHERE Id =:ledgerEntry.Id];
        Event__c relatedEvent = [SELECT Id, SettlementNetGross__c, SettlementPaidTickets__c, PaidAttendance__c, ActualDropCount__c FROM Event__c WHERE Id =:savedLedgerEntry.Event__c ];
        if( relatedEvent == null ){
            throw( new CustomException( ERR_NO_RELATED_EVENT ));
        }

        ledgerEntry = calculateCurrentFlashLE(ledgerEntry, relatedEvent);
        return ledgerEntry;
    }
    
    /**
*  Method to calculate the CurrentFlash on LedgerEntry__c Object.
*  @param LedgerEntryBreakout__c, Event__c
*  @return LedgerEntryBreakout__c
**/
    public static LedgerEntryBreakout__c calculateCurrentFlashLEB(LedgerEntryBreakout__c ledgerEntryBreakout, Event__c relatedEvent){
        Double flashRateAmount = ledgerEntryBreakout.FlashRateAmount__c == null ? 0.0 : ledgerEntryBreakout.FlashRateAmount__c;
        
        if(ledgerEntryBreakout.FlashRateType__c == RATE_TYPE_FLAT){
            ledgerEntryBreakout.CurrentFlash__c = flashRateAmount;
        }
        else{
            if(ledgerEntryBreakout.FlashRateType__c == RATE_TYPE_PER_DROP_COUNT && relatedEvent.ActualDropCount__c != null){
                ledgerEntryBreakout.CurrentFlash__c =  flashRateAmount * relatedEvent.ActualDropCount__c;
            }else if(ledgerEntryBreakout.FlashRateType__c == RATE_TYPE_PER_PAID_TICKET && relatedEvent.PaidAttendance__c != null){
                ledgerEntryBreakout.CurrentFlash__c = flashRateAmount * relatedEvent.PaidAttendance__c;
            }else if(ledgerEntryBreakout.FlashRateType__c == RATE_TYPE_PERCENTAGE_OF_GROSS && relatedEvent.SettlementNetGross__c != null){
                ledgerEntryBreakout.CurrentFlash__c = (flashRateAmount /100)* relatedEvent.SettlementNetGross__c;
            }else{
                ledgerEntryBreakout.CurrentFlash__c = 0;
            }
            
        }
        
        //-- round it to 2 decimal points
        if( ledgerEntryBreakout.CurrentFlash__c != null ){
            ledgerEntryBreakout.CurrentFlash__c = ledgerEntryBreakout.CurrentFlash__c.setScale( 2, RoundingMode.HALF_UP );
        }
        System.debug(ledgerEntryBreakout);
        return ledgerEntryBreakout;
        
    }

    public static LedgerEntryBreakout__c calculateFieldsOnGridLEB (LedgerEntryBreakout__c ledgerEntryBreakout){
        if(ledgerEntryBreakout.FlashRateAmount__c == null){
            return ledgerEntryBreakout;
        }
        
        LedgerEntryBreakout__c savedLedgerEntryBreakout = [SELECT Id, TicketScaleList__c, LedgerEntry__c FROM LedgerEntryBreakout__c WHERE Id =:ledgerEntryBreakout.Id];
        LedgerEntry__c ledgerEntryGL = [SELECT Id, Event__c FROM LedgerEntry__c WHERE Id =:savedLedgerEntryBreakout.LedgerEntry__c];
        Event__c relatedEvent = [SELECT Id, SettlementNetGross__c, SettlementPaidTickets__c, PaidAttendance__c, ActualDropCount__c FROM Event__c WHERE Id =:ledgerEntryGL.Event__c ];
        if( relatedEvent == null ){
            throw( new CustomException( ERR_NO_RELATED_EVENT ));
        }
        
        ledgerEntryBreakout = calculateCurrentFlashLEB(ledgerEntryBreakout, relatedEvent);


        return ledgerEntryBreakout;
    }
    
    /**
*  Method to calculate the CurrentFlash on LedgerEntry__c Object.
*  @param LedgerEntry__c, Event__c
*  @return LedgerEntry__c
**/
    public static LedgerEntry__c calculateCurrentFlashLE(LedgerEntry__c ledgerEntry, Event__c relatedEvent){
        Double flashRateAmount = ledgerEntry.FlashRateAmount__c == null ? 0.0 : ledgerEntry.FlashRateAmount__c;
 
        System.Debug('CurrentFlash Started ' + flashRateAmount + '  ' + ledgerEntry.FlashRateType__c);
        if(ledgerEntry.FlashRateType__c == RATE_TYPE_FLAT){
            ledgerEntry.CurrentFlash__c = flashRateAmount;
        }
        //If the Rate Type of the Ledger Entry is Per Cap, then the Contra at Forecast is calculated applying the ticket scale rule.
        else{
            if(ledgerEntry.FlashRateType__c == RATE_TYPE_PER_DROP_COUNT  && relatedEvent.ActualDropCount__c != null){
                ledgerEntry.CurrentFlash__c =  flashRateAmount * relatedEvent.ActualDropCount__c;
            }else if(ledgerEntry.FlashRateType__c == RATE_TYPE_PER_PAID_TICKET && relatedEvent.PaidAttendance__c != null ){
                ledgerEntry.CurrentFlash__c = flashRateAmount * relatedEvent.PaidAttendance__c;
            }else if(ledgerEntry.FlashRateType__c == RATE_TYPE_PERCENTAGE_OF_GROSS && relatedEvent.SettlementNetGross__c != null){
                ledgerEntry.CurrentFlash__c = (flashRateAmount / 100)* relatedEvent.SettlementNetGross__c;
            }else{
                ledgerEntry.CurrentFlash__c = 0;
            }
            
        }
        
        //-- round it to 2 decimal points
        if( ledgerEntry.CurrentFlash__c != null ){
            ledgerEntry.CurrentFlash__c = ledgerEntry.CurrentFlash__c.setScale( 2, RoundingMode.HALF_UP );
        }
        
        System.debug('CurrentFlash ' +  ledgerEntry.CurrentFlash__c);
        return ledgerEntry;
        
    }
    
    public static Double getSettlementExpensePromoterAmount(Event__c evt, String type, Decimal rateAmount) {
        if(rateAmount == null) {
            return null;
        }

        if(type == RATE_TYPE_PER_DROP_COUNT && evt.ActualDropCount__c != null) {
            return rateAmount * evt.ActualDropCount__c;
        } else if(type == RATE_TYPE_PER_PAID_TICKET && evt.SettlementPaidTickets__c != null) {
            return rateAmount * evt.SettlementPaidTickets__c;
        } else if(type == RATE_TYPE_PERCENTAGE_OF_GROSS && evt.SettlementNetGross__c != null) {
            return rateAmount / 100 * evt.SettlementNetGross__c;
        } else if(type == RATE_TYPE_PERCENTAGE_ADJ_GROSS && evt.SettlementAdjustedGross__c != null) {
            return rateAmount / 100 * evt.SettlementAdjustedGross__c;
        } else if(type == RATE_TYPE_PERCENTAGE_BASE_GROSS && evt.SettlementGross__c != null) {
            return rateAmount / 100 * evt.SettlementGross__c;
        } else if(type == RATE_TYPE_FLAT) {
            return rateAmount;
        }
        
        return null;
    }
}