src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>NotificationAgeLimit__c</fullName>
        <defaultValue>7</defaultValue>
        <inlineHelpText>The limit in number of days that a Notification record is allowed to live.  A daily batch will remove any Notification record that is older than the limit in days.</inlineHelpText>
        <label>Notification Age Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/Notification__c.object
<CustomObject>
    <description>Records that should be used to track specific activity and notify the user. Similar to an Event Log.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acknowledgement Flag</fullName>
                </value>
                <value>
                    <fullName>Approval Flag</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>Not-{000000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventAlerts_C.cls
/** 
 *	Controller class for the LNE_EventAlerts lightning component
 *	@author Scott Will
 *  @group Controller
 **/
public with sharing class LNE_EventAlerts_C {

	private final static GeneralSettings__c settings = GeneralSettings__c.getInstance();
	
	/**
     *  Returns server specific data
     **/
    @AuraEnabled
    public static Map<String,String> getServerData() {
        return new Map<String,String> {
        	'sessionId' => (UserInfo.getSessionId()),
        	'userId' => (UserInfo.getUserId())
        };
    }

    /**
     *  Returns the current list of event notifications
     *	@param eventId Id - expecting an Event__c.Id
     **/
    @AuraEnabled
    public static List<Notification__c> getNotifications(Id eventId) {

    	Integer maxAge = settings.NotificationAgeLimit__c.intValue();
    	DateTime ageLimit = System.now().addDays(-maxAge);

    	return new List<Notification__c>([
        	select
        		CreatedDate,
        		Description__c,
        		Type__c
        	from Notification__c
        	where Event__c = :eventId
        	and CreatedById = :UserInfo.getUserId()
        	and CreatedDate >= :ageLimit
        	order by CreatedDate desc
        ]);

    }

    /**
     *  Deletes the notifications
     *	@param notificationIdsList Id[] - expecting an array of Notification__c.Id
     **/
    @AuraEnabled
    public static Boolean dismissNotifications(List<Id> notificationIdsList) {

    	Set<Id> notificationIds = new Set<Id>(notificationIdsList);
    	List<Notification__c> notifications = new List<Notification__c>([
    		select Id 
    		from Notification__c 
    		where Id in :notificationIds
    	]);

    	Boolean success = true;

    	if (!notifications.isEmpty()) {
    		
    		Database.delete(notifications, false);

    	}

    	return success;

    }

}