src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>OfficeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promoter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promoter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PromoterEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventVenuePromoterPicker_CX.cls
public with sharing class LNE_EventVenuePromoterPicker_CX {

	private final Id eventId;
	
	public Boolean isLocked {get;set;}
	public String eventOfficeId {get;set;}
	public String eventPromoterId {get;set;}
	public String eventVenueId {get;set;}

	public LNE_EventVenuePromoterPicker_CX(ApexPages.StandardController sc) {
		this.eventId = sc.getId();

		Event__c e = (Event__c)sc.getRecord();
		this.eventOfficeId = e.Office__c;
		this.eventPromoterId = e.Promoter__c;
		this.eventVenueId = e.Venue__c;
	}

	public void checkCanEdit() {
		this.isLocked = !LNE_Util.isEventEditable(this.eventId);
	}

	public void save() {

		try {
			update new Event__c(
				Id = this.eventId,
				Office__c = this.eventOfficeId,
				Promoter__c = this.eventPromoterId,
				Venue__c = this.eventVenueId
			);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Save Complete'));
		}
		catch (System.DmlException de) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, de.getMessage()));
		}

	}

}