src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventDateTimeTabs_C.cls
/**
*  Controller class for the LNE_EventDateTimeTabs VF Component
*
*	@group Controller
*	@author Scott Will
**/
public with sharing class LNE_EventDateTimeTabs_C {

	// list of EventDateTimes for the UI to consume
	public List<EventDateTime__c> eventDateTimes { get; private set; }
	public Id event_Id {
		get;
		set {
			// set components load funky need to set the list here
			this.eventDateTimes = getSortedEventDateTimes(value);
		}
	}	

	// empty constructor to make tests and compilers happy
	public LNE_EventDateTimeTabs_C() {}
	
	//- sorts EventDateTime__c by Event Date and Start Time (e.g. 3/15/2017 8:00 AM, 3/15/2017 2:00 PM)
	private List<EventDateTime__c> getSortedEventDateTimes(String eventId) {
		List<EventDateTime__c> edtList =  [SELECT EventDate__c,
												  StartTime__c
										   FROM EventDateTime__c
										   WHERE Event__c = :eventId];
										   
		List<LNE_EventDateTimeUtil_T.EventDateTime> listToSort = new List<LNE_EventDateTimeUtil_T.EventDateTime>();										   
										   
		for (EventDateTime__c edt : edtList) {
			listToSort.add(new LNE_EventDateTimeUtil_T.EventDateTime(edt));
		}
		
		listToSort.sort();
		
		List<EventDateTime__c> returnList = new List<EventDateTime__c>();
		
		for (LNE_EventDateTimeUtil_T.EventDateTime e : listToSort) {
			returnList.add(e.edt);
		}
		
		return returnList;
	}

}