src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AutoMatchedTour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used with the LNE_EventAutoMatchTour_Batch class.</description>
        <label>Auto-Matched Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events (Auto-Matched Tour)</relationshipLabel>
        <relationshipName>AutoMatchedEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DoNotAutoAssociateWithTour__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true the first time an Event is associated with a Tour. It excludes this record from the automated daily process associating Events with Tours by search criteria.</description>
        <label>Do Not Auto Associate with Tour</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_EventAssociateMatchedTour_Batch.cls
/**
* Auto-associates an Event__c to a Tour__c.  If the Event has never been matched before and has been
* pre-selected via the AutoMatchedTour__c value, the Tour Id will be copied to the real Tour__c lookup.
*
* @author Scott Will
* @group Batchable
*
**/
global with sharing class LNE_EventAssociateMatchedTour_Batch implements Database.Batchable<SObject> {
	
	// Events who have been pre-matched, are not assocaited to a Tour and are explicitly allowed
	final static String query = 
		'select ' +
			'AutoMatchedTour__c, ' +
			'Tour__c ' +
		'from Event__c ' +
		'where AutoMatchedTour__c != null ' +
		'and Tour__c = null ' +
		'and DoNotAutoAssociateWithTour__c = false';

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext bc, List<Event__c> events) {
		// only need to copy over the value and update
		for (Event__c event : events) {
			event.Tour__c = event.AutoMatchedTour__c;
			event.AutoMatchedTour__c = null;
		}
		// update whatever can be
		Database.update(events, false);
	}

	global void finish(Database.BatchableContext bc) {
		// nothing to do, required for implements Database.Batchable<SObject>
		return;
	}

}