src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EventSubtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDConfirmedCount__c</fullName>
        <label>TBD Confirmed Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TBDMonthValue__c</fullName>
        <formula>TEXT(MONTH(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDMonthValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDMonth__c</fullName>
        <label>TBD Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBDVenue__c</fullName>
        <formula>IF(RecordType.DeveloperName ==&apos;TBDEvents&apos;, False, Venue__r.TBDVenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBD Venue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBDYearValue__c</fullName>
        <formula>TEXT(YEAR(EventLastDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TBDYearValue</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TBDYear__c</fullName>
        <description>Used in TBD Apex logic</description>
        <label>TBD Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>TBDEvents</fullName>
        <active>true</active>
        <description>Used for TBD Events</description>
        <label>TBD Events</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/EventSubtype.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Club Night</fullName>
    </customValue>
    <customValue>
        <fullName>Filler Show</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Promoted</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Show</fullName>
    </customValue>
    <customValue>
        <fullName>Rental/Special Events/Venue Holds</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant Show</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event</fullName>
    </customValue>
    <customValue>
        <fullName>Tentpole</fullName>
    </customValue>
    <customValue>
        <fullName>Not Used</fullName>
    </customValue>
    <description>Centralized values for the Event Subtype field</description>
    <masterLabel>Event Subtype</masterLabel>
</GlobalValueSet>

src/classes/LNE_TBDCountUpdateClass_BatchSchedule.cls
/**
 *  Scheduler for the LNE_TBDCountUpdateClass_Batch
 *  
 *  LNE_TBDCountUpdateClass_BatchSchedule b = new LNE_TBDCountUpdateClass_BatchSchedule();
 *  System.Schedule(LNE_TBDCountUpdateClass_BatchSchedule.JOB_NAME, LNE_TBDCountUpdateClass_BatchSchedule.DEFAULT_SCHEDULE, b);
 *  
 *  @author Henry Akpala <hakpala@salesforce.com>
**/ 
    global class LNE_TBDCountUpdateClass_BatchSchedule implements Schedulable {
    
    
    global Date myDate = Date.today();
    global Integer intYear = myDate.Year();
    global String TBDEvents = 'TBDEvents';
    global String  PendingLikely = 'Pending Likely' ;
    global String Confirmed ='Confirmed';
    global String FillerShow ='Filler Show';
    global String Year = String.valueof(intYear) ;
   
    /** Time when the job should execute **/
    global static String DEFAULT_SCHEDULE = '0 5 3 * * ?'; //TODO set based on boomi job run.
    
    /** Name of the Scheduled Job **/
    global static String JOB_NAME = 'TBDConfirmCountUpdate';
    
    global void execute(SchedulableContext sc) {
        
        String q = 'SELECT Id, Venue__c, TBDConfirmedCount__c,TBDMonth__c, TBDYear__c, TBDVenue__c, TBDMonthValue__c, TBDYearValue__c, EventLastDate__c from Event__c WHERE  RecordTypeName__c!=:TBDEvents  AND SubType__c!=:FillerShow AND TBDVenue__c=True AND TBDMonthValue__c != null AND  TBDYearValue__c =: Year AND (Status__c  =: PendingLikely  OR Status__c  =:Confirmed) ';
        LNE_TBDCountUpdateClass_Batch confirmCountBatch = new LNE_TBDCountUpdateClass_Batch(q);
        Database.executeBatch(confirmCountBatch);
    }
}