src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>ApplyToPromotedEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Promoted Event</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_SelectExpenseEntriesController_Test.cls
@isTest
public class LNE_SelectExpenseEntriesController_Test {

	@TestSetup
    static void setup() {
		LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    private class TestSettings {
    	
        public Event__c myEvent { get; private set; }
        Id RT_EXPENSES_ID;
        
        public TestSettings() {
        	Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ 'LedgerEntry__c.Expenses' }
			);
			RT_EXPENSES_ID = recordTypeMap.get( 'LedgerEntry__c.Expenses' );
        	
        	//-- we don't need the financial calculator to run until we're done with all this
        	LNE_FinancialCalculator.currentlyRunning = true;
        	LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
        	
        	//-- assert there should only be one event.
			this.myEvent = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = 'Draft'
            );
			
			Map<String, Id> objectToId = LNE_TestObjectFactory.createStandardDataSet( this.myEvent );
			
			LNE_FinancialCalculator.currentlyRunning = true;
			
			LedgerEntry__c ledger = new LedgerEntry__c (
				GLAccount__c = objectToId.get('ancillary'),
				BaseAmount__c = 100,
				RateType__c = 'Flat', 
				RecordTypeId = RT_EXPENSES_ID,
				OfferRate__c = 123,
				Event__c = myEvent.Id
			); 

			insert ledger;
			
			LedgerEntryBreakout__c breakout = new LedgerEntryBreakout__c(LedgerEntry__c=ledger.Id,OfferRate__c = 123);
			insert breakout;
        }
        
        
        public TestSettings typicalSetup(){
        	
        	//-- is any of this background, something we can assume will be there always?            
            LNE_Util.refreshGLAccountCache();

            return this;

        }
        
        public TestSettings finalize(){
        	//-- now we're done with updating everything, have the financial calculator run.
        	LNE_FinancialCalculator.currentlyRunning = false;
        	LNE_FinancialCalculator.popRunningTrigger();
            return this;
        }
    }

	static testMethod void test_SelectExpenseEntries() {

        TestSettings ts = new TestSettings().typicalSetup().finalize();

        //GLAccount__c acct = LNE_TestObjectFactory.createGLAccount('LA National Touring Allocation', '50360');
        GLAccount__c acct = [select ApplyToPromotedEvent__c from GLAccount__c limit 1];
        acct.ApplyToPromotedEvent__c = true;
        update acct;

        PageReference pr = Page.LNE_SelectExpenseEntries;
        pr.getParameters().put('type', 'foo');
        Test.setCurrentPage(pr);        

        LNE_SelectExpenseEntriesController con = new LNE_SelectExpenseEntriesController();
        con.eventId = ts.myEvent.Id;
        List<GLAccount__c> expenseEntries = (List<GLAccount__c>)JSON.deserialize(con.expenseEntriesJson, List<GLAccount__c>.class);
        con.selectedEntriesJson = JSON.serialize(new List<Id> { expenseEntries[0].Id });
        con.addOrRemoveExpenseEntries();
        con.getRelatedExpenses();
        con.addOrRemoveExpenseEntries();
    }

    static testMethod void test_SelectExpenseEntries2() {

        TestSettings ts = new TestSettings().typicalSetup().finalize();

        //GLAccount__c acct = LNE_TestObjectFactory.createGLAccount('LA National Touring Allocation', '50360');
        GLAccount__c acct = [select ApplyToPromotedEvent__c from GLAccount__c limit 1];
        acct.ApplyToPromotedEvent__c = true;
        update acct;

        PageReference pr = Page.LNE_SelectExpenseEntries;
        pr.getParameters().put('type', 'foo');
        pr.getParameters().put('event_id', ts.myEvent.Id);
        Test.setCurrentPage(pr);        

        LNE_SelectExpenseEntriesController con = new LNE_SelectExpenseEntriesController();

    }

}