src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SelectAncillaryCOGSEntries_Test.cls
@isTest
private class LNE_SelectAncillaryCOGSEntries_Test {
    class TestSettings {
        
        public TestSettings() {

        }
        
        public void typicalSetup(){
        }
        
        public void finalize(){
        }
    }

    static GLAccount__c glaAccount1 {get;set;}
    static GLAccount__c glaAccount2 {get;set;}
    static GLAccount__c glaAccount3 {get;set;}
    static GLAccount__c glaAccount4 {get;set;}
    
    static Event__c setupEvent() {
        Event__c evnt = new Event__c();
        //insert evnt;
        LNE_TestObjectFactory.createStandardDataSet(evnt);
        return evnt;
    }
    
    static Event__c setupEventWRel() {
        Event__c evnt = new Event__c();
        // insert evnt;
        LNE_TestObjectFactory.createStandardDataSet(evnt);
        
        glaAccount1 = new GLAccount__c(
            Type__c = 'Ancillary',
            Name = 'Draft Beer',
            Category__c = 'Concession Revenue'
        );
        insert glaAccount1;
        
        glaAccount2 = new GLAccount__c(
            Type__c = 'COGS',
            Name = 'COGS - Beer',
            Category__c = 'COGS - Concessions'
        );
        insert glaAccount2;
        
        glaAccount3 = new GLAccount__c(
            Type__c = 'COGS',
            Name = 'COGS - Draft Beer',
            Category__c = 'COGS - Concessions'
        );
        insert glaAccount3;
        
        glaAccount4 = new GLAccount__c(
            Type__c = 'Ancillary',
            Name = 'Merchandise Revenue',
            Category__c = 'Merchandise Revenue'
        );
        insert glaAccount4;
        
        String ancillaryRecordTypeId = LNE_Util.getRecordTypes(new String[]{'LedgerEntry__c.Ancillary'}).get('LedgerEntry__c.Ancillary');
        
        LedgerEntry__c ledgerEntry1 = new LedgerEntry__c(
            GLAccount__c = glaAccount1.Id,
            Event__c = evnt.Id,
            RecordTypeId = ancillaryRecordTypeId
        );
        insert ledgerEntry1;
        
        String cogsRecordTypeId = LNE_Util.getRecordTypes(new String[]{'LedgerEntry__c.COGS'}).get('LedgerEntry__c.COGS');
        
        LedgerEntry__c ledgerEntry2 = new LedgerEntry__c(
            GLAccount__c = glaAccount2.Id,
            Event__c = evnt.Id,
            RecordTypeId = cogsRecordTypeId
        );
        insert ledgerEntry2;
        
        return evnt;
    }

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    static LNE_SelectAncillaryCOGSEntries setupCtrls(Event__c evnt) {
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = new LNE_SelectAncillaryCOGSEntries();
        selectEntriesCtrl.eventId = evnt.Id;
        
        return selectEntriesCtrl;
    }
    
    @isTest static void validateAddOrRemoveRevenueExpenseEntries() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        Event__c evnt = setupEventWRel();
        
        Test.startTest();
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = setupCtrls(evnt);
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        List<Object> beforeJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);
        
        selectEntriesCtrl.selectedEntriesJson = '[{"type":"Ancillary", "id":"' + glaAccount1.Id + '"}, {"type":"COGS", "id":"' + glaAccount3.Id + '"}]';
        selectEntriesCtrl.addOrRemoveRevenueExpenseEntries();
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        Test.stopTest();
        
        List<Object> afterJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);

        System.assert(beforeJsonObj.size() == 2);
        System.assert(afterJsonObj.size() == 2);
        System.assert(selectEntriesCtrl.previousSelectedEntriesJson != '[]');
    }
    
    @isTest static void validateAddAllRevenueExpenseEntries() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        Event__c evnt = setupEventWRel();
        
        Test.startTest();
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = setupCtrls(evnt);
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        List<Object> beforeJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);
        
        selectEntriesCtrl.selectedEntriesJson = '[{"type":"COGS", "id":"' + glaAccount3.Id + '"}, {"type":"Ancillary", "id":"' + glaAccount4.Id + '"}]';
        selectEntriesCtrl.addOrRemoveRevenueExpenseEntries();
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        Test.stopTest();
        
        List<Object> afterJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);

        System.assert(beforeJsonObj.size() == 2);
        System.assert(afterJsonObj.size() == 2);
        System.assert(selectEntriesCtrl.previousSelectedEntriesJson != '[]');
    }
    
    @isTest static void validateRemoveAllRevenueExpenseEntries() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        Event__c evnt = setupEventWRel();
        
        Test.startTest();
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = setupCtrls(evnt);
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        List<Object> beforeJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);
        
        selectEntriesCtrl.selectedEntriesJson = '[]';
        selectEntriesCtrl.addOrRemoveRevenueExpenseEntries();
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        Test.stopTest();
        
        List<Object> afterJsonObj = (List<Object>) System.JSON.deserializeUntyped(selectEntriesCtrl.previousSelectedEntriesJson);
        
        System.assert(beforeJsonObj.size() == 2);
        System.assert(afterJsonObj.size() == 0);
        System.assert(selectEntriesCtrl.previousSelectedEntriesJson == '[]');
    }
    
    @isTest static void validateGetRelatedRevenuesExpensesWORel() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();

        Event__c evnt = setupEvent();
        
        Test.startTest();
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = setupCtrls(evnt);
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        Test.stopTest();
        
        System.assert(selectEntriesCtrl.previousSelectedEntriesJson == '[]');
    }
    
    @isTest static void validateGetRelatedRevenuesExpensesWRel() {
        TestSettings ts = new TestSettings();
        ts.typicalSetup();
        ts.finalize();
        
        Event__c evnt = setupEventWRel();
        
        Test.startTest();
        LNE_SelectAncillaryCOGSEntries selectEntriesCtrl = setupCtrls(evnt);
        selectEntriesCtrl.getRelatedRevenuesExpenses();
        Test.stopTest();
        
        System.assert(selectEntriesCtrl.previousSelectedEntriesJson != '[]');
    }
}