src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_FlashTab_CX.cls
global class LNE_FlashTab_CX {
    
    private ApexPages.StandardController std;
    private final Event__c relatedEvent;
    private final SObject parent;
    public Boolean flashProcess {get;set;}

    
    public LNE_FlashTab_CX( ApexPages.StandardController standard ){
        this.std = standard;
        parent = std.getRecord();
        relatedEvent = [SELECT Id, Status__c FROM Event__c
                        WHERE Id = :parent.id];
        if(relatedEvent.Status__c == 'Flash Started' || relatedEvent.Status__c == 'Flash Complete'){
            flashProcess = true;
        }else{
            flashProcess = false;
        }
    }
    
    public void startFlashProcess(){
        
        
          relatedEvent.Status__c = 'Flash Started';

          update relatedEvent;

          flashProcess = true;
  
    }

    @RemoteAction
    global static Boolean copyToFlash(Id eventId) {
        LNE_LedgerEntryUtil.copyToFlash(eventId);
        return true;
    }

}