src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdvertisingSettlementPlan__c</fullName>
        <label>Advertising Settlement Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Settle at Actual</fullName>
                </value>
                <value>
                    <fullName>Settle at Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAmount__c</fullName>
        <label>Contra Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraPercent__c</fullName>
        <label>Contra %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ContraType__c</fullName>
        <label>Contra Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventAdvertisingSettlementPlan__c</fullName>
        <description>Internal field only used in Apex triggers</description>
        <formula>TEXT(Event__r.AdvertisingSettlementPlan__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Advertising Settlement Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InHouseMax__c</fullName>
        <label>In House Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InHouseMin__c</fullName>
        <label>In House Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InHouseRateType__c</fullName>
        <label>In House Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferMax__c</fullName>
        <label>Offer Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferMin__c</fullName>
        <label>Offer Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferRateType__c</fullName>
        <label>Offer Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rdPartyPercent__c</fullName>
        <label>3rd Party %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAmount__c</fullName>
        <label>Contra Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraPercent__c</fullName>
        <label>Contra %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ContraType__c</fullName>
        <label>Contra Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventAdvertisingSettlementPlan__c</fullName>
        <description>Internal field only used in Apex triggers</description>
        <formula>TEXT(LedgerEntry__r.Event__r.AdvertisingSettlementPlan__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Advertising Settlement Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InHouseMax__c</fullName>
        <label>In House Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InHouseMin__c</fullName>
        <label>In House Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InHouseRateType__c</fullName>
        <label>In House Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferMax__c</fullName>
        <label>Offer Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferMin__c</fullName>
        <label>Offer Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferRateType__c</fullName>
        <label>Offer Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Truck</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>% of Gross</fullName>
                </value>
                <value>
                    <fullName>% of Adjusted Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentRecordTypeID__c</fullName>
        <description>Internal field only used in Apex triggers</description>
        <formula>LedgerEntry__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Record Type ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TicketScaleList__c</fullName>
        <label>Ticket Scale List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rdPartyPercent__c</fullName>
        <label>3rd Party %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_LedgerEntryBreakoutMetrics_T.cls
/**
 *	Trigger logic to check for changes on any fields that would cause the
 *	financial calculator to fire off
 *	@author Daniel Nakonieczny
 **/
public with sharing class LNE_LedgerEntryBreakoutMetrics_T {
    private static String RT_EXPENSES = 'LedgerEntry__c.Expenses';

    private static Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
        new String[]{ RT_EXPENSES }
    );

    private static Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
    
	/**
     *  Checks if any fields changed that would require a recalculation of event totals
     *  @param newList LedgerEntryBreakout__c[]
     *  @param oldMap Map<Id,LedgerEntryBreakout__c>
     *  @return LedgerEntryBreakout__c[] - list of ledgers updated.
    **/
    
    public static LedgerEntryBreakout__c[] execute( LedgerEntryBreakout__c[] newList, Map<Id,LedgerEntryBreakout__c> oldMap ){
    	List<LedgerEntryBreakout__c> changedLedgers = new List<LedgerEntryBreakout__c>();
    	Set<Id> listOfRelatedEventIds = new Set<Id>();
        Set<Id> parentLedgersId = new Set<Id>();
        ChangedLedgerEntryBreakout objChange = null;

 		if (oldMap == null){
            oldMap = new Map<Id, LedgerEntryBreakout__c>();
        }

        for (LedgerEntryBreakout__c newLedger : newList ){
            if(oldMap.containsKey(newLedger.Id)){
                
                LedgerEntryBreakout__c oldLedger = oldMap.get(newLedger.Id);
                objChange = new ChangedLedgerEntryBreakout(oldLedger, newLedger);
                
                if(
                    objChange.notEquals('BaseAmount__c') ||
                    objChange.notEquals('Min__c') ||
                    objChange.notEquals('Max__c') ||
                    objChange.notEquals('ContraAmount__c') ||
                    objChange.notEquals('ContraPercent__c') ||
                    objChange.notEquals('X3rdPartyPercent__c') ||
                    objChange.notEquals('OfferRate__c') ||
                    objChange.notEquals('OfferMin__c') ||
                    objChange.notEquals('OfferMax__c') ||
                    objChange.notEquals('InHouseRate__c') ||
                    objChange.notEquals('InHouseMin__c') ||
                    objChange.notEquals('InHouseMax__c') ||
                    objChange.notEqualsStr('RateType__c', false) ||
                    objChange.notEqualsStr('ContraType__c', false) ||
                    objChange.notEqualsStr('ApplyTicketScale__c', false) ||
                    objChange.notEqualsStr('TicketScaleList__c', false) ||
                    objChange.notEqualsStr('OfferRateType__c', false) ||
                    objChange.notEqualsStr('InHouseRateType__c', false)
                ) {
                    if (objChange.getNewLedgerEntryBreakout().LedgerEntry__c != null) {
                        parentLedgersId.add(objChange.getNewLedgerEntryBreakout().LedgerEntry__c);  
                    }

                    changedLedgers.add(objChange.getNewLedgerEntryBreakout());
                  }

                processSettlementLedger(objChange);
            } else {
                if (newLedger.LedgerEntry__c != null) {
                    parentLedgersId.add(newLedger.LedgerEntry__c);  
                }
                changedLedgers.add(newLedger);
            }
        }

        if (!parentLedgersId.isEmpty()) {
            List<LedgerEntry__c> parentLedgers = [SELECT Id, Event__c FROM LedgerEntry__c WHERE Id IN :parentLedgersId];

            for (LedgerEntry__c newLedger : parentLedgers ){
                  listOfRelatedEventIds.add(newLedger.Event__c);
            }

            LNE_FinancialCalculator.addEventIdSet(listOfRelatedEventIds);
        }

		return changedLedgers;
    }

    /**
     *  Sets Settle at Actual to true if parent Event__r.AdvertisingSettlementPlan__c is Settle at Actual
     *  SHOULD ONLY RUN BEFORE INSERT
     *  @param newList LedgerEntryBreakout__c[]]
    **/
    public static void checkSettleAtActual(LedgerEntryBreakout__c[] newList) {
        for (LedgerEntryBreakout__c newLedger : newList ) {
            if (newLedger.ParentRecordTypeID__c == RT_EXPENSES_ID && String.isNotBlank(newLedger.EventAdvertisingSettlementPlan__c) && newLedger.Category__c == 'Advertising Expense') {
                if (newLedger.EventAdvertisingSettlementPlan__c == 'Settle at Actual' && newLedger.SettleAtActual__c == false) {
                    newLedger.SettleAtActual__c = true;
                }
                
                if (newLedger.EventAdvertisingSettlementPlan__c == 'Settle at Offer' && newLedger.SettleAtActual__c == true) {
                    newLedger.SettleAtActual__c = false;
                }
            }
        }
    }

    private static void processSettlementLedger(ChangedLedgerEntryBreakout ledger) {
        List<String> fieldsToCheck = new List<String>{'PromoterAmount','ArtistAmount','VenueAmount','LNTouringAmount'};
        Boolean settlementRateTypeChanged = ledger.notEqualsStr('SettlementRateType__c', true);

        for (String field : fieldsToCheck) {
            if (ledger.notEquals(field+'__c') && ledger.equals(field+'Rate__c') && settlementRateTypeChanged == false) {
                populateSettlementValue(ledger.getNewLedgerEntryBreakout(), field);
            }
        }
    }

    private static void populateSettlementValue(LedgerEntryBreakout__c l, String fieldName) {
        String source = fieldName + '__c';
        String destination = fieldName + 'Rate__c';
        l.put(destination, l.get(source));
        l.SettlementRateType__c = 'Flat';
    }

    /**
     *  Internal class to represent the changes from the object.
    **/
    class ChangedLedgerEntryBreakout extends LNE_SObjectChange {
        
        ChangedLedgerEntryBreakout( LedgerEntryBreakout__c oldObject, LedgerEntryBreakout__c newObject ){
            super( oldObject, newObject );
        }
        
        LedgerEntryBreakout__c getNewLedgerEntryBreakout(){
            return( (LedgerEntryBreakout__c)this.newObject );
        }
    }
    
}