src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContraAmount__c</fullName>
        <label>Contra Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraPercent__c</fullName>
        <label>Contra %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ContraType__c</fullName>
        <label>Contra Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X3rdPartyPercent__c</fullName>
        <label>3rd Party %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>ApplyTicketScale__c</fullName>
        <label>Apply Ticket Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RateType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Paid Tickets</fullName>
                </value>
                <value>
                    <fullName>All Drop Count</fullName>
                </value>
                <value>
                    <fullName>Selected Tickets</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <formula>LedgerEntry__r.Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContraAmount__c</fullName>
        <label>Contra Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraPercent__c</fullName>
        <label>Contra %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ContraType__c</fullName>
        <label>Contra Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X3rdPartyPercent__c</fullName>
        <label>3rd Party %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_GridBuddyCalculationAPI_CX_Test.cls
@isTest
public class LNE_GridBuddyCalculationAPI_CX_Test {
	
	static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';
	
	class TestSettings {
		
		public TestSettings() {}
		
		public LedgerEntry__c typicalSetup(){
			
		 List<LedgerEntry__c> savedLedgerEntries = new List<LedgerEntry__c>();
			
		 Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ RT_Ancillary }
			);
			Id RT_ANCILLARY_ID = recordTypeMap.get( RT_Ancillary );
		
			  GLAccount__c testGlaAcct1 = new GLAccount__c (
				Type__c = 'Ancillary',
				Name = 'Parking Revenue',
				Category__c = 'Other Event Revenue',
					GLCode__c = '12345'
			);
			
			insert testGlaAcct1;
			
			Event__c Evt1 = new Event__c(
				ProjectedPaidTickets__c = 20000,
				ProjectedDropCount__c = 30000
			);
			
			LNE_TestObjectFactory.createStandardDataSet( Evt1 );
			
			LedgerEntry__c Ledger1 = new LedgerEntry__c (
				GLAccount__c = testGlaAcct1.Id,
				BaseAmount__c = 33343,
				RateType__c = 'Flat', 
				RecordTypeId = RT_ANCILLARY_ID,
				Event__c = Evt1.Id
			); 

			insert Ledger1;
		   
			return Ledger1;
		}
		
		public void finalize(){}
	}
	
	//-- test test methods here

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
	
	static testMethod void runSetupAWithoutException() {
		try {
			TestSettings ts = new TestSettings();
			ts.typicalSetup();
			ts.finalize();
		} catch( Exception err ){
			System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
		}
	}
	
	//-- test functionality here
	
	static testMethod void testLedgerEntryAPI() {
		TestSettings ts = new TestSettings();
		LedgerEntry__c ledgerEntry = ts.typicalSetup();
		ledgerEntry.BaseAmount__c = 5;
		ledgerEntry.RateType__c = 'Per Cap';
		ledgerEntry.Min__c = 180000;
		ledgerEntry.Max__c = 300000;
		ledgerEntry.ApplyTicketScale__c = 'All Drop Count';
		ledgerEntry.ContraPercent__c = 0.44;
		ledgerEntry.ContraAmount__c = 0;
		ledgerEntry.X3rdPartyPercent__c = 0;
		ledgerEntry.ContraType__c = 'Per Cap';
		
		PageReference pageRef = Page.LNE_GridBuddyCalculationAPI;
		pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(ledgerEntry));
		pageRef.getParameters().put('callback', 'testApiCallback2');
		Test.setCurrentPageReference(pageRef);
		LNE_GridBuddyCalculationAPI_CX api = new LNE_GridBuddyCalculationAPI_CX();
		api.processRequest();
	}

	static testMethod void testLedgerEntryBreakoutAPI() {
		TestSettings ts = new TestSettings();
		LedgerEntry__c ledgerEntry = ts.typicalSetup();
		ledgerEntry.BaseAmount__c = 5;
		ledgerEntry.RateType__c = 'Per Cap';
		ledgerEntry.Min__c = 180000;
		ledgerEntry.Max__c = 300000;
		ledgerEntry.ApplyTicketScale__c = 'All Drop Count';
		ledgerEntry.ContraPercent__c = 0.44;
		ledgerEntry.ContraAmount__c = 0;
		ledgerEntry.X3rdPartyPercent__c = 0;
		ledgerEntry.ContraType__c = 'Per Cap';
		
		Test.startTest();
		
		update ledgerEntry;

		LedgerEntryBreakout__c leb = new LedgerEntryBreakout__c (
            BaseAmount__c = 33343,
            RateType__c = 'Flat', 
            LedgerEntry__c = ledgerEntry.Id,
            OfferRate__c  = 123.5,                  
            InHouseRateType__c = 'Flat',
            InHouseRate__c = 98         
        );
		
		PageReference pageRef = Page.LNE_GridBuddyCalculationAPI;
		pageRef.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(leb));
		pageRef.getParameters().put('callback', 'testApiCallback2');
		Test.setCurrentPageReference(pageRef);
		LNE_GridBuddyCalculationAPI_CX api = new LNE_GridBuddyCalculationAPI_CX();
		api.processRequest();
	}
}