src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Artists__c</fullName>
        <label>Artist(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UsingHouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_UpdateLedgerHouseNut_T_Test.cls
@isTest
private class LNE_UpdateLedgerHouseNut_T_Test {
	
	static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    /**
     *  Test: The Artists__c string should be a line break delimited list of all artists involved (via associated deals) in order of deal rank
     */ 
    static testMethod void testDidHouseNutValueCopy() {
        LNE_TestObjectFactory.createStandardDataSet();
        
        Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{ RT_Ancillary }
		);
		Id RT_ANCILLARY_ID = recordTypeMap.get( RT_Ancillary );

        List<Event__c> testEvents = [SELECT Id, UsingHouseNut__c, Artists__c FROM Event__c LIMIT 1];
        System.assertEquals(1, testEvents.size());
        testEvents[0].UsingHouseNut__c = true;
        update testEvents[0];

        List<GLAccount__c> testGlas = [SELECT Id FROM GLAccount__c WHERE GLCode__c IN ('50103', '50302')];
        System.assertEquals(2, testGlas.size());
        
        System.assertEquals(true, testEvents[0].UsingHouseNut__c);

		 LedgerEntry__c ledgerEntry = new LedgerEntry__c(
			GLAccount__c = testGlas[0].Id,
			RecordTypeId = RT_ANCILLARY_ID,
			BaseAmount__c = 99999999,
			RateType__c = 'Flat',
			Event__c = testEvents[0].Id,
			HouseNut__c = true
		);
		insert ledgerEntry;

        List<LedgerEntry__c> testLedgerEntries = [SELECT Id, HouseNut__c FROM LedgerEntry__c WHERE Event__c = :testEvents[0].Id];
        System.assertEquals(1, testLedgerEntries.size());
        System.assertEquals(true, testLedgerEntries[0].HouseNut__c);

        // Now set Event house nut to false and all the ledgers should be false too
        testEvents[0].UsingHouseNut__c = false;
        update testEvents[0];
        System.assertEquals(false, testEvents[0].UsingHouseNut__c);
        // invoke trigger
        // then the ledgers should have house nut false just like the event
        //System.assertEquals(false, testLedgerEntries[0].HouseNut__c);
    }

}