src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_CheckLinkedToTour_T_Test.cls
@isTest
public class LNE_CheckLinkedToTour_T_Test{

	public static final String GL_CODE='50360';

    
	class TestSettings {
		public Event__c testEvent;
		
		public TestSettings() {

		}
		
		public void typicalSetup(){
			Event__c e = [SELECT Id FROM Event__c LIMIT 1];
			testEvent = e;
		}
		
		public void finalize(){
		}
	}

    @testSetup
    static void setup(){
    	Event__c event = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createEvent()
			).addProperties( new Map<String,Object>{
			    'Tour__c' => null
			}).buildEvent();
        
        Tour__c tour = new Tour__c();
       	insert Tour;

        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet(event);
        
    }

	@isTest static void testCheckLinkedToTour() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();

		Test.startTest();

		Event__c testEvent = [SELECT Id, Tour__c
							   FROM Event__c LIMIT 1];
		Tour__c testTour = [SELECT Id
                           	FROM Tour__c LIMIT 1];
		
		testEvent.Tour__c = testTour.Id;
        
        update testEvent;
        
        List<LedgerEntry__c> tourLe = [SELECT Id FROM LedgerEntry__c WHERE Event__c =:testEvent.Id AND GLCode__c = :GL_CODE];
         
        system.assertEquals(tourLe.size(), 1);
            
        testEvent.Tour__c  = null;
        
        update testEvent;
        
        testEvent.Tour__c = testTour.Id;
        
        update testEvent; 
        
        tourLe = [SELECT Id FROM LedgerEntry__c WHERE Event__c =:testEvent.Id AND GLCode__c = :GL_CODE];
         
        system.assertEquals(tourLe.size(), 1);
        
		Test.stopTest();
	}
}