src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>BookingHouseNut__c</fullName>
        <label>Booking House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementHouseNut__c</fullName>
        <label>Settlement House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UsingHouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_UpdateEventHouseNut.cls
/**
 * Used on the expenseTab page to update the event__c. UsingHouseNut__c and HouseNutAmount__c values
 * @author Dominic Aveyard <daveyard@salesforce.com>
 **/
global class LNE_UpdateEventHouseNut {
    public LNE_UpdateEventHouseNut(ApexPages.StandardController controller) {}
    
    /** 
     *  Remote action to update the event UsingHouseNut__c and BookingHouseNut__c
     **/
    @RemoteAction
    global static Event__c updateEvent(Id eventId, Boolean UsingHouseNut, Decimal HouseNutAmount ){
        return updateEvent(eventId, UsingHouseNut, HouseNutAmount, 'BookingHouseNut__c');
    }

    @RemoteAction
    global static Event__c updateEventSettlement(Id eventId, Boolean UsingHouseNut, Decimal HouseNutAmount ){
        return updateEvent(eventId, UsingHouseNut, HouseNutAmount, 'SettlementHouseNut__c');
    }

    private static Event__c updateEvent(Id eventId, Boolean usingHouseNut, Decimal houseNutAmount, String field) {
        Event__c updateEvent = new Event__c(Id=eventId, UsingHouseNut__c=UsingHouseNut);
        updateEvent.put(field, HouseNutAmount);
        update updateEvent;

        return updateEvent ;
    }
}