src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdjustedGrossPotential__c</fullName>
        <label>Adjusted Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossPotential__c</fullName>
        <label>Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetGrossPotential__c</fullName>
        <label>Net Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberofTrucks__c</fullName>
        <label># of Trucks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedAdjustedGross__c</fullName>
        <label>Projected Adjusted Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedGross__c</fullName>
        <label>Projected Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedNetGross__c</fullName>
        <label>Projected Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutPaidTickets__c</fullName>
        <label>Sellout Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contra</fullName>
        <active>true</active>
        <description>Event expenses calculated from ancillary revenues</description>
        <label>Contra</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <formula>LedgerEntry__r.Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PriceLevel__c</fullName>
        <label>Price Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventExpenseCalculationAPI_CX_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class LNE_EventExpenseCalculationAPI_CX_Test {

    @testSetup
    static void globalSetup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
    static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';

    class TestSettings {

        public TicketScale__c ticketScale1 = null;
        private Event__c event1 = null;
        //private List<GLAccount__c> glAccounts = new List<GLAccount__c>();
        private List<LedgerEntry__c> savedLedgerEntries = new List<LedgerEntry__c>();
        private List<LedgerEntryBreakout__c> savedLedgerEntryBreaks = new List<LedgerEntryBreakout__c>();
        
        public TestSettings() {
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
        }

        private Id getRTAncillaryId(){
            Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
                new String[]{ RT_Ancillary }
            );
            return recordTypeMap.get( RT_Ancillary );
        }

        public List<LedgerEntry__c> getLedgerEntries(){

            List<String> fieldNames = new List<String>(LedgerEntry__c.sObjectType.getDescribe().fields.getMap().keySet());
            String ledgerEntryQuery = 'select ' + String.join(fieldNames, ',') + ' from LedgerEntry__c';
            List<LedgerEntry__c> ledgerEntries = Database.query(ledgerEntryQuery);
            return ledgerEntries;
        }

        private void createEvent(){
            if(event1 == null){
                Event__c event = new Event__c(
                    status__c = 'Draft',
                    ProjectedPaidTickets__c = 20000,
                    ProjectedDropCount__c = 30000,
                    NumberofTrucks__c  = 12,
                    SelloutDropCount__c = 2,
                    SelloutPaidTickets__c = 2,
                    NetGrossPotential__c = 2,
                    ProjectedNetGross__c = 4,
                    GrossPotential__c = 5,
                    ProjectedGross__c  = 9,
                    AdjustedGrossPotential__c = 9,
                    ProjectedAdjustedGross__c  = 11
                );
                
                //insert event;
                LNE_TestObjectFactory.createStandardDataSet( event );
                
                event1 = event;
            }
        }

        private void createTicketScale(){
            if(ticketScale1 == null){
                TicketScale__c ticketScale = new TicketScale__c(
                    Event__c = event1.Id,
                    PriceLevel__c = 'Reserved',
                    ProjectedPaidTickets__c = 10000,
                    Kills__c = 500,
                    Comps__c = 5000,
                    Capacity__c = 16000,
                    Price__c = 2000
                );      
                insert ticketScale;
                ticketScale1 = ticketScale;
            }
        }

        public LedgerEntry__c setupTest1(){
            createEvent();
            createTicketScale();

            GLAccount__c testGlaAcct1 = new GLAccount__c (
                Type__c = 'Ancillary',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12345'
            );
            insert testGlaAcct1;

            LedgerEntry__c ledgerEntry1 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct1.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 123.9,
                InHouseRateType__c = 'Flat',
                InHouseRate__c = 98,
                OfferMin__c = 43.12,
                OfferAtSellout__c = 20.01,
                OfferAtProjection__c = 12.09,   
                InHouseMin__c = 20.09,
                InHouseProjection__c = 8.09,        
                TicketScaleList__c = '|' + ticketScale1.Id + '|'
            ); 
            insert ledgerEntry1;

            LedgerEntryBreakout__c leb1 = new LedgerEntryBreakout__c (
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry1.Id,
                OfferRate__c  = 123.5,                  
                InHouseRateType__c = 'Flat',
                InHouseRate__c = 98         
            );    
            insert leb1;

            return ledgerEntry1;
        }

        public LedgerEntry__c setupTest2(){
            createEvent();
            createTicketScale();

            GLAccount__c testGlaAcct2 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12346'
            );   
            insert testGlaAcct2;
                    
            LedgerEntry__c ledgerEntry2 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct2.Id,
                BaseAmount__c = 33343,
                RateType__c = 'Flat', 
                OfferRateType__c = 'Flat',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 123.5,
                InHouseRate__c = 21,
                InHouseRateType__c = 'Flat',
                OfferMax__c = 65.09,
                OfferAtSellout__c = 70.09,
                OfferAtProjection__c = 78.99,
                InHouseMax__c = 20.09,
                InHouseProjection__c = 22.09
            );       
            insert ledgerEntry2;

            LedgerEntryBreakout__c leb2 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry2.Id,
                OfferRate__c  = 123.8,
                OfferRateType__c = 'Flat',
                InHouseRate__c = 21,
                InHouseRateType__c = 'Flat'
            ); 
            insert leb2;

            return ledgerEntry2;
        }

        public LedgerEntry__c setupTest3(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct3 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12348'
            );    
            insert testGlaAcct3;

            LedgerEntry__c ledgerEntry3 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct3.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = 'Per Truck',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 123.5,
                InHouseRate__c = 22,
                InHouseRateType__c = 'Per Truck'
            );       
            insert ledgerEntry3;

            LedgerEntryBreakout__c leb3 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry3.Id,
                OfferRate__c  = 123.8,
                OfferRateType__c = 'Per Truck',
                InHouseRate__c = 22,
                InHouseRateType__c = 'Per Truck'
            );
            insert leb3;

            return ledgerEntry3;
        }

        public LedgerEntry__c setupTest4(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct4 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12318'
            );         
            insert testGlaAcct4;

            LedgerEntry__c ledgerEntry4 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct4.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = 'Per Drop Count',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 123.5,
                InHouseRate__c = 23,
                InHouseRateType__c = 'Per Drop Count'
            );     
            insert ledgerEntry4;

            LedgerEntryBreakout__c leb4 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry4.Id,
                OfferRate__c  = 123.51 ,
                OfferRateType__c = 'Per Drop Count',
                InHouseRate__c = 23,
                InHouseRateType__c = 'Per Drop Count'
            );    
            insert leb4;

            return ledgerEntry4; 
        }
        
        public LedgerEntry__c setupTest5(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct5 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '12618'
            );     
            insert testGlaAcct5;

            LedgerEntry__c ledgerEntry5 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct5.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = 'Per Paid Ticket',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 123.5,
                InHouseRate__c = 25,
                InHouseRateType__c = 'Per Paid Ticket'
            );       
            insert ledgerEntry5;

            LedgerEntryBreakout__c leb5 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry5.Id,
                OfferRate__c  = 103.51,
                OfferRateType__c = 'Per Paid Ticket',
                InHouseRate__c = 25,
                InHouseRateType__c = 'Per Paid Ticket'
            ); 
            insert leb5; 

            return ledgerEntry5;
        }
        
        public LedgerEntry__c setupTest6(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct6 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '13618'
            );   
            insert testGlaAcct6;

            LedgerEntry__c ledgerEntry6 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct6.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = '% of Net Gross',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 1230.5,
                InHouseRate__c = 29,
                InHouseRateType__c = '% of Net Gross'
            );      
            insert ledgerEntry6;

            LedgerEntryBreakout__c leb6 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry6.Id,
                OfferRate__c  = 103.51,
                OfferRateType__c = '% of Net Gross',
                InHouseRate__c = 29,
                InHouseRateType__c = '% of Net Gross'                   
            ); 
            insert leb6;

            return ledgerEntry6;
        }
        
        public LedgerEntry__c setupTest7(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct7 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '19618'
            );      
            insert testGlaAcct7;

            LedgerEntry__c ledgerEntry7 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct7.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = '% of Gross',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 1230.5,
                InHouseRate__c = 299,
                InHouseRateType__c = '% of Gross'
            );     
            insert ledgerEntry7; 

            LedgerEntryBreakout__c leb7 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry7.Id,
                OfferRate__c  = 103.51,
                OfferRateType__c = '% of Gross',
                InHouseRate__c = 299,
                InHouseRateType__c = '% of Gross'                
            );
            insert leb7;

            return ledgerEntry7;
        }
        
        public LedgerEntry__c setupTest8(){
            createEvent();
            createTicketScale();
            
            GLAccount__c testGlaAcct8 = new GLAccount__c (
                Type__c = 'Contra',
                Name = 'Parking Revenue',
                Category__c = 'Other Event Revenue',
                GLCode__c = '18618'
            );    
            insert testGlaAcct8;

            LedgerEntry__c ledgerEntry8 = new LedgerEntry__c (
                GLAccount__c = testGlaAcct8.Id,
                BaseAmount__c = 33333,
                RateType__c = 'Flat', 
                OfferRateType__c = '% of Adjusted Gross',
                RecordTypeId = getRTAncillaryId(),
                Event__c = event1.Id,
                OfferRate__c  = 1230.5,
                InHouseRate__c = 290,
                InHouseRateType__c = '% of Adjusted Gross'
            );   
            insert ledgerEntry8;

            LedgerEntryBreakout__c leb8 = new LedgerEntryBreakout__c (
                BaseAmount__c = 333,
                RateType__c = 'Flat', 
                LedgerEntry__c = ledgerEntry8.Id,
                OfferRate__c  = 103.51 ,
                OfferRateType__c = '% of Adjusted Gross',
                InHouseRate__c = 290,
                InHouseRateType__c = '% of Adjusted Gross'            
            );
            insert leb8;

            return ledgerEntry8;
        }
        
        public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
        }
    }
    
    //-- test test methods here
  
    static testMethod void testAPI() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c ledgerEntry = ts.setupTest1();
        ledgerEntry.BaseAmount__c = 5;
        ledgerEntry.RateType__c = 'Flat';
        ledGerEntry.OfferRate__c= 123.32;
        ledgerEntry.Min__c = 180000;
        ledgerEntry.Max__c = 300000;
        ledgerEntry.ApplyTicketScale__c = 'All Drop Count';
        
        LedgerEntryBreakout__C LEBreakout = [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, RateType__c, Min__c, Max__c,OfferRatetype__c, ApplyTicketScale__c, GrossRevenue__c, GrossPerPaid__c, ContraAtForecast__c, Contra_At_Forecast__c, Net_Revenue__c, NetPerPaid__c FROM LedgerEntryBreakout__c WHERE LedgerEntry__c =:ledgerEntry.Id LIMIT 1];
         
        LEBreakout.BaseAmount__c = 5;
        LEBreakout.RateType__c = 'Flat';
        LEBreakout.Min__c = 180000;
        LEBreakout.Max__c = 300000;
        LEBreakout.ApplyTicketScale__c = 'All Drop Count';
        
        ts.finalize();
             
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(ledgerEntry));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(LEBreakout));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        
    }
    
    static testMethod void testCalculatedFields1() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest1();
        List<LedgerEntryBreakout__c> ledgerEntries = [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
       
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Flat';
        ledgerEntries.get(0).OfferRateType__c = 'Flat';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        Test.stopTest();
        
    }
        
    static testMethod void testCalculatedFields2() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest2();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
       
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        Test.stopTest();
        
    }
    
    static testMethod void testCalculatedFields() {
        TestSettings ts = new TestSettings();
        ts.finalize();
               
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize('aBC'));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
    }  
    
    static testMethod void testCalculatedFields3() { 
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest3();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
        
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();

        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        Test.stopTest();
        
    }   
    
    static testMethod void testCalculatedFields4() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest4();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
        
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        Test.stopTest();
        
    }   
    
    static testMethod void testCalculatedFields5() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest5();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
       
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();
        Test.stopTest();
        
    }
    
    static testMethod void testCalculatedFields6() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest6();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
      
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();       
        Test.stopTest();
        
    }   
    
    static testMethod void testCalculatedFields7() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest7();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
        
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();       
        Test.stopTest();
        
    }   
    
    static testMethod void testCalculatedFields8() {
        TestSettings ts = new TestSettings();
        LedgerEntry__c leGL = ts.setupTest8();
        List<LedgerEntryBreakout__c> ledgerEntries= [SELECT Id, InHouseRate__c, InHouseRateType__c, BaseAmount__c, OfferRateType__c, RateType__c, Min__c, Max__c, ApplyTicketScale__c, TicketScaleList__c, ContraPercent__c, ContraAmount__c, X3rdPartyPercent__c, ContraType__c FROM LedgerEntryBreakout__c where LedgerEntry__c =:leGL.Id];
        
        ledgerEntries.get(0).TicketScaleList__c = ts.ticketScale1.Id;
        upsert ledgerEntries.get(0);
        ledgerEntries.get(0).BaseAmount__c = 10;
        ledgerEntries.get(0).OfferRate__c = 1009.98;
        ledgerEntries.get(0).RateType__c = 'Per Cap';
        ledgerEntries.get(0).Min__c = 0;
        ledgerEntries.get(0).Max__c = 0;
        ledgerEntries.get(0).ApplyTicketScale__c = 'Selected Tickets';
        ledgerEntries.get(0).ContraPercent__c = 0;
        ledgerEntries.get(0).ContraAmount__c = 1000;
        ledgerEntries.get(0).X3rdPartyPercent__c = 0;
        ledgerEntries.get(0).ContraType__c = 'Flat';
        
        ts.finalize();
        
        Test.startTest();
        PageReference pageRef = Page.LNE_EventExpenseCalculationAPI;
        pageRef.getParameters().put('LedgerEntry__c', JSON.serialize(leGL));
        pageRef.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef);
        LNE_EventExpenseCalculationAPI_CX api = new LNE_EventExpenseCalculationAPI_CX();
        api.processRequest();
        
        PageReference pageRef2 = Page.LNE_EventExpenseCalculationAPI;
        pageRef2.getParameters().put('LedgerEntryBreakout__c', JSON.serialize(ledgerEntries.get(0)));
        pageRef2.getParameters().put('callback', 'testApiCallback2');
        Test.setCurrentPageReference(pageRef2);
        api.processRequest();       
        Test.stopTest();
        
    } 
    
}