src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementArtistDealTab_CX.cls
public with sharing class LNE_SettlementArtistDealTab_CX {
	private final SObject parent;

	public Event__c eventRecord {get;set;}

	public LNE_SettlementArtistDealTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        eventRecord = [SELECT SettlementStarted__c FROM Event__c WHERE Id = :parent.Id];
    }

    public void startSettlement() {
        LNE_SettlementUtil.startSettlementProcess(eventRecord.Id);
    }
}