src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ActualDropCount__c</fullName>
        <label>Actual Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique External Id for the Ledger Entry</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PerformingRightsFee__c.object
<CustomObject>
    <fields>
        <fullName>Breakout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CapacityRangeEnd__c</fullName>
        <label>Capacity Range End</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CapacityRangeStart__c</fullName>
        <label>Capacity Range Start</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Performing Rights Fees</relationshipLabel>
        <relationshipName>PerformanceRightsFees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RateAmount__c</fullName>
        <label>Rate/Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Net Gross</fullName>
                </value>
                <value>
                    <fullName>Per Drop Count</fullName>
                </value>
                <value>
                    <fullName>Per Paid Ticket</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASCAP</fullName>
                </value>
                <value>
                    <fullName>BMI</fullName>
                </value>
                <value>
                    <fullName>GMR</fullName>
                </value>
                <value>
                    <fullName>SESAC</fullName>
                </value>
                <value>
                    <fullName>SOCAN</fullName>
                </value>
                <value>
                    <fullName>Event Insurance Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Performing Rights Fee</label>
    <nameField>
        <displayFormat>PRF-{000000}</displayFormat>
        <label>Performing Rights Fee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performing Rights Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_LedgerEntryDefaultFees_Test.cls
/**
 * 
 *
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class LNE_LedgerEntryDefaultFees_Test {
	
	static final String RT_Expenses = 'LedgerEntry__c.Expenses';
	
	class TestSettings {
		
		public TestSettings() {

		}
		
		
		public void typicalSetup(){
			
			
		 Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
				new String[]{ RT_Expenses }
			);
			Id RT_EXPENSES_ID = recordTypeMap.get( RT_Expenses );

            List<GLAccount__c> gls = new List<GLAccount__c>();
            GLAccount__c breakoutGL = LNE_TestObjectFactory.createGLAccount('ASCAP/BMI/SESAC/GMR/BUMA Expense', '50202');
            gls.add(breakoutGL);
            GLAccount__c eventInsuranceGL = LNE_TestObjectFactory.createGLAccount('Event Insurance Expense', '50306');
            gls.add(eventInsuranceGL);
            
            insert gls;
            
            List<PerformingRightsFee__c> prfs = new List<PerformingRIghtsFee__c>();
            
			PerformingRightsFee__c prf1 = new PerformingRightsFee__c(
            	ExternalId__c = 'ASCAP',
                Type__c = 'ASCAP',
                GLAccount__c = breakoutGL.Id,
                Breakout__c = true,
                CapacityRangeStart__c = 0,
                CapacityRangeEnd__c = 200000,
                RateType__c = '% of Net Gross',
                RateAmount__c = 0.45,
                StartDate__c =  date.ValueOf('2010-01-01'),
                EndDate__c =  date.ValueOf('2030-12-31')
            );
            
            prfs.add(prf1);
            
            PerformingRightsFee__c prf2 = new PerformingRightsFee__c(
            	ExternalId__c = 'EventInsurance',
                Type__c = 'Event Insurance Expense',
                GLAccount__c = eventInsuranceGL.Id,
                Breakout__c = false,
                RateType__c = 'Per Drop Count',
                RateAmount__c = 0.45,
                StartDate__c =  date.ValueOf('2010-01-01'),
                EndDate__c =  date.ValueOf('2030-12-31')
            );
            
            prfs.add(prf2);
            
            insert prfs;
            
			Event__c Evt1 = new Event__c(
				ProjectedPaidTickets__c = 10000,
				ProjectedDropCount__c = 10000,
                ActualDropCount__c = 10000,
                EventLastDate__c = date.today(),
                SelloutDropCount__c= 3000
                
			);
			
			Map<String, Id> objectToId = 
			    LNE_TestObjectFactory.createStandardDataSetList(new List<Event__c>{Evt1});
			
		   	LedgerEntry__c Ledger1 = new LedgerEntry__c (
				GLAccount__c = objectToId.get('ancillary'),
				BaseAmount__c = 100,
				RateType__c = 'Flat', 
				RecordTypeId = RT_EXPENSES_ID,
				Event__c = Evt1.Id
			); 

			insert Ledger1;
		}
		
	   
		
		public void finalize(){
		}
	}
	
	//-- test test methods here

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
	
	static testMethod void runSetupAWithoutException() {
		try {
			TestSettings ts = new TestSettings();
			ts.typicalSetup();
			ts.finalize();
		} catch( Exception err ){
			System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
		}
	}
	
	//-- test functionality here
	
	static testMethod void testLedgerEntryDefaultFees() {
		TestSettings ts = new TestSettings();
	 	ts.typicalSetup();
        
        test.startTest();
        		
        	Event__c evt1 = [SELECT Id FROM Event__c LIMIT 1];
        	LNE_LedgerEntryDefaultFees.defaultFees(evt1.Id);
        	
        	
        test.stopTest();
        List<LedgerEntry__c> le = [SELECT Id FROM LedgerEntry__c];
      	System.assertEquals(3, le.size());
        
		
	}
    
    
}