src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ActualDropCount__c</fullName>
        <label>Actual Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EventStartTimeEntered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Start Time Entered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>COGSAtForecast__c</fullName>
        <label>COGS At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContraAtForecast__c</fullName>
        <label>Contra At Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EventDateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Date Time</label>
        <referenceTo>EventDateTime__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrossRevenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InHouseProjection__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>In House Projection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetRevenue__c</fullName>
        <label>Net Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PlanAmount__c</fullName>
        <label>Plan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectionAmount__c</fullName>
        <label>Projection Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventMetrics_T_Test.cls
@isTest
public class LNE_EventMetrics_T_Test {
	
	static final String RT_Expenses = 'LedgerEntry__c.Expenses';
	
	@testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
	
	class TestSettings {
		
		Event__c testEvent;
		Map<String,GLAccount__c> glAccountMap;
		LedgerEntry__c[] testLedgerEntries;
		
		public TestSettings() {}
		
		public void typicalSetup(){
			testEvent = new Event__c(
				ProjectedPaidTickets__c = 10000,
				ProjectedDropCount__c = 10000,
                ActualDropCount__c = 10000,
                SelloutDropCount__c= 3000,
                Status__c = 'Draft',
                EventStartTimeEntered__c = true
			);
            
            LNE_TestObjectFactory.createStandardDataSet(testEvent);
            
             EventDateTime__c evtdt1 = new EventDateTime__c(
            	EventDate__c = date.today(),
                StartTime__c = '11:00 AM',
                Event__c = testEvent.Id
            );
            
            insert evtdt1;
            
            this.glAccountMap = LNE_Util.refreshGLAccountCache();
		    
		    System.assert( glAccountMap != null && glAccountMap.size() > 0, 'GL Accounts should be created already from the createStandardDataSet method above' );
			Id glAccountId1 = this.glAccountMap.get( LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE ).Id;
			Id glAccountId2 = this.glAccountMap.get( LNE_TestObjectFactory.GL_PARKING_REVENUE ).Id;
			
			testLedgerEntries = new LedgerEntry__c[]{
				//-- first ledger entry
				new LedgerEntry__c(
			        GLAccount__c = glAccountId1,
			        BaseAmount__c = 111,
			        RateType__c = 'Flat',
			        PlanAmount__c = 111,
			        COGSAtForecast__c = 111,
			        InHouseProjection__c = 111,
			        GrossRevenue__c = 111,
			        NetRevenue__c = 111,
			        ContraAtForecast__c = 111,
			        Event__c = testEvent.Id
		        ),
				
				//-- second ledger entry
				new LedgerEntry__c(
			        GLAccount__c = glAccountId2,
			        BaseAmount__c = 111,
			        RateType__c = 'Flat',
			        PlanAmount__c = 111,
			        COGSAtForecast__c = 111,
			        InHouseProjection__c = 111,
			        GrossRevenue__c = 111,
			        NetRevenue__c = 111,
			        ContraAtForecast__c = 111,
			        Event__c = testEvent.Id
		        )
			};
			
			insert testLedgerEntries;
        }
        
		public void finalize() {}
	}
	
	static testMethod void runSetupAWithoutException() {
		try {
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false, false);
			Test.startTest();
			TestSettings ts = new TestSettings();
			ts.typicalSetup();
			ts.finalize();
		} catch( Exception err ){
			System.assert( false, 'Exception must not be thrown:' + err.getMessage() );
		}
	}
	
	static testMethod void testLedgers_PlanToProjection() {
		LNE_FinancialCalculator.currentlyRunning = true;
		LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false, false);
		
		Test.startTest();
		
		TestSettings ts = new TestSettings();
	 	ts.typicalSetup();
        
        List<LedgerEntry__c> ledgers = [SELECT PlanAmount__c, ProjectionAmount__c FROM LedgerEntry__c WHERE Id IN :ts.testLedgerEntries];
        
        system.assertEquals(2, ledgers.size());
        
        for (LedgerEntry__c l : ledgers) {
        	system.assertEquals(111, l.PlanAmount__c);
        	system.assertEquals(null, l.ProjectionAmount__c);
        }
    
    	ts.testEvent.Status__c = 'Pending Likely';
    	
    	update ts.testEvent;
    
      	ts.testEvent.Status__c = 'Confirmed';
    
    	update ts.testEvent;
    	
    	ledgers = [SELECT PlanAmount__c, ProjectionAmount__c FROM LedgerEntry__c WHERE Id IN :ts.testLedgerEntries];
        
        for (LedgerEntry__c l : ledgers) {
        	system.assertEquals(111, l.PlanAmount__c);
        	system.assertEquals(111, l.ProjectionAmount__c);
        }
        	
        Test.stopTest(); 
	}
	
	static testMethod void testLedgers_ProjectionToPlan() {
		LNE_FinancialCalculator.currentlyRunning = true;
		LNE_GeneralSettingsUtil.setLocalBypassSettings(false, true, false, false);
		
		Test.startTest();
		
		TestSettings ts = new TestSettings();
	 	ts.typicalSetup();
        
        List<LedgerEntry__c> ledgers = [SELECT PlanAmount__c, ProjectionAmount__c FROM LedgerEntry__c WHERE Id IN :ts.testLedgerEntries];
        
        system.assertEquals(2, ledgers.size());
        
        for (LedgerEntry__c l : ledgers) {
        	system.assertEquals(111, l.PlanAmount__c);
        	system.assertEquals(null, l.ProjectionAmount__c);
        }
    
    	ts.testEvent.Status__c = 'Pending Likely';
    	
    	update ts.testEvent;
    
      	ts.testEvent.Status__c = 'Confirmed';
    
    	update ts.testEvent;
    	
    	ledgers = [SELECT PlanAmount__c, ProjectionAmount__c FROM LedgerEntry__c WHERE Id IN :ts.testLedgerEntries];
        
        for (LedgerEntry__c l : ledgers) {
        	system.assertEquals(111, l.PlanAmount__c);
        	system.assertEquals(111, l.ProjectionAmount__c);
        	
        	l.ProjectionAmount__c = 222;
        }
        
        update ledgers;
        
        ts.testEvent.Status__c = 'Pending Likely';
    	
    	update ts.testEvent;
    	
    	ledgers = [SELECT PlanAmount__c, ProjectionAmount__c FROM LedgerEntry__c WHERE Id IN :ts.testLedgerEntries];
        
        for (LedgerEntry__c l : ledgers) {
        	system.assertEquals(222, l.PlanAmount__c);
        	system.assertEquals(222, l.ProjectionAmount__c);
        }
        	
        Test.stopTest(); 
	}
}