src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_PromoterCreateEventResults_CC_Test.cls
@isTest
private with sharing class LNE_PromoterCreateEventResults_CC_Test {
	class TestSettings {
        Event__c testEvent;
        
        public TestSettings() {

        }
        
        public void typicalSetup(){
            
            Event__c e = new Event__c(
              ProjectedPaidTickets__c = 20000,
              ProjectedDropCount__c = 30000
            );
            
            insert e;
            testEvent = e;
        }
        
        public void finalize(){}
    }

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    static testMethod void testController() {
    	TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

    	LNE_PromoterCreateEventResults_CC controller = new LNE_PromoterCreateEventResults_CC();
    	controller.gotoEventPage();
    	system.assertEquals(ts.testEvent.Id, controller.newEventId);
    }

    static testMethod void testController_Error() {
    	TestSettings ts = new TestSettings();

    	LNE_PromoterCreateEventResults_CC controller = new LNE_PromoterCreateEventResults_CC();
    	controller.gotoEventPage();
    	system.assertEquals(null, controller.newEventId);
    }
}