src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdvertisingBudget__c</fullName>
        <label>Advertising Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AdvertisingSettlementPlan__c</fullName>
        <label>Advertising Settlement Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Settle at Actual</fullName>
                </value>
                <value>
                    <fullName>Settle at Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberofTrucks__c</fullName>
        <label># of Trucks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SettlementExpensesTab_CX.cls
global with sharing class LNE_SettlementExpensesTab_CX {
	public String VIEW_CALCULATIONS = 'View Calculations';
	public String HIDE_CALCULATIONS = 'Hide Calculations';
	public String calculationsButtonValue {get;set;}
	private final SObject parent;

	public Event__c eventRecord {get;set;}

	global LNE_SettlementExpensesTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        eventRecord = [SELECT SettlementStarted__c, AdvertisingBudget__c, AdvertisingSettlementPlan__c, NumberofTrucks__c 
                                FROM Event__c WHERE Id = :parent.Id];
        calculationsButtonValue = VIEW_CALCULATIONS;
    }

    global void startSettlement() {
        LNE_SettlementUtil.startSettlementProcess(eventRecord.Id);
    }

    global void showHideCalculations() {
    	if (calculationsButtonValue == VIEW_CALCULATIONS) {
    		calculationsButtonValue = HIDE_CALCULATIONS;
    	} else {
    		calculationsButtonValue = VIEW_CALCULATIONS;
    	}
    }
    
    @RemoteAction
    global static void defaultFees(String evtId) {
        LNE_LedgerEntryDefaultFees.defaultFees(evtId, LNE_LedgerEntryDefaultFees.FOR_SETTLEMENT_EXPENSES);
    }  

    @RemoteAction
    global static Boolean saveEvent(Id eventId, String advertisingsettlementplan) {
        Event__c updateEvent = new Event__c(Id=eventId, AdvertisingSettlementPlan__c=advertisingsettlementplan);

        Boolean success = true;
        System.savepoint sp = Database.setSavepoint();
        system.debug('@@@ updateEvent - '+ updateEvent);

        try {
            update updateEvent;
        }
        catch (System.DmlException de) {
            Database.rollback(sp);
            success = false;
        }

        return success;
    }   
}