src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>BaseAmount__c</fullName>
        <label>Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Per Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_SelectFinanceAncCOGSEntries_CX_Test.cls
@IsTest
private class LNE_SelectFinanceAncCOGSEntries_CX_Test {

	static final Id RT_ANCILLARY_ID;
	static final Id RT_COGS_ID;

	static {
		Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
			new String[]{ 'LedgerEntry__c.Ancillary', 'LedgerEntry__c.COGS' }
		);
		RT_ANCILLARY_ID = recordTypeMap.get( 'LedgerEntry__c.Ancillary' );
		RT_COGS_ID = recordTypeMap.get( 'LedgerEntry__c.COGS' );
	}

	@TestSetup
	static void setup() {
		LNE_TestObjectFactory.prepStandardCustomSettings();
		LNE_TestObjectFactory.createStandardDataSet();
	}
 
	class TestSettings {

		public Event__c event {get;set;}
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'TEST_CLASS' );
		}
		
		public TestSettings typicalSetup() {

			GLAccount__c ancillary = [select Id from GLAccount__c where GLCode__c = :LNE_TestObjectFactory.GL_ALCOHOLIC_REVENUE limit 1];
			GLAccount__c cogs = [select Id from GLAccount__c where GLCode__c = :LNE_TestObjectFactory.GL_AUTO_RENTAL_EXPENSE limit 1];
			
			this.event = [select Id from Event__c limit 1];

			LedgerEntry__c ledger0 = new LedgerEntry__c (
				GLAccount__c = ancillary.Id,
				BaseAmount__c = 100,
				RateType__c = 'Flat', 
				RecordTypeId = RT_ANCILLARY_ID,
				Event__c = event.Id
			);
			LedgerEntry__c ledger1 = new LedgerEntry__c (
				GLAccount__c = cogs.Id,
				BaseAmount__c = 100,
				RateType__c = 'Flat', 
				RecordTypeId = RT_COGS_ID,
				Event__c = event.Id
			);
			insert new List<LedgerEntry__c> { ledger0, ledger1 };



			return this;
		}
		
		public TestSettings finalize() {
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
			return this;
		}
	}

	static testMethod void test_SelectFinanceAncillaryCOGSEntries() {
		TestSettings ts = new TestSettings().typicalSetup().finalize();
		Test.startTest();

		PageReference pr = Page.LNE_SelectFinanceAncillaryCOGSEntries;
		pr.getParameters().put('id', ts.event.Id);
		Test.setCurrentPage(pr);

		ApexPages.StandardController sc = new ApexPages.StandardController(ts.event);
		LNE_SelectFinanceAncillaryCOGSEntries_CX cx = new LNE_SelectFinanceAncillaryCOGSEntries_CX(sc);

		List<LNE_LedgerCategoryModel> ancillaries = cx.getAncillaries();
		List<LNE_LedgerCategoryModel> cogs = cx.getCOGs();

		cx.updateLedgerEntries();

	}
	
}