src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ShowCount__c</fullName>
        <label>Show Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventShowCountCalculator_T.cls
/**
 *  Determines the number of shows for an event.
 *  @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
 *  @author Paul Roth <proth@salesforce.com>
 **/
public with sharing class LNE_EventShowCountCalculator_T {
	
	/**
	 * Updates the show count on events based on the number of show counts.
	 * @return Event__c[] - list of events that have the show count changed.
	 **/
	public static Event__c[] execute( EventDateTime__c[] updatedOrDeletedEventDateTimes ){
		
		Set<id> changedEventIds = new Set<id>();
		Event__c[] results = new Event__c[]{};
		
		for( EventDateTime__c changedEvent : updatedOrDeletedEventDateTimes ){
			if( changedEvent.Event__c != null ){
				changedEventIds.add( changedEvent.Event__c );
			}
		}
		
		//-- short circuit if no events have changed
		System.debug( 'changedEvents:' ); System.debug( changedEventIds );
		if( changedEventIds.size() < 1 ){
			return( results );
		}
		
		//-- update the events show counts
		Event__c updatedEvent;
		for( Event__c changedEvent : [
			select id, ShowCount__c, (select id from EventDateTimes__r)
			from Event__c
			where id in :changedEventIds
		]){
			if( changedEvent.ShowCount__c != changedEvent.EventDateTimes__r.size() ){
				updatedEvent = new Event__c( id = changedEvent.Id, ShowCount__c = changedEvent.EventDateTimes__r.size() );
				System.debug( 'changedEvent[' + updatedEvent.id + '].showCount:' + updatedEvent.ShowCount__c );
				results.add( updatedEvent );
			}
		}
		
		System.debug( 'changedEvents:' ); System.debug( results );
		update results;
		
		return( results );
	}
}