src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>BookingHouseNut__c</fullName>
        <label>Booking House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SettlementHouseNut__c</fullName>
        <label>Settlement House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsingHouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_UpdateEventHouseNut_Test.cls
@isTest
public class LNE_UpdateEventHouseNut_Test {
    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }

    @isTest
    static void testUpdateHouseNutValues(){

    	LNE_TestObjectFactory.createStandardDataSet();
        
        List<Event__c> events = new List<Event__c>([SELECT Id FROM Event__c WHERE Status__c = 'Draft' LIMIT 1]);
        Id eventId = events[0].Id;

        Event__c ev = events[0];
        ApexPages.StandardController sc = new ApexPages.StandardController(ev);
        LNE_UpdateEventHouseNut controller = new LNE_UpdateEventHouseNut(sc);

        Boolean UsingHouseNut = true;
        Decimal HouseNutAmount = 500;
        Event__c updatedEvent = LNE_UpdateEventHouseNut.updateEvent(eventId, UsingHouseNut, HouseNutAmount);
        System.assertEquals(500, updatedEvent.BookingHouseNut__c);
        System.assertEquals(true, updatedEvent.UsingHouseNut__c);
        Boolean UsingHouseNut2 = false;
        Decimal HouseNutAmount2 = 999;
        Event__c updatedEvent2 = LNE_UpdateEventHouseNut.updateEvent(eventId, UsingHouseNut2, HouseNutAmount2);
        System.assertEquals(999, updatedEvent2.BookingHouseNut__c);
        System.assertEquals(false, updatedEvent2.UsingHouseNut__c);    
        Event__c updatedEvent3 = LNE_UpdateEventHouseNut.updateEventSettlement(eventId, UsingHouseNut2, HouseNutAmount2);
        System.assertEquals(999, updatedEvent3.SettlementHouseNut__c);
        System.assertEquals(false, updatedEvent3.UsingHouseNut__c);
    }
}