src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ArtistSettlementComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Artist Settlement Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ArtistSettlementCompletedBy__c</fullName>
        <label>Artist Settlement Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxOfficeImportComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Box Office Import Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BoxOfficeImportCompletedBy__c</fullName>
        <label>Box Office Import Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventRecapComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Recap Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventRecapCompletedBy__c</fullName>
        <label>Event Recap Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlashComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flash Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FlashCompletedBy__c</fullName>
        <label>Flash Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlashIntegrationStatus__c</fullName>
        <label>Flash Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
                <value>
                    <fullName>Oracle Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MetricsComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Metrics Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MetricsCompletedBy__c</fullName>
        <label>Metrics Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OracleExportComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Oracle Export Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OracleExportCompletedBy__c</fullName>
        <label>Oracle Export Completed By</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SettlementRecapComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Recap Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SettlementRecapCompletedBy__c</fullName>
        <label>Settlement Recap Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_FinanceSubTabs_CX_Test.cls
@isTest
private class LNE_FinanceSubTabs_CX_Test {
    
    class TestSettings {
		public Event__c testEvent {get; set;}
		
		public TestSettings() {
		    
		}
		
		public void typicalSetup(){
		    testEvent = [select Id, Venue__c from Event__c limit 1];
		}
		
		public void finalize(){
		}
	}
	
	
	@testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
        LNE_TestObjectFactory.createStandardDataSet();
    }
    
	private static testMethod void test() {
	    TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		
	    ApexPages.StandardController standardEventCtlr = new ApexPages.StandardController(tsettings.testEvent);
        LNE_FinanceSubTabs_CX financeSubTabs = new LNE_FinanceSubTabs_CX(standardEventCtlr);
        
        Event__c evt = [select ArtistSettlementComplete__c, SettlementRecapComplete__c, EventRecapComplete__c,
        	MetricsComplete__c, FlashComplete__c, 
            FlashIntegrationStatus__c, OracleExportComplete__c, BoxOfficeImportComplete__c,
            ArtistSettlementCompletedBy__c, SettlementRecapCompletedBy__c, EventRecapCompletedBy__c,
            MetricsCompletedBy__c, FlashCompletedBy__c,
            OracleExportCompletedBy__c, BoxOfficeImportCompletedBy__c, Status__c
            from Event__c where id = :tsettings.testEvent.Id];
        evt.Status__c = 'Pending Likely';
        update evt;
        
        evt.Status__c = 'Flash Started';
        update evt;
            
        system.assertEquals(false, evt.SettlementRecapComplete__c);
        system.assertEquals(false, evt.MetricsComplete__c);
        system.assertEquals(false, evt.OracleExportComplete__c);
        system.assertEquals(false, evt.FlashComplete__c);
        
        //
        // Test 1: complete settlement recap
        //
        financeSubTabs.completeSettlementRecap();
        
        evt = [select ArtistSettlementComplete__c, SettlementRecapComplete__c, EventRecapComplete__c,
        	MetricsComplete__c, FlashComplete__c, 
            FlashIntegrationStatus__c, OracleExportComplete__c, BoxOfficeImportComplete__c,
            ArtistSettlementCompletedBy__c, SettlementRecapCompletedBy__c, EventRecapCompletedBy__c,
            MetricsCompletedBy__c, FlashCompletedBy__c,
            OracleExportCompletedBy__c, BoxOfficeImportCompletedBy__c
            from Event__c where id = :tsettings.testEvent.Id];
            
        system.assertEquals(true, evt.SettlementRecapComplete__c);
        system.assertEquals(false, evt.MetricsComplete__c);
        system.assertEquals(false, evt.OracleExportComplete__c);
        system.assertEquals(false, evt.FlashComplete__c);
        
        //
        // Test 2: complete Metrics
        //
        financeSubTabs.completeEventMetrics();
        
        evt = [select ArtistSettlementComplete__c, SettlementRecapComplete__c, EventRecapComplete__c,
        	MetricsComplete__c, FlashComplete__c, 
            FlashIntegrationStatus__c, OracleExportComplete__c, BoxOfficeImportComplete__c,
            ArtistSettlementCompletedBy__c, SettlementRecapCompletedBy__c, EventRecapCompletedBy__c,
            MetricsCompletedBy__c, FlashCompletedBy__c,
            OracleExportCompletedBy__c, BoxOfficeImportCompletedBy__c
            from Event__c where id = :tsettings.testEvent.Id];
            
        system.assertEquals(true, evt.SettlementRecapComplete__c);
        system.assertEquals(true, evt.MetricsComplete__c);
        system.assertEquals(false, evt.OracleExportComplete__c);
        system.assertEquals(false, evt.FlashComplete__c);
        financeSubTabs.refreshFlags();
        
        //
        // Test 3: complete flash
        //
        financeSubTabs.completeFlash();
        
        evt = [select ArtistSettlementComplete__c, SettlementRecapComplete__c, EventRecapComplete__c,
        	MetricsComplete__c, FlashComplete__c, 
            FlashIntegrationStatus__c, OracleExportComplete__c, BoxOfficeImportComplete__c,
            ArtistSettlementCompletedBy__c, SettlementRecapCompletedBy__c, EventRecapCompletedBy__c,
            MetricsCompletedBy__c, FlashCompletedBy__c,
            OracleExportCompletedBy__c, BoxOfficeImportCompletedBy__c
            from Event__c where id = :tsettings.testEvent.Id];
            
        system.assertEquals(true, evt.SettlementRecapComplete__c);
        system.assertEquals(true, evt.MetricsComplete__c);
        system.assertEquals(false, evt.OracleExportComplete__c);
        system.assertEquals(true, evt.FlashComplete__c);
        
        //
        // Test 4: export to oracle
        //
        financeSubTabs.exportToOracle();
        
        evt = [select ArtistSettlementComplete__c, SettlementRecapComplete__c, EventRecapComplete__c,
        	MetricsComplete__c, FlashComplete__c, 
            FlashIntegrationStatus__c, OracleExportComplete__c, BoxOfficeImportComplete__c,
            ArtistSettlementCompletedBy__c, SettlementRecapCompletedBy__c, EventRecapCompletedBy__c,
            MetricsCompletedBy__c, FlashCompletedBy__c,
            OracleExportCompletedBy__c, BoxOfficeImportCompletedBy__c
            from Event__c where id = :tsettings.testEvent.Id];
            
        system.assertEquals(true, evt.SettlementRecapComplete__c);
        system.assertEquals(true, evt.MetricsComplete__c);
        system.assertEquals(true, evt.OracleExportComplete__c);
        system.assertEquals(true, evt.FlashComplete__c);
        
        evt.FlashIntegrationStatus__c = 'Oracle Updated';
        update evt;
        
        financeSubTabs.refreshFlags();
        
        // @todo
        // Test 5: Test if not flash user
        //
        
        
        
	}

}