src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventFirstDate__c</fullName>
        <label>Event First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Venue__r.Market__c)</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreviousEventInMarket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Event in Market</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Subsequent Events in Market</relationshipLabel>
        <relationshipName>SubsequentEventsInMarket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_FindPreviousEventInMarketBatch.cls
/** 
 *  Batch Class that finds/populates PreviousEventInMarket__c on Event records 
 *  
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 *	To Run:
 *	Database.executeBatch(new LNE_FindPreviousEventInMarketBatch(), LNE_FindPreviousEventInMarketBatch.BATCH_SIZE);
 **/
public without sharing class LNE_FindPreviousEventInMarketBatch implements Database.Batchable<sObject> {
	public static final Integer BATCH_SIZE = 1;

	public Database.QueryLocator start(Database.BatchableContext context) {
		Set<String> statuses = new Set<String>{'Draft', 'Pending Unlikely', 'Pending Likely', 'Cancelled', 'Postponed'};
        return(Database.getQueryLocator([SELECT EventFirstDate__c, Market__c FROM Event__c WHERE Status__c IN :statuses AND EventLastDate__c > TODAY]));
    }

    public void execute(Database.BatchableContext context, List<sObject> scope) {
    	LNE_FinancialCalculator.runUpdates = false;

		Set<String> statusesForVenueChanged = new Set<String>{'Draft', 'Pending Unlikely', 'Pending Likely', 'Cancelled', 'Postponed'};
		
		List<Event__c> toUpdate = LNE_EventMetrics_T.findPreviousEvent([SELECT EventFirstDate__c, Market__c FROM Event__c WHERE Id IN :scope AND Status__c IN :statusesForVenueChanged]);
		
		if (toUpdate != null && toUpdate.size() > 0) {
			update toUpdate;
		}
    }

    public void finish(Database.BatchableContext context) {}
}