src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Unlikely</fullName>
                </value>
                <value>
                    <fullName>Pending Likely</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Flash Started</fullName>
                </value>
                <value>
                    <fullName>Flash Complete</fullName>
                </value>
                <value>
                    <fullName>Artist Passed</fullName>
                </value>
                <value>
                    <fullName>LNE Passed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>NotificationAgeLimit__c</fullName>
        <defaultValue>7</defaultValue>
        <inlineHelpText>The limit in number of days that a Notification record is allowed to live.  A daily batch will remove any Notification record that is older than the limit in days.</inlineHelpText>
        <label>Notification Age Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notification__c.object
<CustomObject>
    <description>Records that should be used to track specific activity and notify the user. Similar to an Event Log.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acknowledgement Flag</fullName>
                </value>
                <value>
                    <fullName>Approval Flag</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>Not-{000000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventAlerts_Test.cls
@IsTest
private class LNE_EventAlerts_Test {
	
	public static GLAccount__c myGL_Account;
	
	@testSetup
	static void setup(){

		LNE_TestObjectFactory.prepStandardCustomSettings();
		//LNE_TestObjectFactory.createStandardDataSet();
		
	}

	class TestSettings {

		public Event__c myEvent { get; private set; }
		
		public TestSettings() {
			//-- global setup here
			
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_EventAlerts_Test' );

			this.myEvent = new Event__c(
                ProjectedPaidTickets__c = 20000,
                ProjectedDropCount__c = 30000,
                Status__c = 'Draft'
            );
			
			LNE_TestObjectFactory.createStandardDataSet( this.myEvent );

			

		}
		
		public void typicalSetup() {

			GeneralSettings__c settings = new GeneralSettings__c(
				SetupOwnerId = UserInfo.getUserId(),
				NotificationAgeLimit__c = 7
			);
			insert settings;

			Integer maxAge = 0 - settings.NotificationAgeLimit__c.intValue();
			
			// create notifications
			insert new List<Notification__c> {
				new Notification__c(
					CreatedDate = System.now().addDays(maxAge - 1), // set date in past so batch can pick it up
					Status__c = 'Open',
					Type__c = 'Approval Flag',
					Description__c = 'description1',
					Event__c = this.myEvent.Id
				),
				new Notification__c(
					CreatedDate = System.now().addDays(maxAge + 1), // set date in past so batch wont pick it up
					Status__c = 'Open',
					Type__c = 'Acknowledgement Flag',
					Description__c = 'description2',
					Event__c = this.myEvent.Id
				)
			};

		}
		
		public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		}
	}
	
	
	//-- test test methods here
	
	static testMethod void runSetupAWithoutException() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		System.assert( true, 'No Exceptions have occurred in getting here' );
	}
	
   	//-- test functionality here
	
	static testMethod void test_EventAlerts() {
		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();
		
		Map<String,String> data = LNE_EventAlerts_C.getServerData();
		//System.assertEquals(UserInfo.getSessionId(), data.get('sessionId')); // this will fail if called from dev console
		System.assertEquals(UserInfo.getUserId(), data.get('userId'));

		List<Notification__c> notes = LNE_EventAlerts_C.getNotifications(ts.myEvent.Id);
		System.assert(!notes.isEmpty());

		Boolean success = LNE_EventAlerts_C.dismissNotifications(new List<Id> { notes[0].Id });
		System.assert(success);
		
	}

	static testMethod void test_EventAlerts_Batch() {

		TestSettings ts = new TestSettings();
		ts.typicalSetup();
		ts.finalize();

		List<Notification__c> notes = [select Id from Notification__c];
		System.assert(notes.size() == 2);

		Test.startTest();

		//run batch
		new LNE_EventAlertsRemoval_Batch().execute(null);

		Test.stopTest();

		// only 1 note should have been destroyed
		notes = [select Id from Notification__c];
		System.assert(notes.size() == 1);

	}

}