src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_BlockLedgerEntryBreakoutDelete_T.cls
public with sharing class LNE_BlockLedgerEntryBreakoutDelete_T {
	/**
    *  Prevents the delete of a Ledger Entry Breakout if it has OfferRate__c or InHouseRate__c
    *  populated and the related Event__r.SettlementStarted__c = true
    *  @param newList LedgerEntryBreakout__c[]
    *  @return LedgerEntryBreakout__c[] - list of ledger entries updated.
    **/
    public static LedgerEntryBreakout__c[] execute( LedgerEntryBreakout__c[] newList){
        
        List<Id> associatedParentIds = new List<Id>();
        for (LedgerEntryBreakout__c le : newList){
            associatedParentIds.add(le.LedgerEntry__c);
        }
        
        Map<Id,LedgerEntry__c> parents = new Map<Id,LedgerEntry__c>([SELECT Event__c, Event__r.SettlementStarted__c FROM LedgerEntry__c WHERE Id =: associatedParentIds ]);
        
        for (LedgerEntryBreakout__c le : newList){

            if (parents.get(le.LedgerEntry__c) != null &&
            	parents.get(le.LedgerEntry__c).Event__c != null &&
                    (le.OfferRate__c != null && le.OfferRate__c != 0) ||
                    (le.InHouseRate__c != null && le.InHouseRate__c != 0)) {

                if (parents.get(le.LedgerEntry__c).Event__r.SettlementStarted__c != null &&
                    parents.get(le.LedgerEntry__c).Event__r.SettlementStarted__c == true) {
                    le.addError('Cannot delete this Ledger Entry Breakout because the Settlement process has started on the Event');
                }
            }
        }
        
        return ( newList );
    }
}