src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AdvertisingBudget__c</fullName>
        <label>Advertising Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AdvertisingSettlementPlan__c</fullName>
        <label>Advertising Settlement Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Settle at Actual</fullName>
                </value>
                <value>
                    <fullName>Settle at Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BookingHouseNut__c</fullName>
        <label>Booking House Nut</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberofTrucks__c</fullName>
        <label># of Trucks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsingHouseNut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Nut</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>Grid_Lost_Focus_Poll_Interval__c</fullName>
        <description>Used in ExpensesTab and AncillaryTab VF pages javascript to set how often the code polls to check the current in focus element. Used to show warning if grid has focus removed but has unsaved changes. Please enter a numeric value for the desired milliseconds.</description>
        <label>Grid Lost Focus Poll Interval</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_ExpenseTab_CX.cls
/**
 *  Class that provides functionality for LNE_ExpenseTab.page
 *
 *  @author Brandon Robins <brobins@salesforce.com>
 *
 **/
global class LNE_ExpenseTab_CX {
    static final String RT_EXPENSES = 'LedgerEntry__c.Expenses';

    private final SObject parent;
    public Event__c relatedEvent {get;set;}

    public String eventId {get;set;}
    public Boolean hasRelatedExpenses {get;set;}
    public Integer relatedExpensesCount {get;set;}
    public Boolean usingHouseNut {get; set;}
    public Integer houseNutAmount {get; set;}

    private static final GeneralSettings__c GENERAL_SETTINGS = GeneralSettings__c.getInstance();
    public String gridLostFocusPollInterval; 

    Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
        new String[]{ RT_EXPENSES }
    );

    Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );

    public LNE_ExpenseTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        relatedEvent = [SELECT Id, UsingHouseNut__c,AdvertisingBudget__c, AdvertisingSettlementPlan__c, NumberofTrucks__c 
                                FROM Event__c WHERE Id = :parent.id];
        eventId = parent.Id;

        getRelatedExpenses();
    }

    public void getRelatedExpenses() {
        Boolean show = false;

        List<LedgerEntry__c> expenses = [SELECT Id FROM LedgerEntry__c WHERE RecordTypeId IN (:RT_EXPENSES_ID) AND Event__c = :relatedEvent.Id];

        relatedExpensesCount = expenses.size();

        if (relatedExpensesCount > 0) {
            show = true;
        }

        hasRelatedExpenses = show;
    }

    public Event__c getEvent() {
        return relatedEvent;
    }

    public String getGridLostFocusPollInterval() {
        String res = GENERAL_SETTINGS.Grid_Lost_Focus_Poll_Interval__c;
        return res;
    }

    public String updateEventHouseNut() {
        Event__c event = getEvent();
        System.debug('human updateEventHouseNut()');
        System.debug('Event id is ' + event.Id);
        System.debug('event.UsingHouseNut__c is ' + event.UsingHouseNut__c);
        
        try {
            event.UsingHouseNut__c = usingHouseNut;
            event.BookingHouseNut__c = houseNutAmount;
            update event;
        } catch(DmlException e) {
            System.debug('human updating event house nut failed!');
            System.debug(e);
        }
        
        System.debug('post update event.UsingHouseNut__c is ' + event.UsingHouseNut__c);
        return null;
    }

    @RemoteAction
    global static Boolean saveEvent(Id eventId, Decimal advertisingbudget, String advertisingsettlementplan, Decimal numberofTrucks) {
        Event__c updateEvent = new Event__c(Id=eventId, AdvertisingBudget__c = advertisingbudget  
                                            ,AdvertisingSettlementPlan__c=advertisingsettlementplan 
                                            ,NumberofTrucks__c = numberofTrucks
                                            );

        Boolean success = true;
        System.savepoint sp = Database.setSavepoint();
        system.debug('@@@ updateEvent - '+ updateEvent);

        try {
            update updateEvent;
        }
        catch (System.DmlException de) {
            Database.rollback(sp);
            success = false;
        }

        return success;
    }  
}