src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>RentalBuildOption__c</fullName>
        <label>Rental Build Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Build as a Promoted Show</fullName>
                </value>
                <value>
                    <fullName>Build Using Rental Accounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>PromotedShow</fullName>
        <active>true</active>
        <description>Local event or part of a tour and fully managed by Live Nation</description>
        <label>Promoted Show</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Event not managed by Live Nation</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>ApplyToPromotedEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Promoted Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplyToRentalEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply To Rental Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableForForecast__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available For Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CategorySort__c</fullName>
        <label>Category Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Advertising Expense</fullName>
                </value>
                <value>
                    <fullName>Barter Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Barter - Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Booking Revenue</fullName>
                </value>
                <value>
                    <fullName>Box Suite Event Revenue</fullName>
                </value>
                <value>
                    <fullName>COGS - All Other</fullName>
                </value>
                <value>
                    <fullName>COGS - Concessions</fullName>
                </value>
                <value>
                    <fullName>COGS - Merchandise</fullName>
                </value>
                <value>
                    <fullName>Concession Revenue</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expenses</fullName>
                </value>
                <value>
                    <fullName>Co Promote Sell Off Revenue</fullName>
                </value>
                <value>
                    <fullName>Event Rent Expense</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship Revenue</fullName>
                </value>
                <value>
                    <fullName>Facility Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Insurance Expense</fullName>
                </value>
                <value>
                    <fullName>Merchandise Revenue</fullName>
                </value>
                <value>
                    <fullName>Operating Expense</fullName>
                </value>
                <value>
                    <fullName>Other Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Other Variable Expense</fullName>
                </value>
                <value>
                    <fullName>Parking Revenue</fullName>
                </value>
                <value>
                    <fullName>Production Expense</fullName>
                </value>
                <value>
                    <fullName>PSS/Box Suites - Event</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Expense</fullName>
                </value>
                <value>
                    <fullName>Rental/Special Event Revenue</fullName>
                </value>
                <value>
                    <fullName>Season Seats - Event</fullName>
                </value>
                <value>
                    <fullName>Service Charge Rebate Revenue</fullName>
                </value>
                <value>
                    <fullName>Sound &amp; Lights Expense</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <externalId>true</externalId>
        <label>GL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <referenceTo>GLAccount__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Expenses</fullName>
        <active>true</active>
        <description>Captures the general ledger expenses for an event</description>
        <label>Expenses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntryBreakout__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>LedgerEntry__r.Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLAccount__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.Name</formula>
        <label>GL Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>LedgerEntry__r.GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LedgerEntry__c</fullName>
        <label>Ledger Entry</label>
        <referenceTo>LedgerEntry__c</referenceTo>
        <relationshipLabel>Ledger Entry Breakouts</relationshipLabel>
        <relationshipName>LedgerEntryBreakouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Ledger Entry Breakout</label>
    <nameField>
        <displayFormat>LEB-{000000}</displayFormat>
        <label>Ledger Entry Breakout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entry Breakouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_SelectExpenseEntriesController.cls
/**
 *  Class that provides functionality for LNE_SelectExpenseEntries.page
 *
 *  @author Brandon Robins <brobins@salesforce.com>
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 *
 **/
public class LNE_SelectExpenseEntriesController {
    static final String RT_EXPENSES = 'LedgerEntry__c.Expenses';
    static final String RT_PROMOTEDSHOW = 'Event__c.PromotedShow';
    static final String RT_RENTAL = 'Event__c.Rental';
    static final String PARAM_EVENT_ID = 'event_id';

    public String eventId {get;set;}
    public String expenseEntriesJson {get;set;}
    public String previousSelectedEntriesJson {get;set;}
    public String selectedEntriesJson {get;set;}
    public String saveSelectedExpensesSuccess {get;set;}
    public Boolean isSettlement {get;set;}

    private List<Id> previousSelectedGLAccountIds {get;set;}

    Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
        new String[]{ RT_EXPENSES, RT_PROMOTEDSHOW, RT_RENTAL }
    );

    Id RT_EXPENSES_ID = recordTypeMap.get( RT_EXPENSES );
    Id RT_PROMOTEDSHOW_ID = recordTypeMap.get( RT_PROMOTEDSHOW );
    Id RT_RENTAL_ID = recordTypeMap.get( RT_RENTAL );

    public LNE_SelectExpenseEntriesController() {
        isSettlement = false;
        Map<String,String> params = ApexPages.currentPage().getParameters();
        if(params.containsKey('type') && params.get('type') != null){
            isSettlement = params.get('type') == 'Settlement';
        }
        eventId = ApexPages.currentPage().getParameters().get( PARAM_EVENT_ID );

        previousSelectedGLAccountIds = new List<Id>();
        getGLAccountListGroupedByCategory();
    }

    private void addLedgerEntries(List<Id> glAccountIds) {
        List<LedgerEntry__c> ledgerEntries = new List<LedgerEntry__c>();

        for (Id accountId : glAccountIds) {
            ledgerEntries.add(new LedgerEntry__c(
                GLAccount__c = accountId,
                Event__c = eventId,
                RecordTypeId = RT_EXPENSES_ID
            ));
        }

        insert ledgerEntries;
    }

    private void getGLAccountListGroupedByCategory() {
        List<GLAccount__c> expenseEntries = new List<GLAccount__c>();
        List<GLAccountWrapper> wrapperList = new List<GLAccountWrapper>();

        List<GLAccount__c> accountList = new List<GLAccount__c>();
        //accountList = [SELECT Name, Category__c, CategorySort__c, GLCode__c FROM GLAccount__c WHERE Type__c = 'Expenses' AND AvailableForForecast__c = true];
        
        // US751 - build dynamic soql for ancillaries and check for rental vs promoted based on event recordtype.
        String additionalFilter = '';
        if(eventId != null){
            List<Event__c> eventList = [Select Id, RecordTypeId, RentalBuildOption__c from Event__c where Id = :eventId];
            if(eventList != null && !eventList.isEmpty()){
                Event__c event = eventList[0];
                if(event.RecordTypeId == RT_PROMOTEDSHOW_ID){
                    additionalFilter = ' AND ApplyToPromotedEvent__c = true ';
                }else if(event.RecordTypeId == RT_RENTAL_ID){
                    if(event.RentalBuildOption__c == 'Build Using Rental Accounts' ){
                        additionalFilter = ' AND ApplyToRentalEvent__c = true ';
                    }else if(event.RentalBuildOption__c == 'Build as a Promoted Show'){
                        additionalFilter = ' AND ApplyToPromotedEvent__c = true ';
                    }
                }
            }
        }
        String accountSOQL = 'SELECT Name, Category__c, CategorySort__c, GLCode__c, Type__c FROM GLAccount__c'
                                    + ' WHERE Type__c = \'Expenses\' AND AvailableForForecast__c = true '
                                    + additionalFilter;
        accountList = Database.Query(accountSOQL);

        for (GLAccount__c account : accountList) {
            wrapperList.add(new GLAccountWrapper(account));
        }

        wrapperList.sort();

        for (GLAccountWrapper glAccountWrapper : wrapperList) {
            expenseEntries.add(glAccountWrapper.glAccount);
        }

        expenseEntriesJson = System.JSON.serialize(expenseEntries);
    }

    private void removeLedgerEntries(List<Id> glAccountIds) {
        List<LedgerEntry__c> ledgerEntries = [SELECT Id FROM LedgerEntry__c WHERE GLAccount__c IN :glAccountIds AND Event__c = :eventId];

        delete ledgerEntries;
    }

    public void addOrRemoveExpenseEntries() {
        List<Integer> elemToRemove = new List<Integer>();
        List<Id> glAccountsToAdd = new List<Id>();
        List<Id> glAccountsToRemove = new List<Id>();

        List<Id> selectedGLAccountIds = (List<Id>) System.JSON.deserialize(selectedEntriesJson, List<Id>.class);

        for (Integer i = 0; i < previousSelectedGLAccountIds.size(); i++) {
            Boolean isMissing = true;

            for (Id selElem : selectedGLAccountIds) {
                if (selElem == previousSelectedGLAccountIds[i]) {
                    isMissing = false;
                    break;
                }
            }

            if (isMissing) {
                glAccountsToRemove.add(previousSelectedGLAccountIds[i]);
                elemToRemove.add(i);
            }
        }

        for (Integer i = elemToRemove.size() - 1; i >= 0; i--) {
            previousSelectedGLAccountIds.remove(elemToRemove[i]);
        }

        for (Id elem : selectedGLAccountIds) {
            Boolean isAlreadyPresent = false;

            for (Id prevSelElem : previousSelectedGLAccountIds) {
                if (prevSelElem == elem) {
                    isAlreadyPresent = true;
                    break;
                }
            }

            if (!isAlreadyPresent) {
                glAccountsToAdd.add(elem);
            }
        }

        try {
            addLedgerEntries(glAccountsToAdd);
            removeLedgerEntries(glAccountsToRemove);

            saveSelectedExpensesSuccess = 'true';
        }
        catch (DmlException e) {
            System.debug(e);

            saveSelectedExpensesSuccess = 'false';
        }
    }

    public void getRelatedExpenses() {
        List<LedgerEntry__c> expenses = [SELECT GLAccount__c,
                                                OfferRate__c,
                                                InHouseRate__c,
                                                (SELECT OfferRate__c,
                                                        InHouseRate__c
                                                 FROM LedgerEntryBreakouts__r)
                                         FROM LedgerEntry__c
                                         WHERE RecordTypeId IN (:RT_EXPENSES_ID) AND Event__c = :eventId];

        if (expenses.size() > 0) {
            List<LedgerEntryWrapper> ledgers = new List<LedgerEntryWrapper>();
            

            for (LedgerEntry__c entry : expenses) {
                previousSelectedGLAccountIds.add(entry.GLAccount__c);
                ledgers.add(new LedgerEntryWrapper(entry));
            }

            previousSelectedEntriesJson = System.JSON.serialize(ledgers);
        } else {
            previousSelectedEntriesJson = '[]';
        }
    }

    public class LedgerEntryWrapper {
        public LedgerEntry__c ledger {get;set;}
        public Boolean disableSelection {get;set;}

        public LedgerEntryWrapper(LedgerEntry__c l) {
            this.ledger = l;
            disableSelection = false;

            for (LedgerEntryBreakout__c b : ledger.LedgerEntryBreakouts__r) {
                if ((b.OfferRate__c != null && b.OfferRate__c != 0) || (b.InHouseRate__c != null && b.InHouseRate__c != 0)) {
                    disableSelection = true;
                    break;
                }
            }

            if ((ledger.OfferRate__c != null && ledger.OfferRate__c != 0) || (ledger.InHouseRate__c != null && ledger.InHouseRate__c != 0)) {
                disableSelection = true;
            }
        }
    }
}