src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>AutoMatchedTour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used with the LNE_EventAutoMatchTour_Batch class.</description>
        <label>Auto-Matched Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events (Auto-Matched Tour)</relationshipLabel>
        <relationshipName>AutoMatchedEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>Drives sharing rules to provide read-only access to other division members</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoNotAutoAssociateWithTour__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true the first time an Event is associated with a Tour. It excludes this record from the automated daily process associating Events with Tours by search criteria.</description>
        <label>Do Not Auto Associate with Tour</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventFirstDate__c</fullName>
        <label>Event First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PrimaryHeadlinerArtist__c</fullName>
        <description>Automatically populated via trigger on Deal and Event PB Flow</description>
        <label>Primary Headliner Artist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Office</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Division</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FilterArtist__c</fullName>
        <description>The Tour daily auto association process will include this Artist&apos;s name in its search of Events to associate.</description>
        <label>Filter Artist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterDivision__c</fullName>
        <description>The Tour daily auto association process will include this Division&apos;s name in its search of Events to associate.</description>
        <label>Filter Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterEndDate__c</fullName>
        <description>The Tour daily auto association process will include this date as the latest show date in its search of Events to associate.</description>
        <label>Filter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FilterExpirationDate__c</fullName>
        <description>Until the date in this field, the Tour daily auto association process will include this record&apos;s filter criteria in its search of Events to associate.</description>
        <label>Filter Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FilterStartDate__c</fullName>
        <description>The Tour daily auto association process will include this date as the earliest show date in its search of Events to associate.</description>
        <label>Filter Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FilterVenueType__c</fullName>
        <description>The Tour daily auto association process will include only this venue type in its search of Events to associate.</description>
        <label>Filter Venue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_EventAutoMatchTour_Batch.cls
/**
* Iterates over Tour__c records that have pre-defined and active Filters setup to automatically find
* and match Event__c records that have those same exact values.
*
* @author	Scott Will
* @group	Batchable, Schedulable
*
**/
global class LNE_EventAutoMatchTour_Batch implements Database.Batchable<sObject>, Schedulable {
	
	final static String query =
		'select ' +
			'FilterArtist__c, ' +
			'FilterDivision__c, ' +
			'FilterEndDate__c, ' +
			'FilterStartDate__c, ' +
			'FilterVenueType__c ' +
		'from Tour__c ' +
		'where FilterExpirationDate__c >= TODAY ' +
		'and FilterArtist__c != null ' +
		'and FilterStartDate__c != null ' +
		'order by CreatedDate desc ';

	private final DateTime batchLastRan;

	public LNE_EventAutoMatchTour_Batch() {
		// retrieve last ran
		List<AsyncApexJob> jobs = new List<AsyncApexJob>([
			select CreatedDate 
			from AsyncApexJob 
			where ApexClass.Name = 'LNE_EventAutoMatchTour_Batch' 
			order by CreatedDate desc 
			limit 1
		]);
		// either run last 24 hours or since last ran
		this.batchLastRan = jobs.isEmpty()
			? System.now().addDays(-1)
			: jobs[0].CreatedDate;

	}

	
	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext bc, List<Tour__c> tours) {

		// SCOPE IS SET TO 1, THIS IS _NOT_ RUNNING IN BULK
		Tour__c tour = tours[0];

		String artist = tour.FilterArtist__c;
		String division = tour.FilterDivision__c;
		String venue = tour.FilterVenueType__c;
		Date beginDate = tour.FilterStartDate__c;
		Date endDate = tour.FilterEndDate__c;
	
		// find any events that match
		List<Event__c> events = new List<Event__c>();

		// find any events that have been modified since the last ran date
		// and that have an exact match to the Tour's filters
		for (Event__c event : (List<Event__c>)Database.query(
			'select AutoMatchedTour__c ' +
			'from Event__c ' +
			'where LastModifiedDate >= :batchLastRan ' +
			'and AutoMatchedTour__c = null ' +
			'and Tour__c = null ' +
			'and DoNotAutoAssociateWithTour__c = false ' +
			'and PrimaryHeadlinerArtist__c = :artist ' +
			'and EventFirstDate__c >= :beginDate ' +
			(endDate == null ? '' : 'and EndLastDate__c <= :endDate ') +
			(String.isBlank(division) ? '' : 'and Division__c = :division ') +
			(String.isBlank(venue) ? '' : 'and Venue__c = :venue ')
		)) {
			// only pre-set for now.  a second, slower, batch will move the value to the real Tour__c
			event.AutoMatchedTour__c = tour.Id;
			events.add(event);
		}

		if (!events.isEmpty()) {
			// update whatever can be updated
			Database.update(events, false);
		}

	}
	
	global void finish(Database.BatchableContext bc) {
		// call next step in process, to associate the events individually to allow financial calc to run
		Database.executeBatch(new LNE_EventAssociateMatchedTour_Batch(), 1);
	}

	global void execute(SchedulableContext sc) {
		// schedule will execute batch @1 scope
		Database.executeBatch(this, 1);
	}
	
}