src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>EventFirstDate__c</fullName>
        <label>Event First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventLastDate__c</fullName>
        <label>Event Last Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EventDateTime__c.object
<CustomObject>
    <description>The specific date(s) and time(s) on which the event is scheduled</description>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Date Times</relationshipLabel>
        <relationshipName>EventDateTimes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Date Time</label>
    <nameField>
        <displayFormat>EDT-{000000}</displayFormat>
        <label>Event Date Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Date Times</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_EventStartEndTimeCalc_T.cls
/**
 *  Trigger class to determine the start and end times for an event.
 *  @author Sebastian Gutierrez <sgutierrez@altimetrik.com>
 **/
public with sharing class LNE_EventStartEndTimeCalc_T {
	
	public static final String ERROR_NODATETIMEFOUND = 'You may not delete the last Date associated with the Event.';
	
	/**
	 * Determines the starting and ending date times for related events.
	 * @return Event__c[] - list of events that have the show count changed.
	 **/
	public static Event__c[] execute( EventDateTime__c[] newEventDateTimes, Map<Id,EventDateTime__c> oldEventDateTimeMap ){
		
		Set<id> changedEventIds = new Set<id>();
		Event__c updatedEvent;
		Event__c[] results = new Event__c[]{};
		
		if( newEventDateTimes == null ){
			//-- we are deleting
			for( EventDateTime__c deletedEDT : oldEventDateTimeMap.values() ){
				changedEventIds.add( deletedEDT.Event__c );
			}
		} else if( oldEventDateTimeMap == null ){
			//-- we are inserting
			for( EventDateTime__c insertedEDT : newEventDateTimes ){
				changedEventIds.add( insertedEDT.Event__c );
			}
		} else {
			//-- we are updating
			EventDateTime__c oldEDT;
			
			for( EventDateTime__c updatedEDT : newEventDateTimes ){
				oldEDT = oldEventDateTimeMap.get( updatedEDT.Id );
				if( updatedEDT.EventDate__c != oldEDT.EventDate__c ){
					changedEventIds.add( updatedEDT.Event__c );
				}
			}
		}
		
		//-- @INVARIANT: we know the list of all events that have had the starting and ending dates possibly changed.
		System.debug( 'changedEventIds:' ); System.debug( changedEventIds );
		if( changedEventIds.size() < 1 ){
			return( results );
		}
		
		//-- update the events show counts
		for( Event__c changedEvent : [
			select id,EventFirstDate__c, EventLastDate__c, (select id, EventDate__c  from EventDateTimes__r order by EventDate__c ASC )
			from Event__c
			where id in :changedEventIds
		]){
			updatedEvent = new Event__c();
			updatedEvent.Id = changedEvent.Id;
			if(changedEvent.EventDateTimes__r.size() > 0){
			    updatedEvent.EventFirstDate__c = changedEvent.EventDateTimes__r[0].EventDate__c;
                updatedEvent.EventLastDate__c = changedEvent.EventDateTimes__r[ changedEvent.EventDateTimes__r.size()-1 ].EventDate__c;
			}else{
				if (LNE_EventDeletionUtil.CURRENTLY_DELETING == false) {
			    	throw (new CustomException (ERROR_NODATETIMEFOUND));
				}
			}
            results.add( updatedEvent );
		}
		
		System.debug( 'changedEvents:' ); System.debug( results );
		update results;
		
		return( results );
	}
	
	/** custom exception **/
    class CustomException extends Exception {}
    
    /**
     *  Internal class to represent the changes from the object.
    **/
    /*
    class ChangedDateTimes extends LNE_SObjectChange {
        
        ChangedDateTimes( EventDateTime__c oldObject, EventDateTime__c newObject ){
            super( oldObject, newObject );
        }
        
        EventDateTime__c getNewDeal(){
            return( (EventDateTime__c)this.newObject );
        }
    }
    */
}