src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>NoExpectedAncillaries__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Expected Ancillaries</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GeneralSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical settings that may apply to any area of the application and can be referenced via code as well as config. Before creating additional hierarchical custom settings, consider whether you can add fields to this setting and achieve the same results.</description>
    <fields>
        <fullName>Grid_Lost_Focus_Poll_Interval__c</fullName>
        <description>Used in ExpensesTab and AncillaryTab VF pages javascript to set how often the code polls to check the current in focus element. Used to show warning if grid has focus removed but has unsaved changes. Please enter a numeric value for the desired milliseconds.</description>
        <label>Grid Lost Focus Poll Interval</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <recordTypes>
        <fullName>Ancillary</fullName>
        <active>true</active>
        <description>Event revenues not directly resulting from ticket sales</description>
        <label>Ancillary</label>
    </recordTypes>
    <recordTypes>
        <fullName>COGS</fullName>
        <active>true</active>
        <description>Event expenses related to ancillary revenues but calculated separately</description>
        <label>COGS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_FinanceAncillaryTab_CX.cls
/**
 *  Class that provides functionality for LNE_AncillaryTab.page
 *
 *  @author Dominic Aveyard <daveyard@salesforce.com>
 *
 **/
global class LNE_FinanceAncillaryTab_CX {
	
	static final String RT_Ancillary = 'LedgerEntry__c.Ancillary';
	static final String RT_COGS = 'LedgerEntry__c.COGS';

	private final SObject parent;
	private final Event__c relatedEvent;

	public Integer ancillaryCount {get;set;}
	public Integer cogCount {get;set;}
	public String eventId {get;set;}
	public Boolean eventNoExpectedAncillaries {get;set;}
	/**
	 *	hideToggle is a flag used by the VF page to know if any error/success messages
	 * 	should be the shown. In other words, was the form just submitted
	 *  TODO: There has to be a better name? even despite the inherint goofiness of naming toggles like this
	 **/
	public Boolean hideToggle {get; set;}

	public Boolean relatedAncillaries {get; set;}
	public Integer relatedAncillariesCount {get; set;}

	private static final GeneralSettings__c GENERAL_SETTINGS = GeneralSettings__c.getInstance();
	public String gridLostFocusPollInterval;

	Map<String,Id> recordTypeMap = LNE_Util.getRecordTypes(
		new String[]{ RT_Ancillary, RT_COGS }
	);

	public String updateEventSuccess {get;set;}

	Id RT_Ancillary_ID = recordTypeMap.get( RT_Ancillary );
	Id RT_COGS_ID = recordTypeMap.get ( RT_COGS );

	public LNE_FinanceAncillaryTab_CX(ApexPages.StandardController controller){
		parent = controller.getRecord();
		relatedEvent = [SELECT Id FROM Event__c
						WHERE Id = :parent.id];
		hideToggle = true;
		getCountOfRelatedAncillaries();
		getRelatedAncillaries();
	}

	public void getCountOfRelatedAncillaries() {
	  LedgerEntry__c[] ancillaries = new LedgerEntry__c[] {};
	  ancillaries = [SELECT Id FROM LedgerEntry__c WHERE RecordTypeId = :RT_Ancillary_ID AND Event__c = :relatedEvent.Id];

	  ancillaryCount = ancillaries.size();

	  LedgerEntry__c[] cogs = new LedgerEntry__c[] {};
	  cogs = [SELECT Id FROM LedgerEntry__c WHERE RecordTypeId = :RT_COGS_ID AND Event__c = :relatedEvent.Id];

	  cogCount = cogs.size();
	}

	public Boolean determineRelatedAncillaries() {
		Boolean show = false;
		LedgerEntry__c[] exist = new LedgerEntry__c[] {};
		exist = [SELECT Id FROM LedgerEntry__c WHERE RecordTypeId IN (:RT_Ancillary_ID, :RT_COGS_ID) AND Event__c = :relatedEvent.Id];

		if ( exist.size() > 0 ) {
			System.debug('Candy: Ok so there were related ledger entries');
			show = true;
		} else {
		   System.debug('Candy: Ok so there were NO related ledger entries');
		}

		relatedAncillariesCount = exist.size();

		return ( show );
	}

	public Boolean getRelatedAncillaries() {
		relatedAncillaries = determineRelatedAncillaries();
		return ( relatedAncillaries );
	}

	public String getGridLostFocusPollInterval() {
		String res = GENERAL_SETTINGS.Grid_Lost_Focus_Poll_Interval__c;
		return res;
	}

	public Event__c getEvent() {
		return ( relatedEvent );
	}

	public void updateEvent() {
	  try {
		  Event__c evnt = [SELECT Id, NoExpectedAncillaries__c FROM Event__c WHERE Id = :eventId];
		  evnt.NoExpectedAncillaries__c = eventNoExpectedAncillaries;

		  Database.Update(evnt, true);

		  updateEventSuccess = 'true';
	  }
	  catch (DmlException e) {
		  System.debug(e);

		  updateEventSuccess = 'false';
	  }
	}

	@RemoteAction
	global static Boolean copyToFlash(Id eventId) {
		LNE_LedgerEntryUtil.copyToFlash(eventId);
		return true;
	}

}