src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>SettlementStarted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Settlement Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LedgerEntry__c.object
<CustomObject>
    <description>General ledger accounting entries enabling standardized revenue and expense tracking for events</description>
    <fields>
        <fullName>AdPlanManaged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Represents a Ledger Entry that is generated based on Ad Plan calculations,
and is managed by the backend.</description>
        <label>Ad Plan Managed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Revenues and Expenses</relationshipLabel>
        <relationshipName>LedgerEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLCode__c</fullName>
        <formula>GLAccount__r.GLCode__c</formula>
        <label>GL Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InHouseRate__c</fullName>
        <label>In House Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfferRate__c</fullName>
        <label>Offer Rate / $</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_BlockDeletingTourLE_T.cls
public class LNE_BlockDeletingTourLE_T {

    /**
    *  Prevent delete of Tour Ledger Entry if Associated Event is Linked to a Tour
    *  Also prevents the delete of a Ledger Entry if it has OfferRate__c or InHouseRate__c
    *  populated and the related Event__r.SettlementStarted__c = true
    *  @param newList LedgerEntry__c[]
    *  @return LedgerEntry__c[] - list of ledger entries updated.
    **/
    public static LedgerEntry__c[] execute( LedgerEntry__c[] newList){
        
        List<Id> associatedEventIds = new List<Id>();
        for (LedgerEntry__c le : newList){
            associatedEventIds.add(le.Event__c);
        }
        
        Map<Id,Event__c> associatedEvents = new Map<Id,Event__c>([SELECT Tour__c, SettlementStarted__c FROM Event__c WHERE Id =: associatedEventIds ]);
        
        for (LedgerEntry__c le : newList){
            if(le.GLCode__c == '50360' && associatedEvents.get(le.Event__c).Tour__c != null){
                le.addError('The Tour Ledger Entry - 50360 cannot be deleted as long as the Event is associated to a Tour');
            }

            if (associatedEvents.get(le.Event__c) != null &&
                    ((le.OfferRate__c != null && le.OfferRate__c != 0) ||
                    (le.InHouseRate__c != null && le.InHouseRate__c != 0))) {

                if (associatedEvents.get(le.Event__c).SettlementStarted__c != null &&
                    associatedEvents.get(le.Event__c).SettlementStarted__c == true) {
                    le.addError('Cannot delete this Ledger Entry because the Settlement process has started on the Event');
                }
            }

            //US 691 - Prevent deletion if Ledger Entry is AdPlan Managed
            if(le.AdPlanManaged__c == TRUE){
                le.addError('Ad Plan Ledger Entries cannot be Deleted');
            }
        }
        
        return ( newList );
    }
}