src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>GrossPotential__c</fullName>
        <label>Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetGrossPotential__c</fullName>
        <label>Net Gross Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberofTrucks__c</fullName>
        <label># of Trucks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedDropCount__c</fullName>
        <label>Projected Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectedGross__c</fullName>
        <label>Projected Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedNetGross__c</fullName>
        <label>Projected Net Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutDropCount__c</fullName>
        <label>Sellout Drop Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SelloutPaidTickets__c</fullName>
        <label>Sellout Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ticket Revenue</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Contra</fullName>
                </value>
                <value>
                    <fullName>COGS</fullName>
                </value>
                <value>
                    <fullName>Talent Fees</fullName>
                </value>
                <value>
                    <fullName>Co Promote Expense</fullName>
                </value>
                <value>
                    <fullName>Co Promote Revenue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TicketScale__c.object
<CustomObject>
    <description>Pricing levels for venue tickets established per event</description>
    <fields>
        <fullName>AverageLiftPerTicket__c</fullName>
        <label>Average Lift Per Ticket</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comps__c</fullName>
        <label>Comps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Ticket Scales</relationshipLabel>
        <relationshipName>TicketScales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kills__c</fullName>
        <label>Kills</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LiftBeforeFee__c</fullName>
        <label>Lift Before Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectedPaidTickets__c</fullName>
        <label>Projected Paid Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageType__c</fullName>
        <label>Stage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                    <default>true</default>
                    <label>Plan</label>
                </value>
                <value>
                    <fullName>Projection</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TMFeePercent__c</fullName>
        <defaultValue>0.129</defaultValue>
        <label>TM Fee %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Lawn</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>Rsvd - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Rsvd - 4 Pack</fullName>
                </value>
                <value>
                    <fullName>Lawn - Value Channel</fullName>
                </value>
                <value>
                    <fullName>Lawn - 4 Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket Scale</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Ticket Scale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Scales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_PlatinumLiftCalculatorAPI_CX_Test.cls
@isTest
private with sharing class LNE_PlatinumLiftCalculatorAPI_CX_Test {

    @testSetup
    static void setup(){
        LNE_TestObjectFactory.prepStandardCustomSettings();
    }
    
	class TestSettings {
		public Event__c testEvent;
		
		public TestSettings() {
			//-- we don't need the financial calculator to run until we're done with all this
			LNE_FinancialCalculator.currentlyRunning = true;
			LNE_FinancialCalculator.pushRunningTrigger( 'LNE_TicketScalesToLedgerController_Test' );
		}
		
		public void typicalSetup(){
			Event__c event = new LNE_TestObjectFactory(
		        LNE_TestObjectFactory.createEvent()
			).addProperties( new Map<String,Object>{
			    'SelloutDropCount__c' => 2100,
			    'ProjectedDropCount__c' => 1940,
			    'SelloutPaidTickets__c' => 2100,
			    'ProjectedPaidTickets__c' => 2000,
			    'GrossPotential__c' => 217420,
			    'ProjectedGross__c' => 207420,
			    'NetGrossPotential__c' => 95074.68,
			    'ProjectedNetGross__c' => 90729.47,
			    'NumberOfTrucks__c' => 5
			}).buildEvent();
			
			LNE_TestObjectFactory.createStandardDataSet( event );

			testEvent = event;
		}
		
		public void finalize(){
			//-- now we're done with updating everything, have the financial calculator run.
			LNE_FinancialCalculator.currentlyRunning = false;
			LNE_FinancialCalculator.popRunningTrigger();
		}
	}
	

	static void setupGLAccounts() {
		/*
		GLAccount__c revGL = new LNE_TestObjectFactory(LNE_TestObjectFactory.createGLAccount('Ticket Revenue', '40100')).buildGLAccount();
		GLAccount__c lawnGL = new LNE_TestObjectFactory(LNE_TestObjectFactory.createGLAccount('Lawn', '40116')).buildGLAccount();
		GLAccount__c groupGL = new LNE_TestObjectFactory(LNE_TestObjectFactory.createGLAccount('Group', 'Group')).buildGLAccount();

		insert new List<GLAccount__c>{revGL,lawnGL,groupGL};
		*/
		GLAccount__c groupGL = new LNE_TestObjectFactory(LNE_TestObjectFactory.createGLAccount('Group', 'Group')).buildGLAccount();
		insert groupGL;
	}

	static void setupData(Event__c event) {

		LNE_FinancialCalculator.runUpdates = true;

		TicketScale__c ticketScale = new TicketScale__c();
		ticketScale.Type__c = 'Platinum';
		ticketScale.Capacity__c = 100;
		ticketScale.Price__c = 100.00;
		ticketScale.Kills__c = 0;
		ticketScale.Comps__c = 0;
		ticketScale.ProjectedPaidTickets__c = 100;
		ticketScale.Event__c = event.Id;
		ticketScale.LiftBeforeFee__c = 7420.00;
		ticketScale.TMFeePercent__c = 0.0;
		ticketScale.StageType__c = 'Projection';

		insert new List<TicketScale__c>{ticketScale};
	}

	@isTest static void testPlatinumLiftCalculator() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();
		setupGLAccounts();
		setupData(tsettings.testEvent);

		TicketScale__c testTS = [SELECT LiftBeforeFee__c, ProjectedPaidTickets__c, AverageLiftPerTicket__c FROM TicketScale__c WHERE Type__c = 'Platinum'];

		Test.startTest();

		PageReference pageRef = Page.LNE_PlatinumLiftCalculatorAPI;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('callback', 'test');
		ApexPages.currentPage().getParameters().put('TicketScale__c', JSON.serialize(testTS));

		LNE_PlatinumLiftCalculatorAPI_CX controller = new LNE_PlatinumLiftCalculatorAPI_CX();
		system.debug('**** CALLING processRequest');
		controller.processRequest();

		Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(controller.jsonResponse);

		system.assert(String.valueOf(m.get('data')).contains('AverageLiftPerTicket__c=74.2'));  

		Test.stopTest();
	}

	@isTest static void testPlatinumLiftCalculator_Error() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();
		setupGLAccounts();
		setupData(tsettings.testEvent);

		TicketScale__c testTS = new TicketScale__c();

		Test.startTest();

		PageReference pageRef = Page.LNE_PlatinumLiftCalculatorAPI;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('callback', 'test');
		ApexPages.currentPage().getParameters().put('TicketScale__c', JSON.serialize(testTS));

		LNE_PlatinumLiftCalculatorAPI_CX controller = new LNE_PlatinumLiftCalculatorAPI_CX();
		controller.processRequest();

		Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(controller.jsonResponse);
		system.assert(String.valueOf(m.get('message')).contains('List has no rows for assignment to SObject'));  

		Test.stopTest();
	}

	@isTest static void testPlatinumLiftCalculator_LiftBeforeFee() {
		TestSettings tsettings = new TestSettings();
		tsettings.typicalSetup();
		tsettings.finalize();
		setupGLAccounts();
		setupData(tsettings.testEvent);

		TicketScale__c testTS = [SELECT LiftBeforeFee__c, ProjectedPaidTickets__c, AverageLiftPerTicket__c FROM TicketScale__c WHERE Type__c = 'Platinum'];
		testTS.AverageLiftPerTicket__c = 74.20;
		testTS.LiftBeforeFee__c = null;
		update testTS;

		Test.startTest();

		PageReference pageRef = Page.LNE_PlatinumLiftCalculatorAPI;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('callback', 'test');
		ApexPages.currentPage().getParameters().put('TicketScale__c', JSON.serialize(testTS));

		LNE_PlatinumLiftCalculatorAPI_CX controller = new LNE_PlatinumLiftCalculatorAPI_CX();
		system.debug('**** CALLING processRequest');
		controller.processRequest();

		Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(controller.jsonResponse);

		system.assert(String.valueOf(m.get('data')).contains('LiftBeforeFee__c=7420'));  

		Test.stopTest();
	}

}