src/objects/Event__c.object
<CustomObject>
    <description>Usually a promoted show or activity coordinated by LNE but also may represent holds, rentals, bookings at third party venues, and festivals</description>
    <fields>
        <fullName>CatereaseProcessDate__c</fullName>
        <formula>CatereaseEvent__r.processdate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Caterease Process Date</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>Evt-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LNE_RunCatereaseCalculator_BatchSchedule.cls
/**
 *  Scheduler for the LNE_RunCatereaseCalculator_Batch
 *  
 *  LNE_RunCatereaseCalculator_BatchSchedule b = new LNE_RunCatereaseCalculator_BatchSchedule();
 *  System.Schedule(LNE_RunCatereaseCalculator_BatchSchedule.JOB_NAME, LNE_RunCatereaseCalculator_BatchSchedule.DEFAULT_SCHEDULE, b);
 *  
 *  @author Henry Akpala <hakpala@salesforce.com>
**/
global class LNE_RunCatereaseCalculator_BatchSchedule implements Schedulable {
    
    /** Time when the job should execute **/
    global static String DEFAULT_SCHEDULE = '0 5 3 * * ?'; //TODO set based on boomi job run.
    
    /** Name of the Scheduled Job **/
    global static String JOB_NAME = 'CatereaseFinancialCalculatorBatch';
    
    global void execute(SchedulableContext sc) {
        Date todayDate = Date.today()  ;
        String q1 = 'SELECT Id from  Event__c WHERE  CatereaseProcessDate__c >:todayDate';
        LNE_RunCatereaseCalculator_Batch catereaseCalculateBatch = new LNE_RunCatereaseCalculator_Batch(q1);
        Database.executeBatch(catereaseCalculateBatch);
    }
}