src/objects/GLAccount__c.object
<CustomObject>
    <description>Definitions for General Ledger Accounts including GL codes, names, import options, etc. (Revenues &amp; Expenses - Ticket Revenues, Ancillary Revenues, Event Expenses, COGS Expenses, etc.)</description>
    <fields>
        <fullName>CategorySort__c</fullName>
        <label>Category Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLAccountWrapper.cls
global class GLAccountWrapper implements Comparable {
    public GLAccount__c glAccount;

    public GLAccountWrapper(GLAccount__c gla) {
        glAccount = gla;
    }

    global Integer compareTo(Object compareTo) {
        GLAccountWrapper compareToGlAccount = (GLAccountWrapper) compareTo;

        Integer returnValue = 0;
        
        if (glAccount.CategorySort__c > compareToGlAccount.glAccount.CategorySort__c) {
            returnValue = 1;
        } else if (glAccount.CategorySort__c < compareToGlAccount.glAccount.CategorySort__c) {
            returnValue = -1;
        }

        return returnValue;
    }
}