src/objects/NonLNETourBudget__c.object
<CustomObject>
    <description>Tour marketing budgets funded by 3rd-party sponsors</description>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sponsor does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Sponsor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Non-LNE Tour Budgets</relationshipLabel>
        <relationshipName>NonLNETourBudgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-LNE Tour Budget</label>
    <nameField>
        <displayFormat>NLTB-{000000}</displayFormat>
        <label>Non-LNE Tour Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-LNE Tour Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Non-LNE Tour Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NonLNETourBudget__c.Tour__c</field>
                <operation>equals</operation>
                <valueField>$Source.Tour__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NonLNETourBudget__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>TourCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FBEvent - buyticketslink</fullName>
                </value>
                <value>
                    <fullName>FBEvent - description</fullName>
                </value>
                <value>
                    <fullName>FBX</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page image</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page link</fullName>
                </value>
                <value>
                    <fullName>Paid - artist page video</fullName>
                </value>
                <value>
                    <fullName>Paid - dark post</fullName>
                </value>
                <value>
                    <fullName>Paid - link post</fullName>
                </value>
                <value>
                    <fullName>Paid - Lncom</fullName>
                </value>
                <value>
                    <fullName>Paid - photo</fullName>
                </value>
                <value>
                    <fullName>Paid - promotion</fullName>
                </value>
                <value>
                    <fullName>Paid - Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Paid - text only</fullName>
                </value>
                <value>
                    <fullName>Paid - video</fullName>
                </value>
                <value>
                    <fullName>Advertising Materials Production</fullName>
                </value>
                <value>
                    <fullName>Agency Commission</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Distribution</fullName>
                </value>
                <value>
                    <fullName>Flyer &amp; Poster Production</fullName>
                </value>
                <value>
                    <fullName>Graphic/Digital Design</fullName>
                </value>
                <value>
                    <fullName>National Allocation - Misc</fullName>
                </value>
                <value>
                    <fullName>Press Conference</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Tour Launch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Rich Media</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>HasNonLNETourBudget__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the Tour Campaign Ad Plan is associated with a tour campaign that has a Non-LNE Tour Budget.
assigned through apex
and used because a roll up summary cannot use formula fields.</description>
        <label>Has Non-LNE Tour Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NonLNETourBudget__c</fullName>
        <formula>TourCampaign__r.NonLNETourBudget__r.Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-LNE Tour Budget</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <label>Sponsor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(TourCampaign__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_TourCampNonLNEBudgetAssign.cls
/**
 *  Trigger logic to update the TourCampaign_AdPlan record
 *  when the Non-LNE Budget is assigned (or removed)
 *  from the tour campaign.
 *  @author Paul Roth <proth@salesforce.com
 *  @see US689 / US146
 **/
public class LNE_TourCampNonLNEBudgetAssign {

    /**
     *  updates all the TourCampaignAdPlans - when the Non-LNE budget
     *  has been assigned.
     *  <p>Please note that the HasNonLNETourBudget is also assigned in LNE_TourLogic_T and LNE_AdPlanLogic_T</p>
     *  <p>This is exclusively for the purpose of when the tour campaign is finally assigned (or removed)</p>
     *  @assumption - only run on update.
     *  @param TourCampaign__c[] newList
     *  @param Map<Id,TourCampaign__c> oldMap
     *  @return TourCampaignAdPlan__c[] - list of tour campaign ad plans that were updated.
     **/
    public static TourCampaignAdPlan__c[] execute( TourCampaign__c[] newList, Map<Id,TourCampaign__c> oldMap ){
        TourCampaignAdPlan__c[] results = new TourCampaignAdPlan__c[]{};
        
        TourCampaign__c[] validTourCampaigns = new TourCampaign__c[]{};
        TourCampaign__c oldTourCampaign;
        for( TourCampaign__c newCampaign : newList ){
            if( oldMap.containsKey( newCampaign.Id )){
                oldTourCampaign = oldMap.get( newCampaign.Id );
                
                //-- continue only if the NonLNETourBudget__c was assigned.
                if(newCampaign.NonLNETourBudget__c != oldTourCampaign.NonLNETourBudget__c){
                    validTourCampaigns.add( newCampaign );
                }
            }
        }
        
        if( validTourCampaigns.size() < 1 ){
            return( results );
        }
        
        for( TourCampaign__c updatedCampaign : [
            select id, NonLNETourBudget__c, NonLNETourBudget__r.Type__r.Name, ( select id, name from Tour_Campaign_Ad_Plan__r )
            from TourCampaign__c
            where id in :validTourCampaigns
        ]){
            for( TourCampaignAdPlan__c tcAdPlan : updatedCampaign.Tour_Campaign_Ad_Plan__r ){
                tcAdPlan.HasNonLNETourBudget__c = ( updatedCampaign.NonLNETourBudget__c != null );
                if( updatedCampaign.NonLNETourBudget__c != null ){
                    tcAdPlan.Sponsor__c = ( updatedCampaign.NonLNETourBudget__r.Type__r.Name );
                } else {
                    tcAdPlan.Sponsor__c = null;
                }
                results.add( tcAdPlan );
            }
        }
        
        if( results.size() > 0 ){
            update results;
        }
        
        return( results );
    }

}