src/objects/NonLNEBudget__c.object
<CustomObject>
    <description>Marketing budgets funded by 3rd-party sponsors</description>
    <label>Non-LNE Budget</label>
    <nameField>
        <displayFormat>NLB-{000000}</displayFormat>
        <label>Non-LNE Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-LNE Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>DigitalSpendPercent__c</fullName>
        <formula>DigitalSpend__c/ LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Spend %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DigitalSpend__c</fullName>
        <label>Digital Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digital</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LNEMarketingBudget__c</fullName>
        <label>LNE Marketing Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LNESpend__c</fullName>
        <label>LNE Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MiscSpendPercent__c</fullName>
        <formula>MiscSpend__c/LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Misc Spend %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MiscSpend__c</fullName>
        <label>Misc Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Misc</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNEBudget__c</fullName>
        <label>Non-LNE Budget</label>
        <summarizedField>NonLNETourBudget__c.Budget__c</summarizedField>
        <summaryForeignKey>NonLNETourBudget__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NonLNESpend__c</fullName>
        <label>Non-LNE Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProductionSpendPercent__c</fullName>
        <formula>ProductionSpend__c/LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production Spend %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProductionSpend__c</fullName>
        <label>Production Spend</label>
        <summarizedField>TourCampaign__c.NetAmount__c</summarizedField>
        <summaryFilterItems>
            <field>TourCampaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Production</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>TourCampaign__c.NonLNETourBudgetBlank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TourCampaign__c.Tour__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RemainingLNEBudget__c</fullName>
        <formula>LNEMarketingBudget__c -  LNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RemainingNonLNEBudget__c</fullName>
        <formula>NonLNEBudget__c -  NonLNESpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Non-LNE Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_CampaignTab_CX.cls
/**
 *  Class that provides functionality for LNE_CampaignTab.page
 *
 *  @author Daniel Nakonieczny <dnakonieczny@salesforce.com>
 *
 **/
public class LNE_CampaignTab_CX {
	public String gridToShow {get;set;}
	public String matrixReportId {get;set;}
	public String tourId {get;set;}
	public Tour__c tour {get;set;} 

	public LNE_CampaignTab_CX(ApexPages.StandardController controller) {
		gridToShow = 'tour_campaign';
		getMatrixReportId();
		tourId = controller.getRecord().Id;
		refreshTour();
    }

    public void showTourCampaigns() {
    	gridToShow = 'tour_campaign';
    }

    public void showTourAdPlans() {
    	gridToShow = 'tour_ad_plan';
    }

    private void getMatrixReportId() {
    	List<Report> reportList = [SELECT Id FROM Report WHERE DeveloperName = 'TourCampaignswithAdPlans'];

    	if (!reportList.isEmpty()){
    		matrixReportId = reportList[0].Id;
    	}
    }

    public void refreshTour() {
        this.tour = [SELECT Name, LNEMarketingBudget__c, LNESpend__c, RemainingLNEBudget__c, NonLNEBudget__c, NonLNESpend__c, RemainingNonLNEBudget__c, DigitalSpendPercent__c,
                MiscSpendPercent__c, ProductionSpendPercent__c, DigitalSpend__c, MiscSpend__c, ProductionSpend__c FROM Tour__c WHERE Id = :tourId];
    }

}