src/objects/PromoPromoScale__c.object
<CustomObject>
    <description>Junction object between Promotions and Promo Scale</description>
    <fields>
        <fullName>NumberofTickets__c</fullName>
        <label># of Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>Promo_Scale__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Promo_Scale__c</fullName>
        <label>Promo Scale</label>
        <referenceTo>PromoScale__c</referenceTo>
        <relationshipLabel>Promo-Promo Scale</relationshipLabel>
        <relationshipName>Promo_Promo_Scale</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TicketValue__c</fullName>
        <inlineHelpText>Total value for the # of Tickets * Price</inlineHelpText>
        <label>Ticket Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Promo-Promo Scale</label>
    <nameField>
        <displayFormat>PPS-{00000}</displayFormat>
        <label>Promo-Promo Scale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo-Promo Scale</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PromoScale__c.object
<CustomObject>
    <description>Promo information related to the ticket scale</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Promo Scale</label>
    <nameField>
        <label>Promo Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_PromoScale_T.cls
/**
 * Created by JK on 1/12/17.
 */

public with sharing class LNE_PromoScale_T {

    public static void calculateTotalTicketValues(Map<Id, PromoScale__c> newMap){

        List<PromoPromoScale__c> promoPromoScales = [Select Id, Promo_Scale__c, NumberofTickets__c, TicketValue__c From PromoPromoScale__c where Promo_Scale__c in :newMap.keySet()];
        List<PromoPromoScale__c> promoPromoScalesToUpdate = new List<PromoPromoScale__c>();

        PromoScale__c ps;
        Decimal correctTotal;

        for(PromoPromoScale__c pps : promoPromoScales){
            ps = newMap.get(pps.Promo_Scale__c);
            correctTotal = pps.NumberofTickets__c * ps.Price__c;
            if(correctTotal != pps.TicketValue__c){
                pps.TicketValue__c = correctTotal;
                promoPromoScalesToUpdate.add(pps);
            }
        }

        if(!promoPromoScalesToUpdate.isEmpty()){
            update promoPromoScalesToUpdate;
        }

    }
}