src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Digital</fullName>
        <active>true</active>
        <description>Represents digital ads</description>
        <label>Digital</label>
    </recordTypes>
    <recordTypes>
        <fullName>Misc</fullName>
        <active>true</active>
        <description>Represents misc expenses</description>
        <label>Misc</label>
    </recordTypes>
    <recordTypes>
        <fullName>Production</fullName>
        <active>true</active>
        <description>Represents production expenses</description>
        <label>Production</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>TourCampaignType__c</fullName>
        <description>Filled through apex, as the RecordType name of the associated Tour Campaign.
Used because RollUpSummaries cannot use formula fields</description>
        <label>Tour Campaign Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_TourCampaignAdPlanType.cls
/**
 *  Trigger logic to update the tour campaign type on tour campaign ad plans
 *  @author Paul Roth <proth@salesforce.com
 *  @see US689 / US146
 **/
public class LNE_TourCampaignAdPlanType {
	
	public static final String RT_TOUR_CAMPAIGN_DIGITAL = 'Digital';
	public static final String RT_TOUR_CAMPAIGN_MISC = 'Misc';
	public static final String RT_TOUR_CAMPAIGN_PROD = 'Production';

	/**
	 *  Updates the tour campaign type on tour campaign ad plans.
	 *  <p>Please note that the HasNonLNETourBudget is also assigned in LNE_TourLogic_T and LNE_AdPlanLogic_T</p>
	 *  <p>This is exclusively for the purpose of when the tour campaign is finally assigned (or removed)</p>
	 *  @assumption - only run on update.
	 *  @param TourCampaign__c[] newList
	 *  @param Map<Id,TourCampaign__c> oldMap
	 *  @return TourCampaignAdPlan__c[] - list of tour campaign ad plans that were updated.
	 **/
	public static TourCampaignAdPlan__c[] execute( TourCampaign__c[] newList, Map<Id,TourCampaign__c> oldMap ){
		TourCampaignAdPlan__c[] results = new TourCampaignAdPlan__c[]{};
		
		Id[] validTourCampaigns = new Id[]{};
		TourCampaign__c oldTourCampaign;
		for( TourCampaign__c newCampaign : newList ){
			if( oldMap.containsKey( newCampaign.Id )){
				oldTourCampaign = oldMap.get( newCampaign.Id );
				
				//-- continue only if the TourCampaign__c.RecordTypeId was updated.
				if( 
					newCampaign.RecordTypeId != oldTourCampaign.RecordTypeId
				){
					validTourCampaigns.add( newCampaign.Id );
				}
			}
		}
		
		if( validTourCampaigns.size() < 1 ){
			return( results );
		}
		
		//-- @INVARIANT: validTourCampaigns are a list of all the tour campaigns that have changed recordTypes.
		//System.debug( validTourCampaigns );
		
		String tourCampaignRT;
		for( TourCampaignAdPlan__c tcAdPlan : [
			select id, name, TourCampaign__r.recordType.Name
			FROM TourCampaignAdPlan__c
			WHERE TourCampaign__c in :validTourCampaigns
		]){
			tcAdPlan.TourCampaignType__c = null;
			if( tcAdPlan.TourCampaign__r != null && tcAdPlan.TourCampaign__r.RecordType != null ){
				tcAdPlan.TourCampaignType__c = tcAdPlan.TourCampaign__r.RecordType.Name;
			}
			results.add( tcAdPlan );
		}
		
		if( results.size() > 0 ){
			update results;
		}
		
		return( results );
	}

}