src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>RequestID__c</fullName>
        <label>Request ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TourCampaign__c.object
<CustomObject>
    <description>Campaigns related to tours tracking digital ads, miscellaneous expenses, and production expenses and associated spend allocated to local Events</description>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <label>Announcement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Announce</fullName>
                </value>
                <value>
                    <fullName>Presale</fullName>
                </value>
                <value>
                    <fullName>Onsale</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>Tour_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tour Campaigns</relationshipLabel>
        <relationshipName>TourCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour Campaign</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Tour Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TourCampaignAdPlan__c.object
<CustomObject>
    <description>Junction object linking Tour Campaigns and Ad Plans</description>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <formula>TEXT(TourCampaign__r.AnnouncementType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Announcement Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <label>Request ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortURL__c</fullName>
        <description>Bitly-generated Tracking URL or from an alternative service</description>
        <label>Short URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourCampaign__c</fullName>
        <label>Tour Campaign</label>
        <referenceTo>TourCampaign__c</referenceTo>
        <relationshipLabel>Tour Campaign-Ad Plan</relationshipLabel>
        <relationshipName>Tour_Campaign_Ad_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TrackingURL__c</fullName>
        <formula>&quot;http://www.livenation.com/events/344444-may-6-2014-backstreet-boys-in-a-world-like-this-tour/?c=LN_NAC_SEM_NAT_Google_Toronto_RogersKRockCentre_BackstreetBoysInaWorldLikeThisTour_NONE_Native_O_12286_20140317_20140317&quot;</formula>
        <label>Tracking URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>TourCampaign__r.Vendor__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <label>Tour Campaign-Ad Plan</label>
    <nameField>
        <displayFormat>TCAP-{000000}</displayFormat>
        <label>Tour Campaign-Ad Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Campaign-Ad Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LNE_GenerateTourShortlinks_C.cls
/**
 *  Controller for the LNE_GenerateTourShortlinks lightning component.
 *
 *  @author Scott Will
 *
 **/
public with sharing class LNE_GenerateTourShortlinks_C {

    /**
     * Returns a list of unique Vendors found under the Tour
     *
     * @param   tourId Id - the id of the Tour__c record
     * @return  String[] - list of unique vendor names
    **/
    @AuraEnabled
    public static List<String> getVendors(Id tourId) {

        List<String> vendors = new List<String>();

        if (tourId != null) {

            // Vendor__c is a formula and cannot be grouped in an aggregate
            Set<String> distincts = new Set<String>();

            for (TourCampaignAdPlan__c tcap : [
                select
                    Vendor__c
                from TourCampaignAdPlan__c
                where TourCampaign__r.Tour__c = :tourId
            ]) {
                distincts.add(tcap.Vendor__c);
            }

            vendors.addAll(distincts);
            vendors.sort();

        }

        return vendors;

    }

    /**
     * Returns a list of unique Announcement Types found under the Tour
     *
     * @param   tourId Id - the id of the Tour__c record
     * @return  String[] - list of unique type names
    **/
    @AuraEnabled
    public static List<String> getTypes(Id tourId) {

        List<String> types = new List<String>();

        if (tourId != null) {

            // AnnouncementType__c is a formula and cannot be grouped in an aggregate
            Set<String> distincts = new Set<String>();

            for (TourCampaignAdPlan__c tcap : [
                select
                    AnnouncementType__c
                from TourCampaignAdPlan__c
                where TourCampaign__r.Tour__c = :tourId
            ]) {
                distincts.add(tcap.AnnouncementType__c);
            }

            types.addAll(distincts);
            types.sort();

        }

        return types;

    }

    /**
     * Returns all TourCampaignAdPlan__c records associated to the tourId
     *
     * @param   tourId Id - the id of the Tour__c record
     * @param   vendors String[] - list of vendor names to filter by
     * @param   types String[] - list of type names to filter by
     * @return  TourCampaignAdPlan__c[]
    **/
    @AuraEnabled
    public static List<TourCampaignAdPlan__c> getTourCampaignAdPlans(Id tourId, List<String> vendors, List<String> types) {

        List<TourCampaignAdPlan__c> records = new List<TourCampaignAdPlan__c>();

        if (tourId != null) {

            Set<String> setVendors = new Set<String>(vendors);
            Set<String> setTypes = new Set<String>(types);
            // lightning component will send an array of [""] if no selection was made
            setVendors.remove('');
            setTypes.remove('');

            for (TourCampaignAdPlan__c record : (List<TourCampaignAdPlan__c>)Database.query(
                'select ' +
                    'ShortURL__c, ' +
                    'TrackingURL__c ' +
                'from TourCampaignAdPlan__c ' +
                'where TourCampaign__r.Tour__c = :tourId ' +
                (setTypes.isEmpty() ? '' : 'and AnnouncementType__c in :setTypes ') +
                (setVendors.isEmpty() ? '' : 'and Vendor__c in :setVendors ')
            )) {
                // since we dont know if the TrackingURL has changed, we will reset all Short URLs
                record.ShortURL__c = '';
                records.add(record);
            }

        }
        
        return records;

    }

    /**
     * Updates each TourCampaignAdPlan__c's ShortURL
     *
     * @param   tourId Id - the id of the Tour__c record
     * @param   requestId String - random value to be added to RequestId__c field
     * @return  Map - map of each updated ShortURL mapped by its record Id
    **/
    @AuraEnabled
    public static Map<Id,String> updateShortUrls(List<Id> recordIds, String requestId) {

        Map<Id,String> result = new Map<Id,String>();
        List<TourCampaignAdPlan__c> records = new List<TourCampaignAdPlan__c>();
        for (TourCampaignAdPlan__c record : [
            select
                RequestID__c,
                ShortURL__c,
                TrackingURL__c 
            from TourCampaignAdPlan__c 
            where Id in :recordIds
        ]) {

            LNE_ShortlinkService.BitlyResult bitly;
            if (!Test.isRunningTest()) {
                bitly = LNE_ShortlinkService.shortenUrl(record.TrackingURL__c);
            }
            else {
                bitly = new LNE_ShortlinkService.BitlyResult();
                bitly.errorCode = 0;
                bitly.errorMessage = '';
                bitly.shortenedUrl = 'foo';
            }

            record.RequestID__c = requestId;
            record.ShortURL__c = (bitly.errorCode == 0)
                ? bitly.shortenedUrl
                : '';

            if (bitly.errorCode == 0) {
                records.add(record);
            }
            else {
                System.debug('Bitly Error Encountered: ' + String.format('{0}-{1}', new List<String> {
                    String.valueOf(bitly.errorCode),
                    bitly.errorMessage
                }));
            }

            result.put(record.Id, record.ShortURL__c);

        }

        if (!records.isEmpty()) {
            List<Database.SaveResult> srs = Database.update(records, false);
            for (Integer i = 0; i < srs.size(); i++) {
                if (!srs[i].isSuccess()) {
                    result.put(records[i].Id, '');
                }
            }
        }

        return result;

    }

    /**
     * Updates the Tour's RequestId with the supplied value
     *
     * @param   tourId Id - the id of the Tour__c record
     * @param   requestId String - random value to be added to RequestId__c field
     * @return  Boolean - success of the save operation
    **/
    @AuraEnabled
    public static Boolean updateTour(Id tourId, String requestId) {

        Tour__c tour = new Tour__c(
            Id = tourId,
            RequestID__c = requestId
        );

        Database.SaveResult sr = Database.update(tour, false);
        return sr.isSuccess();

    }

}