src/objects/Tour__c.object
<CustomObject>
    <description>A collection of Events and Ad Plans that are linked together with additional tour-level processes and activities</description>
    <fields>
        <fullName>TotalEndofTourDinner__c</fullName>
        <label>Total End of Tour Dinner</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalMiscExpense__c</fullName>
        <label>Total Misc Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPerDiems__c</fullName>
        <label>Total Per Diems</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTE__c</fullName>
        <label>Total T&amp;E</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTSO__c</fullName>
        <formula>TotalTE__c + TotalEndofTourDinner__c + TotalTourRep__c + TotalMiscExpense__c + TotalPerDiems__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total TSO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTourRep__c</fullName>
        <label>Total Tour Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>Tou-{000000}</displayFormat>
        <label>Tour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LNE_TSOTab_CX.cls
public class LNE_TSOTab_CX {
	
    private final SObject parent;
    public Tour__c tourTotals {get;set;}
    public String tourId {get;set;}

    public LNE_TSOTab_CX(ApexPages.StandardController controller) {
        parent = controller.getRecord();
        tourId = parent.Id;
        init();
    }
    
     public void init() {
        getTourTotals();
      
    }
     
    public PageReference getTourTotals(){
        tourTotals = [select TotalTourRep__c, TotalMiscExpense__c, TotalEndOfTourDinner__c, TotalTE__C, TotalTSO__c, TotalPerDiems__c  from Tour__c where Id = :tourId][0]; 
        System.debug('getTourTotals');
        System.debug(tourTotals);
        return null;
    }
}